import { beforeEach, afterEach, it, expect, vi } from 'vitest';
import Database from 'better-sqlite3';
import { initializeDatabase } from './db';
import { staffCredentials, saveAdminStaff, adminAccountForEmail } from './adminStaff';
import { hasAdminPermission, type AdminRole, type AdminPermission } from './adminRolesShared';
import bcrypt from 'bcryptjs';
const bootstrap = { id: 'bootstrap_admin', email: 'root@test.ro', role: 'super_admin' as const, revision: 0 };
let db: Database.Database;
const passwordHash = bcrypt.hashSync('test-secret-not-real', 10), secret = 'GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ', staffSecret = 'JBSWY3DPEHPK3PXPJBSWY3DPEHPK3PXP';
beforeEach(() => { db = new Database(':memory:'); db.pragma('foreign_keys=ON'); initializeDatabase(db); vi.stubEnv('NITIDO_ADMIN_EMAIL', bootstrap.email); vi.stubEnv('NITIDO_ADMIN_PASSWORD', 'fixture'); vi.stubEnv('NITIDO_ADMIN_TOTP_SECRET', secret); vi.stubEnv('NITIDO_ADMIN_STAFF_ACCOUNTS_JSON', JSON.stringify([{ email: 'operator@test.ro', passwordHash, totpSecret: staffSecret }])); });
afterEach(() => { db.close(); vi.unstubAllEnvs(); });
const save = (patch: Record<string, unknown> = {}) => db.transaction(() => saveAdminStaff(db, { email: 'operator@test.ro', role: 'operator', active: true, revision: 0, reason: 'Approved', ...patch }, bootstrap)).immediate();
it('applies the complete default-deny role matrix', () => { const allowed = { operator: ['session', 'operations', 'incidents'], manager: ['session', 'operations', 'manage', 'reports', 'incidents'], finance: ['session', 'finance', 'reports', 'incidents'], super_admin: ['session', 'operations', 'manage', 'finance', 'reports', 'super_admin', 'incidents'] }; for (const role of Object.keys(allowed) as AdminRole[])
    for (const permission of ['session', 'operations', 'manage', 'finance', 'reports', 'super_admin', 'incidents'] as AdminPermission[])
        expect(hasAdminPermission(role, permission)).toBe(allowed[role].includes(permission)); expect(hasAdminPermission('unknown' as AdminRole, 'session')).toBe(false); });
it('requires both a provisioned nominal account and valid MFA configuration', () => { expect(adminAccountForEmail(db, 'operator@test.ro')).toBeNull(); save(); expect(adminAccountForEmail(db, 'OPERATOR@test.ro')?.identity.role).toBe('operator'); expect(adminAccountForEmail(db, 'root@test.ro')?.identity).toEqual(bootstrap); vi.stubEnv('NITIDO_ADMIN_STAFF_ACCOUNTS_JSON', '[]'); expect(adminAccountForEmail(db, 'operator@test.ro')).toBeNull(); });
it('rejects duplicate credentials, reused MFA secrets, plaintext passwords and malformed registry', () => { const base = { email: 'a@test.ro', passwordHash, totpSecret: staffSecret }; for (const entries of [[base, base], [base, { ...base, email: 'b@test.ro' }], [{ ...base, passwordHash: 'plaintext' }], [{ ...base, totpSecret: secret }]])
    expect(staffCredentials({ ...process.env, NITIDO_ADMIN_STAFF_ACCOUNTS_JSON: JSON.stringify(entries) }).size).toBe(0); expect(staffCredentials({ ...process.env, NITIDO_ADMIN_STAFF_ACCOUNTS_JSON: 'oops' }).size).toBe(0); });
it('revokes all sessions on role change and records immutable history atomically', () => { const a = save(); db.prepare('INSERT INTO admin_sessions(id,token_hash,expires_at) VALUES(?,?,?)').run('session', 'hash', '2099-01-01'); db.prepare('INSERT INTO admin_session_identity VALUES(?,?,?)').run('hash', a.id, 1); save({ revision: 1, role: 'manager' }); expect(db.prepare('SELECT * FROM admin_sessions').all()).toEqual([]); expect(db.prepare('SELECT COUNT(*) n FROM admin_staff_history').get()).toEqual({ n: 2 }); expect(() => db.exec('DELETE FROM admin_staff_history')).toThrow(/retained/); expect(() => save({ revision: 1, role: 'finance' })).toThrow(/modificat/); save({ revision: 2, active: false }); expect(adminAccountForEmail(db, 'operator@test.ro')).toBeNull(); });
it('blocks privilege elevation by staff, self-change and bootstrap edits', () => { const a = save(); expect(() => db.transaction(() => saveAdminStaff(db, { email: a.email, role: 'super_admin', active: true, revision: 1, reason: 'Test' }, { ...a, role: 'operator' }))()).toThrow(/Super Admin/); expect(() => save({ email: bootstrap.email })).toThrow(/principal/); expect(() => db.transaction(() => saveAdminStaff(db, { email: a.email, role: 'finance', active: true, revision: 1, reason: 'Test' }, { ...a, role: 'super_admin' }))()).toThrow(/Propriul/); });
it('rolls back account changes when history cannot be recorded', () => { db.exec("CREATE TRIGGER fail_history BEFORE INSERT ON admin_staff_history BEGIN SELECT RAISE(ABORT,'audit failed'); END;"); expect(() => save()).toThrow(); expect(db.prepare('SELECT * FROM admin_staff').all()).toEqual([]); });
