import {afterEach,beforeEach,describe,expect,it} from 'vitest';
import Database from 'better-sqlite3';
import {SCHEMA_SQL} from './db';
import {initializeCatalog} from './serviceCatalog';
import {ASSESSMENT_SCHEMA,createAssessment,listAssessments,updateAssessment,validateAssessment} from './assessments';
let db:Database.Database;
const input=()=>({category:'renovation',city:'Brașov',sqm:1500,rooms:20,bathrooms:4,difficulty:'heavy',notes:'Curățenie după renovare',appliances:2,windowsSqm:35,linenSets:0,extraHours:3});
beforeEach(()=>{db=new Database(':memory:');db.pragma('foreign_keys=ON');db.exec(SCHEMA_SQL);initializeCatalog(db);db.exec(ASSESSMENT_SCHEMA);db.exec("INSERT INTO users(id,role,name) VALUES('a','client','A'),('b','client','B'),('f','firma','Firma')")});afterEach(()=>db.close());
describe('assisted assessment workflow',()=>{
 it('accepts an out-of-calculator request without creating a job or payment',()=>{createAssessment(db,'a','r1',input());expect(listAssessments(db,'a')[0]).toMatchObject({sqm:1500,status:'submitted',messages:[]});expect(db.prepare('SELECT COUNT(*) n FROM jobs').get()).toEqual({n:0});expect(db.prepare('SELECT COUNT(*) n FROM payments').get()).toEqual({n:0})});
 it('deduplicates retries and rejects conflicting reuse',()=>{const id=createAssessment(db,'a','r1',input());expect(createAssessment(db,'a','r1',input())).toBe(id);expect(()=>createAssessment(db,'a','r1',{...input(),sqm:1600})).toThrow(/reutilizat/);expect(listAssessments(db,'a')).toHaveLength(1)});
 it('isolates owners and rejects firm submissions',()=>{const id=createAssessment(db,'a','r1',input());expect(listAssessments(db,'b')).toEqual([]);expect(()=>updateAssessment(db,{clientId:'b'},id,1,'reply','Private data')).toThrow(/inexistentă/);expect(()=>createAssessment(db,'f','r1',input())).toThrow(/interzis/)});
 it('completes the admin question, client reply and final assessment with append-only messages',()=>{const id=createAssessment(db,'a','r1',input());updateAssessment(db,{admin:true},id,1,'needs_details','Ce materiale sunt în spațiu?');updateAssessment(db,{clientId:'a'},id,2,'reply','Parchet și marmură.');updateAssessment(db,{admin:true},id,3,'reviewed','Evaluarea este încheiată. Condițiile sunt descrise aici.');const r=listAssessments(db,'a')[0];expect(r.status).toBe('reviewed');expect(r.messages.map(m=>m.author)).toEqual(['admin','client','admin']);expect(()=>updateAssessment(db,{clientId:'a'},id,4,'reply','Alt mesaj')).toThrow(/închisă/)});
 it('rejects stale decisions without partial message writes',()=>{const id=createAssessment(db,'a','r1',input());updateAssessment(db,{clientId:'a'},id,1,'reply','Completare');expect(()=>updateAssessment(db,{admin:true},id,1,'declined','Nu putem prelua')).toThrow(/actualizată/);expect(listAssessments(db,'a')[0].messages).toHaveLength(1)});
 it('cancels an open request and prevents subsequent admin decisions',()=>{const id=createAssessment(db,'a','r1',input());updateAssessment(db,{clientId:'a'},id,1,'cancel','');expect(listAssessments(db,'a')[0].status).toBe('cancelled');expect(()=>updateAssessment(db,{admin:true},id,2,'reviewed','Done')).toThrow(/nepermisă/)});
 it('preserves the original category definition and submitted payload',()=>{const id=createAssessment(db,'a','r1',input());db.exec("UPDATE service_catalog_drafts SET version=9,definition='{}' WHERE key='renovation'");updateAssessment(db,{admin:true},id,1,'needs_details','Clarifică');const row=db.prepare('SELECT category_version,category_definition,payload FROM service_assessments WHERE id=?').get(id) as {category_version:number;category_definition:string;payload:string};expect(row.category_version).toBe(0);expect(row.category_definition).not.toBe('{}');expect(JSON.parse(row.payload)).toEqual(input())});
 it('validates quantities, text and supported categories',()=>{for(const change of [{sqm:Infinity},{rooms:1.5},{notes:''},{notes:'x'.repeat(4001)},{category:'unknown'},{difficulty:'unknown'}])expect(()=>validateAssessment({...input(),...change})).toThrow()});
});
