import type {Database} from 'better-sqlite3';
import {MarginError} from './operationalMargin';
export const ASSESSMENT_EVIDENCE_SCHEMA=`
CREATE TABLE IF NOT EXISTS assessment_photos(photo_id TEXT PRIMARY KEY REFERENCES job_photos(id),assessment_id TEXT NOT NULL REFERENCES service_assessments(id),created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS assessment_photos_parent ON assessment_photos(assessment_id);
CREATE TABLE IF NOT EXISTS assessment_photo_reviews(id INTEGER PRIMARY KEY AUTOINCREMENT,assessment_id TEXT NOT NULL REFERENCES service_assessments(id),assessment_version INTEGER NOT NULL,photo_ids TEXT NOT NULL,decision TEXT NOT NULL CHECK(decision IN ('approved','rejected')),reason TEXT NOT NULL,actor_id TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TRIGGER IF NOT EXISTS assessment_photo_no_update BEFORE UPDATE ON assessment_photos BEGIN SELECT RAISE(ABORT,'Assessment evidence immutable'); END;
CREATE TRIGGER IF NOT EXISTS assessment_photo_no_delete BEFORE DELETE ON assessment_photos BEGIN SELECT RAISE(ABORT,'Assessment evidence retained'); END;
CREATE TRIGGER IF NOT EXISTS assessment_review_no_update BEFORE UPDATE ON assessment_photo_reviews BEGIN SELECT RAISE(ABORT,'Evidence review immutable'); END;
CREATE TRIGGER IF NOT EXISTS assessment_review_no_delete BEFORE DELETE ON assessment_photo_reviews BEGIN SELECT RAISE(ABORT,'Evidence review retained'); END;
CREATE TRIGGER IF NOT EXISTS assessment_photo_content_lock BEFORE UPDATE ON job_photos WHEN EXISTS(SELECT 1 FROM assessment_photos WHERE photo_id=OLD.id) BEGIN SELECT RAISE(ABORT,'Assessment photo cannot be reassigned or changed'); END;
`;
function assessment(db:Database,id:unknown,clientId:string|null){if(typeof id!=='string'||!id||id.length>100)throw new MarginError('Referință invalidă.');const r=db.prepare('SELECT client_id,version,status FROM service_assessments WHERE id=?').get(id) as {client_id:string;version:number;status:string}|undefined;if(!r||(clientId!==null&&r.client_id!==clientId))throw new MarginError('Cerere inexistentă.',404);return r;}
function photos(db:Database,id:string){return db.prepare("SELECT p.id,p.created_at FROM assessment_photos a JOIN job_photos p ON p.id=a.photo_id WHERE a.assessment_id=? AND p.status='VALID' AND p.validated_at IS NOT NULL ORDER BY p.id").all(id) as {id:string;created_at:string}[];}
export function attachAssessmentPhoto(db:Database,id:string,clientId:string,photoId:string){
 return db.transaction(()=>{const a=assessment(db,id,clientId);if(['cancelled','declined'].includes(a.status))throw new MarginError('Cererea este închisă.',409);if(photos(db,id).length>=10)throw new MarginError('Maximum 10 fotografii per cerere.',409);
 const p=db.prepare("SELECT 1 FROM job_photos WHERE id=? AND owner_user_id=? AND job_id IS NULL AND proof_type='CLIENT_CONTEXT' AND status='VALID' AND validated_at IS NOT NULL").get(photoId,clientId);if(!p)throw new MarginError('Fotografia nu este disponibilă pentru această cerere.',403);
 db.prepare('INSERT INTO assessment_photos VALUES(?,?,?)').run(photoId,id,new Date().toISOString());db.prepare('UPDATE service_assessments SET version=version+1 WHERE id=?').run(id);
 }).immediate();
}
export function readAssessmentEvidence(db:Database,id:string,clientId:string|null){const a=assessment(db,id,clientId);const items=photos(db,id);const review=db.prepare('SELECT * FROM assessment_photo_reviews WHERE assessment_id=? ORDER BY id DESC LIMIT 1').get(id) as {id:number;assessment_version:number;photo_ids:string;decision:string;reason:string;actor_id:string;created_at:string}|undefined;const current=review&&review.assessment_version===a.version&&review.photo_ids===JSON.stringify(items.map(p=>p.id));return {version:a.version,photos:items.map(p=>({...p,url:`/api/uploads/${p.id}`})),review:review?{id:review.id,decision:review.decision,current:Boolean(current),created_at:review.created_at,...(clientId===null?{reason:review.reason,actor_id:review.actor_id}:{})}:null};}
export function reviewAssessmentEvidence(db:Database,args:{id:unknown;version:unknown;decision:unknown;reason:unknown},actor:string){
 if(!actor||typeof args.reason!=='string'||!args.reason.trim()||args.reason.length>2000||!['approved','rejected'].includes(String(args.decision)))throw new MarginError('Completează decizia și motivul verificării.');
 return db.transaction(()=>{const a=assessment(db,args.id,null);if(a.version!==args.version||['cancelled','declined'].includes(a.status))throw new MarginError('Cererea s-a schimbat sau este închisă.',409);const items=photos(db,args.id as string);if(!items.length)throw new MarginError('Nu există fotografii valide de verificat.',409);db.prepare('INSERT INTO assessment_photo_reviews(assessment_id,assessment_version,photo_ids,decision,reason,actor_id,created_at) VALUES(?,?,?,?,?,?,?)').run(args.id,a.version,JSON.stringify(items.map(p=>p.id)),args.decision,(args.reason as string).trim(),actor,new Date().toISOString());return readAssessmentEvidence(db,args.id as string,null);}).immediate();
}
export function requireVerifiedAssessmentEvidence(db:Database,id:string){const evidence=readAssessmentEvidence(db,id,null);if(!evidence.photos.length||!evidence.review?.current||evidence.review.decision!=='approved')throw new MarginError('Sunt necesare fotografii verificate pentru versiunea curentă a cererii.',422);return {reviewId:evidence.review.id,photoIds:evidence.photos.map(p=>p.id)};}
