import type {Database} from 'better-sqlite3';
import {randomUUID} from 'node:crypto';
import {CATALOG_CATEGORIES} from './serviceCatalog';
import type {Assessment,AssessmentInput,AssessmentStatus,AssessmentMessage} from './assessmentShared';
export const ASSESSMENT_SCHEMA=`CREATE TABLE IF NOT EXISTS service_assessments(id TEXT PRIMARY KEY,client_id TEXT NOT NULL REFERENCES users(id),request_key TEXT NOT NULL,payload TEXT NOT NULL,category_version INTEGER NOT NULL,category_definition TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'submitted' CHECK(status IN ('submitted','needs_details','reviewed','declined','cancelled')),version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,UNIQUE(client_id,request_key));CREATE INDEX IF NOT EXISTS service_assessments_owner ON service_assessments(client_id,created_at);CREATE INDEX IF NOT EXISTS service_assessments_status ON service_assessments(status,created_at);CREATE TABLE IF NOT EXISTS service_assessment_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,assessment_id TEXT NOT NULL REFERENCES service_assessments(id),author TEXT NOT NULL CHECK(author IN ('client','admin')),body TEXT NOT NULL,created_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS service_assessment_messages_parent ON service_assessment_messages(assessment_id,id);`;
export class AssessmentError extends Error{constructor(message:string,public status=400){super(message)}}
function text(v:unknown,max:number){if(typeof v!=='string'||!v.trim()||v.length>max)throw new AssessmentError(`Text obligatoriu, maximum ${max} de caractere.`);return v.trim()}
export function validateAssessment(v:unknown):AssessmentInput{
 if(!v||typeof v!=='object'||Array.isArray(v))throw new AssessmentError('Cerere invalidă');const d=v as Record<string,unknown>;
 if(!CATALOG_CATEGORIES.some(c=>c[0]===d.category)||!['light','normal','heavy'].includes(String(d.difficulty)))throw new AssessmentError('Categoria sau dificultatea nu este validă');
 const n=(key:string,min=0,max=1000000)=>{if(!Number.isSafeInteger(d[key])||Number(d[key])<min||Number(d[key])>max)throw new AssessmentError('Cantitățile trebuie să fie numere întregi în limitele formularului.');return Number(d[key])};
 return {category:String(d.category),city:text(d.city,100),sqm:n('sqm',1),rooms:n('rooms',0,10000),bathrooms:n('bathrooms',0,10000),difficulty:d.difficulty as AssessmentInput['difficulty'],notes:text(d.notes,4000),appliances:n('appliances'),windowsSqm:n('windowsSqm'),linenSets:n('linenSets'),extraHours:n('extraHours',0,10000)};
}
export function createAssessment(db:Database,clientId:string,requestKey:unknown,value:unknown){const input=validateAssessment(value),key=text(requestKey,100),payload=JSON.stringify(input);return db.transaction(()=>{
 if(!db.prepare("SELECT 1 FROM users WHERE id=? AND role='client'").get(clientId))throw new AssessmentError('Acces interzis',403);
 const old=db.prepare('SELECT id,payload FROM service_assessments WHERE client_id=? AND request_key=?').get(clientId,key) as {id:string;payload:string}|undefined;
 if(old){if(old.payload!==payload)throw new AssessmentError('Identificator reutilizat pentru altă cerere.',409);return old.id}
 const catalog=db.prepare('SELECT version,definition FROM service_catalog_drafts WHERE key=?').get(input.category) as {version:number;definition:string}|undefined;if(!catalog)throw new AssessmentError('Categoria nu este disponibilă pentru evaluare.',404);
 const id=randomUUID();db.prepare('INSERT INTO service_assessments(id,client_id,request_key,payload,category_version,category_definition,created_at) VALUES(?,?,?,?,?,?,?)').run(id,clientId,key,payload,catalog.version,catalog.definition,new Date().toISOString());return id;
 })()}
export function listAssessments(db:Database,clientId:string|null):Assessment[]{const rows=db.prepare(`SELECT a.id,a.payload,a.status,a.version,a.created_at,u.name FROM service_assessments a JOIN users u ON u.id=a.client_id ${clientId===null?'':'WHERE a.client_id=?'} ORDER BY ${clientId===null?"CASE WHEN a.status IN ('submitted','needs_details') THEN 0 ELSE 1 END,":''} a.created_at DESC,a.id LIMIT 200`).all(...(clientId===null?[]:[clientId])) as {id:string;payload:string;status:AssessmentStatus;version:number;created_at:string;name:string}[];return rows.map(r=>({...JSON.parse(r.payload),id:r.id,status:r.status,version:r.version,createdAt:r.created_at,...(clientId===null?{clientName:r.name}:{}),messages:db.prepare('SELECT id,author,body,created_at AS createdAt FROM service_assessment_messages WHERE assessment_id=? ORDER BY id').all(r.id) as AssessmentMessage[]}));}
export function updateAssessment(db:Database,actor:{clientId:string}|{admin:true},id:unknown,version:unknown,action:unknown,body:unknown){
 const key=text(id,100);if(!Number.isSafeInteger(version)||Number(version)<1)throw new AssessmentError('Versiune invalidă');
 return db.transaction(()=>{const row=db.prepare('SELECT client_id,status,version FROM service_assessments WHERE id=?').get(key) as {client_id:string;status:AssessmentStatus;version:number}|undefined;if(!row||('clientId' in actor&&row.client_id!==actor.clientId))throw new AssessmentError('Cerere inexistentă',404);if(row.version!==version)throw new AssessmentError('Cererea a fost actualizată. Reîncarcă înainte de a continua.',409);
 let status:AssessmentStatus;let message:string;
 if('admin' in actor){if(!['submitted','needs_details'].includes(row.status)||!['needs_details','reviewed','declined'].includes(String(action)))throw new AssessmentError('Tranziție nepermisă',409);status=action as AssessmentStatus;message=text(body,4000)}else{if(!['submitted','needs_details'].includes(row.status))throw new AssessmentError('Cererea este închisă',409);if(action==='cancel'){status='cancelled';message='Cerere anulată de client.'}else if(action==='reply'){status='submitted';message=text(body,4000)}else throw new AssessmentError('Acțiune invalidă')}
 db.prepare('INSERT INTO service_assessment_messages(assessment_id,author,body,created_at) VALUES(?,?,?,?)').run(key,'admin' in actor?'admin':'client',message,new Date().toISOString());db.prepare('UPDATE service_assessments SET status=?,version=version+1 WHERE id=?').run(status,key);
 })();
}
