import {beforeEach,afterEach,it,expect} from 'vitest';
import Database from 'better-sqlite3';
import {ASSESSMENT_EVIDENCE_SCHEMA,attachAssessmentPhoto,readAssessmentEvidence,reviewAssessmentEvidence,requireVerifiedAssessmentEvidence} from './assessmentEvidence';
import {MANUAL_ESTIMATE_SCHEMA,saveManualEstimate} from './manualEstimates';
import {MANUAL_OFFERS_SCHEMA,publishManualOffer,decideManualOffer} from './manualOffers';
import {MARGIN_POLICY_SCHEMA,saveMarginPolicy} from './marginPolicy';
import {emptyManualEstimate,COST_CODES} from './operationalMargin';
let db:Database.Database;
function photo(id='p',owner='c'){db.prepare("INSERT INTO job_photos VALUES(?,?,NULL,'CLIENT_CONTEXT','VALID','2026-09-25','2026-09-25','photo.jpg')").run(id,owner);}
function review(decision='approved',version=2){return reviewAssessmentEvidence(db,{id:'a',version,decision,reason:'Fotografii verificate, motiv intern'},'verified-admin');}
function publish(){const d=emptyManualEstimate();d.lines=[{label:'Renovare',amountBani:50000}];d.reason='Calcul';d.provider={amountBani:30000,state:'confirmed',source:'Confirmare',recordedAt:new Date().toISOString()};for(const k of COST_CODES)d.costs[k]={...d.costs[k],amountBani:0,state:'confirmed',source:'Confirmare',recordedAt:new Date().toISOString()};saveManualEstimate(db,{id:'a',revision:0,assessmentVersion:2,definition:d},'admin');return publishManualOffer(db,{id:'a',revision:1,scope:'După renovare',reason:'Ofertă',expiresAt:'2036-01-01T00:00:00Z',policyRevision:1},'admin');}
beforeEach(()=>{db=new Database(':memory:');db.pragma('foreign_keys=ON');db.exec(`CREATE TABLE service_assessments(id TEXT PRIMARY KEY,client_id TEXT,version INTEGER,status TEXT,payload TEXT);INSERT INTO service_assessments VALUES('a','c',1,'submitted','{"category":"renovation","city":"București","sqm":100}'),('b','other',1,'submitted','{}');CREATE TABLE job_photos(id TEXT PRIMARY KEY,owner_user_id TEXT,job_id TEXT,proof_type TEXT,status TEXT,validated_at TEXT,created_at TEXT,filename TEXT);`+MANUAL_ESTIMATE_SCHEMA+MANUAL_OFFERS_SCHEMA+MARGIN_POLICY_SCHEMA+ASSESSMENT_EVIDENCE_SCHEMA);saveMarginPolicy(db,{revision:0,minBani:0,minBasisPoints:null,reason:'Test'},'admin');photo();});
afterEach(()=>db.close());
it('requires request and photograph ownership',()=>{expect(()=>attachAssessmentPhoto(db,'b','c','p')).toThrow(/inexistentă/);photo('foreign','other');expect(()=>attachAssessmentPhoto(db,'a','c','foreign')).toThrow(/disponibilă/);expect(()=>readAssessmentEvidence(db,'a','other')).toThrow(/inexistentă/);});
it('increments version and excludes internal review notes from client responses',()=>{attachAssessmentPhoto(db,'a','c','p');expect(readAssessmentEvidence(db,'a','c').version).toBe(2);review();expect(JSON.stringify(readAssessmentEvidence(db,'a','c'))).not.toMatch(/motiv intern|verified-admin/);expect(readAssessmentEvidence(db,'a',null).review).toMatchObject({current:true,reason:'Fotografii verificate, motiv intern'});});
it('invalidates evidence review after a new photo or changed request',()=>{attachAssessmentPhoto(db,'a','c','p');review();expect(requireVerifiedAssessmentEvidence(db,'a').photoIds).toEqual(['p']);photo('p2');attachAssessmentPhoto(db,'a','c','p2');expect(()=>requireVerifiedAssessmentEvidence(db,'a')).toThrow(/verificate/);review('approved',3);db.exec('UPDATE service_assessments SET version=4');expect(()=>requireVerifiedAssessmentEvidence(db,'a')).toThrow(/verificate/);});
it('requires at least one valid photo and rejects stale review decisions',()=>{expect(()=>review('approved',1)).toThrow(/fotografii/);attachAssessmentPhoto(db,'a','c','p');expect(()=>review('approved',1)).toThrow(/schimbat/);review('rejected');expect(()=>requireVerifiedAssessmentEvidence(db,'a')).toThrow(/verificate/);});
it('prevents reassignment, mutation and deletion of attached evidence',()=>{attachAssessmentPhoto(db,'a','c','p');expect(()=>db.exec("UPDATE job_photos SET job_id='j'")).toThrow(/reassigned/);expect(()=>db.exec("UPDATE job_photos SET filename='changed.jpg'")).toThrow(/changed/);expect(()=>db.exec('DELETE FROM job_photos')).toThrow();expect(()=>db.exec('DELETE FROM assessment_photos')).toThrow(/retained/);});
it('caps evidence at ten and blocks closed requests',()=>{for(let i=0;i<10;i++){photo('n'+i);attachAssessmentPhoto(db,'a','c','n'+i);}expect(()=>attachAssessmentPhoto(db,'a','c','p')).toThrow(/10/);db.exec("UPDATE service_assessments SET status='cancelled'");expect(()=>review('approved',11)).toThrow(/închisă/);});
it('refuses invalid images, job photos and repeated attachment',()=>{db.exec("UPDATE job_photos SET status='INVALID'");expect(()=>attachAssessmentPhoto(db,'a','c','p')).toThrow(/disponibilă/);db.exec("UPDATE job_photos SET status='VALID',job_id='j'");expect(()=>attachAssessmentPhoto(db,'a','c','p')).toThrow(/disponibilă/);db.exec('UPDATE job_photos SET job_id=NULL');attachAssessmentPhoto(db,'a','c','p');expect(()=>attachAssessmentPhoto(db,'a','c','p')).toThrow();expect(readAssessmentEvidence(db,'a','c').version).toBe(2);});
it('publishes renovation terms with the exact reviewed evidence and allows explicit acceptance',()=>{attachAssessmentPhoto(db,'a','c','p');const r=review(),o=publish();expect((o.terms as unknown as {evidence:{reviewId:number}}).evidence.reviewId).toBe(r.review!.id);expect(decideManualOffer(db,'c',{id:o.id,action:'accept',confirmed:true,totalBani:50000}).status).toBe('accepted');});
it('blocks acceptance if photo approval is revoked after publication',()=>{attachAssessmentPhoto(db,'a','c','p');review();const o=publish();review('rejected');expect(()=>decideManualOffer(db,'c',{id:o.id,action:'accept',confirmed:true,totalBani:50000})).toThrow(/verificate/);});
it('retains review history and rolls back a review if enclosing audit fails',()=>{attachAssessmentPhoto(db,'a','c','p');expect(()=>db.transaction(()=>{review();throw Error('audit');}).immediate()).toThrow();expect(readAssessmentEvidence(db,'a','c').review).toBeNull();review();expect(()=>db.exec("UPDATE assessment_photo_reviews SET decision='rejected'")).toThrow(/immutable/);expect(()=>db.exec('DELETE FROM assessment_photo_reviews')).toThrow(/retained/);});
