import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import Database from 'better-sqlite3';
import {BOOKING_QUOTES_SCHEMA,managedBookingEnabled,bookingPriceContext,issueBookingQuote,acceptedBookingQuote,linkBookingQuote} from './bookingQuotes';
import {MANAGED_PRICING_SCHEMA,createTariff,simulateTariff,publishTariff,withdrawTariff,saveTariff} from './managedPricingStore';
import {readPublishedPrice} from './publishedPrice';
let db:Database.Database;
const now=new Date('2026-10-01T09:00:00Z');
const context=bookingPriceContext({city:'București',spaceType:'apartament',sqm:80,windowsSqm:10,mode:'standard'});
function tariff(){const t=createTariff(db,'Baseline',undefined,new Date(now.getTime()-1000));const s=simulateTariff(db,t.id,0);return publishTariff(db,t.id,0,s.simulationId,now.toISOString(),null,now);}
beforeEach(()=>{db=new Database(':memory:');db.pragma('foreign_keys=ON');db.exec("CREATE TABLE users(id TEXT PRIMARY KEY,role TEXT,credit_balance REAL);CREATE TABLE jobs(id TEXT PRIMARY KEY);INSERT INTO users VALUES('c','client',20),('other','client',0);"+MANAGED_PRICING_SCHEMA+BOOKING_QUOTES_SCHEMA);});
afterEach(()=>{db.close();vi.unstubAllEnvs();});
describe('persisted booking quotes',()=>{
 it('starts disabled and cannot be enabled on LIVE or with a live Stripe key',()=>{vi.stubEnv('NITIDO_MANAGED_PRICING_SANDBOX','');expect(managedBookingEnabled()).toBe(false);vi.stubEnv('NITIDO_MANAGED_PRICING_SANDBOX','true');vi.stubEnv('NEXT_PUBLIC_SITE_URL','https://nitido.ro');expect(managedBookingEnabled()).toBe(false);vi.stubEnv('NEXT_PUBLIC_SITE_URL','https://sandbox.nitido.ro');vi.stubEnv('STRIPE_SECRET_KEY','sk_live_example');expect(managedBookingEnabled()).toBe(false);vi.stubEnv('STRIPE_SECRET_KEY','sk_test_example');expect(managedBookingEnabled()).toBe(true);});
 it('records lines, version, credit once and an explicit expiry',()=>{tariff();const q=issueBookingQuote(db,'c',context,now);expect(q.pricing).toMatchObject({grossBani:63000,creditBani:2000,clientTotalBani:61000,expiresAt:'2026-10-01T09:15:00.000Z'});expect(readPublishedPrice(JSON.stringify(q.pricing))).not.toBeNull();expect(q.pricing.version).toMatch(/^managed:/);});
 it('preserves the issued price after withdrawal and replacement',()=>{const old=tariff(),q=issueBookingQuote(db,'c',context,now);withdrawTariff(db,old.id,old.revision,'Replaced');const t=createTariff(db,'New');t.definition.rules.apartament={method:'sqm',rateBani:1000,minimumBani:0};const saved=saveTariff(db,t.id,0,t.definition,t.scope,t.label);const sim=simulateTariff(db,saved.id,saved.revision);publishTariff(db,saved.id,saved.revision,sim.simulationId,now.toISOString(),null,now);expect(issueBookingQuote(db,'c',context,now).pricing.grossBani).toBe(88000);expect(acceptedBookingQuote(db,'c',q.id,context,now).snapshot.grossBani).toBe(63000);});
 it('rejects expiry exactly at deadline and rejects another client',()=>{tariff();const q=issueBookingQuote(db,'c',context,now);expect(()=>acceptedBookingQuote(db,'c',q.id,context,new Date(q.expiresAt))).toThrow(/expirat/);expect(()=>acceptedBookingQuote(db,'other',q.id,context,now)).toThrow(/cont/);});
 it.each([{sqm:81},{city:'iasi'},{mode:'express' as const},{express60:true},{windowsSqm:11}])('requires a fresh offer for changed context %o',change=>{tariff();const q=issueBookingQuote(db,'c',context,now);expect(()=>acceptedBookingQuote(db,'c',q.id,{...context,...change},now)).toThrow(/schimbat/);});
 it('rechecks current credit but never silently applies additional credit',()=>{tariff();const q=issueBookingQuote(db,'c',context,now);db.exec("UPDATE users SET credit_balance=10 WHERE id='c'");expect(()=>acceptedBookingQuote(db,'c',q.id,context,now)).toThrow(/Creditul/);db.exec("UPDATE users SET credit_balance=30 WHERE id='c'");expect(acceptedBookingQuote(db,'c',q.id,context,now).snapshot.creditBani).toBe(2000);});
 it('binds once, replays after expiry and preserves immutable history',()=>{tariff();const q=issueBookingQuote(db,'c',context,now);db.exec("INSERT INTO jobs VALUES('job'),('otherjob')");linkBookingQuote(db,'c',q.id,'job');expect(acceptedBookingQuote(db,'c',q.id,context,new Date('2027-01-01Z')).jobId).toBe('job');expect(()=>linkBookingQuote(db,'c',q.id,'otherjob')).toThrow(/folosită/);expect(()=>db.exec("UPDATE booking_price_quotes SET snapshot_json='{}'")).toThrow(/immutable/);expect(()=>db.exec('DELETE FROM booking_price_quotes')).toThrow(/retained/);});
 it('rolls back binding when the enclosing job transaction fails',()=>{tariff();const q=issueBookingQuote(db,'c',context,now);expect(()=>db.transaction(()=>{db.exec("INSERT INTO jobs VALUES('job')");linkBookingQuote(db,'c',q.id,'job');throw Error('rollback');}).immediate()).toThrow('rollback');expect(acceptedBookingQuote(db,'c',q.id,context,now).jobId).toBeNull();expect(db.prepare('SELECT * FROM jobs').all()).toEqual([]);});
 it('never falls back for missing or manual tariff',()=>{expect(()=>issueBookingQuote(db,'c',context,now)).toThrow(/Nu există/);const t=createTariff(db,'Manual');t.definition.rules.apartament={method:'manual'};const s=saveTariff(db,t.id,0,t.definition,t.scope,t.label),sim=simulateTariff(db,s.id,s.revision);publishTariff(db,s.id,s.revision,sim.simulationId,now.toISOString(),null,now);expect(()=>issueBookingQuote(db,'c',context,now)).toThrow(/manuală/);});
 it.each(['zone','contractId','hours'])('does not trust client supplied %s',key=>{expect(()=>bookingPriceContext({...context,[key]:'spoof'})).toThrow(/nu validează/);});
 it('does not bypass applicable zone tariffs',()=>{tariff();const t=createTariff(db,'Zone'),s=saveTariff(db,t.id,0,t.definition,{kind:'zone',city:'Bucuresti',zone:'1'},t.label),sim=simulateTariff(db,s.id,s.revision);publishTariff(db,s.id,s.revision,sim.simulationId,now.toISOString(),null,now);expect(()=>issueBookingQuote(db,'c',context,now)).toThrow(/zone/);});
});
