import {describe,it,expect} from 'vitest';
import {saveBookingDraft,takeBookingDraft,clearBookingDraft,BOOKING_DRAFT_TTL,type BookingDraft} from './bookingDraft';
function memory(){let value:string|null=null;return{getItem:()=>value,setItem:(_key:string,raw:string)=>{value=raw;},removeItem:()=>{value=null;}};}
const draft:BookingDraft={street:'Strada test 1',postalCode:'123456',city:'Brașov',floor:'2',details:'Instrucțiuni test',sqm:60,spaceType:'apartament',whenType:'scheduled',mode:'express',express60:false,scheduledDate:'2026-09-20',scheduledHour:14,propertyId:'property-1',approvalId:'approval-1',photos:[{id:'photo-1',url:'/api/uploads/photo-1',room:'kitchen'}]};
describe('booking continuity across external card setup',()=>{
 it('restores all booking inputs once, including photos and references',()=>{const s=memory();expect(saveBookingDraft(s,'client-1',draft,1000)).toBe(true);expect(takeBookingDraft(s,'client-1',2000)).toEqual(draft);expect(takeBookingDraft(s,'client-1',2000)).toBeNull();});
 it('does not expose a previous client draft to another account',()=>{const s=memory();saveBookingDraft(s,'client-1',draft,1000);expect(takeBookingDraft(s,'client-2',2000)).toBeNull();expect(s.getItem()).toBeNull();});
 it.each([1000+BOOKING_DRAFT_TTL+1,999])('rejects stale or future timestamp at %s',now=>{const s=memory();saveBookingDraft(s,'client-1',draft,1000);expect(takeBookingDraft(s,'client-1',now)).toBeNull();});
 it.each(['bad-json','null','[]',JSON.stringify({version:2}), 'x'.repeat(40001)])('rejects corrupt or unsupported storage',raw=>{const s=memory();s.setItem('',raw);expect(takeBookingDraft(s,'client-1')).toBeNull();});
 it.each([{sqm:NaN},{sqm:1001},{scheduledDate:'2026-02-30'},{scheduledHour:13},{mode:'other'},{photos:[{id:'../private',url:'/private',room:null}]}])('rejects invalid persisted input %j',change=>{expect(saveBookingDraft(memory(),'client-1',{...draft,...change} as BookingDraft)).toBe(false);});
 it('reconstructs private photo URLs and ignores injected financial/authentication state',()=>{const s=memory();s.setItem('',JSON.stringify({version:1,userId:'client-1',savedAt:1000,draft:{...draft,price:1,hasCard:true,role:'admin',photos:[{id:'photo-1',url:'https://external.invalid/image',room:null}]}}));const restored=takeBookingDraft(s,'client-1',2000);expect(restored?.photos[0].url).toBe('/api/uploads/photo-1');expect(restored).not.toHaveProperty('price');expect(restored).not.toHaveProperty('hasCard');expect(restored).not.toHaveProperty('role');});
 it('fails safely when storage is unavailable instead of authorizing navigation',()=>{const fail=()=>{throw new Error('storage disabled');};const s={getItem:fail,setItem:fail,removeItem:fail};expect(saveBookingDraft(s,'client-1',draft)).toBe(false);expect(takeBookingDraft(s,'client-1')).toBeNull();expect(()=>clearBookingDraft(s)).not.toThrow();});
 it('removes a saved draft after successful publication or unrelated setup',()=>{const s=memory();saveBookingDraft(s,'client-1',draft);clearBookingDraft(s);expect(takeBookingDraft(s,'client-1')).toBeNull();});
});

it('preserves only the local card choice across Checkout and revalidates it on publication',()=>{const storage=memory();expect(saveBookingDraft(storage,'client-1',{...draft,cardId:'card_choice'},1000)).toBe(true);expect(takeBookingDraft(storage,'client-1',2000)?.cardId).toBe('card_choice');expect(saveBookingDraft(storage,'client-1',{...draft,cardId:'../bad'},1000)).toBe(false);});
