import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import Sqlite from 'better-sqlite3';
import type Stripe from 'stripe';
import {createHash} from 'node:crypto';
import {SCHEMA_SQL} from './db';
import {cardConfirmation} from './cardConfirmation';
let db:Sqlite.Database;
const retrieve=vi.fn(),stripe={paymentIntents:{retrieve}} as unknown as Stripe;
function intent(extra:Record<string,unknown>={}){return {id:'pi_test',amount:50000,currency:'ron',customer:'cus_test',payment_method:'pm_test',capture_method:'manual',metadata:{jobId:'j',paymentId:'p'},status:'requires_action',client_secret:'fixture_client_secret',...extra};}
beforeEach(()=>{vi.resetAllMocks();vi.stubEnv('STRIPE_SECRET_KEY','sk_test_fixture');vi.stubEnv('NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY','pk_test_fixture');db=new Sqlite(':memory:');db.exec(SCHEMA_SQL);db.exec("ALTER TABLE users ADD COLUMN stripe_customer_id TEXT;INSERT INTO users(id,role,name,stripe_customer_id) VALUES('u','client','Client','cus_test');INSERT INTO jobs(id,client_id,street,city,sqm,space_type,when_type,price_gross,duration_minutes,status) VALUES('j','u','Test','Test',50,'apartament','asap',500,120,'waiting')");db.prepare("INSERT INTO payment_authorization_attempts(job_id,request_json,provider_key_hash,created_ms,stripe_payment_intent_id,status) VALUES(?,?,?,1,'pi_test','requires_action')").run('j',JSON.stringify({amount:50000,currency:'ron',customer:'cus_test',payment_method:'pm_test',metadata:{paymentId:'p',jobId:'j'}}),createHash('sha256').update('sk_test_fixture').digest('hex'));retrieve.mockResolvedValue(intent());});
afterEach(()=>{db.close();vi.unstubAllEnvs()});
describe('owner-bound 3DS confirmation',()=>{
 it('returns confirmation credentials only for the booking owner',async()=>{await expect(cardConfirmation(db,stripe,'other','j','start')).rejects.toThrow('găsită');expect(retrieve).not.toHaveBeenCalled();const result=await cardConfirmation(db,stripe,'u','j','start');expect(result).toMatchObject({status:'requires_action',amountMinor:50000,clientSecret:'fixture_client_secret',paymentMethodId:'pm_test'});expect(db.prepare('SELECT * FROM payments').all()).toHaveLength(0)});
 it('does not return the secret during verification',async()=>{expect(await cardConfirmation(db,stripe,'u','j','verify')).toEqual({status:'requires_action',amountMinor:50000})});
 it('persists only a server-confirmed full hold, idempotently, without allocating a firm',async()=>{retrieve.mockResolvedValue(intent({status:'requires_capture',amount_capturable:50000}));await cardConfirmation(db,stripe,'u','j','verify');await cardConfirmation(db,stripe,'u','j','verify');expect(db.prepare('SELECT status,amount_gross FROM payments').all()).toEqual([{status:'authorized',amount_gross:500}]);expect(db.prepare('SELECT status,accepted_firm_id FROM jobs').get()).toEqual({status:'waiting',accepted_firm_id:null})});
 it.each([{customer:'cus_other'},{amount:49000},{currency:'eur'},{capture_method:'automatic'},{metadata:{jobId:'other',paymentId:'p'}},{payment_method:'pm_other'}])('rejects inconsistent intent %j',async mismatch=>{retrieve.mockResolvedValue(intent(mismatch));await expect(cardConfirmation(db,stripe,'u','j','start')).rejects.toThrow();expect(db.prepare('SELECT * FROM payments').all()).toHaveLength(0)});
 it('does not claim a processing payment succeeded',async()=>{retrieve.mockResolvedValue(intent({status:'processing'}));await expect(cardConfirmation(db,stripe,'u','j','verify')).rejects.toThrow();expect(db.prepare('SELECT * FROM payments').all()).toHaveLength(0)});
 it('rejects cancelled bookings before reading Stripe',async()=>{db.exec("UPDATE jobs SET status='cancelled'");await expect(cardConfirmation(db,stripe,'u','j','start')).rejects.toThrow();expect(retrieve).not.toHaveBeenCalled()});
 it('rechecks booking changes after the provider call',async()=>{retrieve.mockImplementation(async()=>{db.exec("UPDATE jobs SET status='cancelled'");return intent()});await expect(cardConfirmation(db,stripe,'u','j','start')).rejects.toThrow('schimbat')});
 it('rejects mixed live/test public keys',async()=>{vi.stubEnv('NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY','pk_live_fixture');await expect(cardConfirmation(db,stripe,'u','j','start')).rejects.toThrow('configurată')});
 it('allows authentication_required on a saved card, but not an ordinary card decline',async()=>{retrieve.mockResolvedValue(intent({status:'requires_payment_method',last_payment_error:{code:'authentication_required'}}));expect(await cardConfirmation(db,stripe,'u','j','start')).toHaveProperty('clientSecret');retrieve.mockResolvedValue(intent({status:'requires_payment_method',last_payment_error:{code:'card_declined'}}));await expect(cardConfirmation(db,stripe,'u','j','start')).rejects.toThrow()});
});
