import type {Database} from 'better-sqlite3';
import {CatalogError} from './serviceCatalog';
import {firmCoversCity} from './text';
export const CATALOG_CAPACITY_SCHEMA=`CREATE TABLE IF NOT EXISTS service_catalog_firms(category_key TEXT NOT NULL REFERENCES service_catalog_drafts(key),firm_id TEXT NOT NULL REFERENCES firms(id),enabled INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(category_key,firm_id));`;
export function setCatalogFirm(db:Database,key:string,firmId:string,enabled:boolean){
 if(typeof enabled!=='boolean'||!firmId)throw new CatalogError('Asociere invalidă');
 return db.transaction(()=>{if(!db.prepare('SELECT 1 FROM service_catalog_drafts WHERE key=?').get(key)||!db.prepare('SELECT 1 FROM firms WHERE id=?').get(firmId))throw new CatalogError('Categoria sau firma nu există',404);const old=db.prepare('SELECT enabled FROM service_catalog_firms WHERE category_key=? AND firm_id=?').get(key,firmId) as {enabled:number}|undefined;if(Boolean(old?.enabled)===enabled)return false;db.prepare('INSERT INTO service_catalog_firms(category_key,firm_id,enabled) VALUES(?,?,?) ON CONFLICT(category_key,firm_id) DO UPDATE SET enabled=excluded.enabled,updated_at=CURRENT_TIMESTAMP').run(key,firmId,enabled?1:0);return true})();
}
export function catalogCapacity(db:Database,key:string,city:string,interval?:{start:string;end:string},now=Date.now()){
 if(!db.prepare('SELECT 1 FROM service_catalog_drafts WHERE key=?').get(key))throw new CatalogError('Categorie inexistentă',404);
 if(typeof city!=='string'||city.length>100)throw new CatalogError('Localitate invalidă');
 const start=interval?Date.parse(interval.start):null,end=interval?Date.parse(interval.end):null;
 if(interval&&(!Number.isFinite(start)||!Number.isFinite(end)||end!<=start!||start!<now||end!-start!>31*86400000))throw new CatalogError('Interval viitor invalid sau mai mare de 31 de zile');
 const rows=db.prepare(`SELECT f.id,u.name,f.verified,f.suspended_until,f.coverage_city,f.coverage_cities_extra,COALESCE(c.enabled,0) configured FROM firms f JOIN users u ON u.id=f.user_id LEFT JOIN service_catalog_firms c ON c.firm_id=f.id AND c.category_key=? ORDER BY u.name,f.id`).all(key) as {id:string;name:string;verified:number;suspended_until:string|null;coverage_city:string;coverage_cities_extra:string|null;configured:number}[];
 return rows.map(f=>{
  const reasons:string[]=[];if(!f.configured)reasons.push('Categoria nu este asociată');if(!f.verified)reasons.push('Firma nu este verificată');if(f.suspended_until&&(!Number.isFinite(Date.parse(f.suspended_until))||Date.parse(f.suspended_until)>now))reasons.push('Firma este suspendată sau starea suspendării este invalidă');if(!city.trim())reasons.push('Alege localitatea');else if(!firmCoversCity(f.coverage_city,f.coverage_cities_extra,city))reasons.push('Localitate neacoperită');
  const teams=db.prepare('SELECT id,name FROM workspace_teams WHERE firm_id=? AND active=1').all(f.id) as {id:string;name:string}[];
  const free=teams.filter(t=>{if(!interval)return true;const blocks=db.prepare('SELECT starts_at,ends_at FROM workspace_team_blocks WHERE team_id=? AND cancelled=0').all(t.id) as {starts_at:string;ends_at:string}[];if(blocks.some(b=>{const a=Date.parse(b.starts_at),z=Date.parse(b.ends_at);return !Number.isFinite(a)||!Number.isFinite(z)||a<end!&&z>start!}))return false;const jobs=db.prepare("SELECT j.scheduled_at,j.duration_minutes,j.buffer_minutes FROM workspace_assignments a JOIN jobs j ON j.id=a.job_id WHERE a.team_id=? AND j.status IN ('accepted','arrived')").all(t.id) as {scheduled_at:string|null;duration_minutes:number;buffer_minutes:number}[];return !jobs.some(j=>{const a=Date.parse(j.scheduled_at??''),duration=j.duration_minutes+j.buffer_minutes,z=a+duration*60000;return !Number.isFinite(a)||!Number.isFinite(z)||duration<=0||a<end!&&z>start!})});
  if(interval){const unplanned=db.prepare("SELECT j.scheduled_at,j.duration_minutes,j.buffer_minutes FROM jobs j WHERE j.accepted_firm_id=? AND j.status IN ('accepted','arrived') AND NOT EXISTS(SELECT 1 FROM workspace_assignments a JOIN workspace_teams t ON t.id=a.team_id WHERE a.job_id=j.id AND t.active=1 AND t.firm_id=j.accepted_firm_id)").all(f.id) as {scheduled_at:string|null;duration_minutes:number;buffer_minutes:number}[];if(unplanned.some(j=>{const a=Date.parse(j.scheduled_at??''),z=a+(j.duration_minutes+j.buffer_minutes)*60000;return !Number.isFinite(a)||!Number.isFinite(z)||z<=a||a<end!&&z>start!}))reasons.push('Există lucrări fără echipă alocată în interval; planificarea trebuie completată');}
  if(!teams.length)reasons.push('Nicio echipă activă');else if(interval&&!free.length)reasons.push('Toate echipele sunt ocupate în interval');
  return {id:f.id,name:f.name,configured:Boolean(f.configured),eligible:reasons.length===0,reasons,coverageCity:f.coverage_city,activeTeams:teams.length,availableTeams:interval?free.length:null};
 });
}
