import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import Database from 'better-sqlite3';
import {SCHEMA_SQL} from './db';
import {WORKSPACE_SCHEMA,saveProperty,assignTeam,setChecklist} from './workspace';
import {acceptInvite,createInvite,revokeMember,executionAccess,createApproval,decideApproval,consumeApproval,enforcePropertyBudget,submitExecutionReport} from './collaborationAccess';
import {calcGrossPrice} from './pricing';
let db:Database.Database,p:string;
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-09-11T08:00:00Z'));db=new Database(':memory:');db.pragma('foreign_keys=ON');db.exec(SCHEMA_SQL);db.exec(WORKSPACE_SCHEMA);db.exec("INSERT INTO users(id,role,name,email) VALUES('a','client','Owner','owner@test.ro'),('b','client','Worker','worker@test.ro'),('c','client','Other','other@test.ro'),('f','firma','Firm','firm@test.ro');INSERT INTO firms(id,user_id,coverage_city) VALUES('firm','f','București');INSERT INTO workspace_teams(id,firm_id,name) VALUES('t','firm','Team'),('t2','firm','Other')");p=saveProperty(db,'a',{name:'Office',city:'București',street:'Test 1',sqm:75,space_type:'apartament',kind:'business',budget_bani:1000000})});
afterEach(()=>{db.close();vi.useRealTimers()});
function job(id='j',date='2026-09-12T09:00:00Z'){db.prepare("INSERT INTO jobs(id,client_id,street,city,sqm,space_type,when_type,scheduled_at,price_gross,credit_applied,duration_minutes,status,accepted_firm_id) VALUES(?,'a','Test 1','București',75,'apartament','scheduled',?,?,25,120,'accepted','firm')").run(id,date,calcGrossPrice('apartament',75))}
function member(kind='team',resource='t',role='worker'){const i=createInvite(db,kind==='team'?'f':'a',kind,resource,'worker@test.ro',role);acceptInvite(db,'b',i.token);return i;}
function approval(){return createApproval(db,'a',{propertyId:p,date:'2026-09-12',note:'Clean',requestKey:'req'})}
describe('collaboration access boundaries',()=>{
 it('binds invitations to email, hashes secrets and rejects outsiders',()=>{const i=createInvite(db,'f','team','t','worker@test.ro','worker');expect(()=>acceptInvite(db,'c',i.token)).toThrow(/email/);expect(JSON.stringify(db.prepare('SELECT * FROM workspace_invites').all())).not.toContain(i.token);expect(()=>createInvite(db,'c','team','t','other@test.ro','worker')).toThrow();acceptInvite(db,'b',i.token);acceptInvite(db,'b',i.token);expect(db.prepare('SELECT * FROM workspace_members').all()).toHaveLength(1)});
 it('expires invitations and revokes accepted links without allowing reactivation',()=>{const i=member();const m=db.prepare('SELECT id FROM workspace_members').get() as {id:string};revokeMember(db,'f',m.id);expect(()=>acceptInvite(db,'b',i.token)).toThrow();const fresh=createInvite(db,'f','team','t','worker@test.ro','worker');vi.advanceTimersByTime(8*86400000);expect(()=>acceptInvite(db,'b',fresh.token)).toThrow()});
 it('resolves assignment and revocation immediately, independently of marketplace role',()=>{job();member();expect(executionAccess(db,'b','j')).toBeNull();assignTeam(db,'f','t','j');expect(executionAccess(db,'b','j')?.firm_id).toBe('firm');setChecklist(db,'b','j','floors',true);assignTeam(db,'f','t2','j');expect(executionAccess(db,'b','j')).toBeNull();expect(()=>setChecklist(db,'b','j','floors',false)).toThrow();expect(executionAccess(db,'c','j')).toBeNull()});
 it('requires all checklist items and both validated proofs before a report',()=>{job();member();assignTeam(db,'f','t','j');db.exec("UPDATE jobs SET status='arrived'");expect(()=>submitExecutionReport(db,'b','j','')).toThrow();for(const key of ['surfaces','kitchen','bathroom','floors','waste','inspection'])setChecklist(db,'b','j',key,true);for(const type of ['ARRIVAL','COMPLETION'])db.prepare("INSERT INTO job_photos(id,job_id,filename,proof_type,uploaded_by_firm_id,status,validated_at) VALUES(?,'j','test.jpg',?,'firm','VALID',datetime('now'))").run(type,type);submitExecutionReport(db,'b','j','Done');expect(db.prepare("SELECT status FROM jobs WHERE id='j'").get()).toEqual({status:'arrived'});expect(db.prepare('SELECT * FROM workspace_execution_reports').all()).toHaveLength(1)});
});
describe('business approval and booking atomicity',()=>{
 it('allows managers to request but only owners to decide; viewers cannot request',()=>{member('property',p,'manager');const id=createApproval(db,'b',{propertyId:p,date:'2026-09-12',note:'',requestKey:'b'});expect(()=>decideApproval(db,'b',id,true,'')).toThrow();decideApproval(db,'a',id,true,'');db.exec("UPDATE workspace_members SET role='viewer'");expect(()=>createApproval(db,'b',{propertyId:p,date:'2026-09-12',note:'',requestKey:'c'})).toThrow()});
 it('deduplicates requests and rejects changed contents',()=>{const id=approval();expect(approval()).toBe(id);expect(()=>createApproval(db,'a',{propertyId:p,date:'2026-09-13',note:'Clean',requestKey:'req'})).toThrow();expect(()=>createApproval(db,'a',{propertyId:p,date:'2026-02-31',note:'',requestKey:'bad'})).toThrow()});
 it('holds budget for approvals and blocks overspending',()=>{const price=calcGrossPrice('apartament',75)*100;db.prepare('UPDATE workspace_properties SET budget_enforced=1,budget_bani=?').run(price);const id=approval();decideApproval(db,'a',id,true,'');const second=createApproval(db,'a',{propertyId:p,date:'2026-09-13',note:'',requestKey:'next'});expect(()=>decideApproval(db,'a',second,true,'')).toThrow(/Buget/)});
 it('consumes exactly once at full price even when credit was used, without double counting hold',()=>{const price=calcGrossPrice('apartament',75)*100;db.prepare('UPDATE workspace_properties SET budget_enforced=1,budget_bani=?').run(price);const id=approval();decideApproval(db,'a',id,true,'');job();db.transaction(()=>{consumeApproval(db,'a',id,'j');enforcePropertyBudget(db,p,'j')})();expect(()=>consumeApproval(db,'a',id,'j')).toThrow();expect(db.prepare('SELECT status FROM workspace_approvals').get()).toEqual({status:'fulfilled'})});
 it('rolls back a changed-price booking and keeps the approval usable',()=>{const id=approval();decideApproval(db,'a',id,true,'');expect(()=>db.transaction(()=>{job();db.exec('UPDATE jobs SET price_gross=999');consumeApproval(db,'a',id,'j')})()).toThrow(/prețul/);expect(db.prepare('SELECT * FROM jobs').all()).toHaveLength(0);expect(db.prepare('SELECT status FROM workspace_approvals').get()).toEqual({status:'approved'})});
 it('releases an approved budget hold when owner withdraws approval',()=>{const id=approval();decideApproval(db,'a',id,true,'');decideApproval(db,'a',id,false,'Plans changed');job();expect(()=>consumeApproval(db,'a',id,'j')).toThrow();expect(db.prepare('SELECT status FROM workspace_approvals').get()).toEqual({status:'rejected'})});
 it('rejects booking at an address changed after the request',()=>{const id=approval();decideApproval(db,'a',id,true,'');job();db.exec("UPDATE workspace_properties SET street='Changed';UPDATE jobs SET street='Changed'");expect(()=>consumeApproval(db,'a',id,'j')).toThrow(/Detaliile/)});
 it('checks direct bookings against approved holds',()=>{db.prepare('UPDATE workspace_properties SET budget_enforced=1,budget_bani=?').run(calcGrossPrice('apartament',75)*100);const id=approval();decideApproval(db,'a',id,true,'');job();db.prepare('INSERT INTO workspace_property_jobs VALUES(?,?)').run('j',p);expect(()=>enforcePropertyBudget(db,p,'j')).toThrow(/Buget/)});
});
