import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import Database from 'better-sqlite3';
import {initializeDatabase} from './db';
import {saveProperty,assignTeam,setChecklist} from './workspace';
import {acceptInvite,createInvite,revokeMember,executionAccess,createApproval,decideApproval,consumeApproval,enforcePropertyBudget,submitExecutionReport,executionReportRecord} from './collaborationAccess';
import {calcGrossPrice} from './pricing';
let db:Database.Database,p:string;
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-09-11T08:00:00Z'));db=new Database(':memory:');db.pragma('foreign_keys=ON');initializeDatabase(db);db.exec("INSERT INTO users(id,role,name,email) VALUES('a','client','Owner','owner@test.ro'),('b','client','Worker','worker@test.ro'),('c','client','Other','other@test.ro'),('f','firma','Firm','firm@test.ro');INSERT INTO firms(id,user_id,coverage_city) VALUES('firm','f','București');INSERT INTO workspace_teams(id,firm_id,name) VALUES('t','firm','Team'),('t2','firm','Other')");p=saveProperty(db,'a',{name:'Office',city:'București',street:'Test 1',sqm:75,space_type:'apartament',kind:'business',budget_bani:1000000})});
afterEach(()=>{db.close();vi.useRealTimers()});
function job(id='j',date='2026-09-12T09:00:00Z'){db.prepare("INSERT INTO jobs(id,client_id,street,city,sqm,space_type,when_type,scheduled_at,price_gross,credit_applied,duration_minutes,status,accepted_firm_id) VALUES(?,'a','Test 1','București',75,'apartament','scheduled',?,?,25,120,'accepted','firm')").run(id,date,calcGrossPrice('apartament',75))}
function member(kind='team',resource='t',role='worker'){const i=createInvite(db,kind==='team'?'f':'a',kind,resource,'worker@test.ro',role);acceptInvite(db,'b',i.token);return i;}
function approval(){return createApproval(db,'a',{propertyId:p,date:'2026-09-12',note:'Clean',requestKey:'req'})}
describe('collaboration access boundaries',()=>{
 it('binds invitations to email, hashes secrets and rejects outsiders',()=>{const i=createInvite(db,'f','team','t','worker@test.ro','worker');expect(()=>acceptInvite(db,'c',i.token)).toThrow(/email/);expect(JSON.stringify(db.prepare('SELECT * FROM workspace_invites').all())).not.toContain(i.token);expect(()=>createInvite(db,'c','team','t','other@test.ro','worker')).toThrow();acceptInvite(db,'b',i.token);acceptInvite(db,'b',i.token);expect(db.prepare('SELECT * FROM workspace_members').all()).toHaveLength(1)});
 it('expires invitations and revokes accepted links without allowing reactivation',()=>{const i=member();const m=db.prepare('SELECT id FROM workspace_members').get() as {id:string};revokeMember(db,'f',m.id);expect(()=>acceptInvite(db,'b',i.token)).toThrow();const fresh=createInvite(db,'f','team','t','worker@test.ro','worker');vi.advanceTimersByTime(8*86400000);expect(()=>acceptInvite(db,'b',fresh.token)).toThrow()});
 it('resolves assignment and revocation immediately, independently of marketplace role',()=>{job();member();expect(executionAccess(db,'b','j')).toBeNull();assignTeam(db,'f','t','j');expect(executionAccess(db,'b','j')?.firm_id).toBe('firm');setChecklist(db,'b','j','floors',true);assignTeam(db,'f','t2','j');expect(executionAccess(db,'b','j')).toBeNull();expect(()=>setChecklist(db,'b','j','floors',false)).toThrow();expect(executionAccess(db,'c','j')).toBeNull()});
 it('requires all checklist items and both validated proofs before a report',()=>{job();member();assignTeam(db,'f','t','j');db.exec("UPDATE jobs SET status='arrived'");expect(()=>submitExecutionReport(db,'b','j','')).toThrow();for(const key of ['surfaces','kitchen','bathroom','floors','waste','inspection'])setChecklist(db,'b','j',key,true);for(const type of ['ARRIVAL','COMPLETION'])db.prepare("INSERT INTO job_photos(id,job_id,filename,proof_type,uploaded_by_firm_id,status,validated_at) VALUES(?,'j','test.jpg',?,'firm','VALID',datetime('now'))").run(type,type);submitExecutionReport(db,'b','j','Done');expect(()=>setChecklist(db,'b','j','floors',false)).toThrow(/Raportul a fost trimis/);expect(db.prepare("SELECT status FROM jobs WHERE id='j'").get()).toEqual({status:'arrived'});expect(db.prepare('SELECT * FROM workspace_execution_reports').all()).toHaveLength(1)});
});
describe('business approval and booking atomicity',()=>{
 it('allows managers to request but only owners to decide; viewers cannot request',()=>{member('property',p,'manager');const id=createApproval(db,'b',{propertyId:p,date:'2026-09-12',note:'',requestKey:'b'});expect(()=>decideApproval(db,'b',id,true,'')).toThrow();decideApproval(db,'a',id,true,'');db.exec("UPDATE workspace_members SET role='viewer'");expect(()=>createApproval(db,'b',{propertyId:p,date:'2026-09-12',note:'',requestKey:'c'})).toThrow()});
 it('deduplicates requests and rejects changed contents',()=>{const id=approval();expect(approval()).toBe(id);expect(()=>createApproval(db,'a',{propertyId:p,date:'2026-09-13',note:'Clean',requestKey:'req'})).toThrow();expect(()=>createApproval(db,'a',{propertyId:p,date:'2026-02-31',note:'',requestKey:'bad'})).toThrow()});
 it('holds budget for approvals and blocks overspending',()=>{const price=calcGrossPrice('apartament',75)*100;db.prepare('UPDATE workspace_properties SET budget_enforced=1,budget_bani=?').run(price);const id=approval();decideApproval(db,'a',id,true,'');const second=createApproval(db,'a',{propertyId:p,date:'2026-09-13',note:'',requestKey:'next'});expect(()=>decideApproval(db,'a',second,true,'')).toThrow(/Buget/)});
 it('consumes exactly once at full price even when credit was used, without double counting hold',()=>{const price=calcGrossPrice('apartament',75)*100;db.prepare('UPDATE workspace_properties SET budget_enforced=1,budget_bani=?').run(price);const id=approval();decideApproval(db,'a',id,true,'');job();db.transaction(()=>{consumeApproval(db,'a',id,'j');enforcePropertyBudget(db,p,'j')})();expect(()=>consumeApproval(db,'a',id,'j')).toThrow();expect(db.prepare('SELECT status FROM workspace_approvals').get()).toEqual({status:'fulfilled'})});
 it('rolls back a changed-price booking and keeps the approval usable',()=>{const id=approval();decideApproval(db,'a',id,true,'');expect(()=>db.transaction(()=>{job();db.exec('UPDATE jobs SET price_gross=999');consumeApproval(db,'a',id,'j')})()).toThrow(/prețul/);expect(db.prepare('SELECT * FROM jobs').all()).toHaveLength(0);expect(db.prepare('SELECT status FROM workspace_approvals').get()).toEqual({status:'approved'})});
 it('releases an approved budget hold when owner withdraws approval',()=>{const id=approval();decideApproval(db,'a',id,true,'');decideApproval(db,'a',id,false,'Plans changed');job();expect(()=>consumeApproval(db,'a',id,'j')).toThrow();expect(db.prepare('SELECT status FROM workspace_approvals').get()).toEqual({status:'rejected'})});
 it('rejects booking at an address changed after the request',()=>{const id=approval();decideApproval(db,'a',id,true,'');job();db.exec("UPDATE workspace_properties SET street='Changed';UPDATE jobs SET street='Changed'");expect(()=>consumeApproval(db,'a',id,'j')).toThrow(/Detaliile/)});
 it('checks direct bookings against approved holds',()=>{db.prepare('UPDATE workspace_properties SET budget_enforced=1,budget_bani=?').run(calcGrossPrice('apartament',75)*100);const id=approval();decideApproval(db,'a',id,true,'');job();db.prepare('INSERT INTO workspace_property_jobs VALUES(?,?)').run('j',p);expect(()=>enforcePropertyBudget(db,p,'j')).toThrow(/Buget/)});
});


describe('submitted execution evidence',()=>{
 function ready(){job();member();assignTeam(db,'f','t','j');db.exec("UPDATE jobs SET status='arrived'");for(const key of ['surfaces','kitchen','bathroom','floors','waste','inspection'])setChecklist(db,'b','j',key,true);for(const type of ['ARRIVAL','COMPLETION'])db.prepare("INSERT INTO job_photos(id,job_id,filename,proof_type,uploaded_by_firm_id,status,validated_at) VALUES(?,'j','test.jpg',?,'firm','VALID',datetime('now'))").run(type,type);}
 it('preserves exactly the submitted checks and validated proof references',()=>{ready();submitExecutionReport(db,'b','j','  Done  ');const before=executionReportRecord(db,'j')!;expect(before.note).toBe('Done');expect(before.evidence?.checklist).toHaveLength(6);expect(before.evidence?.photos.map(p=>p.id)).toEqual(['ARRIVAL','COMPLETION']);db.exec("UPDATE job_photos SET status='DELETED';UPDATE workspace_checklist SET done=0");expect(executionReportRecord(db,'j')).toEqual(before);});
 it('does not include another firm, unvalidated photos or context photos',()=>{ready();db.exec("INSERT INTO users(id,role,name) VALUES('g','firma','G');INSERT INTO firms(id,user_id,coverage_city) VALUES('other','g','București')");const insert=db.prepare("INSERT INTO job_photos(id,job_id,filename,proof_type,uploaded_by_firm_id,status,validated_at) VALUES(?,'j','test.jpg',?,?,'VALID',?)");insert.run('wrong','ARRIVAL','other','2026-09-11');insert.run('pending','COMPLETION','firm',null);insert.run('context','CLIENT_CONTEXT',null,'2026-09-11');submitExecutionReport(db,'b','j','Done');expect(executionReportRecord(db,'j')?.evidence?.photos).toHaveLength(2);});
 it('makes exact retries idempotent and rejects changed contents or authors',()=>{ready();submitExecutionReport(db,'b','j','Done');submitExecutionReport(db,'b','j',' Done ');expect(()=>submitExecutionReport(db,'b','j','Different')).toThrow(/alt autor sau alt conținut/);expect(()=>submitExecutionReport(db,'f','j','Done')).toThrow(/alt autor sau alt conținut/);expect(db.prepare("SELECT * FROM workspace_audit WHERE action='execution.submit'").all()).toHaveLength(1);expect(db.prepare('SELECT * FROM workspace_execution_evidence').all()).toHaveLength(1);});
 it('allows an exact retry after completion but cannot create a new late report',()=>{ready();submitExecutionReport(db,'b','j','Done');db.exec("UPDATE jobs SET status='completed'");submitExecutionReport(db,'b','j','Done');job('late');db.exec("UPDATE jobs SET status='completed' WHERE id='late'");expect(()=>submitExecutionReport(db,'f','late','Done')).toThrow(/nu poate/);expect(executionReportRecord(db,'late')).toBeNull();});
 it('still verifies access on retries after membership revocation',()=>{ready();submitExecutionReport(db,'b','j','Done');db.exec('UPDATE workspace_members SET active=0');expect(()=>submitExecutionReport(db,'b','j','Done')).toThrow(/nu poate/);});
 it('rejects changes or deletion of snapshot-backed reports and evidence',()=>{ready();submitExecutionReport(db,'b','j','Done');for(const sql of ["UPDATE workspace_execution_reports SET note='Changed'",'DELETE FROM workspace_execution_reports',"UPDATE workspace_execution_evidence SET snapshot_json='{}'",'DELETE FROM workspace_execution_evidence'])expect(()=>db.exec(sql)).toThrow(/immutable/);});
 it('rolls back both records if audit fails and permits a clean retry',()=>{ready();db.exec("CREATE TRIGGER fail_report_audit BEFORE INSERT ON workspace_audit BEGIN SELECT RAISE(ABORT,'audit failed'); END;");expect(()=>submitExecutionReport(db,'b','j','Done')).toThrow(/audit failed/);expect(executionReportRecord(db,'j')).toBeNull();expect(db.prepare('SELECT * FROM workspace_execution_evidence').all()).toHaveLength(0);db.exec('DROP TRIGGER fail_report_audit');submitExecutionReport(db,'b','j','Done');expect(executionReportRecord(db,'j')?.evidence).not.toBeNull();});
 it('rolls back the report if evidence persistence fails',()=>{ready();db.exec("CREATE TRIGGER fail_snapshot BEFORE INSERT ON workspace_execution_evidence BEGIN SELECT RAISE(ABORT,'snapshot failed'); END;");expect(()=>submitExecutionReport(db,'b','j','Done')).toThrow(/snapshot failed/);expect(executionReportRecord(db,'j')).toBeNull();expect(db.prepare("SELECT * FROM workspace_audit WHERE action='execution.submit'").all()).toHaveLength(0);});
 it('keeps historical reports without invented evidence, including on retries',()=>{ready();db.exec("INSERT INTO workspace_execution_reports VALUES('j','b','Old','2026-09-10')");submitExecutionReport(db,'b','j','Old');initializeDatabase(db);expect(executionReportRecord(db,'j')).toEqual({note:'Old',submitted_at:'2026-09-10',evidence:null});expect(db.prepare("SELECT * FROM workspace_audit WHERE action='execution.submit'").all()).toHaveLength(0);});
 it('preserves execution and financial state when submitting',()=>{ready();const before=db.prepare('SELECT * FROM jobs').get();submitExecutionReport(db,'b','j','Done');expect(db.prepare('SELECT * FROM jobs').get()).toEqual(before);expect(db.prepare('SELECT * FROM payments').all()).toHaveLength(0);});
});
