import { beforeEach, afterEach, it, expect } from 'vitest';
import Database from 'better-sqlite3';
import { initializeDatabase } from './db';
import { resolveIncident, incidentResolutions } from './incidentResolution';
import type { AdminRole } from './adminRolesShared';
let db: Database.Database;
const revision = '2026-01-01T00:00:00.000Z';
beforeEach(() => { db = new Database(':memory:'); db.pragma('foreign_keys=ON'); initializeDatabase(db); db.exec("INSERT INTO users(id,role,name) VALUES('c','client','Client'),('u','firma','Firm');INSERT INTO firms(id,user_id,coverage_city,verified) VALUES('f','u','București',1);INSERT INTO jobs(id,client_id,street,city,sqm,space_type,when_type,price_gross,duration_minutes,status,accepted_firm_id) VALUES('j','c','Str','București',80,'apartament','asap',500,120,'completed','f');"); db.prepare('INSERT INTO visit_cases(id,job_id,opened_by,request_key,category,description,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run('case', 'j', 'c', 'key', 'quality', 'Problem', revision, revision); });
afterEach(() => db.close());
const act = (body: Record<string, unknown> = {}, role: AdminRole = 'manager') => db.transaction(() => resolveIncident(db, { caseId: 'case', revision, note: 'Checked evidence', kind: 'remediation', action: 'propose', ...body }, { id: 'staff', role })).immediate();
const review = (outcome = 'confirmed') => db.prepare('INSERT INTO visit_case_reviews VALUES(?,?,?,?,?,?)').run('r', 'case', outcome, 'Evidence', 'reviewer', revision);
it('stores proposals without applying money, suspension or closing cases', () => { act({ kind: 'credit' }, 'operator'); expect(incidentResolutions(db, 'case')[0]).toMatchObject({ kind: 'credit', state: 'pending' }); expect(db.prepare('SELECT status FROM visit_cases').get()).toEqual({ status: 'open' }); expect(db.prepare("SELECT credit_balance FROM users WHERE id='c'").get()).toEqual({ credit_balance: 0 }); });
it('requires the right role, current revision and verified outcome', () => { expect(() => act({ action: 'complete' }, 'operator')).toThrow(/Rolul/); expect(() => act({ revision: 'stale' })).toThrow(/schimbat/); expect(() => act({ action: 'complete', kind: 'reject' })).toThrow(/neconfirmată/); review('not_confirmed'); act({ action: 'complete', kind: 'reject' }); expect(db.prepare('SELECT status FROM visit_cases').get()).toEqual({ status: 'closed' }); expect(() => act({ revision: incidentResolutions(db, 'case')[0].created_at })).toThrow(/soluționat/); });
it('cannot mark a refund complete unless existing financial records confirm it', () => { review(); expect(() => act({ kind: 'refund', action: 'complete' })).toThrow(/Rolul/); expect(() => act({ kind: 'refund', action: 'complete' }, 'finance')).toThrow(/nu este confirmată/); db.exec("INSERT INTO payments(id,job_id,amount_gross,commission_amount,amount_net,status,refund_status) VALUES('p','j',500,75,425,'refunded','succeeded');INSERT INTO payment_refunds(id,payment_id,amount,status) VALUES('refund','p',500,'succeeded')"); act({ kind: 'refund', action: 'complete' }, 'finance'); expect(incidentResolutions(db, 'case')[0]).toMatchObject({ reference: 'p', state: 'completed' }); });
it('retains policy-dependent credit and penalty decisions as proposals', () => { review(); for (const kind of ['credit', 'provider_penalty'])
    expect(() => act({ kind, action: 'complete' }, 'super_admin')).toThrow(/politicii/); });
it('rejects unfinished remediation and preserves existing suspension duration', () => { review(); expect(() => act({ action: 'complete' })).toThrow(/remediere finalizată/); db.exec("UPDATE firms SET suspended_until='2099-01-01T00:00:00Z'"); expect(() => act({ kind: 'provider_suspension', action: 'complete', reference: '2098-01-01T00:00:00Z' })).toThrow(/scurta/); });
it('applies approved suspension atomically and retains immutable audit', () => { review(); act({ kind: 'provider_suspension', action: 'complete', reference: '2099-01-01T00:00:00Z' }); expect(db.prepare('SELECT suspended_until FROM firms').get()).toEqual({ suspended_until: '2099-01-01T00:00:00.000Z' }); expect(() => db.exec('UPDATE incident_resolutions SET state=\'pending\'')).toThrow(/immutable/); });
it('rolls back suspension if resolution storage fails', () => { review(); db.exec("CREATE TRIGGER fail_resolution BEFORE INSERT ON incident_resolutions BEGIN SELECT RAISE(ABORT,'audit failed'); END;"); expect(() => act({ kind: 'provider_suspension', action: 'complete', reference: '2099-01-01T00:00:00Z' })).toThrow(); expect(db.prepare('SELECT suspended_until FROM firms').get()).toEqual({ suspended_until: null }); });
