import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import Database from 'better-sqlite3';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {initializeDatabase} from './db';
import {INCIDENT_SLA_ALERT_SCHEMA} from './incidentSlaSchema';
import {runIncidentSla,incidentSlaInbox,acknowledgeIncidentSla} from './incidentSla';
import {saveIncidentPolicy,saveIncidentTriage} from './incidentTriage';
let db:Database.Database;
const created='2026-09-25T08:00:00.000Z',picked='2026-09-25T09:00:00.000Z',now=new Date('2026-09-25T12:00:00.000Z');
function setup(path=':memory:'){
 const db=new Database(path);db.pragma('foreign_keys=ON');initializeDatabase(db);db.exec(INCIDENT_SLA_ALERT_SCHEMA);
 db.exec(`INSERT INTO users(id,role,name) VALUES('client','client','Client'),('provider','firma','Prestator');INSERT INTO firms(id,user_id,coverage_city) VALUES('firm','provider','București');INSERT INTO jobs(id,client_id,street,city,sqm,space_type,when_type,price_gross,duration_minutes,status,accepted_firm_id) VALUES('job','client','PRIVATE ADDRESS','București',80,'apartament','scheduled',500,120,'completed','firm');`);
 db.prepare("INSERT INTO visit_cases(id,job_id,opened_by,request_key,category,description,created_at,updated_at) VALUES('case','job','client','request','quality','Problemă',?,?)").run(created,created);
 return db;
}
beforeEach(()=>{db=setup();vi.stubEnv('NITIDO_INCIDENT_SLA_ALERTS_ENABLED','true');});
afterEach(()=>{db.close();vi.unstubAllEnvs();});
const policy=(revision=0,patch:Record<string,unknown>={})=>db.transaction(()=>saveIncidentPolicy(db,{revision,pickupMinutes:30,providerMinutes:60,resolutionMinutes:120,reason:'Termene aprobate pentru test',...patch},'manager')).immediate();
const triage=()=>db.transaction(()=>saveIncidentTriage(db,{caseId:'case',caseRevision:created,revision:0,severity:'high',owner:'Operator test',note:'NOTĂ INTERNĂ'},'operator',picked)).immediate();
const count=()=>db.prepare('SELECT COUNT(*) n FROM incident_sla_alerts').get();
it('requires activation and configured policy without inventing deadlines',()=>{expect(runIncidentSla(db,now).created).toBe(0);policy();const before=db.prepare('SELECT * FROM incident_sla_worker_state').all();vi.stubEnv('NITIDO_INCIDENT_SLA_ALERTS_ENABLED','false');expect(runIncidentSla(db,now)).toMatchObject({enabled:false,created:0});expect(count()).toEqual({n:0});expect(db.prepare('SELECT * FROM incident_sla_worker_state').all()).toEqual(before);});
it('creates one internal escalation per overdue target and rechecks state without changing case, payment or provider',()=>{policy();const state=db.prepare('SELECT * FROM visit_cases').all();expect(runIncidentSla(db,now)).toMatchObject({created:1,cycleComplete:true});expect(runIncidentSla(db,now).created).toBe(0);let inbox=incidentSlaInbox(db,undefined,now.getTime());expect(inbox.alerts).toHaveLength(1);expect(inbox.alerts[0]).toMatchObject({kind:'pickup',escalation:'management',policy_revision:1});expect(db.prepare('SELECT * FROM visit_cases').all()).toEqual(state);triage();expect(incidentSlaInbox(db,undefined,now.getTime()).alerts).toHaveLength(0);expect(runIncidentSla(db,now).created).toBe(2);inbox=incidentSlaInbox(db,'case',now.getTime());expect(inbox.alerts.map(a=>a.kind).sort()).toEqual(['provider','resolution']);db.exec("UPDATE visit_cases SET status='resolved'");expect(incidentSlaInbox(db,undefined,now.getTime()).alerts).toHaveLength(0);expect(runIncidentSla(db,now).created).toBe(0);expect(count()).toEqual({n:3});});
it('stops only the provider response target for a response from the assigned firm',()=>{policy();triage();runIncidentSla(db,now);db.prepare('INSERT INTO visit_case_events VALUES(?,?,?,?,?,?)').run('client-message','case','client','reply','Client reply','2026-09-25T10:00:00Z');expect(incidentSlaInbox(db,'case',now.getTime()).alerts).toHaveLength(2);db.prepare('INSERT INTO visit_case_events VALUES(?,?,?,?,?,?)').run('provider-message','case','provider','reply','Provider reply','2026-09-25T10:00:00Z');expect(incidentSlaInbox(db,'case',now.getTime()).alerts.map(a=>a.kind)).toEqual(['resolution']);});
it('pins triaged policy and avoids duplicate escalations on reassignment while showing current owner',()=>{policy();const first=triage();runIncidentSla(db,now);policy(1,{providerMinutes:1,resolutionMinutes:1});db.transaction(()=>saveIncidentTriage(db,{caseId:'case',caseRevision:first.caseRevision,revision:1,severity:'critical',owner:'Alt operator',note:'Reatribuire'},'manager','2026-09-25T10:00:00Z')).immediate();expect(runIncidentSla(db,now).created).toBe(0);expect(incidentSlaInbox(db,'case',now.getTime()).alerts).toHaveLength(2);for(const a of incidentSlaInbox(db,'case',now.getTime()).alerts)expect(a).toMatchObject({policy_revision:1,triage_revision:1,owner:'Alt operator'});});
it('supersedes untriaged alerts when policy changes and preserves historical evidence',()=>{policy();runIncidentSla(db,now);policy(1,{pickupMinutes:300});expect(runIncidentSla(db,now).created).toBe(0);expect(incidentSlaInbox(db,'case',now.getTime()).alerts).toHaveLength(0);expect(count()).toEqual({n:1});policy(2,{pickupMinutes:10});expect(runIncidentSla(db,now).created).toBe(1);expect(incidentSlaInbox(db,'case',now.getTime()).alerts[0].policy_revision).toBe(3);});
it('acknowledges nominally with audit and idempotent replay without closing the case or restarting its clock',()=>{policy();runIncidentSla(db,now);const a=incidentSlaInbox(db,'case',now.getTime()).alerts[0],input={alertId:a.id,caseRevision:a.caseRevision,note:'Preluat pentru verificare'};const before=db.prepare('SELECT * FROM visit_cases').all();expect(()=>acknowledgeIncidentSla(db,input,'operator',now.getTime(),true)).toThrow(/Tranzacție/);expect(db.transaction(()=>acknowledgeIncidentSla(db,input,'operator',now.getTime(),true)).immediate()).toMatchObject({acknowledged:true,replayed:false});expect(db.transaction(()=>acknowledgeIncidentSla(db,input,'operator',now.getTime(),true)).immediate()).toMatchObject({replayed:true});expect(()=>db.transaction(()=>acknowledgeIncidentSla(db,input,'forged',now.getTime(),true)).immediate()).toThrow(/deja preluată/);expect(incidentSlaInbox(db,'case',now.getTime()).alerts).toHaveLength(0);expect(db.prepare('SELECT * FROM visit_cases').all()).toEqual(before);expect(db.prepare("SELECT COUNT(*) n FROM admin_audit_log WHERE action='incident.sla.acknowledge'").get()).toEqual({n:1});expect(db.prepare('SELECT actor_id FROM incident_sla_acknowledgements').get()).toEqual({actor_id:'operator'});});
it('rejects stale or no longer actionable acknowledgements and rolls back both alert and acknowledgement when audit fails',()=>{policy();db.exec("CREATE TRIGGER deny_sla_audit BEFORE INSERT ON admin_audit_log BEGIN SELECT RAISE(ABORT,'audit failed'); END");expect(()=>runIncidentSla(db,now)).toThrow('audit failed');expect(count()).toEqual({n:0});expect(db.prepare('SELECT * FROM incident_sla_worker_state').all()).toEqual([]);db.exec('DROP TRIGGER deny_sla_audit');runIncidentSla(db,now);const a=incidentSlaInbox(db,'case',now.getTime()).alerts[0],input={alertId:a.id,caseRevision:a.caseRevision,note:'Verificare'};db.exec("CREATE TRIGGER deny_sla_ack BEFORE INSERT ON admin_audit_log WHEN NEW.action='incident.sla.acknowledge' BEGIN SELECT RAISE(ABORT,'ack audit failed'); END");expect(()=>db.transaction(()=>acknowledgeIncidentSla(db,input,'operator',now.getTime(),true)).immediate()).toThrow('ack audit failed');expect(db.prepare('SELECT * FROM incident_sla_acknowledgements').all()).toEqual([]);db.exec('DROP TRIGGER deny_sla_ack');expect(()=>db.transaction(()=>acknowledgeIncidentSla(db,{...input,caseRevision:'stale'},'operator',now.getTime(),true)).immediate()).toThrow(/s-a schimbat/);db.exec("UPDATE visit_cases SET status='closed'");expect(()=>db.transaction(()=>acknowledgeIncidentSla(db,input,'operator',now.getTime(),true)).immediate()).toThrow(/s-a schimbat/);});
it.each([['2026-03-29 00:00:00','2026-03-29T01:00:00Z'],['2026-10-25 00:00:00','2026-10-25T01:00:00Z']])('uses UTC instants for SQLite times across Romanian DST: %s',(anchor,deadline)=>{db.prepare('UPDATE visit_cases SET created_at=?').run(anchor);policy(0,{pickupMinutes:60});expect(runIncidentSla(db,new Date(deadline)).created).toBe(0);expect(runIncidentSla(db,new Date(Date.parse(deadline)+1)).created).toBe(1);expect(incidentSlaInbox(db,undefined,Date.parse(deadline)+1).alerts[0].due_at).toBe(new Date(deadline).toISOString());});
it('skips invalid dates and absent provider assignment instead of inventing actionable deadlines',()=>{policy();db.exec("UPDATE visit_cases SET created_at='2026-02-30 08:00:00'");expect(runIncidentSla(db,now).created).toBe(0);db.prepare('UPDATE visit_cases SET created_at=?').run(created);triage();db.exec("UPDATE jobs SET accepted_firm_id=NULL");expect(runIncidentSla(db,now).created).toBe(1);expect(incidentSlaInbox(db,'case',now.getTime()).alerts.map(a=>a.kind)).toEqual(['resolution']);});
it('scans beyond one bounded batch without starvation and retains immutable history',()=>{policy();db.transaction(()=>{for(let i=0;i<260;i++)db.prepare("INSERT INTO visit_cases(id,job_id,opened_by,request_key,category,description,created_at,updated_at) VALUES(?,'job','client',?,'quality','Test',?,?)").run('additional-'+String(i).padStart(3,'0'),'key-'+i,created,created);})();expect(runIncidentSla(db,now)).toMatchObject({scanned:250,created:250,cycleComplete:false});expect(runIncidentSla(db,now)).toMatchObject({scanned:11,created:11,cycleComplete:true});expect(runIncidentSla(db,now).created).toBe(0);expect(count()).toEqual({n:261});expect(()=>db.exec('DELETE FROM incident_sla_alerts')).toThrow(/retained/);expect(()=>db.exec("UPDATE incident_sla_alerts SET escalation='management'")).toThrow(/immutable/);});
it('deduplicates independent SQLite workers and competing nominal acknowledgements',()=>{const folder=mkdtempSync(join(tmpdir(),'nitido-sla-'));let first:Database.Database|undefined,second:Database.Database|undefined;try{first=setup(join(folder,'test.sqlite'));second=new Database(join(folder,'test.sqlite'));first.transaction(()=>saveIncidentPolicy(first!,{revision:0,pickupMinutes:30,providerMinutes:null,resolutionMinutes:null,reason:'Concurrent test'},'manager')).immediate();second.pragma('busy_timeout=20');first.exec('BEGIN IMMEDIATE');try{expect(()=>runIncidentSla(second!,now)).toThrow(/locked/);expect(first.prepare('SELECT * FROM incident_sla_alerts').all()).toEqual([]);}finally{first.exec('ROLLBACK');}expect(runIncidentSla(first,now).created).toBe(1);expect(runIncidentSla(second,now).created).toBe(0);const a=incidentSlaInbox(first,'case',now.getTime()).alerts[0],input={alertId:a.id,caseRevision:a.caseRevision,note:'Concurrent preluat'};first.transaction(()=>acknowledgeIncidentSla(first!,input,'first',now.getTime(),true)).immediate();expect(()=>second!.transaction(()=>acknowledgeIncidentSla(second!,input,'second',now.getTime(),true)).immediate()).toThrow(/deja preluată/);expect(second.prepare('SELECT COUNT(*) n FROM incident_sla_acknowledgements').get()).toEqual({n:1});}finally{second?.close();first?.close();rmSync(folder,{recursive:true,force:true});}});

it('rejects corrupted triage deadlines instead of escalating normalized or mismatched dates',()=>{policy();db.exec("INSERT INTO incident_triage VALUES('case',1,'normal','Operator','Internal',1,'2026-09-25T09:00:00Z','2026-02-30T10:00:00Z','2026-09-25T09:01:00Z','manager','2026-09-25T09:00:00Z')");expect(runIncidentSla(db,now).created).toBe(0);expect(incidentSlaInbox(db,'case',now.getTime()).alerts).toHaveLength(0);});

it('refuses an oversized global history instead of returning a silently truncated or falsely complete inbox',()=>{policy();db.transaction(()=>{for(let i=0;i<1001;i++)db.prepare("INSERT INTO incident_sla_alerts VALUES(?,'case','pickup',1,NULL,?,?,'management')").run('old-'+i,new Date(Date.parse(created)+i*60000).toISOString(),created);})();expect(()=>incidentSlaInbox(db,undefined,now.getTime())).toThrow(/peste 1.000/);expect(incidentSlaInbox(db,'other',now.getTime()).alerts).toEqual([]);});
