import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import Database from 'better-sqlite3';
import {MANUAL_ESTIMATE_SCHEMA,saveManualEstimate} from './manualEstimates';
import {COST_CODES,emptyManualEstimate} from './operationalMargin';
import {MANUAL_OFFERS_SCHEMA,listManualOffers,publishManualOffer,withdrawManualOffer,decideManualOffer,manualOffersEnabled} from './manualOffers';
let db:Database.Database;
const now=new Date('2026-09-24T12:00:00.000Z');
const input=()=>({id:'a',revision:1,scope:'Curățenie generală, fără geamuri.',expiresAt:'2026-09-25T12:00:00Z',reason:'Aprobare internă test'});
function estimate(){const d=emptyManualEstimate();d.lines=[{label:'Curățenie',amountBani:50000}];d.reason='SECRET INTERNAL';d.provider={amountBani:30000,state:'confirmed',source:'SECRET PROVIDER',recordedAt:now.toISOString()};for(const c of COST_CODES)d.costs[c]={...d.costs[c],amountBani:0,state:'confirmed',source:'SECRET COST',recordedAt:now.toISOString()};return d;}
function save(revision=0){return saveManualEstimate(db,{id:'a',revision,assessmentVersion:1,definition:estimate()},'admin',now);}
const publish=()=>publishManualOffer(db,input(),'admin',now);
const accept=(id:string,date=now)=>decideManualOffer(db,'client',{id,action:'accept',confirmed:true,totalBani:50000},date);
beforeEach(()=>{db=new Database(':memory:');db.pragma('foreign_keys=ON');db.exec(`CREATE TABLE service_assessments(id TEXT PRIMARY KEY,client_id TEXT,status TEXT,version INTEGER,payload TEXT);INSERT INTO service_assessments VALUES('a','client','submitted',1,'{"category":"general"}');`+MANUAL_ESTIMATE_SCHEMA+MANUAL_OFFERS_SCHEMA);save();});
afterEach(()=>{db.close();vi.unstubAllEnvs();});
describe('manual offer lifecycle',()=>{
 it('exposes only frozen client terms without cost or margin details',()=>{const o=publish();expect(o.terms.totalBani).toBe(50000);const json=JSON.stringify(listManualOffers(db,'a','client',now));expect(json).not.toMatch(/SECRET|provider|margin|actor|reason/);expect(listManualOffers(db,'a','intruder',now)).toEqual([]);});
 it('publishes once on retry and rejects changed terms for the same revision',()=>{const o=publish();expect(publish().id).toBe(o.id);expect(db.prepare('SELECT * FROM assessment_offer_events').all()).toHaveLength(1);expect(()=>publishManualOffer(db,{...input(),scope:'Changed'},'admin',now)).toThrow(/alți termeni/);});
 it('requires all cost sources before publication',()=>{const d=estimate();d.provider=emptyManualEstimate().provider;saveManualEstimate(db,{id:'a',revision:1,assessmentVersion:1,definition:d},'admin',now);expect(()=>publishManualOffer(db,{...input(),revision:2},'admin',now)).toThrow(/costurile/);});
 it('blocks renovation without verified photos',()=>{db.exec(`UPDATE service_assessments SET payload='{"category":"renovation"}'`);expect(publish).toThrow(/fotografii/);});
 it.each(['cancelled','declined'])('blocks closed assessment %s',status=>{db.prepare('UPDATE service_assessments SET status=?').run(status);expect(publish).toThrow(/închisă/);});
 it('rejects stale estimate revisions and changed assessment versions',()=>{save(1);expect(publish).toThrow(/modificat/);db.exec('UPDATE service_assessments SET version=2');expect(()=>publishManualOffer(db,{...input(),revision:2},'admin',now)).toThrow(/modificat/);});
 it.each(['2026-09-24T12:00:00Z','bad','2026-09-25T12:00:00','2027-02-30T12:00:00Z'])('rejects invalid or elapsed expiry %s',expiresAt=>{expect(()=>publishManualOffer(db,{...input(),expiresAt},'admin',now)).toThrow(/Expirarea/);});
 it('normalizes timezone and expires exactly at boundary',()=>{const o=publishManualOffer(db,{...input(),expiresAt:'2026-09-25T15:00:00+03:00'},'admin',now);expect(o.expiresAt).toBe('2026-09-25T12:00:00.000Z');const date=new Date(o.expiresAt);expect(listManualOffers(db,'a','client',date)[0].status).toBe('expired');expect(()=>accept(o.id,date)).toThrow(/expirat/);});
 it('requires ownership and explicit confirmation of the exact frozen total',()=>{const o=publish();expect(()=>decideManualOffer(db,'other',{id:o.id,action:'accept',confirmed:true,totalBani:50000},now)).toThrow(/disponibilă/);for(const args of [{confirmed:false,totalBani:50000},{confirmed:true,totalBani:49999}])expect(()=>decideManualOffer(db,'client',{id:o.id,action:'accept',...args},now)).toThrow(/explicit/);});
 it('accepts once, including retry after expiry, without creating jobs or payments',()=>{const o=publish();expect(accept(o.id).status).toBe('accepted');expect(accept(o.id,new Date('2026-10-01')).status).toBe('accepted');expect(db.prepare('SELECT * FROM assessment_offer_events').all()).toHaveLength(2);expect(db.prepare("SELECT name FROM sqlite_master WHERE name IN ('jobs','payments')").all()).toEqual([]);});
 it('refuses to overwrite or withdraw accepted terms',()=>{const o=publish();accept(o.id);save(1);expect(()=>publishManualOffer(db,{...input(),revision:2},'admin',now)).toThrow(/acceptată/);expect(()=>withdrawManualOffer(db,o.id,'admin','Motiv',now)).toThrow(/retrasă/);});
 it('supersedes an older offer atomically and blocks its acceptance',()=>{const o=publish();save(1);publishManualOffer(db,{...input(),revision:2},'admin',now);expect(()=>accept(o.id)).toThrow(/disponibilă/);expect(listManualOffers(db,'a','client',now).map(o=>o.status).sort()).toEqual(['offered','superseded']);});
 it('withdraws and rejects idempotently and prevents subsequent acceptance',()=>{const o=publish();expect(withdrawManualOffer(db,o.id,'admin','Corecție',now).status).toBe('withdrawn');withdrawManualOffer(db,o.id,'admin','Corecție',now);expect(()=>accept(o.id)).toThrow();save(1);const next=publishManualOffer(db,{...input(),revision:2},'admin',now);for(let i=0;i<2;i++)expect(decideManualOffer(db,'client',{id:next.id,action:'reject'},now).status).toBe('rejected');expect(()=>accept(next.id)).toThrow();expect(db.prepare('SELECT * FROM assessment_offer_events').all()).toHaveLength(4);});
 it('blocks acceptance after context changes',()=>{const o=publish();db.exec('UPDATE service_assessments SET version=2');expect(()=>accept(o.id)).toThrow(/schimbat/);});
 it('retains immutable terms and audit history',()=>{publish();expect(()=>db.exec("UPDATE assessment_offers SET public_json='{}'")).toThrow(/immutable/);expect(()=>db.exec('DELETE FROM assessment_offers')).toThrow(/retained/);expect(()=>db.exec("UPDATE assessment_offer_events SET reason='x'")).toThrow(/immutable/);expect(()=>db.exec('DELETE FROM assessment_offer_events')).toThrow(/retained/);});
 it('rolls back publication and supersession when outer audit fails',()=>{const old=publish();save(1);expect(()=>db.transaction(()=>{publishManualOffer(db,{...input(),revision:2},'admin',now);throw Error('audit');}).immediate()).toThrow();expect(listManualOffers(db,'a','client',now)).toMatchObject([{id:old.id,status:'offered'}]);});
 it('requires an explicit sandbox flag, sandbox host and non-live Stripe key',()=>{vi.stubEnv('NITIDO_MANUAL_OFFERS_SANDBOX','true');vi.stubEnv('NEXT_PUBLIC_SITE_URL','https://sandbox.nitido.ro');vi.stubEnv('STRIPE_SECRET_KEY','sk_test_example');expect(manualOffersEnabled()).toBe(true);vi.stubEnv('STRIPE_SECRET_KEY','sk_live_example');expect(manualOffersEnabled()).toBe(false);vi.stubEnv('STRIPE_SECRET_KEY','sk_test_example');vi.stubEnv('NEXT_PUBLIC_SITE_URL','https://nitido.ro');expect(manualOffersEnabled()).toBe(false);vi.stubEnv('NITIDO_MANUAL_OFFERS_SANDBOX','false');expect(manualOffersEnabled()).toBe(false);});
});
