import {afterEach,beforeEach,describe,it,expect} from 'vitest';
import Database from 'better-sqlite3';
import {MARGIN_POLICY_SCHEMA,saveMarginPolicy,currentMarginPolicy,evaluateMarginPolicy,marginExceptionReport} from './marginPolicy';
import {MANUAL_ESTIMATE_SCHEMA,saveManualEstimate} from './manualEstimates';
import {MANUAL_OFFERS_SCHEMA,publishManualOffer,listManualOffers} from './manualOffers';
import {emptyManualEstimate,COST_CODES} from './operationalMargin';
let db:Database.Database;
const now=new Date('2026-09-25T10:00:00Z');
function estimate(total=10000,cost=8000){const d=emptyManualEstimate();d.lines=[{label:'Serviciu',amountBani:total}];d.reason='Calcul intern';d.provider={amountBani:cost,state:'confirmed',source:'Cost confirmat',recordedAt:now.toISOString()};for(const c of COST_CODES)d.costs[c]={...d.costs[c],amountBani:0,state:'confirmed',source:'Sursă',recordedAt:now.toISOString()};return d;}
const policy=(minBani:number|null=2000,minBasisPoints:number|null=2000,revision=0)=>saveMarginPolicy(db,{revision,minBani,minBasisPoints,reason:'Regulă de test'},'admin',now);
const publish=(exceptionReason?:string,policyRevision=1)=>publishManualOffer(db,{id:'a',revision:1,scope:'Serviciu complet',expiresAt:'2026-09-26T10:00:00Z',reason:'Publicare',policyRevision,exceptionReason},'admin',now);
beforeEach(()=>{db=new Database(':memory:');db.pragma('foreign_keys=ON');db.exec(`CREATE TABLE service_assessments(id TEXT PRIMARY KEY,client_id TEXT,status TEXT,version INTEGER,payload TEXT);INSERT INTO service_assessments VALUES('a','client','submitted',1,'{"category":"general","city":"București","sqm":80}');`+MANUAL_ESTIMATE_SCHEMA+MANUAL_OFFERS_SCHEMA+MARGIN_POLICY_SCHEMA);saveManualEstimate(db,{id:'a',revision:0,assessmentVersion:1,definition:estimate()},'admin',now);});
afterEach(()=>db.close());
describe('margin controls',()=>{
 it('does not invent defaults and blocks publishing without a policy',()=>{expect(currentMarginPolicy(db)).toBeNull();expect(evaluateMarginPolicy(estimate(),null).status).toBe('not_configured');expect(publish).toThrow(/Configurează/);});
 it('supports absolute, percentage and combined minima with equality allowed',()=>{const p=policy();expect(evaluateMarginPolicy(estimate(),p).status).toBe('pass');expect(evaluateMarginPolicy(estimate(10000,8001),p).status).toBe('below');expect(evaluateMarginPolicy(estimate(20000,17000),p).status).toBe('below');expect(evaluateMarginPolicy(estimate(5000,3500),p).status).toBe('below');expect(evaluateMarginPolicy(estimate(5000,3500),{...p,min_bani:null}).status).toBe('pass');expect(evaluateMarginPolicy(estimate(20000,17000),{...p,min_basis_points:null}).status).toBe('pass');});
 it('compares precise integer ratios instead of rounded percentages',()=>{const p=policy(null,2000);const r=evaluateMarginPolicy(estimate(100001,80001),p);expect(r.margin.marginBasisPoints).toBe(2000);expect(r.status).toBe('below');});
 it('blocks unknown costs and undefined percentage at zero client revenue',()=>{const p=policy();const d=estimate();d.provider=emptyManualEstimate().provider;expect(evaluateMarginPolicy(d,p).status).toBe('incomplete');const free=estimate();free.platformDiscountBani=10000;expect(evaluateMarginPolicy(free,p).status).toBe('undefined_percentage');});
 it.each([{minBani:null,minBasisPoints:null},{minBani:-1,minBasisPoints:null},{minBani:0,minBasisPoints:10001},{minBani:1.5,minBasisPoints:null}])('rejects invalid rules %j',args=>{expect(()=>saveMarginPolicy(db,{revision:0,...args,reason:'Test'},'admin',now)).toThrow();});
 it('requires audit reason and optimistic revision, preserves prior rules',()=>{policy();expect(()=>policy(0,null)).toThrow(/operator/);expect(()=>saveMarginPolicy(db,{revision:1,minBani:0,minBasisPoints:null,reason:' '},'admin')).toThrow(/Justificarea/);policy(5000,null,1);expect(db.prepare('SELECT * FROM margin_policies').all()).toHaveLength(2);expect(()=>db.exec('UPDATE margin_policies SET min_bani=0')).toThrow(/immutable/);expect(()=>db.exec('DELETE FROM margin_policies')).toThrow(/retained/);});
 it('requires a distinct exception reason and records the exact threshold and operator',()=>{policy(3000,null);expect(()=>publish()).toThrow(/Justificarea/);expect(db.prepare('SELECT * FROM assessment_offers').all()).toHaveLength(0);const o=publish('Test comercial justificat');expect(marginExceptionReport(db)).toMatchObject([{offer_id:o.id,policy_revision:1,margin_bani:2000,below_threshold:1,exception_reason:'Test comercial justificat',actor_id:'admin',min_bani:3000}]);expect(JSON.stringify(listManualOffers(db,'a','client',now))).not.toMatch(/Test comercial|margin|below_threshold/);});
 it('rejects stale policy versions without creating offers',()=>{policy();policy(4000,null,1);expect(()=>publish('Motiv')).toThrow(/s-a schimbat/);expect(db.prepare('SELECT * FROM assessment_offers').all()).toEqual([]);});
 it('replays prior publication after policy changes without reinterpreting history',()=>{policy();const o=publish();policy(5000,null,1);expect(publish(undefined,2).id).toBe(o.id);expect(db.prepare('SELECT policy_revision,below_threshold FROM offer_margin_decisions').all()).toEqual([{policy_revision:1,below_threshold:0}]);expect(marginExceptionReport(db)).toEqual([]);});
 it('rolls back offer, event and margin decision together on audit failure',()=>{policy();expect(()=>db.transaction(()=>{publish();throw Error('audit');}).immediate()).toThrow();for(const table of ['assessment_offers','assessment_offer_events','offer_margin_decisions'])expect(db.prepare(`SELECT * FROM ${table}`).all()).toEqual([]);});
 it('retains immutable exception decisions',()=>{policy(3000,null);publish('Motiv');expect(()=>db.exec("UPDATE offer_margin_decisions SET exception_reason='changed'")).toThrow(/immutable/);expect(()=>db.exec('DELETE FROM offer_margin_decisions')).toThrow(/retained/);});
});
