import { beforeEach,describe,expect,it } from "vitest";
import DatabaseCtor from "better-sqlite3";
import type { Database } from "better-sqlite3";
import { SCHEMA_SQL } from "./db";
import { acceptJobAtomic } from "./acceptJob";
import {queueAcceptedClientPush} from "./push";
import { eligibleSmsRecipients,processSmsOutbox,queueJobArrivedClientSms,queueJobCreatedFirmAlerts } from "./notifications";

function setup():Database{const db=new DatabaseCtor(":memory:");db.exec(SCHEMA_SQL);db.prepare("INSERT INTO users(id,role,name,phone) VALUES ('client','client','Ana','0721000000')").run();for(const [id,city,verified,phone] of [["a","București",1,"0722000001"],["b","Brașov",1,"0722000002"],["c","București",0,"0722000003"]] as const){db.prepare("INSERT INTO users(id,role,name,phone) VALUES (?, 'firma', ?, ?)").run(`u_${id}`,`Firma ${id}`,phone);db.prepare("INSERT INTO firms(id,user_id,coverage_city,verified) VALUES (?,?,?,?)").run(`f_${id}`,`u_${id}`,city,verified);}return db;}
function job(db:Database,id="job",status="waiting"){db.prepare(`INSERT INTO jobs(id,client_id,street,city,sqm,space_type,when_type,price_gross,duration_minutes,status) VALUES (?,'client','Strada Secretă 99','București',70,'apartament','asap',500,120,?)`).run(id,status);}

describe("SMS outbox",()=>{let db:Database;beforeEach(()=>{db=setup();});
  it("selectează numai firme eligibile, în zonă, nesuspendate și cu telefon valid",()=>{const future=new Date(Date.now()+100000).toISOString();const recipients=eligibleSmsRecipients([{coverage_city:"București",coverage_cities_extra:null,phone:"0722000001",suspended_until:null},{coverage_city:"Brașov",coverage_cities_extra:null,phone:"0722000002",suspended_until:null},{coverage_city:"București",coverage_cities_extra:null,phone:"0722000004",suspended_until:future},{coverage_city:"București",coverage_cities_extra:null,phone:"invalid",suspended_until:null}],"București");expect(recipients).toEqual(["+40722000001"]);});
  it("creează fan-out fără duplicate și fără adresa clientului",()=>{job(db);const ids=queueJobCreatedFirmAlerts(db,{id:"job",city:"București",spaceType:"apartament",sqm:70,scheduledAt:null},["0722000001","+40722000001","0722000002"]);expect(ids).toHaveLength(2);const rows=db.prepare("SELECT message_body FROM notification_outbox").all() as {message_body:string}[];expect(rows.every(r=>!r.message_body.includes("Secretă")&&!r.message_body.includes("client"))).toBe(true);});
  it("acceptarea reușită permite exact o confirmare push chiar sub concurență",async()=>{job(db);const results=await Promise.all([acceptJobAtomic(db,"job","f_a"),acceptJobAtomic(db,"job","f_a")]);expect(results.filter(r=>r.ok)).toHaveLength(1);queueAcceptedClientPush(db,"job");queueAcceptedClientPush(db,"job");expect((db.prepare("SELECT count(*) n FROM push_notification_outbox WHERE event_type='JOB_ACCEPTED_CLIENT_PUSH'").get() as {n:number}).n).toBe(1);});
  it("eșecul autorizării plății nu creează confirmare",async()=>{job(db);db.exec("CREATE TRIGGER fail_payment BEFORE INSERT ON payments BEGIN SELECT RAISE(ABORT,'payment failure'); END");const result=await acceptJobAtomic(db,"job","f_a");expect(result.ok).toBe(false);expect(queueAcceptedClientPush(db,"job")).toEqual([]);expect((db.prepare("SELECT count(*) n FROM push_notification_outbox").get() as {n:number}).n).toBe(0);});
  it("sosirea creează o singură notificare pentru clientul corect",()=>{job(db,"arrived","arrived");db.prepare("UPDATE jobs SET accepted_firm_id='f_a' WHERE id='arrived'").run();queueJobArrivedClientSms(db,"arrived");queueJobArrivedClientSms(db,"arrived");const row=db.prepare("SELECT recipient,message_body FROM notification_outbox").get() as {recipient:string;message_body:string};expect(row.recipient).toBe("+40721000000");expect(row.message_body).toContain("Firma a");expect((db.prepare("SELECT count(*) n FROM notification_outbox").get() as {n:number}).n).toBe(1);});
  it("retry nu retrimite un eveniment deja sent",async()=>{job(db);const [id]=queueJobCreatedFirmAlerts(db,{id:"job",city:"București",spaceType:"apartament",sqm:70,scheduledAt:null},["0722000001"]);let calls=0;const sender=async()=>{calls++;return {providerMessageId:"SM123"};};await processSmsOutbox(db,[id],sender);await processSmsOutbox(db,[id],sender);expect(calls).toBe(1);expect((db.prepare("SELECT status,attempt_count FROM notification_outbox WHERE id=?").get(id) as {status:string;attempt_count:number})).toEqual({status:"sent",attempt_count:1});});
  it("un eșec rămâne observabil și poate fi retried fără alt eveniment",async()=>{job(db);const [id]=queueJobCreatedFirmAlerts(db,{id:"job",city:"București",spaceType:"apartament",sqm:70,scheduledAt:null},["0722000001"]);await processSmsOutbox(db,[id],async()=>{throw new Error("provider down")});expect((db.prepare("SELECT status,last_error FROM notification_outbox WHERE id=?").get(id) as {status:string;last_error:string})).toEqual({status:"failed",last_error:"SMS_PROVIDER_ERROR"});await processSmsOutbox(db,[id],async()=>({providerMessageId:"SM-retry"}));expect((db.prepare("SELECT status,attempt_count FROM notification_outbox WHERE id=?").get(id) as {status:string;attempt_count:number})).toEqual({status:"sent",attempt_count:2});});
  it("numerele invalide sunt ignorate sigur",()=>{job(db);expect(queueJobCreatedFirmAlerts(db,{id:"job",city:"București",spaceType:"apartament",sqm:70,scheduledAt:null},["invalid",null])).toEqual([]);});
});
