import {describe,it,expect} from 'vitest';
import {COST_CODES,emptyManualEstimate,validateManualEstimate,calculateOperationalMargin,type ManualEstimate} from './operationalMargin';
const known=(amountBani=0)=>({amountBani,state:'confirmed' as const,source:'Document test — fără taxe în acest exemplu',recordedAt:'2026-09-24T12:00:00Z'});
export function baseline():ManualEstimate{const d=emptyManualEstimate();d.lines=[{label:'Curățenie',amountBani:50000}];d.platformDiscountBani=5000;d.provider=known(41000);for(const code of COST_CODES)d.costs[code]={...known(),bearer:'platform',includedInProvider:false};d.reason='Exemplu aprobat în brief, fără TVA sau taxe';return d;}
describe('operational margin without double deductions',()=>{
 it('reproduces 500 - 50 - 410 = 40 lei from the brief',()=>{expect(calculateOperationalMargin(validateManualEstimate(baseline()))).toMatchObject({grossBani:50000,clientDueBani:45000,providerBani:41000,marginBani:4000,status:'confirmed',thresholdStatus:'not_configured'});});
 it('does not deduct materials/travel included in provider remuneration twice',()=>{const d=baseline();d.costs.materials={...known(3000),bearer:'provider',includedInProvider:true};d.costs.travel={...known(2000),bearer:'provider',includedInProvider:true};expect(calculateOperationalMargin(validateManualEstimate(d)).marginBani).toBe(4000);});
 it('deducts platform-borne expenses and permits a negative operational margin',()=>{const d=baseline();d.costs.materials={...known(5000),bearer:'platform',includedInProvider:false};expect(calculateOperationalMargin(validateManualEstimate(d)).marginBani).toBe(-1000);});
 it.each(['provider',...COST_CODES])('does not turn missing %s into zero',code=>{const d=baseline();if(code==='provider')d.provider={amountBani:null,state:'unknown',source:'',recordedAt:null};else d.costs[code as typeof COST_CODES[number]]={...d.costs[code as typeof COST_CODES[number]],amountBani:null,state:'unknown',source:'',recordedAt:null};expect(calculateOperationalMargin(validateManualEstimate(d))).toMatchObject({status:'incomplete',marginBani:null,missing:[code]});});
 it('distinguishes estimated costs from confirmed facts',()=>{const d=baseline();d.provider.state='estimated';expect(calculateOperationalMargin(validateManualEstimate(d))).toMatchObject({status:'estimated',estimated:['provider'],marginBani:4000});});
 it('avoids division by zero when the platform covers the whole price',()=>{const d=baseline();d.platformDiscountBani=50000;expect(calculateOperationalMargin(validateManualEstimate(d))).toMatchObject({clientDueBani:0,marginBani:-41000,marginBasisPoints:null});});
 it.each([-1,0.5,NaN,Infinity,'100',null])('rejects invalid financial amounts %s',value=>{const d=baseline();d.lines[0].amountBani=value as number;expect(()=>validateManualEstimate(d)).toThrow();});
 it('requires sources and dates even for confirmed zero, and a reason for revisions',()=>{for(const key of ['source','recordedAt']){const d=baseline();Object.assign(d.costs.fiscal,{[key]:''});expect(()=>validateManualEstimate(d)).toThrow();}const d=baseline();d.reason='';expect(()=>validateManualEstimate(d)).toThrow();});
 it('rejects contradictory bearer/inclusion and unknown amounts disguised as zero',()=>{const d=baseline();d.costs.materials.includedInProvider=true;expect(()=>validateManualEstimate(d)).toThrow();d.costs.materials.includedInProvider=false;d.costs.fiscal.state='unknown';expect(()=>validateManualEstimate(d)).toThrow();});
 it('rejects discount above price and unapproved currency',()=>{const d=baseline();d.platformDiscountBani=50001;expect(()=>validateManualEstimate(d)).toThrow();d.platformDiscountBani=0;Object.assign(d,{currency:'EUR'});expect(()=>validateManualEstimate(d)).toThrow();});
});
