import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import Database from 'better-sqlite3';
import {initializeDatabase} from './db';
import {queueNewJobFirmPushes,processPushOutbox} from './push';
import {queueJobCreatedFirmAlerts,processSmsOutbox} from './notifications';
import {claimNotification,startNotificationDispatch,finishNotification} from './notificationClaims';
import {confirmInvitationWinner,providerAcceptance} from './providerInvitations';
import {acceptJobAtomic} from './acceptJob';
import {createOffer,withdrawOffer} from './offers';
import {operationalReport} from './operationalReport';
vi.mock('@/lib/payments',()=>({connectTransfersEnabled:()=>false,authorizePayment:vi.fn(async()=> 'test-authorized')}));
let db:Database.Database;
beforeEach(()=>{db=new Database(':memory:');db.pragma('foreign_keys=ON');initializeDatabase(db);vi.stubEnv('PUSH_ENABLED','true');vi.stubEnv('SMS_FALLBACK_ENABLED','false');db.exec(`INSERT INTO users(id,role,name,phone) VALUES('c','client','Client','0721000000'),('u1','firma','Firma 1','0722000001'),('u2','firma','Firma 2','0722000002');INSERT INTO firms(id,user_id,coverage_city,verified) VALUES('f1','u1','București',1),('f2','u2','București',1);INSERT INTO jobs(id,client_id,street,city,sqm,space_type,when_type,price_gross,duration_minutes,status,mode) VALUES('j','c','PRIVATE ADDRESS','București',80,'apartament','asap',500,120,'waiting','express');INSERT INTO push_devices(id,user_id,platform,device_token) VALUES('d1','u1','ANDROID','device_one_long_token'),('d2','u1','ANDROID','device_two_long_token'),('d3','u2','ANDROID','device_three_long_token');`);});
afterEach(()=>{db.close();vi.unstubAllEnvs();vi.clearAllMocks();});
const queue=()=>queueNewJobFirmPushes(db,{id:'j',city:'București',spaceType:'apartament',sqm:80});
it('does not treat a feed view, an untracked legacy job or queued notifications as sent',()=>{expect(providerAcceptance(db,['j'])).toMatchObject({percent:null,untrackedJobs:1,denominator:0});queue();expect(providerAcceptance(db,['j'])).toMatchObject({percent:null,incompleteJobs:1,denominator:0});expect(db.prepare('SELECT * FROM provider_invitation_events').all()).toEqual([]);});
it('deduplicates devices and channels, excludes unknown deliveries, and preserves losing invitations',async()=>{const ids=queue();await processPushOutbox(db,ids,async()=>({providerMessageId:'test-push'}));const sms=queueJobCreatedFirmAlerts(db,{id:'j',city:'București',spaceType:'apartament',sqm:80,scheduledAt:null},['0722000001']);await processSmsOutbox(db,sms,async()=>({providerMessageId:'test-sms'}));expect(providerAcceptance(db,['j'])).toMatchObject({denominator:2,numerator:0,completeJobs:1});const winners=await Promise.all([acceptJobAtomic(db,'j','f1'),acceptJobAtomic(db,'j','f2')]);expect(winners.filter(w=>w.ok)).toHaveLength(1);expect(providerAcceptance(db,['j'])).toMatchObject({denominator:2,numerator:1,lost:1,withdrawn:0,percent:50});expect(providerAcceptance(db,['j'],'f2')).toMatchObject({denominator:1,numerator:0,lost:1});expect(db.prepare("SELECT COUNT(*) n FROM provider_invitation_events WHERE kind='accepted'").get()).toEqual({n:1});});
it('does not infer allocation acceptance from a Standard candidature or withdrawal',async()=>{db.exec("UPDATE jobs SET mode='standard' WHERE id='j'");await processPushOutbox(db,queue(),async()=>({providerMessageId:'test'}));const offer=createOffer(db,'j','f1');expect(offer.ok).toBe(true);if(!offer.ok)throw Error('Missing offer');expect(providerAcceptance(db,['j'])).toMatchObject({numerator:0,denominator:2});expect(withdrawOffer(db,offer.offerId,'f1').ok).toBe(true);expect(providerAcceptance(db,['j'])).toMatchObject({numerator:0,withdrawn:1,lost:0});});
it('rolls back an acknowledgement when its immutable audit fails and can safely confirm the same external response',()=>{const [id]=queue();const token=claimNotification(db,'push',id)!;expect(startNotificationDispatch(db,'push',id,token)).toBe(true);db.exec("CREATE TRIGGER reject_invitation_audit BEFORE INSERT ON provider_invitation_events BEGIN SELECT RAISE(ABORT,'audit failure'); END");expect(()=>finishNotification(db,'push',id,token,{providerMessageId:'external-confirmed'})).toThrow('audit failure');expect(db.prepare('SELECT status FROM push_notification_outbox WHERE id=?').get(id)).toEqual({status:'sending'});db.exec('DROP TRIGGER reject_invitation_audit');expect(finishNotification(db,'push',id,token,{providerMessageId:'external-confirmed'})).toBe(true);expect(finishNotification(db,'push',id,token,{providerMessageId:'external-confirmed'})).toBe(false);expect(db.prepare("SELECT COUNT(*) n FROM provider_invitation_events WHERE kind='sent'").get()).toEqual({n:1});});
it('does not count cohorts with an external outcome still unknown',async()=>{const ids=queue();await processPushOutbox(db,[ids[0]],async()=>{throw Error('network uncertainty')});await processPushOutbox(db,ids.slice(1),async()=>({providerMessageId:'other-device'}));expect(providerAcceptance(db,['j'])).toMatchObject({percent:null,denominator:0,incompleteJobs:1});});
it('retains immutable evidence and rolls back confirmation alongside its ledger when audit fails',()=>{queue();db.exec("CREATE TRIGGER reject_acceptance_audit BEFORE INSERT ON provider_invitation_events WHEN NEW.kind='accepted' BEGIN SELECT RAISE(ABORT,'audit failure'); END");expect(()=>db.transaction(()=>{db.prepare("UPDATE jobs SET status='accepted',accepted_firm_id='f1' WHERE id='j'").run();confirmInvitationWinner(db,'j','f1','claim');})()).toThrow('audit failure');expect(db.prepare("SELECT status FROM jobs WHERE id='j'").get()).toEqual({status:'waiting'});for(const table of ['provider_invitation_campaigns','provider_invitations','provider_invitation_deliveries']){expect(()=>db.prepare(`DELETE FROM ${table}`).run()).toThrow(/retained/);expect(()=>db.prepare(`UPDATE ${table} SET job_id='j'`).run()).toThrow(/immutable/);}});

it('filters provider acceptance by invitations received including lost allocations rather than only jobs won',async()=>{db.exec("UPDATE jobs SET created_at='2026-09-15T10:00:00Z' WHERE id='j'");await processPushOutbox(db,queue(),async()=>({providerMessageId:'test'}));expect((await acceptJobAtomic(db,'j','f1')).ok).toBe(true);const report=operationalReport(db,{from:'2026-09-01',to:'2026-09-30',firm:'f2'});expect(report.total).toBe(0);expect(report.kpis.providerAcceptance).toMatchObject({numerator:0,denominator:1,percent:0,lost:1});});

it('keeps a finalized allocation with a missing acceptance audit unavailable instead of showing false zero acceptance',async()=>{await processPushOutbox(db,queue(),async()=>({providerMessageId:'test'}));db.exec("UPDATE jobs SET status='accepted',accepted_firm_id='f1' WHERE id='j'");expect(providerAcceptance(db,['j'])).toMatchObject({percent:null,incompleteJobs:1,denominator:0});db.transaction(()=>confirmInvitationWinner(db,'j','f1','reconciled-claim'))();expect(providerAcceptance(db,['j'])).toMatchObject({percent:50,numerator:1,denominator:2,completeJobs:1});});
