import {afterEach,beforeEach,describe,expect,it} from "vitest";
import DatabaseCtor from "better-sqlite3";
import type {Database} from "better-sqlite3";
import {SCHEMA_SQL} from "./db";
import {PushProviderError} from "./pushProviders";
import fs from "node:fs";
import {processPushOutbox,queueAcceptedClientPush,queueArrivedClientPush,queueCompletedClientPush,queueNewJobFirmPushes} from "./push";

function setup():Database{const db=new DatabaseCtor(":memory:");db.exec(SCHEMA_SQL);db.exec(`INSERT INTO users(id,role,name,phone) VALUES('client','client','Ana','0721000000'),('ua','firma','Firma A','0722000001'),('ub','firma','Firma B','0722000002'),('uc','firma','Firma C','0722000003');INSERT INTO firms(id,user_id,coverage_city,verified) VALUES('fa','ua','București',1),('fb','ub','Brașov',1),('fc','uc','București',0);INSERT INTO jobs(id,client_id,street,city,sqm,space_type,when_type,price_gross,duration_minutes,status) VALUES('job','client','Strada Secretă 99','București',120,'apartament','asap',780,210,'waiting');`);return db;}
function device(db:Database,id:string,user:string,platform="ANDROID"){db.prepare("INSERT INTO push_devices(id,user_id,platform,device_token) VALUES(?,?,?,?)").run(id,user,platform,`${id}_abcdefghijklmnopqrstuvwxyz`);}
describe("push primary with SMS fallback",()=>{let db:Database;beforeEach(()=>{db=setup();process.env.PUSH_ENABLED="true";process.env.SMS_FALLBACK_ENABLED="true";});afterEach(()=>{db.close();delete process.env.PUSH_ENABLED;delete process.env.SMS_FALLBACK_ENABLED;});
  it("queues only eligible firms and excludes exact address",()=>{device(db,"da","ua");const ids=queueNewJobFirmPushes(db,{id:"job",city:"București",spaceType:"apartament",sqm:120});expect(ids).toHaveLength(1);const row=db.prepare("SELECT recipient_user_id,title,message_body,data_json FROM push_notification_outbox").get() as Record<string,string>;expect(row.recipient_user_id).toBe("ua");expect(row.title).toBe("Lucrare nouă disponibilă");expect(row.message_body).not.toContain("Secretă");expect(row.data_json).not.toContain("Secretă");});
  it("deduplicates events and supports multiple devices",()=>{device(db,"d1","ua");device(db,"d2","ua","IOS");expect(queueNewJobFirmPushes(db,{id:"job",city:"București",spaceType:"apartament",sqm:120})).toHaveLength(2);queueNewJobFirmPushes(db,{id:"job",city:"București",spaceType:"apartament",sqm:120});expect((db.prepare("SELECT count(*) n FROM push_notification_outbox").get() as {n:number}).n).toBe(2);});
  it("successful push does not queue fallback SMS",async()=>{device(db,"d1","ua");const ids=queueNewJobFirmPushes(db,{id:"job",city:"București",spaceType:"apartament",sqm:120});await processPushOutbox(db,ids,async()=>({providerMessageId:"push-1"}));expect((db.prepare("SELECT count(*) n FROM notification_outbox").get() as {n:number}).n).toBe(0);});
  it("missing token queues SMS fallback",async()=>{const ids=queueNewJobFirmPushes(db,{id:"job",city:"București",spaceType:"apartament",sqm:120});await processPushOutbox(db,ids,async()=>({providerMessageId:"never"}));expect((db.prepare("SELECT count(*) n FROM notification_outbox").get() as {n:number}).n).toBe(1);});
  it("permanent invalid token is revoked safely",async()=>{device(db,"d1","ua");const ids=queueNewJobFirmPushes(db,{id:"job",city:"București",spaceType:"apartament",sqm:120});await processPushOutbox(db,ids,async()=>{throw new PushProviderError("PUSH_TOKEN_INVALID",true)});expect((db.prepare("SELECT push_enabled,revoked_at FROM push_devices WHERE id='d1'").get() as {push_enabled:number;revoked_at:string|null}).push_enabled).toBe(0);});
  it("queues client events only after authoritative payment, proof, and job states",()=>{expect(queueAcceptedClientPush(db,"job")).toEqual([]);db.prepare("UPDATE jobs SET status='accepted',accepted_firm_id='fa' WHERE id='job'").run();expect(queueAcceptedClientPush(db,"job")).toEqual([]);db.prepare("INSERT INTO payments(id,job_id,amount_gross,commission_amount,amount_net,status) VALUES('pay','job',780,140,640,'authorized')").run();expect(queueAcceptedClientPush(db,"job")).toHaveLength(1);db.prepare("UPDATE jobs SET status='arrived' WHERE id='job'").run();expect(queueArrivedClientPush(db,"job")).toEqual([]);db.prepare("INSERT INTO job_photos(id,job_id,owner_user_id,uploaded_by_firm_id,proof_type,filename,mime_type,file_size,status,validated_at) VALUES('a','job','ua','fa','ARRIVAL','a.jpg','image/jpeg',10,'VALID',datetime('now'))").run();expect(queueArrivedClientPush(db,"job")).toHaveLength(1);db.prepare("UPDATE jobs SET status='completed' WHERE id='job'").run();expect(queueCompletedClientPush(db,"job")).toEqual([]);db.prepare("INSERT INTO job_photos(id,job_id,owner_user_id,uploaded_by_firm_id,proof_type,filename,mime_type,file_size,status,validated_at) VALUES('c','job','ua','fa','COMPLETION','c.jpg','image/jpeg',10,'VALID',datetime('now'))").run();db.prepare("UPDATE payments SET status='captured' WHERE id='pay'").run();expect(queueCompletedClientPush(db,"job")).toHaveLength(1);});
  it("registration API derives identity and never accepts a user id",()=>{const source=fs.readFileSync("src/app/api/push/register/route.ts","utf8");expect(source).toContain("getCurrentUser(req)");expect(source).not.toMatch(/body\.userId|body\.user_id/);});
});
