import DatabaseCtor from "better-sqlite3";
import type {Database} from "better-sqlite3";
import {beforeEach,describe,expect,it} from "vitest";
import {SCHEMA_SQL} from "./db";
import {createVerifiedReview,getPublicTrustSnapshot,recalculateFirmRating} from "./reviews";

function setup(){const db=new DatabaseCtor(":memory:");db.exec(SCHEMA_SQL);db.exec(`INSERT INTO users(id,role,name,email,phone) VALUES ('client','client','Andrei Popescu','andrei@example.ro','0712345678'),('other','client','Alt Client','alt@example.ro','0799999999'),('fu','firma','Firma Curată','firma@example.ro','0700000000');INSERT INTO firms(id,user_id,coverage_city,verified) VALUES ('firm','fu','Constanța',1);`);return db;}
function job(db:Database,id="job",status="completed",client="client"){db.prepare(`INSERT INTO jobs(id,client_id,street,city,sqm,space_type,when_type,price_gross,duration_minutes,status,accepted_firm_id) VALUES (?,?,'Adresă secretă','Constanța',50,'apartament','asap',500,120,?,'firm')`).run(id,client,status);}
function eligible(db:Database,id="job"){for(const [pid,type] of [[`${id}a`,`ARRIVAL`],[`${id}c`,`COMPLETION`]])db.prepare(`INSERT INTO job_photos(id,job_id,owner_user_id,uploaded_by_firm_id,proof_type,filename,mime_type,file_size,status,validated_at) VALUES (?,?,'fu','firm',?,'x.jpg','image/jpeg',10,'VALID',datetime('now'))`).run(pid,id,type);db.prepare("INSERT INTO payments(id,job_id,amount_gross,commission_amount,amount_net,status) VALUES (?,?,?,?,?,'captured')").run(`pay-${id}`,id,500,75,425);}

describe("verified reviews core",()=>{let db:Database;beforeEach(()=>{db=setup();});
  it("rejects unrelated client and derives firm from job",()=>{job(db);eligible(db);expect(createVerifiedReview(db,{jobId:"job",clientId:"other",rating:5}).ok).toBe(false);const result=createVerifiedReview(db,{jobId:"job",clientId:"client",rating:5});expect(result.ok).toBe(true);expect((db.prepare("SELECT firm_id,client_id FROM ratings").get() as {firm_id:string;client_id:string})).toEqual({firm_id:"firm",client_id:"client"});});
  it("rejects review before completion",()=>{job(db,"job","arrived");eligible(db);const r=createVerifiedReview(db,{jobId:"job",clientId:"client",rating:5});expect(r.ok).toBe(false);if(!r.ok)expect(r.status).toBe(409);});
  it("requires proof and captured payment",()=>{job(db);expect(createVerifiedReview(db,{jobId:"job",clientId:"client",rating:5}).ok).toBe(false);});
  it("allows exactly one review per completed eligible job",()=>{job(db);eligible(db);expect(createVerifiedReview(db,{jobId:"job",clientId:"client",rating:4,reviewText:"Foarte bine"}).ok).toBe(true);const duplicate=createVerifiedReview(db,{jobId:"job",clientId:"client",rating:1});expect(duplicate.ok).toBe(false);if(!duplicate.ok)expect(duplicate.status).toBe(409);});
  it("calculates average server-side from published eligible reviews",()=>{job(db,"j1");eligible(db,"j1");job(db,"j2");eligible(db,"j2");createVerifiedReview(db,{jobId:"j1",clientId:"client",rating:5});createVerifiedReview(db,{jobId:"j2",clientId:"client",rating:3});const firm=getPublicTrustSnapshot(db,"firm").firms[0];expect(firm.average_rating).toBe(4);expect(firm.review_count).toBe(2);});
  it("excludes hidden reviews from average and public display",()=>{job(db);eligible(db);const r=createVerifiedReview(db,{jobId:"job",clientId:"client",rating:5});if(!r.ok)throw new Error();db.prepare("UPDATE ratings SET moderation_status='hidden' WHERE id=?").run(r.id);recalculateFirmRating(db,"firm");expect(getPublicTrustSnapshot(db).reviews).toHaveLength(0);expect((db.prepare("SELECT rating_count FROM firms WHERE id='firm'").get() as {rating_count:number}).rating_count).toBe(0);});
  it("derives verified badge and redacts public contact data",()=>{job(db);eligible(db);createVerifiedReview(db,{jobId:"job",clientId:"client",rating:5,reviewText:"Scrie la secret@example.ro sau 0712345678"});const review=getPublicTrustSnapshot(db).reviews[0];expect(review.badge).toBe("Recenzie verificată");expect(review.reviewer).toBe("Andrei P.");expect(JSON.stringify(review)).not.toContain("secret@example.ro");expect(JSON.stringify(review)).not.toContain("0712345678");expect(JSON.stringify(review)).not.toContain("Adresă secretă");});
  it("shows an honest zero-review state without generated testimonials",()=>{const snapshot=getPublicTrustSnapshot(db);expect(snapshot.reviews).toEqual([]);});
});
