import {beforeEach,afterEach,describe,it,expect} from "vitest";
import Database from "better-sqlite3";
import {SCHEMA_SQL} from "./db";
import {inventoryHistory,setInventoryThreshold,hostInventory,createInventoryItem,moveInventory,createTeamBlock,cancelTeamBlock,teamBlocks,hostChecks,setHostCheck,WORKSPACE_SCHEMA,saveProperty,ownProperty,linkPropertyJob,assignTeam,sendJobMessage,setChecklist,importCalendar,parseCalendar} from "./workspace";
let db:Database.Database;
beforeEach(()=>{db=new Database(":memory:");db.pragma("foreign_keys=ON");db.exec(SCHEMA_SQL);db.exec(WORKSPACE_SCHEMA);db.exec("INSERT INTO users(id,role,name) VALUES('a','client','A'),('b','client','B'),('f','firma','F'),('g','firma','G');INSERT INTO firms(id,user_id,coverage_city) VALUES('firm','f','București'),('other','g','București')");});
afterEach(()=>db.close());
const property={name:"Acasă",city:"București",street:"Strada Test 1",sqm:75,space_type:"apartament",kind:"home",budget_bani:120000};
function job(id:string,start="2026-09-12T09:00:00Z",client="a",firm="firm"){db.prepare("INSERT INTO jobs(id,client_id,street,city,sqm,space_type,when_type,scheduled_at,price_gross,duration_minutes,status,accepted_firm_id) VALUES(?,?, 'Test','București',75,'apartament','scheduled',?,500,120,'accepted',?)").run(id,client,start,firm)}
describe("workspace ownership and scheduling",()=>{
 it("does not reveal, edit or associate another client's property",()=>{const id=saveProperty(db,"a",property);expect(()=>ownProperty(db,"b",id)).toThrow();expect(()=>saveProperty(db,"b",{...property,id})).toThrow();job("j");expect(()=>linkPropertyJob(db,"b",id,"j")).toThrow();expect(ownProperty(db,"a",id).budget_bani).toBe(120000)});
 it("rejects unbounded and noninteger budgets",()=>{expect(()=>saveProperty(db,"a",{...property,budget_bani:1.5})).toThrow();expect(()=>saveProperty(db,"a",{...property,sqm:Infinity})).toThrow()});
 it("associates only the owner's jobs",()=>{const id=saveProperty(db,"a",property);job("j",undefined,"b");expect(()=>linkPropertyJob(db,"a",id,"j")).toThrow()});
 it("rejects overlapping team assignments, including buffer, but allows adjacent slots",()=>{job("j1");job("j2","2026-09-12T11:15:00Z");job("j3","2026-09-12T11:30:00Z");db.exec("INSERT INTO workspace_teams(id,firm_id,name) VALUES('t','firm','Echipa')");assignTeam(db,"f","t","j1");expect(()=>assignTeam(db,"f","t","j2")).toThrow(/interval/);assignTeam(db,"f","t","j3");expect(db.prepare("SELECT * FROM workspace_assignments").all()).toHaveLength(2);expect(()=>assignTeam(db,"g","t","j1")).toThrow()});
 it("deduplicates retried messages and rejects conflicting reuse or outsiders",()=>{job("j");const id=sendJobMessage(db,"a","j","Bună ziua","retry-1");expect(sendJobMessage(db,"a","j","Bună ziua","retry-1")).toBe(id);expect(()=>sendJobMessage(db,"a","j","Alt mesaj","retry-1")).toThrow();expect(()=>sendJobMessage(db,"b","j","Salut","retry-2")).toThrow();expect(()=>sendJobMessage(db,"g","j","Salut","retry-3")).toThrow();expect(sendJobMessage(db,"f","j","Bună ziua","reply-1")).toBeTruthy()});
 it("restricts checklist updates to the allocated firm while job is active",()=>{job("j");expect(()=>setChecklist(db,"a","j","floors",true)).toThrow();expect(()=>setChecklist(db,"g","j","floors",true)).toThrow();setChecklist(db,"f","j","floors",true);db.exec("UPDATE jobs SET status='completed' WHERE id='j'");expect(()=>setChecklist(db,"f","j","floors",false)).toThrow()});
});
const calendar=(event:string)=>`BEGIN:VCALENDAR\r\n${event}\r\nEND:VCALENDAR`;
const event="BEGIN:VEVENT\r\nUID:booking-1\r\nDTSTART;VALUE=DATE:20260915\r\nDTEND;VALUE=DATE:20260918\r\nSUMMARY:Private guest name\r\nEND:VEVENT";
describe("calendar imports",()=>{
 it("upserts by property/source/UID and does not expose guest names",()=>{const id=saveProperty(db,"a",{...property,kind:"host"});importCalendar(db,"a",id,"PMS",calendar(event));importCalendar(db,"a",id,"PMS",calendar(event.replace("20260918","20260919")));const rows=db.prepare("SELECT * FROM workspace_calendar_events").all() as {summary:string;ends_at:string}[];expect(rows).toHaveLength(1);expect(rows[0].ends_at).toContain("2026-09-19");expect(rows[0].summary).toBe("Perioadă ocupată");expect(()=>importCalendar(db,"b",id,"PMS",calendar(event))).toThrow()});
 it("applies explicit cancellation and keeps events omitted from a later partial import",()=>{const id=saveProperty(db,"a",property);importCalendar(db,"a",id,"PMS",calendar(event));importCalendar(db,"a",id,"PMS",calendar("BEGIN:VEVENT\r\nUID:booking-1\r\nSTATUS:CANCELLED\r\nEND:VEVENT"));expect(db.prepare("SELECT status FROM workspace_calendar_events").get()).toEqual({status:"cancelled"})});
 it("rejects invalid dates and unsupported recurrence instead of silently shifting bookings",()=>{expect(()=>parseCalendar(calendar(event.replace("20260915","20260231")))).toThrow();expect(()=>parseCalendar(calendar(event.replace("SUMMARY:","RRULE:FREQ=DAILY\r\nSUMMARY:")))).toThrow()});
});

describe('host readiness per stay',()=>{
 const past='BEGIN:VEVENT\r\nUID:past-stay\r\nDTSTART:20240101T110000Z\r\nDTEND:20240102T110000Z\r\nEND:VEVENT';
 function setup(){const id=saveProperty(db,'a',{...property,kind:'host'});importCalendar(db,'a',id,'PMS',calendar(past));return db.prepare('SELECT id,ends_at FROM workspace_calendar_events WHERE property_id=?').get(id) as {id:string;ends_at:string}}
 it('persists checks only for the owner and audits changes',()=>{const e=setup();expect(()=>setHostCheck(db,'b',e.id,e.ends_at,'linen',true)).toThrow();setHostCheck(db,'a',e.id,e.ends_at,'linen',true);expect(hostChecks(db,'a')).toHaveLength(1);expect(hostChecks(db,'b')).toHaveLength(0);setHostCheck(db,'a',e.id,e.ends_at,'linen',false);expect(hostChecks(db,'a')[0]).toMatchObject({done:0});expect(db.prepare("SELECT * FROM workspace_audit WHERE action='host.check'").all()).toHaveLength(2)});
 it('does not reuse readiness after changed checkout, cancellation or archival',()=>{const e=setup();setHostCheck(db,'a',e.id,e.ends_at,'linen',true);db.prepare('UPDATE workspace_calendar_events SET ends_at=? WHERE id=?').run('2024-01-03T11:00:00.000Z',e.id);expect(hostChecks(db,'a')).toHaveLength(0);expect(()=>setHostCheck(db,'a',e.id,e.ends_at,'linen',true)).toThrow(/modificat/);db.prepare("UPDATE workspace_calendar_events SET status='cancelled' WHERE id=?").run(e.id);expect(()=>setHostCheck(db,'a',e.id,'2024-01-03T11:00:00.000Z','linen',true)).toThrow();db.exec('UPDATE workspace_properties SET archived=1');expect(hostChecks(db,'a')).toHaveLength(0)});
 it('rejects future checkouts and unsupported keys',()=>{const e=setup();expect(()=>setHostCheck(db,'a',e.id,e.ends_at,'fake',true)).toThrow();db.prepare('UPDATE workspace_calendar_events SET ends_at=? WHERE id=?').run('2099-01-03T11:00:00.000Z',e.id);expect(()=>setHostCheck(db,'a',e.id,'2099-01-03T11:00:00.000Z','linen',true)).toThrow(/eliberarea/)});
});


describe('team unavailability',()=>{
 beforeEach(()=>db.exec("INSERT INTO workspace_teams(id,firm_id,name) VALUES('t','firm','Echipa')"));
 it('blocks allocation through the travel buffer and allows an adjacent interval',()=>{job('j');createTeamBlock(db,'f','t','2026-09-12T11:15:00.000Z','2026-09-12T12:00:00.000Z','Concediu');expect(()=>assignTeam(db,'f','t','j')).toThrow(/indisponibilă/);const b=teamBlocks(db,'f')[0] as {id:string};cancelTeamBlock(db,'f',b.id);createTeamBlock(db,'f','t','2026-09-12T11:30:00.000Z','2026-09-12T12:00:00.000Z','Concediu');assignTeam(db,'f','t','j')});
 it('refuses a new block over an existing allocated job without changing the job',()=>{job('j');assignTeam(db,'f','t','j');expect(()=>createTeamBlock(db,'f','t','2026-09-12T10:00:00.000Z','2026-09-12T12:00:00.000Z','Concediu')).toThrow(/Realocă/);expect(teamBlocks(db,'f')).toHaveLength(0);expect(db.prepare('SELECT * FROM workspace_assignments').all()).toHaveLength(1)});
 it('isolates owners and makes unblock retry safe',()=>{expect(()=>createTeamBlock(db,'g','t','2026-09-12T09:00:00.000Z','2026-09-12T12:00:00.000Z','Concediu')).toThrow();const id=createTeamBlock(db,'f','t','2026-09-12T09:00:00.000Z','2026-09-12T12:00:00.000Z','Concediu');expect(teamBlocks(db,'g')).toHaveLength(0);expect(()=>cancelTeamBlock(db,'g',id)).toThrow();cancelTeamBlock(db,'f',id);cancelTeamBlock(db,'f',id);expect(teamBlocks(db,'f')).toHaveLength(0);expect(db.prepare("SELECT * FROM workspace_audit WHERE action='team.unblock'").all()).toHaveLength(1)});
 it('rejects malformed dates, reversed intervals and overlapping blocks',()=>{expect(()=>createTeamBlock(db,'f','t','bad','bad','Concediu')).toThrow();expect(()=>createTeamBlock(db,'f','t','2026-09-12T12:00:00.000Z','2026-09-12T09:00:00.000Z','Concediu')).toThrow();createTeamBlock(db,'f','t','2026-09-12T09:00:00.000Z','2026-09-12T12:00:00.000Z','Concediu');expect(()=>createTeamBlock(db,'f','t','2026-09-12T11:00:00.000Z','2026-09-12T13:00:00.000Z','Concediu')).toThrow(/suprapusă/)});
});


describe('Host stock ledger',()=>{
 function item(){const p=saveProperty(db,'a',{...property,kind:'host'});return createInventoryItem(db,'a',p,'Set lenjerie','seturi',2)}
 it('updates thresholds only for the owner and isolates history',()=>{const id=item();expect(()=>setInventoryThreshold(db,'b',id,4)).toThrow();setInventoryThreshold(db,'a',id,4);expect(hostInventory(db,'a')[0]).toMatchObject({threshold:4});moveInventory(db,'a',id,2,'Intrare','r1');expect(inventoryHistory(db,'a')).toHaveLength(1);expect(inventoryHistory(db,'b')).toHaveLength(0)});
 it('records supply and consumption atomically without duplicate retries',()=>{const id=item();moveInventory(db,'a',id,5,'Aprovizionare','r1');moveInventory(db,'a',id,5,'Aprovizionare','r1');moveInventory(db,'a',id,-3,'Pregătire sejur','r2');expect(hostInventory(db,'a')[0]).toMatchObject({quantity:2,threshold:2});expect(db.prepare('SELECT * FROM workspace_inventory_movements').all()).toHaveLength(2)});
 it('rejects negative stock, fractional quantities and conflicting retry keys',()=>{const id=item();expect(()=>moveInventory(db,'a',id,-1,'Consum','r0')).toThrow();expect(()=>moveInventory(db,'a',id,1.5,'Intrare','r0')).toThrow();moveInventory(db,'a',id,5,'Intrare','r1');expect(()=>moveInventory(db,'a',id,6,'Intrare','r1')).toThrow();expect(hostInventory(db,'a')[0]).toMatchObject({quantity:5});expect(db.prepare('SELECT * FROM workspace_inventory_movements').all()).toHaveLength(1)});
 it('isolates property owners and rejects archived and non-host stock',()=>{const id=item();expect(hostInventory(db,'b')).toHaveLength(0);expect(()=>moveInventory(db,'b',id,5,'Intrare','r1')).toThrow();const home=saveProperty(db,'a',property);expect(()=>createInventoryItem(db,'a',home,'Săpun','buc',1)).toThrow();db.exec('UPDATE workspace_properties SET archived=1');expect(()=>moveInventory(db,'a',id,5,'Intrare','r2')).toThrow();expect(hostInventory(db,'a')).toHaveLength(0)});
});
