'use client';
import {useCallback,useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import Script from 'next/script';
import Link from 'next/link';
import {useCurrentUser} from '@/lib/useCurrentUser';
import {Button,Card,Logo} from '@/components/ui';
type Confirmation={status:'authorized'|'requires_action';amountMinor:number;clientSecret?:string;paymentMethodId?:string;publishableKey?:string};
type StripeBrowser={confirmCardPayment:(secret:string,data:{payment_method:string})=>Promise<{error?:{message?:string}}>};
export default function ConfirmCard(){
 const {id}=useParams<{id:string}>(),router=useRouter(),{user,loading}=useCurrentUser();
 const [data,setData]=useState<Confirmation|null>(null),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState<string|null>(null);
 const request=useCallback(async(action:'start'|'verify')=>{const res=await fetch(`/api/jobs/${encodeURIComponent(id)}/authorize-card`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action}),cache:'no-store'});const body=await res.json();if(!res.ok)throw Error(body.error??'Confirmarea nu poate fi verificată.');return body as Confirmation;},[id]);
 const load=useCallback(async()=>{setBusy(true);setError(null);try{setData(await request('start'))}catch(e){setError(e instanceof Error?e.message:'Verificarea nu a reușit.')}finally{setBusy(false)}},[request]);
 useEffect(()=>{if(loading)return;if(!user){router.replace(`/login?next=${encodeURIComponent(`/client/plata/${id}`)}`);return}if(user.role!=='client')return;let active=true;void request('start').then(result=>{if(active)setData(result)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Verificarea nu a reușit.')});return()=>{active=false};},[user,loading,router,id,request]);
 async function confirm(){if(busy||!ready||!data?.clientSecret||!data.paymentMethodId||!data.publishableKey)return;setBusy(true);setError(null);try{const create=(window as unknown as {Stripe?:(key:string)=>StripeBrowser}).Stripe;if(!create)throw Error('Conexiunea securizată nu este disponibilă. Reîncarcă pagina.');const result=await create(data.publishableKey).confirmCardPayment(data.clientSecret,{payment_method:data.paymentMethodId});if(result.error)throw Error(result.error.message??'Banca nu a confirmat autorizarea.');const verified=await request('verify');setData(verified);if(verified.status!=='authorized')throw Error('Confirmarea este încă necesară. Reîncarcă starea plății.');}catch(e){setError(e instanceof Error?e.message:'Conexiunea s-a întrerupt. Reîncarcă starea plății.')}finally{setBusy(false)}}
 return <main className="min-h-screen bg-mist px-4 py-10"><div className="mx-auto max-w-lg"><Link href="/client"><Logo/></Link><Card className="mt-8"><h1 className="text-2xl font-display font-bold">Confirmă autorizarea cardului</h1><p className="mt-3 text-sm text-muted">Banca poate solicita un cod sau aprobarea în aplicația sa. Suma este rezervată pentru lucrare; încasarea se face la finalizare.</p>{loading?<p className="mt-5">Se verifică sesiunea…</p>:user?.role!=='client'?<p className="mt-5">Folosește contul clientului care a creat lucrarea.</p>:<>{data&&<p className="my-6 text-3xl font-bold">{new Intl.NumberFormat('ro-RO',{style:'currency',currency:'RON'}).format(data.amountMinor/100)}</p>}{data?.status==='authorized'?<div role="status" className="mt-5 space-y-4"><p className="font-bold text-aqua-deep">Autorizarea este confirmată.</p><p className="text-sm text-muted">Revino la lucrare pentru continuarea alocării firmei.</p><Link className="font-bold underline" href="/client">Revino la lucrare</Link></div>:<div className="mt-5 space-y-3"><Button className="w-full" disabled={busy||!ready||!data?.clientSecret} onClick={()=>void confirm()}>{busy?'Se verifică…':'Confirmă prin bancă'}</Button><button className="w-full text-sm underline py-2" disabled={busy} onClick={()=>void load()}>Reîncarcă starea plății</button></div>}</>}{error&&<p role="alert" className="mt-4 text-sm text-coral">{error}</p>}</Card></div>{user?.role==='client'&&<Script src="https://js.stripe.com/v3/" onReady={()=>setReady(true)} onError={()=>setError('Stripe nu s-a putut încărca. Verifică internetul și reîncarcă pagina.')}/>}</main>;
}
