import { useCallback, useState } from "react";
import { useFocusEffect, useLocalSearchParams, router } from "expo-router";
import { StyleSheet, Text, View } from "react-native";
import { api, normalizeApiError } from "@/api";
import { acceptFirmJob, firmOperationError } from "@/firmOperations";
import { jobTypeLabel } from "@/jobTypes";
import { AppScreen, EmptyState, InlineState, Pill, PremiumCard, PrimaryButton } from "@/mobileUi";
import { colors } from "@/theme";
import type { Job } from "@/types";

export default function JobPreview(){const {id}=useLocalSearchParams<{id:string}>();const [job,setJob]=useState<Job|null>(null);const [loading,setLoading]=useState(true);const [accepting,setAccepting]=useState(false);const [error,setError]=useState<string|null>(null);const load=useCallback(async()=>{if(!id)return;setLoading(true);setError(null);try{const result=await api<{job:Job}>(`/api/jobs/${id}`);setJob(result.job)}catch(cause){setError(normalizeApiError(cause).message)}finally{setLoading(false)}},[id]);useFocusEffect(useCallback(()=>{void load()},[load]));async function accept(){if(!job||accepting)return;setAccepting(true);setError(null);try{await acceptFirmJob(job.id,api);router.replace("/(firma)/active")}catch(cause){setError(firmOperationError(cause));await load()}finally{setAccepting(false)}}if(loading||error&&!job)return <AppScreen title="Previzualizare lucrare"><InlineState loading={loading} error={error} onRetry={()=>void load()}/></AppScreen>;if(!job)return <AppScreen title="Previzualizare lucrare"><EmptyState icon="alert-circle-outline" title="Lucrarea nu mai este disponibilă" body="Revino la feed pentru alte lucrări."/></AppScreen>;const date=job.scheduled_at?new Date(job.scheduled_at).toLocaleString("ro-RO",{day:"numeric",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—";return <AppScreen eyebrow="PREVIEW SIGUR" title={jobTypeLabel(job.space_type)} subtitle={`${job.city} · ${job.sqm} m²`}><PremiumCard><View style={s.head}><Pill label="DISPONIBILĂ" tone="green"/><Text style={s.payout}>{typeof job.firm_payout==="number"?`${job.firm_payout} lei`:"—"}</Text></View><Row label="Programare" value={date}/><Row label="Durată estimată" value={job.duration_minutes?`${job.duration_minutes} minute`:"—"}/><Row label="Localitate" value={job.city}/><Text style={s.privacy}>Adresa exactă, datele Clientului, notele private și fotografiile nu sunt disponibile înainte de alocarea confirmată de server.</Text></PremiumCard>{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}<PrimaryButton loading={accepting} disabled={accepting||job.status!=="waiting"} title="Acceptă lucrarea" onPress={()=>void accept()}/><PrimaryButton secondary title="Înapoi la feed" icon="arrow-back" onPress={()=>router.back()}/></AppScreen>}
function Row({label,value}:{label:string;value:string}){return <View style={s.row}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>};const s=StyleSheet.create({head:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},payout:{fontSize:25,fontWeight:"800",color:colors.ink},row:{flexDirection:"row",gap:15,justifyContent:"space-between",paddingVertical:9,borderBottomWidth:1,borderBottomColor:colors.border},label:{fontSize:12,color:colors.muted},value:{fontSize:13,fontWeight:"700",color:colors.ink,textAlign:"right"},privacy:{fontSize:12,lineHeight:19,color:colors.greenDark,backgroundColor:colors.greenSoft,padding:13,borderRadius:14},error:{fontSize:13,color:colors.danger,backgroundColor:"#F8E3E1",padding:13,borderRadius:14}});
