import { useEffect, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { api, normalizeApiError } from "@/api";
import { AppScreen, EmptyState, InlineState, Pill, PremiumCard, SectionTitle } from "@/mobileUi";
import { colors } from "@/theme";
type Snapshot={reviews:{id:string;firmName:string;rating:number;reviewText:string|null;reviewer:string;badge:string}[];firms:{id:string;name:string;verified:number;review_count:number;average_rating:number|null;completed_jobs:number}[]};
export default function Trust(){const [data,setData]=useState<Snapshot|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);async function load(){setLoading(true);setError(null);try{setData(await api<Snapshot>("/api/trust"))}catch(cause){setError(normalizeApiError(cause).message)}finally{setLoading(false)}}useEffect(()=>{void Promise.resolve().then(load)},[]);return <AppScreen eyebrow="ÎNCREDERE & SIGURANȚĂ" title="Dovezi, nu promisiuni" subtitle="NITIDO leagă verificarea, dovezile foto, plata și recenziile de lucrări reale."><PremiumCard><TrustRow title="Firme verificate" body="Statusul este furnizat de backend, fără insigne inventate."/><TrustRow title="Dovezi obligatorii" body="Fotografia de sosire permite începerea, iar fotografia finală permite finalizarea."/><TrustRow title="Plată controlată" body="Autorizarea și capturarea sunt confirmate de server și procesator; NITIDO nu promite decontare bancară instant."/><TrustRow title="Adresă protejată" body="Adresa exactă este ascunsă înainte de alocarea confirmată."/></PremiumCard><SectionTitle title="Recenzii verificate"/><InlineState loading={loading} error={error} onRetry={()=>void load()}/>{!loading&&!error&&(data?.reviews.length?data.reviews.map(review=><PremiumCard key={review.id}><View style={s.row}><Text style={s.title}>{review.firmName}</Text><Pill label={review.badge} tone="green"/></View><Text style={s.stars}>{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</Text>{review.reviewText?<Text style={s.body}>{review.reviewText}</Text>:null}<Text style={s.reviewer}>{review.reviewer} · Client verificat</Text></PremiumCard>):<EmptyState icon="star-outline" title="Încă nu există recenzii publice" body="Recenziile apar numai după lucrări eligibile și finalizate prin NITIDO."/>)}<Text style={s.support}>Raportare și suport: 0341.402.403 · contact@nitido.ro</Text></AppScreen>}
function TrustRow({title,body}:{title:string;body:string}){return <View style={s.trust}><Text style={s.title}>{title}</Text><Text style={s.body}>{body}</Text></View>}
const s=StyleSheet.create({trust:{paddingVertical:6},row:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10},title:{fontSize:16,fontWeight:"800",color:colors.ink},body:{fontSize:13,lineHeight:20,color:colors.muted},stars:{fontSize:19,color:"#B98017",letterSpacing:2},reviewer:{fontSize:11,color:colors.muted},support:{fontSize:12,color:colors.greenDark,textAlign:"center"}});
