import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {NextRequest} from 'next/server';
const state=vi.hoisted(()=>({constructEvent:vi.fn(),retrieve:vi.fn(),balance:vi.fn(),payout:vi.fn(),dispute:vi.fn()}));
vi.mock('@/lib/db',async original=>{const actual=await original<typeof import('@/lib/db')>();const {default:Sqlite}=await import('better-sqlite3');const db=new Sqlite(':memory:');db.exec(actual.SCHEMA_SQL);return {...actual,db};});
vi.mock('stripe',()=>({default:class{webhooks={constructEvent:state.constructEvent};refunds={retrieve:state.retrieve};balanceTransactions={retrieve:state.balance};payouts={retrieve:state.payout};disputes={retrieve:state.dispute}}}));
import {db} from '@/lib/db';
import {POST} from './route';
function request(){return new NextRequest('https://nitido.test/api/stripe/webhook',{method:'POST',headers:{'stripe-signature':'fixture'},body:'fixture'});}
const refund=(status:string)=>({id:'re_test',payment_intent:'pi_test',currency:'ron',amount:50000,status});
beforeEach(()=>{vi.resetAllMocks();vi.stubEnv('STRIPE_SECRET_KEY','sk_test_fixture');vi.stubEnv('STRIPE_WEBHOOK_SECRET','whsec_fixture');db.exec("DROP TRIGGER IF EXISTS reject_refund_update;DELETE FROM payment_authorization_attempts;DELETE FROM stripe_bank_payouts;DELETE FROM stripe_events;DELETE FROM payment_refunds;DELETE FROM payments;DELETE FROM jobs;DELETE FROM firms;DELETE FROM users;INSERT INTO users(id,role,name) VALUES('u','client','Test');INSERT INTO jobs(id,client_id,city,street,sqm,space_type,when_type,price_gross,duration_minutes,status) VALUES('j','u','Test','Test',50,'apartament','asap',500,120,'completed');INSERT INTO payments(id,job_id,amount_gross,commission_amount,amount_net,status,stripe_payment_intent_id,refund_status) VALUES('p','j',500,90,410,'captured','pi_test','pending');INSERT INTO payment_refunds(id,payment_id,amount,stripe_refund_id,status) VALUES('r','p',500,'re_test','pending')");state.constructEvent.mockReturnValue({id:'evt_test',type:'refund.updated',data:{object:{id:'re_test'}}});});
afterEach(()=>vi.unstubAllEnvs());
describe('refund webhook reconciliation',()=>{
 it('fetches current provider state and deduplicates delivery',async()=>{state.retrieve.mockResolvedValue(refund('succeeded'));expect((await POST(request())).status).toBe(200);expect(db.prepare('SELECT status FROM payments').get()).toEqual({status:'refunded'});expect((await POST(request())).status).toBe(200);expect(state.retrieve).toHaveBeenCalledTimes(1);});
 it('allows retry after provider failure',async()=>{state.retrieve.mockRejectedValueOnce(Error('timeout')).mockResolvedValueOnce(refund('succeeded'));expect((await POST(request())).status).toBe(500);expect(db.prepare('SELECT * FROM stripe_events').all()).toHaveLength(0);expect((await POST(request())).status).toBe(200);expect(db.prepare('SELECT status FROM payments').get()).toEqual({status:'refunded'});});
 it('does not equate a charge notification with successful full refund',async()=>{state.constructEvent.mockReturnValue({id:'evt_test',type:'charge.refunded',data:{object:{payment_intent:'pi_test',metadata:{paymentId:'p'},amount_refunded:100}}});state.retrieve.mockResolvedValue(refund('pending'));expect((await POST(request())).status).toBe(200);expect(db.prepare('SELECT status FROM payments').get()).toEqual({status:'captured'});});
 it('rejects invalid signatures without fetching provider data',async()=>{state.constructEvent.mockImplementation(()=>{throw Error('bad signature')});expect((await POST(request())).status).toBe(400);expect(state.retrieve).not.toHaveBeenCalled();});
});

function event(type:string,object:Record<string,unknown>,account?:string){state.constructEvent.mockReturnValue({id:'evt_test',type,data:{object},...(account?{account}:{})});}
function firm(){db.exec("INSERT INTO users(id,role,name) VALUES('fu','firma','Firma');INSERT INTO firms(id,user_id,coverage_city,stripe_account_id) VALUES('f','fu','București','acct_f');UPDATE jobs SET accepted_firm_id='f';UPDATE payments SET stripe_transfer_id='tr_test',transfer_status='processed'");}
describe('atomic webhook delivery and bank payout isolation',()=>{
 it('synchronizes cancellation only to the matching authorized payment',async()=>{db.exec("UPDATE payments SET status='authorized';INSERT INTO payment_authorization_attempts(job_id,request_json,provider_key_hash,created_ms,stripe_payment_intent_id,status) VALUES('j','{}','fixture',1,'pi_test','requires_capture')");event('payment_intent.canceled',{id:'pi_test'});expect((await POST(request())).status).toBe(200);expect(db.prepare('SELECT status FROM payments').get()).toEqual({status:'cancelled'});expect(db.prepare('SELECT status FROM payment_authorization_attempts').get()).toEqual({status:'canceled'});});

 it('retries fee synchronization after network failure instead of losing the event',async()=>{event('charge.succeeded',{id:'ch_test',payment_intent:'pi_test',balance_transaction:'txn_test'});state.balance.mockRejectedValueOnce(Error('timeout')).mockResolvedValueOnce({fee:123,currency:'ron',source:'ch_test'});expect((await POST(request())).status).toBe(500);expect(db.prepare('SELECT * FROM stripe_events').all()).toHaveLength(0);expect((await POST(request())).status).toBe(200);expect(db.prepare('SELECT stripe_fee_amount FROM payments').get()).toEqual({stripe_fee_amount:123});});
 it('rejects a fee for another charge',async()=>{event('charge.succeeded',{id:'ch_test',payment_intent:'pi_test',balance_transaction:'txn_test'});state.balance.mockResolvedValue({fee:123,currency:'ron',source:'ch_other'});expect((await POST(request())).status).toBe(500);expect(db.prepare('SELECT stripe_fee_amount FROM payments').get()).toEqual({stripe_fee_amount:null});});
 it('rolls back the event receipt together with every refund mutation',async()=>{db.exec("CREATE TRIGGER reject_refund_update BEFORE UPDATE ON payments BEGIN SELECT RAISE(ABORT,'fixture'); END");state.retrieve.mockResolvedValue(refund('succeeded'));expect((await POST(request())).status).toBe(500);expect(db.prepare('SELECT * FROM stripe_events').all()).toHaveLength(0);expect(db.prepare('SELECT status FROM payment_refunds').get()).toEqual({status:'pending'});db.exec('DROP TRIGGER reject_refund_update');expect((await POST(request())).status).toBe(200);});
 it('does not erase a successful concurrent delivery when another delivery fails',async()=>{let reject!:(reason:Error)=>void;state.retrieve.mockImplementationOnce(()=>new Promise((_,fail)=>{reject=fail})).mockResolvedValueOnce(refund('succeeded'));const first=POST(request());await vi.waitFor(()=>expect(state.retrieve).toHaveBeenCalledTimes(1));expect((await POST(request())).status).toBe(200);reject(Error('timeout'));expect((await first).status).toBe(500);expect(db.prepare('SELECT * FROM stripe_events').all()).toHaveLength(1);expect(db.prepare('SELECT status FROM payments').get()).toEqual({status:'refunded'});});
 it('records a bank payout without marking individual jobs paid',async()=>{firm();event('payout.paid',{id:'po_test'},'acct_f');state.payout.mockResolvedValue({id:'po_test',amount:41000,currency:'ron',status:'paid',arrival_date:1800000000});expect((await POST(request())).status).toBe(200);expect(state.payout).toHaveBeenCalledWith('po_test',{}, {stripeAccount:'acct_f'});expect(db.prepare('SELECT status,amount_minor FROM stripe_bank_payouts').get()).toEqual({status:'paid',amount_minor:41000});expect(db.prepare('SELECT payout_status FROM payments').get()).toEqual({payout_status:'unknown'});});
 it('uses current payout state even for an old failed notification',async()=>{firm();event('payout.failed',{id:'po_test'},'acct_f');state.payout.mockResolvedValue({id:'po_test',amount:41000,currency:'ron',status:'paid',arrival_date:1800000000});expect((await POST(request())).status).toBe(200);expect(db.prepare('SELECT status FROM stripe_bank_payouts').get()).toEqual({status:'paid'});});
 it('ignores payouts for an unknown connected account',async()=>{event('payout.paid',{id:'po_other'},'acct_other');expect((await POST(request())).status).toBe(200);expect(state.payout).not.toHaveBeenCalled();expect(db.prepare('SELECT * FROM stripe_bank_payouts').all()).toHaveLength(0);});
 it('does not mutate platform refunds from a connected-account notification',async()=>{event('refund.updated',{id:'re_test'},'acct_other');expect((await POST(request())).status).toBe(200);expect(state.retrieve).not.toHaveBeenCalled();expect(db.prepare('SELECT status FROM payments').get()).toEqual({status:'captured'});});
 it('does not turn a failed authorization event into a failed transfer',async()=>{firm();event('payment_intent.payment_failed',{id:'pi_test',metadata:{paymentId:'p'}});expect((await POST(request())).status).toBe(200);expect(db.prepare('SELECT transfer_status FROM payments').get()).toEqual({transfer_status:'processed'});});
 it('does not mark a partial transfer reversal as fully reversed',async()=>{firm();event('transfer.reversed',{id:'tr_test',reversed:false,amount_reversed:100});expect((await POST(request())).status).toBe(200);expect(db.prepare('SELECT transfer_status FROM payments').get()).toEqual({transfer_status:'processed'});});
 it('matches a dispute to the charge and reads its current status',async()=>{db.exec("UPDATE payments SET stripe_charge_id='ch_test'");event('charge.dispute.created',{id:'dp_test',charge:'ch_test'});state.dispute.mockResolvedValue({id:'dp_test',charge:'ch_test',status:'won'});expect((await POST(request())).status).toBe(200);expect(db.prepare('SELECT dispute_status FROM payments').get()).toEqual({dispute_status:'won'});});
});
