import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import Database from 'better-sqlite3';
import {NextRequest} from 'next/server';
import {initializeDatabase} from '@/lib/db';
import {requestAccountDeletion} from '@/lib/accountDeletion';
import type {AdminRole} from '@/lib/adminRolesShared';
const state=vi.hoisted(()=>({db:null as unknown as Database.Database,role:'operator' as AdminRole|null,actor:'nominal-operator',rate:true}));
vi.mock('@/lib/db',async original=>({...await original<typeof import('@/lib/db')>(),get db(){return state.db;}}));
vi.mock('@/lib/adminAuth',()=>({getAdminIdentity:async()=>state.role?{role:state.role,id:state.actor}:null}));
vi.mock('@/lib/security',async original=>({...await original<typeof import('@/lib/security')>(),consumeRateLimit:()=>state.rate}));
import {GET,POST} from './route';
let id:string;
const read=(offset='0')=>GET(new NextRequest('https://nitido.ro/api/admin/account-deletion?offset='+offset));
const send=(body:unknown={id,revision:1,reason:'Verificare nominală',actorId:'forged',status:'deleted'},headers:Record<string,string>={origin:'https://nitido.ro'})=>POST(new NextRequest('https://nitido.ro/api/admin/account-deletion',{method:'POST',headers,body:JSON.stringify(body)}));
beforeEach(()=>{state.db=new Database(':memory:');state.db.pragma('foreign_keys=ON');initializeDatabase(state.db);state.db.exec("INSERT INTO users(id,role,name,email) VALUES('c','client','Client','client@example.test')");id=requestAccountDeletion(state.db,'c').request.id;state.role='operator';state.actor='nominal-operator';state.rate=true;vi.stubEnv('NITIDO_ENABLE_BEARER_AUTH','false');});
afterEach(()=>{state.db.close();vi.unstubAllEnvs();});
it('allows only operational roles, and rechecks authorization before review replay',async()=>{for(const role of ['operator','manager','super_admin'] as const){state.role=role;expect((await read()).status).toBe(200);}state.role='finance';expect((await read()).status).toBe(403);expect((await send()).status).toBe(403);state.role=null;expect((await read()).status).toBe(401);state.role='operator';expect((await send()).status).toBe(200);state.role=null;expect((await send()).status).toBe(401);});
it('uses nominal identity and fixed under_review transition; idempotent replay is author-specific',async()=>{const response=await send();expect(await response.json()).toMatchObject({request:{status:'under_review',revision:2},replayed:false});expect(state.db.prepare('SELECT actor_id FROM account_deletion_events WHERE revision=2').get()).toEqual({actor_id:'nominal-operator'});expect((await (await send()).json()).replayed).toBe(true);state.actor='other-operator';expect((await send()).status).toBe(409);expect(response.headers.get('Cache-Control')).toBe('private, no-store');});
it('blocks missing/foreign origin and arbitrary bearer admin overrides',async()=>{vi.stubEnv('NITIDO_ENABLE_BEARER_AUTH','true');for(const headers of ([{},{origin:'https://evil.test'},{origin:'https://evil.test',authorization:'Bearer token'}] as Record<string,string>[]))expect((await send(undefined,headers)).status).toBe(403);});
it('validates pagination/body/rate without truncating or mutating the journal',async()=>{expect((await read('-1')).status).toBe(400);expect((await read('bad')).status).toBe(400);expect((await send([])).status).toBe(400);expect((await send({id,revision:1,reason:'x'.repeat(12001)})).status).toBe(413);state.rate=false;expect((await read()).status).toBe(429);expect((await send()).status).toBe(429);expect(state.db.prepare('SELECT * FROM account_deletion_events').all()).toHaveLength(1);});
