import {createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode} from "react";
import {api,normalizeApiError,setSessionToken} from "./api";
import {nativeSessionRequired} from "./sessionStore";
import type {SessionUser,UserRole} from "./types";
import {unregisterCurrentPush} from "./push";
type AuthValue={user:SessionUser|null;loading:boolean;error:string|null;login:(email:string,password:string,role:UserRole)=>Promise<void>;logout:()=>Promise<void>;restore:()=>Promise<void>};
const AuthContext=createContext<AuthValue|null>(null);
export function AuthProvider({children}:{children:ReactNode}){const [user,setUser]=useState<SessionUser|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const restore=useCallback(async()=>{setLoading(true);try{const result=await api<{user:SessionUser|null}>("/api/auth/me");setUser(result.user)}catch(e){if(normalizeApiError(e).status===401)await setSessionToken(null);setUser(null)}finally{setLoading(false)}},[]);const login=useCallback(async(email:string,password:string,role:UserRole)=>{setError(null);try{const result=await api<{sessionToken?:string}>("/api/auth/login",{method:"POST",body:JSON.stringify({email,password,role})});if(nativeSessionRequired&&!result.sessionToken)throw new Error("Backendul mobil nu a returnat o sesiune securizată.");await setSessionToken(result.sessionToken??null);await restore()}catch(e){const message=normalizeApiError(e).message;setError(message);throw e}},[restore]);const logout=useCallback(async()=>{try{await unregisterCurrentPush();await api("/api/auth/logout",{method:"POST"})}finally{await setSessionToken(null);setUser(null)}},[]);useEffect(()=>{void Promise.resolve().then(restore)},[restore]);return <AuthContext.Provider value={useMemo(()=>({user,loading,error,login,logout,restore}),[user,loading,error,login,logout,restore])}>{children}</AuthContext.Provider>}
export function useAuth(){const value=useContext(AuthContext);if(!value)throw new Error("AuthProvider lipsește");return value}
