import {useCallback,useEffect,useRef,useState} from 'react';
import {Share,StyleSheet,Switch,Text,TextInput,View} from 'react-native';
import {router} from 'expo-router';
import {api,API_BASE_URL} from './api';
import {useAuth} from './auth';
import {AppScreen,EmptyState,InlineState,PremiumCard,PrimaryButton,SettingRow} from './mobileUi';
import {colors} from './theme';
import {chooseProofPhoto} from './permissions';
import {uploadFirmProof} from './photoUpload';
interface Resource{id:string;kind:string;name:string;role:string}
interface Data{resources:Resource[];members:{id:string;resource_id:string;name:string;email:string}[];properties:{id:string;name:string;role:string;budget_bani:number;budget_enforced:number}[];approvals:{id:string;property_id:string;date:string;price_bani:number;status:string;note:string}[];jobs:{id:string;street:string;city:string;status:string;scheduled_at:string;details:string;checklist:{item_key:string;done:number}[];photos:{id:string;proof_type:string}[];report:{note:string}|null}[]}
const checks=[['surfaces','Suprafețe'],['kitchen','Bucătărie'],['bathroom','Băi'],['floors','Pardoseli'],['waste','Deșeuri'],['inspection','Verificare finală']];
export function NativeCollaboration(){
 const {user,loading:authLoading}=useAuth();const [data,setData]=useState<Data>({resources:[],members:[],properties:[],approvals:[],jobs:[]}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState(''),[token,setToken]=useState(''),[selected,setSelected]=useState<Resource|null>(null),[email,setEmail]=useState(''),[date,setDate]=useState(''),[note,setNote]=useState('');
 const refresh=useCallback(async()=>{try{setData(await api<Data>('/api/collaboration'));setError(null)}catch(e){setError(e instanceof Error?e.message:'Date indisponibile')}finally{setLoading(false)}},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- initial authenticated remote fetch
 useEffect(()=>{if(user)void refresh()},[user,refresh]);
 const requestRef=useRef<{signature:string;key:unknown}|null>(null);
 async function act(body:Record<string,unknown>){if(busy)return;setBusy(true);setError(null);try{if(body.action==='approval.request'){const signature=JSON.stringify({...body,requestKey:undefined});if(requestRef.current?.signature!==signature)requestRef.current={signature,key:body.requestKey};body={...body,requestKey:requestRef.current.key}}const d=await api<{token?:string}>('/api/collaboration',{method:'POST',body:JSON.stringify(body)});if(body.action==='approval.request')requestRef.current=null;await refresh();setNotice('Salvat.');return d}catch(e){setError(e instanceof Error?e.message:'Nu s-a putut salva')}finally{setBusy(false)}}
 async function photo(id:string,status:string){setBusy(true);try{const asset=await chooseProofPhoto();if(asset){await uploadFirmProof(asset,id,status==='accepted'?'ARRIVAL':'COMPLETION');await refresh()}}catch(e){setError(e instanceof Error?e.message:'Fotografie netrimisă')}finally{setBusy(false)}}
 if(authLoading)return <AppScreen title="Colaborare"><InlineState loading error={null} onRetry={()=>void refresh()}/></AppScreen>;
 if(!user)return <AppScreen title="Colaborare"><EmptyState icon="people-outline" title="Autentificare necesară" body="Intră cu adresa de email din invitație."/></AppScreen>;
 const statuses:Record<string,string>={pending:'În aprobare',approved:'Aprobată',rejected:'Respinsă',fulfilled:'Rezervată'};
 return <AppScreen eyebrow="NITIDO WORKSPACE" title="Echipă și colaborare" onRefresh={()=>void refresh()} refreshing={loading}><InlineState loading={loading} error={error} onRetry={()=>void refresh()}/>{!!notice&&<Text accessibilityRole="alert" style={s.body}>{notice}</Text>}
 <PremiumCard><Text style={s.title}>Ai o invitație?</Text><Field label="Cod sau link invitație" value={token} onChange={setToken}/><PrimaryButton title="Acceptă invitația" loading={busy} onPress={()=>{let code=token.trim();try{code=new URL(code).searchParams.get('token')??code}catch{}void act({action:'invite.accept',token:code})}}/></PremiumCard>
 {data.resources.filter(r=>r.role==='owner').map(r=><SettingRow key={r.id} icon="people-outline" title={r.name} subtitle="Gestionează accesul" onPress={()=>setSelected(r)}/>)}
 {selected&&<PremiumCard><Text style={s.title}>Acces · {selected.name}</Text><Field label="Email coleg" value={email} onChange={setEmail}/><PrimaryButton title={selected.kind==='team'?'Invită angajat':'Invită manager de locație'} loading={busy} onPress={()=>void(async()=>{const d=await act({action:'invite.create',kind:selected.kind,resourceId:selected.id,email,role:selected.kind==='team'?'worker':'manager'});if(d?.token)try{await Share.share({message:`Invitație NITIDO: ${API_BASE_URL}/invitatie?token=${d.token}`})}catch{setError('Linkul nu a putut fi distribuit. Creează o invitație nouă.')}})()}/>{data.members.filter(m=>m.resource_id===selected.id).map(m=><View key={m.id} style={{gap:8}}><Text style={s.body}>{m.name} · {m.email}</Text><PrimaryButton secondary title="Revocă accesul" loading={busy} onPress={()=>void act({action:'member.revoke',id:m.id})}/></View>)}</PremiumCard>}
 {data.jobs.map(j=><PremiumCard key={j.id}><Text style={s.title}>{j.street} · {j.city}</Text><Text style={s.body}>{new Date(j.scheduled_at).toLocaleString('ro-RO')} · {j.status==='accepted'?'Programată':'În lucru'}</Text>{!!j.details&&<Text style={s.body}>{j.details}</Text>}{checks.map(([key,label])=><View key={key} style={s.row}><Text style={s.body}>{label}</Text><Switch accessibilityLabel={label} disabled={busy||!!j.report} value={!!j.checklist.find(c=>c.item_key===key)?.done} onValueChange={done=>void act({action:'checklist.set',jobId:j.id,key,done})}/></View>)}<Text style={s.body}>Fotografii: {j.photos.filter(p=>p.proof_type==='ARRIVAL').length} început · {j.photos.filter(p=>p.proof_type==='COMPLETION').length} final</Text>{j.report?<><Text style={s.body}>Raport trimis firmei. {j.report.note}</Text>{user.role==='firma'&&<PrimaryButton title="Verifică și finalizează" onPress={()=>router.push('/(firma)/active')}/>}</>:<><PrimaryButton secondary title={j.status==='accepted'?'Fotografie înainte':'Fotografie la final'} loading={busy} onPress={()=>void photo(j.id,j.status)}/>{j.status==='accepted'?<PrimaryButton title="Am ajuns · începe" loading={busy} onPress={()=>void act({action:'execution.arrived',jobId:j.id})}/>:<><Field label="Observații raport" value={note} onChange={setNote}/><PrimaryButton title="Trimite raportul firmei" loading={busy} onPress={()=>void act({action:'execution.submit',jobId:j.id,note})}/><Text style={s.body}>Firma verifică și finalizează. Raportul nu încasează plata.</Text></>}</>}</PremiumCard>)}
 {data.properties.map(p=><PremiumCard key={p.id}><Text style={s.title}>{p.name}</Text><Text style={s.body}>Buget lunar: {p.budget_bani/100} RON</Text>{p.role==='owner'&&<View style={s.row}><Text style={[s.body,{flex:1}]}>Blochează depășirea bugetului</Text><Switch accessibilityLabel="Aplică limita de buget" disabled={busy} value={!!p.budget_enforced} onValueChange={enabled=>void act({action:'budget.configure',propertyId:p.id,enabled})}/></View>}{p.role!=='viewer'&&<><Field label="Data lucrării (AAAA-LL-ZZ)" value={date} onChange={setDate}/><Field label="Detalii solicitare" value={note} onChange={setNote}/><PrimaryButton secondary title="Solicită aprobare" loading={busy} onPress={()=>void act({action:'approval.request',propertyId:p.id,date,note,requestKey:`mobile-${Date.now()}-${Math.random().toString(36).slice(2)}`})}/></>}{data.approvals.filter(a=>a.property_id===p.id).map(a=><View style={{gap:10}} key={a.id}><Text style={s.title}>{a.date} · {a.price_bani/100} RON</Text><Text style={s.body}>{statuses[a.status]} · {a.note}</Text>{p.role==='owner'&&a.status==='pending'&&<><PrimaryButton title="Aprobă" loading={busy} onPress={()=>void act({action:'approval.decide',id:a.id,approve:true})}/><PrimaryButton secondary title="Respinge" loading={busy} onPress={()=>void act({action:'approval.decide',id:a.id,approve:false})}/></>}{p.role==='owner'&&a.status==='approved'&&<PrimaryButton title="Rezervă lucrarea aprobată" onPress={()=>router.push({pathname:'/(client)/post',params:{propertyId:p.id,approvalId:a.id,approvalDate:a.date}})}/>}</View>)}</PremiumCard>)}
 {!loading&&!data.jobs.length&&!data.properties.length&&<EmptyState icon="people-outline" title="Spațiul tău de colaborare" body="Acceptă o invitație sau creează o echipă ori o proprietate. Lucrările și aprobările apar aici."/>}
 </AppScreen>
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <View style={{gap:8}}><Text style={s.body}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} maxLength={2000} autoCapitalize="none" style={s.input}/></View>}
const s=StyleSheet.create({title:{fontSize:20,fontWeight:'700',color:colors.ink},body:{fontSize:14,lineHeight:22,color:colors.muted},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},input:{borderWidth:1,borderColor:colors.border,borderRadius:12,padding:14,color:colors.ink,minHeight:48}});
