import {useCallback,useEffect,useState} from "react";
import {Pressable,StyleSheet,Text,TextInput,View} from "react-native";
import {Ionicons} from "@expo/vector-icons";
import {api,normalizeApiError} from "./api";
import {PremiumCard,PrimaryButton} from "./mobileUi";
import {colors} from "./theme";
const TASKS=[{key:"surfaces",label:"Suprafețe și mobilier"},{key:"kitchen",label:"Bucătărie"},{key:"bathroom",label:"Băi și obiecte sanitare"},{key:"floors",label:"Aspirare și pardoseli"},{key:"waste",label:"Coșuri și deșeuri"},{key:"inspection",label:"Verificare finală"}];
type Entry={job_id:string;item_key:string;done:number};
export function ExecutionChecklist({jobId,editable=false,jobStatus,hasArrival=false,hasCompletion=false}:{jobId:string;editable?:boolean;jobStatus?:string;hasArrival?:boolean;hasCompletion?:boolean}){
 const [entries,setEntries]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const [report,setReport]=useState<{note:string;submitted_at:string}|null>(null),[note,setNote]=useState("");
 const load=useCallback(async()=>{try{const d=await api<{checklist:Entry[]}>("/api/workspace");setEntries(d.checklist.filter(e=>e.job_id===jobId));if(editable){const c=await api<{jobs:{id:string;report:{note:string;submitted_at:string}|null}[]}>("/api/collaboration");setReport(c.jobs.find(j=>j.id===jobId)?.report??null)}setError(null)}catch(e){setError(normalizeApiError(e).message)}finally{setLoading(false)}},[jobId,editable]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- synchronize checklist from authenticated remote request
 useEffect(()=>{void load()},[load]);
 async function toggle(key:string,done:boolean){if(busy)return;setBusy(true);setError(null);try{await api("/api/workspace",{method:"POST",body:JSON.stringify({action:"checklist.set",jobId,key,done})});await load()}catch(e){setError(normalizeApiError(e).message)}finally{setBusy(false)}}
 async function submitReport(){if(busy)return;setBusy(true);setError(null);try{await api("/api/collaboration",{method:"POST",body:JSON.stringify({action:"execution.submit",jobId,note})});await load()}catch(e){setError(normalizeApiError(e).message)}finally{setBusy(false)}}
 const count=TASKS.filter(t=>entries.some(e=>e.item_key===t.key&&e.done===1)).length;
 return <PremiumCard><View style={s.head}><Text style={s.title}>Progresul lucrării</Text>{!loading&&!error&&<Text style={s.count}>{count} / {TASKS.length}</Text>}</View>{loading?<Text style={s.note}>Se încarcă verificările…</Text>:<><View accessibilityRole="progressbar" accessibilityValue={{min:0,max:TASKS.length,now:count}} style={s.track}><View style={[s.fill,{width:`${count/TASKS.length*100}%`}]}/></View>{TASKS.map(task=>{const done=entries.some(e=>e.item_key===task.key&&e.done===1);const content=<><Ionicons name={done?"checkbox":"square-outline"} size={24} color={done?colors.green:colors.muted}/><Text style={s.label}>{task.label}</Text></>;return editable?<Pressable key={task.key} accessibilityRole="checkbox" accessibilityLabel={task.label} accessibilityState={{checked:done,disabled:busy||Boolean(error)||Boolean(report)}} disabled={busy||Boolean(error)||Boolean(report)} onPress={()=>void toggle(task.key,!done)} style={s.row}>{content}</Pressable>:<View key={task.key} accessibilityLabel={`${task.label}: ${done?"Bifat":"În așteptare"}`} style={s.row}>{content}</View>})}<Text style={s.note}>Bifările echipei sunt separate de raportul foto și confirmarea finalizării.</Text></>}{editable&&jobStatus&&<>{report?<Text style={s.note}>Raport trimis: {new Date(report.submitted_at).toLocaleString("ro-RO")}</Text>:<><Text style={s.label}>Observații pentru raport</Text><TextInput accessibilityLabel="Observații pentru raport" value={note} onChangeText={setNote} multiline maxLength={2000} style={{minHeight:80,borderWidth:1,borderColor:colors.border,padding:12,borderRadius:8,color:colors.ink}}/><PrimaryButton title="Trimite raportul" icon="send-outline" loading={busy} disabled={loading||Boolean(error)||jobStatus!=="arrived"||count!==TASKS.length||!hasArrival||!hasCompletion} onPress={()=>void submitReport()}/><Text style={s.note}>Sunt necesare toate verificările și fotografiile de sosire/final. Raportul nu încasează plata.</Text></>}</>}{error&&<><Text accessibilityRole="alert" style={s.error}>{error}</Text><PrimaryButton secondary title="Reîncarcă verificările" onPress={()=>void load()}/></>}</PremiumCard>;
}
export function ExecutionSteps({arrived,completed}:{arrived:boolean;completed:boolean}){return <View style={s.steps}>{["Sosire","Sarcini","Raport"].map((label,index)=><View key={label} style={s.step}><View style={[s.circle,(index===0&&arrived||completed)&&s.active]}><Text style={s.stepNumber}>{index+1}</Text></View><Text style={s.stepLabel}>{label}</Text><Text style={s.note}>{completed?"Finalizat":index===0&&arrived?"Confirmată":index===1&&arrived?"În lucru":"În așteptare"}</Text></View>)}</View>}
const s=StyleSheet.create({head:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",gap:10},title:{fontSize:17,fontWeight:"800",color:colors.ink},count:{fontSize:13,color:colors.green},track:{height:8,backgroundColor:colors.border,borderRadius:5,overflow:"hidden",marginVertical:10},fill:{height:8,backgroundColor:colors.green},row:{minHeight:54,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:colors.border},label:{flex:1,fontSize:14,color:colors.ink},note:{fontSize:11,lineHeight:17,color:colors.muted},error:{fontSize:13,color:colors.danger},steps:{flexDirection:"row",justifyContent:"space-between",paddingVertical:18},step:{flex:1,alignItems:"center",gap:5},circle:{height:32,width:32,borderRadius:16,borderWidth:2,borderColor:colors.border,alignItems:"center",justifyContent:"center"},active:{backgroundColor:colors.greenSoft,borderColor:colors.green},stepNumber:{color:colors.greenDark,fontWeight:"700"},stepLabel:{fontSize:13,fontWeight:"700",color:colors.ink}});
