import type {ComponentProps,ReactNode} from "react";
import {Ionicons} from "@expo/vector-icons";
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View,type ColorValue,type ViewStyle} from "react-native";
import {colors} from "./theme";

export type IconName=ComponentProps<typeof Ionicons>["name"];
export function AppScreen({children,eyebrow,title,subtitle,refreshing,onRefresh}:{children:ReactNode;eyebrow?:string;title:string;subtitle?:string;refreshing?:boolean;onRefresh?:()=>void}){return <ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.screen} refreshControl={onRefresh?undefined:undefined}><View style={styles.brandRow}><Text style={styles.brand}>NITIDO<Text style={styles.brandDot}>.RO</Text></Text><View style={styles.brandMark}><Ionicons name="sparkles" size={16} color={colors.green}/></View></View>{eyebrow?<Text style={styles.eyebrow}>{eyebrow}</Text>:null}<Text accessibilityRole="header" style={styles.title}>{title}</Text>{subtitle?<Text style={styles.subtitle}>{subtitle}</Text>:null}{refreshing?<ActivityIndicator color={colors.green}/>:null}{children}</ScrollView>}
export function PrimaryButton({title,onPress,icon="arrow-forward",disabled,loading,secondary=false}:{title:string;onPress:()=>void;icon?:IconName;disabled?:boolean;loading?:boolean;secondary?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled||loading} onPress={onPress} style={({pressed})=>[styles.button,secondary&&styles.buttonSecondary,(disabled||loading)&&styles.disabled,pressed&&styles.pressed]}>{loading?<ActivityIndicator color={secondary?colors.green:colors.white}/>:<><Text style={[styles.buttonLabel,secondary&&styles.buttonLabelSecondary]}>{title}</Text><Ionicons name={icon} size={19} color={secondary?colors.green:colors.white}/></>}</Pressable>}
export function PremiumCard({children,style}:{children:ReactNode;style?:ViewStyle}){return <View style={[styles.card,style]}>{children}</View>}
export function SectionTitle({title,action,onPress}:{title:string;action?:string;onPress?:()=>void}){return <View style={styles.sectionHead}><Text style={styles.sectionTitle}>{title}</Text>{action?<Pressable accessibilityRole="button" onPress={onPress}><Text style={styles.sectionAction}>{action}</Text></Pressable>:null}</View>}
export function Pill({label,tone="neutral"}:{label:string;tone?:"neutral"|"green"|"amber"|"red"}){return <View style={[styles.pill,tone==="green"&&styles.pillGreen,tone==="amber"&&styles.pillAmber,tone==="red"&&styles.pillRed]}><Text style={[styles.pillText,tone==="green"&&styles.pillTextGreen,tone==="amber"&&styles.pillTextAmber,tone==="red"&&styles.pillTextRed]}>{label}</Text></View>}
export function EmptyState({icon,title,body,cta,onPress}:{icon:IconName;title:string;body:string;cta?:string;onPress?:()=>void}){return <PremiumCard style={styles.empty}><View style={styles.emptyIcon}><Ionicons name={icon} size={25} color={colors.green}/></View><Text style={styles.cardTitle}>{title}</Text><Text style={styles.body}>{body}</Text>{cta&&onPress?<PrimaryButton secondary title={cta} onPress={onPress}/>:null}</PremiumCard>}
export function InlineState({loading,error,onRetry}:{loading:boolean;error:string|null;onRetry:()=>void}){if(loading)return <PremiumCard><ActivityIndicator color={colors.green}/><Text style={styles.centerBody}>Se încarcă informațiile…</Text></PremiumCard>;if(error)return <EmptyState icon="cloud-offline-outline" title="Conexiune indisponibilă" body={error} cta="Încearcă din nou" onPress={onRetry}/>;return null}
export function Metric({value,label,icon}:{value:string;label:string;icon:IconName}){return <PremiumCard style={styles.metric}><Ionicons name={icon} size={21} color={colors.green}/><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></PremiumCard>}
export function SettingRow({icon,title,subtitle,onPress}:{icon:IconName;title:string;subtitle?:string;onPress?:()=>void}){const content=<><View style={styles.settingIcon}><Ionicons name={icon} size={20} color={colors.greenDark}/></View><View style={{flex:1}}><Text style={styles.settingTitle}>{title}</Text>{subtitle?<Text style={styles.settingSubtitle}>{subtitle}</Text>:null}</View>{onPress?<Ionicons name="chevron-forward" size={18} color="#9AA39D"/>:null}</>;return onPress?<Pressable accessibilityRole="button" accessibilityLabel={title} onPress={onPress} style={styles.setting}>{content}</Pressable>:<View accessibilityLabel={title} style={styles.setting}>{content}</View>}
export function TabIcon({name,color}:{name:IconName;color:ColorValue}){return <Ionicons name={name} size={23} color={color}/>}
const styles=StyleSheet.create({screen:{flexGrow:1,backgroundColor:colors.ivory,paddingHorizontal:20,paddingTop:18,paddingBottom:120,gap:14},brandRow:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:16},brand:{fontSize:19,fontWeight:"900",letterSpacing:-.8,color:colors.ink},brandDot:{color:colors.green},brandMark:{width:34,height:34,borderRadius:12,backgroundColor:colors.greenSoft,alignItems:"center",justifyContent:"center"},eyebrow:{fontSize:11,fontWeight:"800",letterSpacing:1.5,color:colors.greenDark,textTransform:"uppercase"},title:{fontSize:34,lineHeight:39,fontWeight:"800",letterSpacing:-1.2,color:colors.ink},subtitle:{fontSize:16,lineHeight:24,color:colors.muted,marginBottom:4},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:22,padding:20,gap:10,shadowColor:"#101711",shadowOpacity:.045,shadowRadius:16,shadowOffset:{width:0,height:7}},button:{minHeight:54,borderRadius:16,paddingHorizontal:20,backgroundColor:colors.green,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:10,marginTop:6},buttonSecondary:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border},buttonLabel:{fontSize:16,fontWeight:"800",color:colors.white},buttonLabelSecondary:{color:colors.greenDark},disabled:{opacity:.45},pressed:{opacity:.82},sectionHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:12},sectionTitle:{fontSize:20,fontWeight:"800",letterSpacing:-.4,color:colors.ink},sectionAction:{fontSize:14,fontWeight:"700",color:colors.greenDark},pill:{alignSelf:"flex-start",borderRadius:99,paddingHorizontal:10,paddingVertical:6,backgroundColor:"#ECEDE9"},pillGreen:{backgroundColor:colors.greenSoft},pillAmber:{backgroundColor:"#F6ECD4"},pillRed:{backgroundColor:"#F8E3E1"},pillText:{fontSize:11,fontWeight:"800",color:colors.muted},pillTextGreen:{color:colors.greenDark},pillTextAmber:{color:"#8A6217"},pillTextRed:{color:colors.danger},empty:{alignItems:"center",paddingVertical:28},emptyIcon:{width:52,height:52,borderRadius:18,backgroundColor:colors.greenSoft,alignItems:"center",justifyContent:"center",marginBottom:4},cardTitle:{fontSize:19,fontWeight:"800",color:colors.ink,textAlign:"center"},body:{fontSize:14,lineHeight:21,color:colors.muted,textAlign:"center"},centerBody:{fontSize:14,color:colors.muted,textAlign:"center"},metric:{flex:1,minWidth:100,padding:16},metricValue:{fontSize:25,fontWeight:"800",letterSpacing:-.8,color:colors.ink},metricLabel:{fontSize:12,lineHeight:17,color:colors.muted},setting:{minHeight:66,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:colors.border},settingIcon:{width:38,height:38,borderRadius:13,backgroundColor:colors.greenSoft,alignItems:"center",justifyContent:"center"},settingTitle:{fontSize:15,fontWeight:"700",color:colors.ink},settingSubtitle:{fontSize:12,color:colors.muted,marginTop:3}});
