import {useRef,useState} from 'react';
import {Modal,ScrollView,Text,TextInput,View,Pressable} from 'react-native';
import {PrimaryButton} from './mobileUi';
import {colors} from './theme';
import {propertyDraft,propertyPayload,type EditableProperty} from './propertyForm';
export function PropertyEditor({property,onClose,onSave}:{property:EditableProperty;onClose:()=>void;onSave:(payload:Record<string,unknown>)=>Promise<boolean>}){
 const [draft,setDraft]=useState(()=>propertyDraft(property)),[error,setError]=useState(''),[busy,setBusy]=useState(false);const locked=useRef(false);
 async function save(){if(locked.current)return;locked.current=true;setBusy(true);setError('');try{if(await onSave(propertyPayload(draft)))onClose();else setError('Salvarea nu a reușit. Datele completate au fost păstrate.')}catch(e){setError(e instanceof Error?e.message:'Date invalide.')}finally{locked.current=false;setBusy(false)}}
 return <Modal visible animationType="slide" presentationStyle="pageSheet" onRequestClose={()=>{if(!busy)onClose()}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:24,paddingTop:50,gap:16,backgroundColor:colors.ivory}}><Text style={{fontSize:24,fontWeight:'700',color:colors.ink}}>{property.id?'Editează proprietatea':'Proprietate nouă'}</Text>{([['name','Denumire',100],['city','Oraș',100],['street','Stradă și număr',250],['sqm','Suprafață m²',4],['cost_center','Centru de cost',100],['budget','Buget lunar RON',12],['notes','Preferințe de curățenie',2000]] as const).map(([key,label,max])=><View key={key} style={{gap:8}}><Text style={{color:colors.ink,fontWeight:'600'}}>{label}</Text><TextInput accessibilityLabel={label} editable={!busy} value={draft[key]} maxLength={max} multiline={key==='notes'} keyboardType={key==='budget'?'decimal-pad':key==='sqm'?'number-pad':'default'} onChangeText={v=>setDraft({...draft,[key]:v})} style={{borderWidth:1,borderColor:colors.border,borderRadius:12,padding:14,minHeight:48,backgroundColor:colors.white,color:colors.ink}}/></View>)}{([['space_type','Tip spațiu',[['apartament','Apartament'],['casa','Casă'],['birou','Birou'],['altul','Alt spațiu']]],['kind','Utilizare',[['home','Locuință'],['business','Business'],['host','Gazdă']]]] as const).map(([key,label,options])=><View key={key} style={{gap:8}}><Text style={{fontWeight:'600',color:colors.ink}}>{label}</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{options.map(([value,text])=><Pressable accessibilityRole="button" accessibilityState={{selected:draft[key]===value,disabled:busy}} disabled={busy} key={value} onPress={()=>setDraft({...draft,[key]:value})} style={{padding:12,minHeight:44,borderRadius:12,backgroundColor:draft[key]===value?colors.greenSoft:colors.white,borderWidth:1,borderColor:colors.border}}><Text style={{color:colors.ink}}>{text}</Text></Pressable>)}</View></View>)}{error?<Text accessibilityRole="alert" style={{color:colors.danger}}>{error}</Text>:null}<PrimaryButton title="Salvează proprietatea" loading={busy} onPress={()=>void save()}/><PrimaryButton secondary title="Renunță la modificări" disabled={busy} onPress={onClose}/></ScrollView></Modal>
}
