import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { api, normalizeApiError } from "./api";
import { AppScreen, PremiumCard, PrimaryButton } from "./mobileUi";
import { colors } from "./theme";
type Message={role:"user"|"assistant";content:string};
const suggestions=["Cum funcționează plata?","Când vede firma adresa exactă?","Pot finaliza fără fotografia finală?","Cum contactez un om?"];
export function SupportChat(){const [messages,setMessages]=useState<Message[]>([]);const [question,setQuestion]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);async function send(value=question){const content=value.trim();if(!content||busy)return;const next=[...messages,{role:"user" as const,content}];setMessages(next);setQuestion("");setBusy(true);setError(null);try{const result=await api<{answer:string}>("/api/support/ai",{method:"POST",body:JSON.stringify({messages:next.slice(-8)})});setMessages([...next,{role:"assistant",content:result.answer}])}catch(cause){setError(normalizeApiError(cause).message)}finally{setBusy(false)}}return <AppScreen eyebrow="SUPORT CONSULTATIV" title="Asistent AI NITIDO" subtitle="Întreabă liber despre cont, lucrări, dovezi, plăți sau reguli NITIDO."><View style={s.suggestions}>{suggestions.map(item=><Pressable accessibilityRole="button" key={item} onPress={()=>void send(item)} style={s.chip}><Text style={s.chipText}>{item}</Text></Pressable>)}</View>{messages.length?messages.map((message,index)=><PremiumCard key={`${message.role}-${index}`} style={message.role==="user"?s.user:s.assistant}><Text style={s.role}>{message.role==="user"?"TU":"NITIDO AI"}</Text><Text selectable style={s.answer}>{message.content}</Text></PremiumCard>):<PremiumCard><Text style={s.answer}>Poți întreba și orice altceva despre NITIDO. Răspunsurile folosesc baza de cunoștințe și contextul permis rolului tău.</Text></PremiumCard>}<TextInput accessibilityLabel="Întrebare pentru Asistentul AI" multiline maxLength={2000} value={question} onChangeText={setQuestion} placeholder="Scrie întrebarea ta…" placeholderTextColor={colors.muted} style={s.input}/>{error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}<PrimaryButton loading={busy} disabled={!question.trim()||busy} title="Trimite" icon="send-outline" onPress={()=>void send()}/><Text style={s.human}>Pentru intervenție umană: 0341.402.403 · contact@nitido.ro</Text></AppScreen>}
const s=StyleSheet.create({suggestions:{flexDirection:"row",flexWrap:"wrap",gap:8},chip:{borderWidth:1,borderColor:colors.border,borderRadius:99,paddingHorizontal:12,paddingVertical:9,backgroundColor:colors.white},chipText:{fontSize:12,fontWeight:"700",color:colors.greenDark},user:{backgroundColor:colors.greenSoft},assistant:{backgroundColor:colors.white},role:{fontSize:10,fontWeight:"900",letterSpacing:1.2,color:colors.greenDark},answer:{fontSize:14,lineHeight:22,color:colors.ink},input:{minHeight:110,textAlignVertical:"top",borderWidth:1,borderColor:colors.border,borderRadius:18,backgroundColor:colors.white,padding:15,fontSize:15,lineHeight:22,color:colors.ink},error:{fontSize:13,lineHeight:19,color:colors.danger},human:{fontSize:11,lineHeight:17,color:colors.muted,textAlign:"center"}});
