import {PropertyEditor} from "./PropertyEditor";
import type {EditableProperty} from "./propertyForm";
import {useCallback,useEffect,useRef,useState} from "react";
import {Pressable,StyleSheet,Switch,Text,TextInput,View} from "react-native";
import {router} from "expo-router";
import {api} from "./api";
import {useJobs} from "./useJobs";
import {AppScreen,EmptyState,InlineState,PremiumCard,PrimaryButton,SectionTitle,SettingRow} from "./mobileUi";
import {colors} from "./theme";
interface Property{notes?:string;id:string;name:string;city:string;street:string;sqm:number;space_type:string;kind:string;cost_center:string;budget_bani:number;month_total:number}
interface Data{properties:Property[];teams:{id:string;name:string}[];assignments:{job_id:string;team_id:string}[];checklist:{job_id:string;item_key:string;done:number}[];events:{id:string;property_name:string;ends_at:string;status:string}[]}
const blank:Data={properties:[],teams:[],assignments:[],checklist:[],events:[]};
const checks=[["surfaces","Suprafețe și mobilier"],["kitchen","Bucătărie"],["bathroom","Băi și obiecte sanitare"],["floors","Aspirare și pardoseli"],["waste","Coșuri și deșeuri"],["inspection","Verificare finală"]];
export function NativeWorkspace({mode}:{mode:"properties"|"business"|"host"|"teams"|"execution"}){
 const [data,setData]=useState<Data>(blank),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[name,setName]=useState(""),[editing,setEditing]=useState<EditableProperty|null>(null);
 const {jobs}=useJobs();
 const refresh=useCallback(async()=>{try{setData(await api<Data>("/api/workspace"));setError(null)}catch(e){setError(e instanceof Error?e.message:"Conexiune indisponibilă")}finally{setLoading(false)}},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- initial authenticated remote fetch
 useEffect(()=>{void refresh()},[refresh]);
 async function save(payload:Record<string,unknown>){setBusy(true);setError(null);try{await api("/api/workspace",{method:"POST",body:JSON.stringify(payload)});await refresh();setNotice("Modificările au fost salvate.");return true}catch(e){setError(e instanceof Error?e.message:"Nu s-a putut salva");return false}finally{setBusy(false)}}
 const titles={properties:"Proprietățile tale",business:"NITIDO Business",host:"Pregătit de oaspeți",teams:"Calendar și echipe",execution:"Verificările lucrării"};
 const properties=data.properties.filter(p=>mode==="business"?p.kind==="business":mode==="host"?p.kind==="host":true);
 const active=jobs.filter(j=>["accepted","arrived"].includes(j.status));
 return <AppScreen eyebrow="NITIDO WORKSPACE" title={titles[mode]} onRefresh={()=>void refresh()} refreshing={loading}>
 <InlineState loading={loading} error={error} onRetry={()=>void refresh()}/>{notice?<Text accessibilityRole="alert" style={s.notice}>{notice}</Text>:null}
 {["properties","business","host"].includes(mode)&&<><PrimaryButton title="Adaugă proprietate" icon="add" onPress={()=>setEditing({name:"",city:"",street:"",sqm:75,space_type:mode==="business"?"birou":"apartament",kind:mode==="host"?"host":mode==="business"?"business":"home",cost_center:"",budget_bani:0,notes:""})}/>{editing&&<PropertyEditor property={editing} onClose={()=>setEditing(null)} onSave={save}/>}{!loading&&!properties.length?<EmptyState icon="home-outline" title="Nicio proprietate încă" body="Adaugă adresa și suprafața pentru a organiza rezervările."/>:properties.map(p=><PremiumCard key={p.id}><Text style={s.heading}>{p.name}</Text><Text style={s.body}>{p.city} · {p.sqm} m²</Text><Text style={s.body}>{p.street}</Text>{p.kind==="business"?<><Text style={s.body}>Centru de cost: {p.cost_center||"Nespecificat"}</Text><Text style={s.heading}>{p.month_total} RON / {p.budget_bani/100} RON</Text><Text style={s.body}>Lucrări finalizate luna aceasta / buget</Text></>:null}<PrimaryButton secondary title="Editează proprietatea" onPress={()=>setEditing(p)}/><PrimaryButton secondary title="Rezervă aici" onPress={()=>router.push({pathname:"/(client)/post",params:{propertyId:p.id}})}/></PremiumCard>)}</>}
 {mode==="host"&&<><SectionTitle title="Calendar importat"/>{data.events.length?data.events.map(e=><PremiumCard key={e.id}><Text style={s.heading}>{e.property_name}</Text><Text style={s.body}>Eliberare: {new Date(e.ends_at).toLocaleDateString("ro-RO")}</Text><Text style={s.body}>{e.status==="cancelled"?"Anulat":"Perioadă ocupată"}</Text></PremiumCard>):<EmptyState icon="calendar-outline" title="Niciun calendar" body="Importă fișierul .ics în contul web. Evenimentele vor apărea și aici."/>}</>}
 {mode==="teams"&&<><PremiumCard><Field label="Nume echipă" value={name} onChangeText={setName}/><PrimaryButton title="Adaugă echipa" loading={busy} onPress={()=>void (async()=>{if(await save({action:"team.create",name}))setName("")})()}/></PremiumCard><SectionTitle title="Programul echipelor"/>{!active.length&&<EmptyState icon="calendar-outline" title="Nicio lucrare activă" body="Programările confirmate vor apărea aici."/>}{active.sort((a,b)=>(a.scheduled_at??"").localeCompare(b.scheduled_at??"")).map(j=><PremiumCard key={j.id}><Text style={s.heading}>{j.city} · {j.sqm} m²</Text><Text style={s.body}>{j.scheduled_at?new Date(j.scheduled_at).toLocaleString("ro-RO"):"Fără dată"}</Text><Text style={s.body}>{j.street}</Text><Text style={s.label}>Alocă echipa</Text><View style={s.chips}>{data.teams.map(t=><Pressable accessibilityRole="button" accessibilityState={{selected:data.assignments.some(a=>a.job_id===j.id&&a.team_id===t.id),disabled:busy}} disabled={busy} key={t.id} style={[s.chip,data.assignments.some(a=>a.job_id===j.id&&a.team_id===t.id)&&s.selected]} onPress={()=>void save({action:"team.assign",jobId:j.id,teamId:t.id})}><Text style={s.chipText}>{t.name}</Text></Pressable>)}</View></PremiumCard>)}</>}
 {mode==="execution"&&<>{!active.length&&<EmptyState icon="checkmark-done-outline" title="Nicio lucrare de verificat" body="Verificările sunt disponibile pentru lucrările firmei tale."/>}{active.map(j=><PremiumCard key={j.id}><Text style={s.heading}>{j.street} · {j.city}</Text>{checks.map(([key,label])=><View style={s.check} key={key}><Text style={[s.body,{flex:1}]}>{label}</Text><Switch accessibilityLabel={label} disabled={busy} trackColor={{true:colors.green}} value={Boolean(data.checklist.find(c=>c.job_id===j.id&&c.item_key===key)?.done)} onValueChange={done=>void save({action:"checklist.set",jobId:j.id,key,done})}/></View>)}<PrimaryButton title="Fotografii și finalizare" secondary onPress={()=>router.push("/(firma)/active")}/></PremiumCard>)}</>}
 </AppScreen>
}
export function NativeJobMessages(){
 const {jobs}=useJobs();const [jobId,setJobId]=useState(""),[messages,setMessages]=useState<{id:string;sender_name:string;body:string;created_at:string}[]>([]),[body,setBody]=useState(""),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);const request=useRef<{body:string;jobId:string;id:string}|null>(null);
 const refresh=useCallback(async()=>{if(!jobId)return;try{const d=await api<{messages:typeof messages}>(`/api/workspace/messages?jobId=${encodeURIComponent(jobId)}`);setMessages(d.messages);setError(null)}catch(e){setError(e instanceof Error?e.message:"Mesaje indisponibile")}},[jobId]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- initial authenticated remote fetch
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),10000);return()=>clearInterval(timer)},[refresh]);
 const allocated=jobs.filter(j=>j.accepted_firm_id);
 async function send(){if(!body.trim()||busy)return;setBusy(true);if(request.current?.body!==body||request.current?.jobId!==jobId)request.current={body,jobId,id:`msg-${Date.now()}-${Math.random().toString(36).slice(2)}`};try{await api("/api/workspace/messages",{method:"POST",body:JSON.stringify({jobId,body,requestId:request.current.id})});request.current=null;setBody("");await refresh()}catch(e){setError(e instanceof Error?e.message:"Mesaj netrimis")}finally{setBusy(false)}}
 return <AppScreen eyebrow="CONVERSAȚII" title="Mesajele lucrărilor"><InlineState loading={false} error={error} onRetry={()=>void refresh()}/>{!allocated.length?<EmptyState icon="chatbubbles-outline" title="Nicio conversație încă" body="Conversațiile se deschid după alocarea firmei."/>:allocated.map(j=><SettingRow key={j.id} icon="chatbubble-outline" title={`${j.city} · ${j.sqm} m²`} subtitle={j.street} onPress={()=>{setJobId(j.id);setMessages([]);setBody("")}}/>)}{jobId&&<><SectionTitle title="Conversația selectată"/>{messages.map(m=><PremiumCard key={m.id}><Text style={s.label}>{m.sender_name}</Text><Text style={s.body}>{m.body}</Text><Text style={s.time}>{new Date(m.created_at).toLocaleString("ro-RO")}</Text></PremiumCard>)}<Field label="Mesaj" value={body} onChangeText={setBody} multiline/><PrimaryButton title="Trimite mesajul" icon="send-outline" disabled={!body.trim()} loading={busy} onPress={()=>void send()}/></>}</AppScreen>
}
function Field({label,value,onChangeText,numeric,multiline}:{label:string;value:string;onChangeText:(v:string)=>void;numeric?:boolean;multiline?:boolean}){return <View style={{gap:8}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} keyboardType={numeric?"number-pad":"default"} multiline={multiline} maxLength={multiline?2000:250} style={[s.input,multiline&&{minHeight:100,textAlignVertical:"top"}]}/></View>}
const s=StyleSheet.create({input:{borderWidth:1,borderColor:colors.border,borderRadius:12,padding:14,minHeight:48,color:colors.ink,backgroundColor:colors.white},label:{fontSize:13,fontWeight:"600",color:colors.ink},heading:{fontSize:20,fontWeight:"700",color:colors.ink},body:{fontSize:14,lineHeight:22,color:colors.muted},notice:{fontSize:14,color:colors.greenDark,padding:14,backgroundColor:colors.greenSoft,borderRadius:12},chips:{flexDirection:"row",gap:8,flexWrap:"wrap"},chip:{borderWidth:1,borderColor:colors.border,borderRadius:12,padding:12,minHeight:44},selected:{backgroundColor:colors.greenSoft,borderColor:colors.green},chipText:{color:colors.greenDark,fontSize:13},check:{flexDirection:"row",alignItems:"center",gap:12,minHeight:52},time:{fontSize:11,color:colors.muted}});
