import { useCallback, useEffect, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { api, normalizeApiError } from "@/api";
import { useAuth } from "@/auth";
import { AppScreen, EmptyState, InlineState, Pill, PremiumCard, PrimaryButton } from "@/mobileUi";
import { colors } from "@/theme";
type Review={id:string;rating:number;reviewText:string|null;reviewer:string;badge:string};type FirmMetric={average_rating:number|null;review_count:number;completed_jobs:number;verified:number};
export default function FirmReviews(){const {user}=useAuth();const firmId=user?.firm?.id;const [reviews,setReviews]=useState<Review[]>([]);const [metric,setMetric]=useState<FirmMetric|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [reported,setReported]=useState<string|null>(null);const load=useCallback(async()=>{if(!firmId)return;setLoading(true);setError(null);try{const data=await api<{reviews:Review[];firms:FirmMetric[]}>(`/api/trust?firmId=${encodeURIComponent(firmId)}`);setReviews(data.reviews);setMetric(data.firms[0]??null)}catch(cause){setError(normalizeApiError(cause).message)}finally{setLoading(false)}},[firmId]);async function report(id:string){setError(null);try{await api(`/api/reviews/${id}/report`,{method:"POST",body:JSON.stringify({reason:"alt_motiv",details:"Solicit analizarea recenziei din aplicația Firmă."})});setReported(id)}catch(cause){setError(normalizeApiError(cause).message)}}useEffect(()=>{void Promise.resolve().then(load)},[load]);return <AppScreen eyebrow="REPUTAȚIE REALĂ" title="Recenzii verificate" subtitle="Firma nu poate modifica, șterge sau marca singură o recenzie ca verificată."><InlineState loading={loading} error={error} onRetry={()=>void load()}/>{!loading&&!error&&metric?<PremiumCard><View style={s.row}><Text style={s.rating}>{metric.average_rating===null?"—":metric.average_rating.toFixed(1)} / 5</Text><Pill label={metric.verified?"FIRMĂ VERIFICATĂ":"NEVERIFICATĂ"} tone={metric.verified?"green":"amber"}/></View><Text style={s.body}>{metric.review_count} recenzii verificate · {metric.completed_jobs} lucrări finalizate</Text></PremiumCard>:null}{!loading&&!error&&(reviews.length?reviews.map(review=><PremiumCard key={review.id}><View style={s.row}><Text style={s.stars}>{"★".repeat(review.rating)}</Text><Pill label={review.badge} tone="green"/></View>{review.reviewText?<Text style={s.body}>{review.reviewText}</Text>:null}<Text style={s.reviewer}>{review.reviewer}</Text><PrimaryButton secondary disabled={reported===review.id} title={reported===review.id?"Trimisă spre analiză":"Raportează pentru analiză"} icon="flag-outline" onPress={()=>void report(review.id)}/></PremiumCard>):<EmptyState icon="star-outline" title="Încă nu există suficiente evaluări" body="Recenziile eligibile vor apărea după lucrări reale finalizate prin NITIDO."/> )}</AppScreen>}
const s=StyleSheet.create({row:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10},rating:{fontSize:27,fontWeight:"800",color:colors.ink},stars:{fontSize:20,color:"#B98017"},body:{fontSize:13,lineHeight:20,color:colors.muted},reviewer:{fontSize:11,color:colors.greenDark}});
