import Image from "next/image";
import Link from "next/link";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";
const Check = () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75"><path d="m5 12 4 4L19 6"/></svg>;
const Arrow = () => <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>;

export default function Home() {
  const verified = (db.prepare("SELECT COUNT(*) n FROM firms WHERE verified=1").get() as {n:number}).n;
  return <main className="bg-[#f4f3ee] text-[#101711]">
    <header className="sticky top-0 z-50 h-[66px] bg-[#f4f3ee]/95 backdrop-blur border-b border-[#e3e2da]"><div className="v2-container h-full flex items-center justify-between"><Link href="/" className="text-xl font-bold tracking-[-.04em]">NITIDO<span className="text-[#1b8a4c]">.RO</span></Link><nav className="v2-hide-mobile flex items-center gap-7 text-sm font-medium text-[#3e4842]"><a href="#cum">Cum funcționează</a><a href="#clienti">Pentru clienți</a><a href="#firme">Pentru firme</a><a href="#preturi">Prețuri</a><a href="#score">Despre noi</a><a href="#contact">Contact</a></nav><div className="flex items-center gap-2"><Link href="/login" className="v2-btn v2-btn-secondary v2-hide-mobile">Autentificare</Link><Link href="/signup" className="v2-btn v2-btn-primary">Înregistrează-te</Link></div></div></header>

    <section className="v2-container py-16 pb-14 grid grid-cols-[1.02fr_1fr] gap-12 items-center v2-hero-grid"><div><div className="inline-flex rounded-full bg-[#e4f0e8] text-[#14663a] px-4 py-2 text-xs font-bold mb-6">O singură regulă: primul care acceptă, ia lucrarea.</div><h1 className="text-[60px] max-md:text-[43px] leading-[1.04] tracking-[-.035em] font-bold">Postezi lucrarea.<br/>Prima firmă care apasă <span className="text-[#1b8a4c]">Accept</span> o ia.</h1><p className="mt-6 text-[17px] leading-7 text-[#3e4842] max-w-xl">NITIDO.RO conectează clienții care au nevoie de servicii de curățenie cu firme de încredere, într-un mod rapid, corect și transparent.</p><div className="flex flex-wrap gap-3 mt-8"><Link href="/signup?role=client" className="v2-btn v2-btn-primary">Postează o lucrare <Arrow/></Link><Link href="/signup?role=firma" className="v2-btn v2-btn-secondary">Sunt firmă de curățenie</Link></div><div className="flex flex-wrap gap-x-6 gap-y-2 mt-8 text-sm text-[#5c6660]">{["Fără comisioane ascunse","Notificări în timp real","Suport dedicat"].map(x=><span key={x} className="flex gap-2 items-center text-[#14663a]"><Check/><i className="not-italic text-[#5c6660]">{x}</i></span>)}</div></div>
      <div className="relative min-h-[590px] max-md:min-h-[540px]"><Image src="/design-v2/hero-cleaning.png" alt="Profesionist NITIDO într-un apartament curat" fill priority className="object-cover rounded-[20px]"/><div className="absolute left-[-26px] top-10 w-[270px] bg-white rounded-2xl p-5 v2-shadow max-sm:left-3"><div className="flex justify-between"><span className="text-xs font-bold text-[#1b8a4c]">LUCRARE NOUĂ</span><span className="text-xs text-[#94620a] bg-[#fbf1dc] rounded-full px-2 py-1">11:24</span></div><h3 className="font-bold mt-3">Curățenie apartament</h3><p className="text-sm text-[#5c6660] mt-1">Sector 1 · 120 m² · astăzi</p><div className="text-2xl font-bold mt-4">450–600 lei</div><button className="v2-btn v2-btn-primary w-full mt-4">Accept lucrarea</button></div><div className="absolute right-[-18px] bottom-[-20px] w-[300px] bg-[#101711] text-white rounded-2xl p-5 shadow-2xl max-sm:right-3"><div className="text-xs text-[#8fd8ae] font-bold">ESTIMATOR LIVE</div><div className="flex justify-between items-end mt-3"><span className="text-sm text-[#a8b2ac]">Apartament · 120 m²</span><b className="text-3xl">520 lei</b></div><div className="h-1.5 bg-[#2a332c] rounded-full mt-5"><div className="h-full w-[58%] bg-[#39c97c] rounded-full"/></div><div className="flex justify-between text-[11px] text-[#8b958f] mt-2"><span>10 m²</span><span>1000 m²</span></div></div></div>
    </section>

    <section id="cum" className="bg-white"><div className="v2-container v2-section"><div className="v2-eyebrow">Cum funcționează</div><h2 className="v2-h2 mt-3">Patru pași. Fără telefoane inutile.</h2><div className="grid grid-cols-4 gap-4 mt-9 v2-mobile-two">{[["01","Postezi lucrarea","Descrii spațiul, adaugi fotografii și vezi estimarea."],["02","Firmele sunt notificate","Push simultan către toate firmele eligibile din zonă."],["03","Prima firmă acceptă","Alocare atomică. Primești SMS instant cu firma câștigătoare."],["04","Lucrarea se realizează","Urmărești progresul și confirmi finalizarea."]].map(([n,t,d],i)=><article key={n} className="bg-[#f4f3ee] rounded-2xl p-[26px]"><div className="text-sm font-bold text-[#1b8a4c]">{n}</div><h3 className="font-bold text-lg mt-8">{t}</h3><p className="text-sm text-[#5c6660] leading-6 mt-2">{d}</p>{i===1&&<span className="inline-block mt-4 text-[11px] bg-[#e4f0e8] text-[#14663a] px-2 py-1 rounded-full font-bold">push la toate firmele</span>}{i===2&&<span className="inline-block mt-4 text-[11px] bg-[#e4f0e8] text-[#14663a] px-2 py-1 rounded-full font-bold">SMS instant</span>}</article>)}</div></div></section>

    <section className="v2-container v2-section grid grid-cols-[.9fr_1.1fr] gap-16 items-center v2-mobile-stack"><div><div className="v2-eyebrow">Urmărire live</div><h2 className="v2-h2 mt-3">Știi în orice moment ce se întâmplă.</h2><p className="mt-5 text-[#5c6660] leading-7">De la acceptare până la confirmarea finală, fiecare etapă este vizibilă în cont. Fotografiile înainte și după păstrează istoricul lucrării clar.</p><div className="grid grid-cols-2 gap-3 mt-7"><Image src="/design-v2/before-kitchen.png" width={330} height={230} alt="Înainte de curățenie" className="h-40 w-full object-cover rounded-2xl"/><Image src="/design-v2/after-kitchen.png" width={330} height={230} alt="După curățenie" className="h-40 w-full object-cover rounded-2xl"/></div></div><LiveCard/></section>

    <section className="bg-white"><div className="v2-container v2-section grid grid-cols-3 gap-5 v2-mobile-stack"><Benefit id="clienti" title="Pentru clienți" items={["Preț estimat înainte de postare","Firme verificate în zona ta","Adresă protejată până la alocare","Urmărire și mesaje live"]}/><div className="v2-card p-6"><div className="v2-eyebrow">Plată protejată</div><h3 className="text-2xl font-bold mt-3">Banii rămân în siguranță până la final.</h3><div className="flex gap-2 mt-5"><span className="border rounded-lg px-3 py-2 font-bold text-sm">VISA</span><span className="border rounded-lg px-3 py-2 font-bold text-sm">mastercard</span><span className="border rounded-lg px-3 py-2 font-bold text-sm">Stripe</span></div><div className="bg-[#101711] text-white rounded-2xl p-5 mt-6"><div className="text-xs text-[#8fd8ae] font-bold">ESCROW CONFIRMAT</div><div className="text-3xl font-bold mt-2">500 lei</div><p className="text-sm text-[#a8b2ac] mt-2">Se eliberează firmei numai după confirmarea finalizării.</p></div></div><Benefit id="firme" title="Pentru firme" items={["Lucrări noi în zona deservită","Acceptare rapidă, fără licitație","Traseu și adresă după alocare","Rating și istoric verificabil"]}/></div></section>

    <section id="score" className="v2-container v2-section"><div className="bg-[#101711] text-white rounded-[20px] p-8 md:p-12 grid grid-cols-[.7fr_1.3fr] gap-12 v2-mobile-stack"><div><div className="text-[#8fd8ae] text-xs font-bold">NITIDO SCORE</div><div className="text-7xl font-bold mt-5">94</div><p className="text-[#a8b2ac] mt-3">Scor operațional calculat din performanță reală, documente și incidente.</p></div><div className="space-y-6 self-center"><Score label="Punctualitate" value="98%" width="98%"/><Score label="Fără reclamații" value="95%" width="95%"/><Score label="Acte și asigurare" value="Complet" width="100%"/></div></div></section>

    <section id="preturi" className="bg-white"><div className="v2-container v2-section"><div className="text-center"><div className="v2-eyebrow">Prețuri pentru firme</div><h2 className="v2-h2 mt-3">Planul potrivit ritmului tău.</h2></div><div className="grid grid-cols-3 gap-5 mt-10 v2-mobile-stack"><Price name="Start" price="99 lei/lună" items={["Alerte în zona ta","Profil verificat","Istoric lucrări"]}/><Price dark name="Pro" price="249 lei/lună" items={["Tot din Start","Notificări prioritare cu 30 sec","Analiză performanță"]}/><Price name="Teams" price="Ofertă" items={["Echipe multiple","Zone extinse","Suport dedicat"]}/></div></div></section>

    <section className="v2-container v2-section"><div className="v2-eyebrow">Întrebări frecvente</div><h2 className="v2-h2 mt-3">Clar, înainte să începi.</h2><div className="grid grid-cols-2 gap-4 mt-9 v2-mobile-stack">{[["Cum este aleasă firma?","Prima firmă verificată și eligibilă care acceptă pe server primește lucrarea."],["Când vede firma adresa exactă?","Numai după ce acceptarea a fost confirmată și lucrarea i-a fost alocată."],["Când se face plata?","Suma este rezervată la acceptare și eliberată după finalizare."],["Ce se întâmplă la no-show?","Rezervarea se anulează, iar incidentul intră în scorul firmei."]].map(([q,a])=><article className="v2-card p-6" key={q}><h3 className="font-bold">{q}</h3><p className="text-sm text-[#5c6660] mt-2 leading-6">{a}</p></article>)}</div></section>

    <footer id="contact" className="bg-[#101711] text-white"><div className="v2-container py-14 grid grid-cols-5 gap-8 v2-mobile-two"><div><div className="text-xl font-bold">NITIDO<span className="text-[#39c97c]">.RO</span></div><p className="text-sm text-[#8b958f] mt-4">Marketplace românesc pentru servicii de curățenie.</p></div>{[["Produs","Cum funcționează","Prețuri","Pentru firme"],["Clienți","Postează o lucrare","Urmărire live","Siguranță"],["Companie","Despre noi","Contact","Cariere"],["Legal","Termeni","Confidențialitate","Cookie-uri"]].map(([h,...xs])=><div key={h}><h4 className="text-sm font-bold">{h}</h4>{xs.map(x=><div className="text-sm text-[#8b958f] mt-3" key={x}>{x}</div>)}</div>)}</div><div className="border-t border-[#2a332c]"><div className="v2-container py-5 text-xs text-[#8b958f] flex justify-between"><span>© 2026 NITIDO.RO</span><span>{verified>0?`${verified} firme verificate în platformă`:"România"}</span></div></div></footer>
  </main>;
}

function LiveCard(){return <div className="v2-card p-7 shadow-[0_24px_60px_rgba(16,23,17,.10)]"><div className="flex justify-between"><div><div className="text-xs text-[#1b8a4c] font-bold">ÎN LUCRU ACUM</div><h3 className="font-bold text-xl mt-2">Curățenie apartament · Sector 1</h3></div><span className="bg-[#e4f0e8] text-[#14663a] h-fit rounded-full px-3 py-1 text-xs font-bold">6 / 9 pași</span></div><div className="mt-7 space-y-0">{[["Acceptată","09:12",true],["Echipa a ajuns","10:04",true],["În lucru acum","6 din 9 pași",true],["Confirmare estimată","14:00",false]].map(([x,t,on],i)=><div key={x as string} className="flex gap-4 min-h-16"><div className="flex flex-col items-center"><span className={`w-3 h-3 rounded-full ${on?"bg-[#1b8a4c]":"bg-[#d8d7d0]"}`}/>{i<3&&<span className="w-px flex-1 bg-[#d8d7d0]"/>}</div><div className="flex justify-between w-full text-sm"><b>{x}</b><span className="text-[#5c6660]">{t}</span></div></div>)}</div></div>}
function Benefit({id,title,items}:{id:string,title:string,items:string[]}){return <div id={id} className="bg-[#e9f2ec] rounded-[18px] p-7"><div className="v2-eyebrow">{title}</div><h3 className="text-2xl font-bold mt-3">Mai mult control, mai puține incertitudini.</h3><div className="space-y-3 mt-6">{items.map(x=><div className="flex gap-2 text-sm" key={x}><span className="text-[#1b8a4c]"><Check/></span>{x}</div>)}</div></div>}
function Score({label,value,width}:{label:string,value:string,width:string}){return <div><div className="flex justify-between text-sm"><span>{label}</span><b>{value}</b></div><div className="h-2 bg-[#2a332c] rounded-full mt-2"><div className="h-full bg-[#39c97c] rounded-full" style={{width}}/></div></div>}
function Price({name,price,items,dark=false}:{name:string,price:string,items:string[],dark?:boolean}){return <article className={`rounded-[18px] p-7 border ${dark?"bg-[#101711] text-white border-[#101711]":"bg-white border-[#e3e2da]"}`}>{dark&&<span className="text-xs bg-[#39c97c] text-[#101711] px-3 py-1 rounded-full font-bold">RECOMANDAT</span>}<h3 className="text-xl font-bold mt-5">{name}</h3><div className="text-3xl font-bold mt-2">{price}</div><div className="space-y-3 mt-6">{items.map(x=><div className={`flex gap-2 text-sm ${dark?"text-[#d3dad5]":""}`} key={x}><Check/>{x}</div>)}</div><Link href="/signup?role=firma" className={`v2-btn w-full mt-7 ${dark?"v2-btn-primary":"v2-btn-secondary"}`}>Alege planul</Link></article>}
