import Image from "next/image";
import Link from "next/link";
import { db } from "@/lib/db";
import { SiteHeader, SiteFooter } from "@/components/SiteChrome";
import { VerifiedReviews } from "@/components/VerifiedReviews";
import { getPublicTrustSnapshot } from "@/lib/reviews";
import { getActiveEstimatorOptions } from "@/lib/estimatorConfig";
import { BookingEstimator } from "@/components/BookingEstimator";
export const dynamic = "force-dynamic";
const services = [
  { title: "Acasă, în ordine", text: "Apartamente și case, pentru timpul tău liber.", image: "hero-cleaning.png", type: "apartament" },
  { title: "Un birou primitor", text: "Spații de lucru pregătite pentru o nouă zi.", image: "about-professionals-v3.webp", type: "birou" },
  { title: "Pregătit de oaspeți", text: "Organizează curățenia proprietăților tale.", image: "after-kitchen.png", type: "casa" },
];
export default function Home() {
 const trust = getPublicTrustSnapshot(db);
 return <><SiteHeader/><main id="main-content">
  <section className="home-hero v2-container">
   <div className="home-hero-copy"><span className="eyebrow-pill">Curățenie. Mai simplu, de la început.</span><h1>Curățenia începe cu o <em>alegere simplă.</em></h1><p>Găsește firme verificate, vezi prețul și organizează fiecare lucrare într-un singur loc. Pentru acasă, birou sau proprietățile tale.</p><div className="flex gap-3 flex-wrap"><Link href="/client#sec-form" className="v2-btn v2-btn-primary">Rezervă o curățenie <span aria-hidden="true">↗</span></Link><Link href="/cum-functioneaza" className="v2-btn v2-btn-secondary">Cum funcționează</Link></div><div className="home-trust"><span>✓ Firme verificate</span><span>✓ Preț înainte de publicare</span><span>✓ Dovezi foto</span></div></div>
   <div className="home-hero-photo"><Image src="/design-v2/hero-cleaning.png" alt="Curățenie profesională într-o locuință luminoasă" fill priority sizes="(max-width: 900px) 100vw, 50vw" className="object-cover"/><div className="home-photo-note"><span className="home-note-icon" aria-hidden="true">✓</span><div><strong>Mai mult timp pentru tine</strong><p>De la prima rezervare la ultima verificare.</p></div></div></div>
  </section>
  <div className="v2-container"><BookingEstimator options={getActiveEstimatorOptions(db)}/></div>
  <section className="v2-container v2-section" id="clienti"><div className="section-heading"><div><div className="v2-eyebrow">Spațiul tău. Ritmul tău.</div><h2 className="v2-h2 mt-3">Cu ce te putem ajuta?</h2></div><Link href="/preturi" className="text-aqua font-semibold">Vezi prețurile ↗</Link></div><div className="service-grid">{services.map(s=><Link href={`/client?spaceType=${s.type}#sec-form`} className="service-card" key={s.title}><div className="service-photo"><Image src={`/design-v2/${s.image}`} alt={s.title} fill sizes="(max-width: 760px) 100vw, 33vw" className="object-cover"/></div><div className="p-6"><h3 className="font-bold text-xl">{s.title} <span className="float-right text-aqua">↗</span></h3><p className="text-muted text-sm mt-2">{s.text}</p></div></Link>)}</div></section>
  <section className="v2-container pb-16" id="cum"><div className="mode-grid"><article className="mode-card"><span className="eyebrow-pill">STANDARD</span><h2>Alegi firma potrivită.</h2><p>Prețul lucrării este stabilit de platformă. Compari experiența și recenziile firmelor care candidează, apoi alegi.</p><Link href="/client#sec-form" className="v2-btn v2-btn-primary">Începe rezervarea ↗</Link></article><article className="mode-card mode-express"><span className="eyebrow-pill">EXPRESS</span><h2>Ai nevoie cât mai curând?</h2><p>Prima firmă eligibilă care acceptă preia lucrarea. Disponibilitatea depinde de firmele din zona ta.</p><Link href="/client?mode=express#sec-form" className="v2-btn v2-btn-secondary">Alege Express ↗</Link></article></div></section>
  <section className="bg-white" id="score"><div className="v2-container v2-section"><div className="v2-eyebrow">Fiecare etapă, la vedere</div><h2 className="v2-h2 mt-3">Tu alegi. Noi păstrăm lucrurile clare.</h2><div className="steps-grid">{[["01","Descrii spațiul","Alegi tipul spațiului, suprafața și programul. Vezi prețul înainte să publici."],["02","Primești candidaturi","Firmele eligibile văd cererea. La Standard alegi tu; la Express acceptă prima firmă disponibilă."],["03","Urmărești lucrarea","Vezi etapele și dovezile foto în cont. Adresa exactă este protejată înainte de alocare."],["04","Evaluezi experiența","La final poți lăsa o recenzie pentru lucrarea realizată."]].map(([n,t,d])=><article key={n}><span className="step-number">{n}</span><h3 className="text-lg font-bold mt-5">{t}</h3><p className="text-sm text-muted leading-6 mt-2">{d}</p></article>)}</div><Link href="/incredere" className="inline-block mt-8 text-aqua font-semibold">Încredere & Siguranță ↗</Link></div></section>
  <VerifiedReviews reviews={trust.reviews}/>
  <section className="v2-container v2-section" id="firme"><div className="partner-banner"><div><div className="text-sm text-teal-200">NITIDO PENTRU PROFESIONIȘTI</div><h2 className="v2-h2 mt-3">Mai multă ordine.<br/>În lucrări și în afacere.</h2><p className="mt-4 text-slate-300 max-w-lg">Oportunități, programări, echipe și istoricul lucrărilor. Un loc pentru organizarea activității firmei tale.</p></div><Link href="/signup?role=firma" className="v2-btn bg-white text-ink">Înscrie-ți firma ↗</Link></div></section>
  <section className="v2-container pb-16" id="preturi"><h2 className="v2-h2 mb-6">Bine de știut.</h2><div className="faq-list">{[["Cum se calculează prețul?","Din tipul spațiului și suprafață, conform regulilor active. Prețul final este verificat de server la publicare."],["Când se încasează plata?","Cardul este procesat de Stripe. Autorizarea și încasarea sunt etape distincte; starea plății este afișată în cont."],["Cine vede adresa și fotografiile?","Datele private ale lucrării sunt accesibile clientului și firmei alocate, conform drepturilor lor."],["Pot programa curățenii repetate?","Da. Din cont poți gestiona planuri săptămânale, la două săptămâni sau lunare."]].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
 </main><SiteFooter/></>;
}
