import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import {HomeLogoLink} from "@/components/HomeLogoLink";

export const metadata: Metadata = {
  title: "Despre noi | NITIDO.RO",
  description: "NITIDO.RO conectează clienții cu firme eligibile de curățenie printr-un proces rapid, transparent și protejat.",
};

const services = [
  ["link", "Conectăm rapid", "Punem în legătură clienții cu firme eligibile din zona potrivită, fără timp pierdut cu zeci de apeluri."],
  ["check", "Alocăm corect", "Lucrarea este atribuită printr-un flux clar și controlat de server: prima firmă eligibilă care acceptă primește lucrarea."],
  ["shield", "Protejăm procesul", "Identitatea, accesul la date și pașii sensibili sunt controlați astfel încât fiecare parte să vadă doar informațiile de care are nevoie."],
  ["star", "Construim reputație", "Ratingurile, istoricul și comportamentul pe platformă ajută la formarea unui ecosistem mai serios și mai responsabil."],
] as const;
const clients = ["Publicare simplă și rapidă", "Firme eligibile și verificate", "Preț clar și fără surprize", "Status vizibil în timp real", "Protecția adresei înainte de alocare", "Plată și finalizare controlate", "Sistem de evaluare"];
const firms = ["Lucrări relevante pe zonă", "Acceptare rapidă", "Reducerea timpului pierdut cu ofertare", "Istoric și rating", "Vizibilitate asupra lucrărilor", "Proces de plată urmărit", "Reputație construită în timp"];
const steps = ["Clientul postează lucrarea", "Firmele eligibile sunt notificate", "Prima firmă eligibilă acceptă", "Lucrarea este alocată", "Firma primește detaliile necesare", "Lucrarea este executată", "Finalizarea și plata sunt confirmate", "Clientul poate evalua firma"];
const values = [
  ["Claritate", "Comunicăm simplu, arătăm clar pașii, costurile și statusurile."],
  ["Rapiditate", "Reducem timpul pierdut și răspundem nevoilor în timp real."],
  ["Corectitudine", "Reguli egale și transparente pentru clienți și firme."],
  ["Responsabilitate", "Ne asumăm calitatea produsului și impactul lui în piață."],
] as const;

export default function AboutPage() {
  return <main className="overflow-hidden bg-[#f4f3ee] text-[#101711]">
    <Header />
    <section className="v2-container grid min-h-[720px] grid-cols-[1.02fr_.98fr] items-center gap-14 py-16 max-[900px]:grid-cols-1 max-[900px]:gap-10 max-[900px]:pt-12">
      <div className="max-w-[690px]"><div className="v2-eyebrow">DESPRE NITIDO.RO</div><h1 className="mt-5 text-[clamp(42px,5vw,72px)] font-bold leading-[1.01] tracking-[-.05em]">Construim o piață mai simplă, mai rapidă și mai corectă pentru serviciile de curățenie.</h1><p className="mt-7 max-w-[650px] text-[17px] leading-8 text-[#3e4842]">NITIDO.RO este o platformă tehnologică dedicată serviciilor de curățenie, creată pentru a conecta rapid clienții care au nevoie de ajutor cu firme eligibile și verificate din zona lor. În locul telefoanelor repetate, ofertelor neclare și timpului pierdut, NITIDO aduce procesul într-un singur loc: publicarea lucrării, alocarea firmei, urmărirea statusului, plata și evaluarea.</p><p className="mt-4 max-w-[620px] leading-7 text-[#5c6660]">În locul telefoanelor repetate și ofertelor neclare, aducem tot procesul într-un singur loc: publicare, alocare, execuție, plată și evaluare.</p><Ctas /></div>
      <div className="relative min-h-[620px] max-[900px]:min-h-[570px] max-sm:min-h-[500px]"><Image src="/design-v2/about-professionals-v3.webp" alt="Profesioniști în curățenie lucrând într-o locuință modernă" fill priority sizes="(max-width: 900px) 100vw, 48vw" className="rounded-[26px] object-cover shadow-[0_32px_80px_rgba(16,23,17,.16)]"/><div className="absolute -bottom-7 -left-8 w-[330px] rounded-[20px] border border-white/10 bg-[#101711] p-6 text-white shadow-2xl max-sm:-bottom-5 max-sm:left-4 max-sm:right-4 max-sm:w-auto"><div className="flex items-center gap-3 text-[#8fd8ae]"><Icon name="shield"/><b className="text-sm">Platformă sigură și transparentă</b></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs text-[#d3dad5]"><span className="rounded-xl bg-white/5 p-3">Flux controlat de server</span><span className="rounded-xl bg-white/5 p-3">Date protejate</span><span className="col-span-2 rounded-xl bg-white/5 p-3">Reguli clare pentru toți</span></div></div></div>
    </section>

    <section className="bg-white"><div className="v2-container grid grid-cols-[.75fr_1.25fr] gap-20 py-28 max-[820px]:grid-cols-1 max-[820px]:gap-8 max-[820px]:py-20"><div><div className="v2-eyebrow">CINE SUNTEM</div><h2 className="v2-h2 mt-4">Tehnologie construită în jurul unei nevoi foarte simple.</h2></div><div className="space-y-6 text-[18px] leading-8 text-[#3e4842]"><p>Când cineva are nevoie de servicii de curățenie, procesul ar trebui să fie simplu. Clientul trebuie să știe cât costă, cine vine, când ajunge și ce se întâmplă cu plata. Firma trebuie să primească lucrări relevante, să poată accepta rapid și să aibă un flux clar de lucru și încasare.</p><p className="font-medium text-[#101711]">NITIDO.RO a fost construit exact în jurul acestei idei: mai puțină fricțiune, mai puțină incertitudine și mai mult control pentru ambele părți.</p></div></div></section>

    <section className="v2-container py-28 max-md:py-20"><div className="rounded-[28px] bg-[#101711] px-12 py-16 text-white max-sm:px-6 max-sm:py-10"><div className="grid grid-cols-[1fr_.9fr] gap-16 max-[820px]:grid-cols-1 max-[820px]:gap-8"><div><div className="text-xs font-bold tracking-[.16em] text-[#8fd8ae]">MISIUNEA NOASTRĂ</div><h2 className="mt-5 text-[clamp(40px,5vw,68px)] font-bold leading-[1.02] tracking-[-.045em]">Mai puțină așteptare.<br/>Mai puține telefoane.<br/><span className="text-[#39c97c]">Mai multă transparență.</span></h2></div><p className="self-end text-lg leading-8 text-[#c5cec8]">Misiunea NITIDO este să transforme modul în care sunt contractate serviciile de curățenie: rapid, clar și predictibil. Clientul publică lucrarea, firmele eligibile sunt notificate, iar prima firmă care acceptă în condițiile platformei primește lucrarea. Tot procesul este urmărit digital, pas cu pas.</p></div></div></section>

    <section className="bg-white"><div className="v2-container py-28 max-md:py-20"><div className="max-w-2xl"><div className="v2-eyebrow">CE FACEM</div><h2 className="v2-h2 mt-4">Un proces coerent, de la nevoie la rezultat.</h2></div><div className="mt-12 grid grid-cols-4 gap-5 max-[1000px]:grid-cols-2 max-sm:grid-cols-1">{services.map(([icon,title,body],i)=><article key={title} className="rounded-[20px] border border-[#e3e2da] bg-[#f4f3ee] p-7"><div className="flex items-center justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#e4f0e8] text-[#14663a]"><Icon name={icon}/></span><span className="text-xs font-bold text-[#9aa39d]">0{i+1}</span></div><h3 className="mt-10 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#5c6660]">{body}</p></article>)}</div></div></section>

    <Audience eyebrow="PENTRU CLIENȚI" title="Control, claritate și liniște." body="NITIDO.RO este gândit pentru oamenii care vor să rezolve rapid o nevoie reală, fără să transforme o simplă curățenie într-un proiect de o zi întreagă." benefits={clients} image="/design-v2/after-kitchen.png" alt="Locuință curată și luminoasă după finalizarea serviciului"/>
    <Audience reverse dark eyebrow="PENTRU FIRME" title="Lucrări relevante. Proces eficient." body="NITIDO.RO oferă firmelor de curățenie un mod mai direct de a găsi lucrări reale și de a-și organiza activitatea. În loc să consume timp cu oferte trimise fără răspuns, firmele eligibile primesc alerte pentru lucrări din zonele lor și pot decide rapid dacă vor să le accepte." benefits={firms} image="/design-v2/about-professionals-v3.webp" alt="Echipă profesionistă de curățenie într-o locuință contemporană"/>

    <section className="v2-container py-28 max-md:py-20"><div className="grid grid-cols-[.8fr_1.2fr] gap-20 max-[900px]:grid-cols-1 max-[900px]:gap-10"><div><div className="v2-eyebrow">ÎNCREDERE ȘI SIGURANȚĂ</div><h2 className="v2-h2 mt-4">Încrederea nu este un slogan. Este parte din produs.</h2></div><div><p className="text-lg leading-8 text-[#3e4842]">Pentru NITIDO, încrederea înseamnă reguli clare în produs: autentificare, autorizare, protecția datelor, limitarea accesului la adresa exactă înainte de acceptare, control asupra operațiunilor sensibile și separarea rolurilor între client, firmă și administrare.</p><p className="mt-5 text-lg font-medium leading-8">Nu vrem doar ca platforma să arate profesionist. Vrem ca fluxurile din spate să fie construite corect.</p></div></div><div className="mt-12 grid grid-cols-4 gap-4 max-[900px]:grid-cols-2 max-sm:grid-cols-1">{[["user","Identitate și acces controlat"],["lock","Date protejate"],["check","Alocare corectă"],["shield","Plăți și acțiuni sensibile protejate"]].map(([icon,title])=><div key={title} className="rounded-2xl border border-[#dcdad1] bg-white p-6"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#e4f0e8] text-[#14663a]"><Icon name={icon as IconName}/></span><h3 className="mt-7 font-bold leading-6">{title}</h3></div>)}</div></section>

    <section className="bg-[#e9f2ec]"><div className="v2-container py-28 max-md:py-20"><div className="text-center"><div className="v2-eyebrow">CUM FUNCȚIONEAZĂ, PE SCURT</div><h2 className="v2-h2 mx-auto mt-4 max-w-3xl">Opt pași clari. Un singur flux.</h2></div><div className="relative mt-14 grid grid-cols-8 gap-3 max-[1050px]:grid-cols-4 max-sm:grid-cols-2"><div className="absolute left-[6%] right-[6%] top-5 h-px bg-[#acd0ba] max-[1050px]:hidden"/>{steps.map((step,i)=><div key={step} className="relative"><span className="relative z-10 flex h-10 w-10 items-center justify-center rounded-full bg-[#1b8a4c] text-sm font-bold text-white">{i+1}</span><p className="mt-5 text-sm font-semibold leading-5">{step}</p></div>)}</div></div></section>

    <section className="bg-white"><div className="v2-container py-28 max-md:py-20"><div className="v2-eyebrow">VALORILE NITIDO</div><h2 className="v2-h2 mt-4">Principiile după care construim</h2><div className="mt-12 grid grid-cols-4 gap-5 max-[900px]:grid-cols-2 max-sm:grid-cols-1">{values.map(([title,body],i)=><article key={title} className="rounded-[20px] bg-[#f4f3ee] p-7"><span className="text-xs font-bold text-[#1b8a4c]">0{i+1}</span><h3 className="mt-10 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#5c6660]">{body}</p></article>)}</div></div></section>

    <section className="v2-container py-24 max-md:py-16"><div className="relative overflow-hidden rounded-[30px] bg-[#1b8a4c] px-12 py-16 text-white max-sm:px-6 max-sm:py-10"><div className="absolute -right-24 -top-32 h-80 w-80 rounded-full border-[70px] border-white/10"/><div className="relative z-10 max-w-4xl"><h2 className="text-[clamp(38px,5vw,64px)] font-bold leading-[1.04] tracking-[-.045em]">Un proces mai simplu pentru client.<br/>Un flux mai bun pentru firmă.</h2><p className="mt-6 text-lg text-white/80">NITIDO.RO construiește legătura dintre nevoie și execuție într-un singur produs.</p><Ctas light/></div></div></section>
    <Footer />
  </main>;
}

function Header(){return <header className="sticky top-0 z-50 h-[66px] border-b border-[#e3e2da] bg-[#f4f3ee]/95 backdrop-blur"><div className="v2-container flex h-full items-center justify-between"><HomeLogoLink/><nav className="v2-hide-mobile flex items-center gap-7 text-sm font-medium text-[#3e4842]"><Link href="/#cum">Cum funcționează</Link><Link href="/#clienti">Pentru clienți</Link><Link href="/#firme">Pentru firme</Link><Link href="/#preturi">Prețuri</Link><Link href="/despre-noi" aria-current="page" className="text-[#14663a]">Despre noi</Link><Link href="/contact">Contact</Link></nav><div className="flex items-center gap-2"><Link href="/login" className="v2-btn v2-btn-secondary v2-hide-mobile">Autentificare</Link><Link href="/signup" className="v2-btn v2-btn-primary">Înregistrează-te</Link></div></div></header>}
function Footer(){return <footer className="bg-[#101711] text-white"><div className="v2-container grid grid-cols-5 gap-8 py-14 v2-mobile-two"><div><Link href="/" className="text-xl font-bold">NITIDO<span className="text-[#39c97c]">.RO</span></Link><p className="mt-4 text-sm text-[#8b958f]">Platformă românească pentru servicii de curățenie.</p></div><FooterGroup title="Produs" links={[["Cum funcționează","/cum-functioneaza"],["Pentru clienți","/pentru-clienti"],["Pentru firme","/pentru-firme"],["Prețuri","/preturi"]]}/><FooterGroup title="Clienți" links={[["Postează o lucrare","/signup?role=client"],["Urmărire live","/urmarire-live"],["Siguranță","/siguranta"]]}/><FooterGroup title="Companie" links={[["Despre noi","/despre-noi"],["Contact","/contact"],["Cariere","/cariere"]]}/><FooterGroup title="Legal" links={[["Termeni","/termeni"],["Confidențialitate","/confidentialitate"],["Cookie-uri","/cookie-uri"]]}/></div><div className="border-t border-[#2a332c]"><div className="v2-container flex justify-between py-5 text-xs text-[#8b958f]"><span>© 2026 NITIDO.RO</span><span>România</span></div></div></footer>}
function FooterGroup({title,links}:{title:string;links:[string,string][]}){return <div><h4 className="text-sm font-bold">{title}</h4>{links.map(([label,href])=><Link className="mt-3 block text-sm text-[#8b958f] hover:text-white" href={href} key={href}>{label}</Link>)}</div>}
function Ctas({light=false}:{light?:boolean}){return <div className="mt-8 flex flex-wrap gap-3"><Link href="/signup?role=client" className={`v2-btn ${light?"bg-white text-[#14663a] hover:bg-[#f4f3ee]":"v2-btn-primary"}`}>Postează o lucrare <Arrow/></Link><Link href="/signup?role=firma" className={`v2-btn ${light?"border border-white/35 text-white hover:bg-white/10":"v2-btn-secondary"}`}>Înregistrează-ți firma</Link></div>}
function Audience({reverse=false,dark=false,eyebrow,title,body,benefits,image,alt}:{reverse?:boolean;dark?:boolean;eyebrow:string;title:string;body:string;benefits:string[];image:string;alt:string}){return <section className={dark?"bg-[#101711] text-white":"bg-[#f4f3ee]"}><div className={`v2-container grid grid-cols-2 items-center gap-20 py-28 max-[900px]:grid-cols-1 max-[900px]:gap-10 max-[900px]:py-20 ${reverse?"[&>*:first-child]:order-2 max-[900px]:[&>*:first-child]:order-1":""}`}><div><div className={dark?"text-xs font-bold tracking-[.16em] text-[#8fd8ae]":"v2-eyebrow"}>{eyebrow}</div><h2 className="v2-h2 mt-4">{title}</h2><p className={`mt-5 text-lg leading-8 ${dark?"text-[#c5cec8]":"text-[#3e4842]"}`}>{body}</p><div className="mt-8 grid grid-cols-2 gap-x-6 gap-y-4 max-sm:grid-cols-1">{benefits.map(x=><div key={x} className="flex items-start gap-3 text-sm"><span className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full ${dark?"bg-[#274a39] text-[#8fd8ae]":"bg-[#dceee3] text-[#14663a]"}`}><Check/></span><span>{x}</span></div>)}</div></div><div className="relative min-h-[540px]"><Image src={image} alt={alt} fill sizes="(max-width: 900px) 100vw, 50vw" className="rounded-[24px] object-cover"/><div className={`absolute bottom-5 left-5 right-5 rounded-2xl p-5 backdrop-blur-md ${dark?"bg-[#101711]/85":"bg-white/90"}`}><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#1b8a4c] text-white"><Icon name={dark?"briefcase":"home"}/></span><div><b className="block text-sm">{dark?"Flux construit pentru firme":"Experiență construită pentru client"}</b><span className={`text-xs ${dark?"text-[#a8b2ac]":"text-[#5c6660]"}`}>{dark?"Alerte, alocare, execuție și istoric":"De la publicare până la evaluare"}</span></div></div></div></div></div></section>}

type IconName="link"|"check"|"shield"|"star"|"user"|"lock"|"briefcase"|"home";
const paths:Record<IconName,React.ReactNode>={link:<><path d="M10 13a5 5 0 0 0 7.1.1l2-2a5 5 0 0 0-7.1-7.1l-1.1 1.1"/><path d="M14 11a5 5 0 0 0-7.1-.1l-2 2A5 5 0 0 0 12 20l1.1-1.1"/></>,check:<path d="m5 12 4 4L19 6"/>,shield:<path d="M12 3 20 6v5c0 5-3.4 8.4-8 10-4.6-1.6-8-5-8-10V6z"/>,star:<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-2.9-5.6 2.9 1.1-6.2L3 9.6l6.2-.9z"/>,user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,lock:<><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>,briefcase:<><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V5h8v2m-13 5h18"/></>,home:<><path d="m3 11 9-8 9 8"/><path d="M5 10v11h14V10M9 21v-7h6v7"/></>};
function Icon({name}:{name:IconName}){return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}
function Check(){return <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>}
function Arrow(){return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>}
