'use client';
import {useEffect,useState} from 'react';
import type {AssistedOperation} from '@/lib/assistedOperations';
import type {SavedAssessmentPlan} from '@/lib/assessmentPlan';
export function AdminAssistedOperation({offerId}:{offerId:string}){
 const [operation,setOperation]=useState<AssistedOperation|null>(null),[plan,setPlan]=useState<SavedAssessmentPlan|null>(null),[enabled,setEnabled]=useState(false),[team,setTeam]=useState(''),[expires,setExpires]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const url=`/api/admin/assisted-operations?id=${encodeURIComponent(offerId)}`;
 async function load(){const r=await fetch(url,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setPlan(d.plan);setOperation(d.operation);setEnabled(d.enabled);setTeam('');}
 useEffect(()=>{const c=new AbortController();fetch(url,{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{if(!c.signal.aborted){setPlan(d.plan);setOperation(d.operation);setEnabled(d.enabled);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[url]);
 async function save(){setBusy(true);setError('');try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:offerId,revision:operation?.revision??0,planRevision:plan?.revision,teamId:team,expiresAt:new Date(expires).toISOString(),reason})}),d=await r.json();if(!r.ok)throw Error(d.error);setOperation(d.operation);}catch(e){setError(e instanceof Error?e.message:'Propunere nereușită');}finally{setBusy(false);}}
 return <section className="design-panel"><h4>Leagă planul și echipa de ofertă</h4><p>Clientul confirmă planul și firma propusă la rezervare. Echipa se alocă efectiv numai când firma preia lucrarea, după reverificarea capacității. Este acceptată o singură echipă pe lucrare. Un plan operațional înlocuiește alegerea simplă a intervalului.</p>{error&&<p role="alert">{error}</p>}<button type="button" disabled={busy} onClick={()=>void load().then(()=>setError('')).catch(e=>setError(e.message))}>Actualizează planul și propunerea</button>{operation&&<p>Propunerea {operation.revision}: {operation.firmName} / {operation.teamName} · {new Date(operation.startsAt).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'})} · {operation.durationMinutes} minute + {operation.bufferMinutes} minute deplasare.</p>}{!plan?<p>Salvează mai întâi planul operațional al cererii.</p>:<form onSubmit={e=>{e.preventDefault();void save();}}><p>Planul {plan.revision} · {new Date(plan.definition.startsAt).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'})}, ora României. Disponibilitatea afișată provine din ultima evaluare și se verifică din nou la salvare.</p><fieldset disabled={!enabled||busy||plan.definition.requiredTeams!==1}><label>Echipă propusă<select required value={team} onChange={e=>setTeam(e.target.value)}><option value="">Alege echipa</option>{plan.capacity.firms.flatMap(f=>f.eligible?f.teams.filter(t=>t.available).map(t=><option key={t.teamId} value={t.teamId}>{f.name} · {t.teamId}</option>):[])}</select></label><label>Confirmare până la (ora dispozitivului)<input required type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)}/></label><label>Motiv intern<textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="submit" className="design-button">Propune clientului planul și echipa</button></fieldset>{plan.definition.requiredTeams!==1&&<p>Planul cere mai multe echipe; alocarea automată nu este disponibilă pentru acest caz.</p>}</form>}</section>;
}
