'use client';
import {useEffect,useState} from 'react';
import type {SavedAssessmentPlan} from '@/lib/assessmentPlan';
const date=(s:string)=>new Date(s).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'});
export function AdminAssessmentPlan({id}:{id:string}){
 const [plans,setPlans]=useState<SavedAssessmentPlan[]>([]),[version,setVersion]=useState<number|null>(null),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [start,setStart]=useState(''),[duration,setDuration]=useState(''),[buffer,setBuffer]=useState(''),[teams,setTeams]=useState(''),[source,setSource]=useState(''),[reason,setReason]=useState('');
 const endpoint=`/api/admin/assessment-plans?id=${encodeURIComponent(id)}`;
 async function load(){const r=await fetch(endpoint,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setPlans(d.plans);setVersion(d.assessmentVersion);setEnabled(d.enabled);}
 useEffect(()=>{const c=new AbortController();fetch(endpoint,{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{if(!c.signal.aborted){setPlans(d.plans);setVersion(d.assessmentVersion);setEnabled(d.enabled);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[endpoint]);
 async function save(){setBusy(true);setError('');try{if(!duration||!buffer||!teams)throw Error('Completează explicit durata, deplasarea și echipele.');const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,revision:plans[0]?.revision??0,assessmentVersion:version,definition:{startsAt:new Date(start).toISOString(),durationMinutes:Number(duration),bufferMinutes:Number(buffer),requiredTeams:Number(teams),source,reason}})}),d=await r.json();if(!r.ok)throw Error(d.error);setPlans(p=>[d.plan,...p].slice(0,50));}catch(e){setError(e instanceof Error?e.message:'Planificare nereușită');}finally{setBusy(false);}}
 return <section className="design-panel"><h3>Durată și capacitate pentru evaluare</h3><p>Completează durata efectivă de lucru și deplasarea separat, inclusiv zero dacă este confirmat. Verificarea include regulile echipelor și suprapunerile firmei. Rezultatul este o evaluare internă la momentul salvării; nu rezervă echipe, nu modifică oferta și nu creează o lucrare.</p>{error&&<p role="alert">{error}</p>}<button type="button" disabled={busy} onClick={()=>void load().then(()=>setError('')).catch(e=>setError(e.message))}>Actualizează cererea și istoricul</button><form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={!enabled||version===null||busy}><label>Început (ora dispozitivului)<input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Durata lucrării în minute<input required type="number" min="1" max="10080" step="1" value={duration} onChange={e=>setDuration(e.target.value)}/></label><label>Deplasare / rezervă după lucrare, minute<input required type="number" min="0" max="10080" step="1" value={buffer} onChange={e=>setBuffer(e.target.value)}/></label><label>Echipe necesare din aceeași firmă<input required type="number" min="1" max="100" step="1" value={teams} onChange={e=>setTeams(e.target.value)}/></label><label>Sursa duratei și a necesarului de echipe<textarea required maxLength={2000} value={source} onChange={e=>setSource(e.target.value)}/></label><label>Motiv intern<textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="design-button" type="submit">Verifică și salvează revizia planului</button></fieldset></form>{plans.map(p=><details key={p.revision} open={p.revision===plans[0]?.revision}><summary>Revizia {p.revision} · {date(p.created_at)} · {p.capacity.eligibleFirms} firme cu capacitate la verificare</summary>{p.assessment_version!==version&&<p role="alert">Cererea s-a schimbat. Această evaluare este istorică.</p>}<p>{p.definition.durationMinutes} minute lucru + {p.definition.bufferMinutes} minute deplasare · {p.definition.requiredTeams} echipe · {date(p.definition.startsAt)} (România)</p><p>Sursă: {p.definition.source}. Motiv: {p.definition.reason}.</p><p>Capacitatea nu este rezervată. Repetă verificarea înainte de alocare. Planurile cu mai multe echipe necesită alocare asistată; nu activează automat lucrări cu mai multe echipe.</p>{p.capacity.firms.map(f=><article key={f.id}><strong>{f.name}</strong><p>{f.eligible?'Criteriile verificate sunt îndeplinite':f.reasons.join(' · ')} · {f.availableTeams} echipe fără suprapuneri</p>{f.teams.map(t=><p key={t.teamId}>Echipa {t.teamId}: {t.reason??`interval până la ${date(t.endsAt!)} (România)`}</p>)}</article>)}</details>)}</section>;
}
