'use client';
import {useEffect,useState} from 'react';
import type {OfferSchedule} from '@/lib/manualOfferSchedule';
import {SLOT_HOURS} from '@/lib/pricing';
export function AdminOfferSchedule({offerId}:{offerId:string}){
 const [schedule,setSchedule]=useState<OfferSchedule|null>(null),[enabled,setEnabled]=useState(false),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [date,setDate]=useState(''),[hour,setHour]=useState<number>(8),[expires,setExpires]=useState(''),[reason,setReason]=useState('');
 const url=`/api/assessments/schedule?id=${encodeURIComponent(offerId)}&admin=true`;
 async function load(){const r=await fetch(url,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setSchedule(d.schedule);setEnabled(d.enabled);setLoaded(true);}
 useEffect(()=>{const c=new AbortController();fetch(url,{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{if(!c.signal.aborted){setSchedule(d.schedule);setEnabled(d.enabled);setLoaded(true);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[url]);
 async function save(action:'propose'|'withdraw'){
  setBusy(true);setError('');try{const body={id:offerId,revision:schedule?.revision??0,action,reason,...(action==='propose'?{scheduledDate:date,scheduledHour:hour,expiresAt:new Date(expires).toISOString()}:{})};const r=await fetch('/api/assessments/schedule',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error);setSchedule(d.schedule);setReason('');}catch(e){setError(e instanceof Error?e.message:'Operațiune nereușită');}finally{setBusy(false);}
 }
 return <section><h4>Propune data rezervării</h4><p>Disponibil pentru ofertele compatibile cu rezervarea simplă. Ora propusă este ora României. Clientul confirmă intervalul la crearea rezervării; echipa și capacitatea se verifică la preluarea lucrării. Pentru rezervări deja create se folosește reprogramarea existentă.</p>{error&&<p role="alert">{error}</p>}{schedule&&<p>Revizia {schedule.revision}: {schedule.action==='withdraw'?'propunere retrasă':`${new Date(schedule.starts_at!).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'})} · expiră ${new Date(schedule.expires_at!).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'})}`}</p>}<button type="button" disabled={busy} onClick={()=>void load().then(()=>setError('')).catch(e=>setError(e.message))}>Actualizează programarea</button><form onSubmit={e=>{e.preventDefault();void save('propose');}}><fieldset disabled={!loaded||!enabled||busy}><label>Ziua în România<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Ora în România<select value={hour} onChange={e=>setHour(Number(e.target.value))}>{SLOT_HOURS.map(h=><option key={h} value={h}>{h}:00</option>)}</select></label><label>Termen de confirmare (ora dispozitivului)<input type="datetime-local" required value={expires} onChange={e=>setExpires(e.target.value)}/></label><label>Motiv intern<textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="design-button" type="submit">Propune intervalul clientului</button><button type="button" disabled={schedule?.action!=='propose'||!reason.trim()} onClick={()=>void save('withdraw')}>Retrage propunerea cu motiv</button></fieldset></form></section>;
}
