'use client';
import {useState} from 'react';
import type {CustomerRecord} from '@/lib/customerOperations';
import {inputClass} from './ui';
type Entry={id:string;name:string;email:string|null};
export function AdminCustomers(){
 const [query,setQuery]=useState(''),[clients,setClients]=useState<Entry[]>([]),[directoryOffset,setDirectoryOffset]=useState(0),[directoryMore,setDirectoryMore]=useState(false),[record,setRecord]=useState<CustomerRecord|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function request(url:string,body?:unknown){const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Operațiune neconfirmată.');}finally{setBusy(false);}}
 async function search(offset=0){await run(async()=>{const d=await request('/api/admin/customers?'+new URLSearchParams({q:query,offset:String(offset)}));setClients(d.clients);setDirectoryMore(d.hasMore);setDirectoryOffset(offset);setRecord(null);});}
 async function open(id:string,offset=0){await run(async()=>setRecord(await request('/api/admin/customers?'+new URLSearchParams({clientId:id,offset:String(offset)}))));}
 async function save(form:HTMLFormElement,action:'note'|'classify'|'restrict'){if(!record)return;const values=Object.fromEntries(new FormData(form));await run(async()=>{await request('/api/admin/customers',{action,clientId:record.user.id,revision:action==='restrict'?record.restriction.revision:record.classification.revision,...values,...(action==='restrict'?{blockBookings:values.blockBookings==='on',blockAssessments:values.blockAssessments==='on'}:{}),...(action==='classify'?{tags:String(values.tags).split(',').map(s=>s.trim()).filter(Boolean)}:{})});setRecord(await request('/api/admin/customers?clientId='+encodeURIComponent(record.user.id)));form.reset();});}
 return <section id="clienti" className="design-panel my-5 space-y-4" style={{background:'#f7f3ec',minWidth:0}}>
  <h2 className="text-xl font-bold">Clienți: context și istoric operațional</h2>
  <p>Caută după nume, email sau identificator. Etichetele și notele sunt interne și documentează contextul; nu aplică automat blocări, reduceri, penalizări sau schimbări de preț.</p>
  <form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();void search();}}><label className="grow">Caută un client<input className={inputClass} maxLength={150} value={query} onChange={e=>setQuery(e.target.value)} disabled={busy}/></label><button className="v2-btn v2-btn-primary self-end" disabled={busy}>Caută clienți</button></form>
  {error&&<p role="alert">{error}</p>}
  <div className="flex flex-wrap gap-2">{clients.map(c=><button key={c.id} className="v2-btn v2-btn-secondary break-words" style={{maxWidth:"100%",whiteSpace:"normal",textAlign:"left"}} disabled={busy} onClick={()=>void open(c.id)}>{c.name} · {c.email??c.id}</button>)}</div>
  <div className="flex gap-2"><button className="v2-btn v2-btn-secondary" disabled={busy||directoryOffset===0} onClick={()=>void search(directoryOffset-50)}>Clienții anteriori</button><button className="v2-btn v2-btn-secondary" disabled={busy||!directoryMore} onClick={()=>void search(directoryOffset+50)}>Clienții următori</button></div>
  {record&&<article className="space-y-4" aria-busy={busy}>
   <h3 className="text-lg font-bold">{record.user.name}</h3><p className="break-all">{record.user.id} · {record.user.email??'Email neînregistrat'} · {record.user.phone??'Telefon neînregistrat'}</p>
   <p>{record.properties} proprietăți active în workspace. Proprietățile Pro rămân administrate separat în organizație. Sold credit înregistrat: {record.user.credit_balance} lei. Marja se verifică în secțiunea Performanță, filtrând acest identificator de client; costurile lipsă nu sunt zero.</p>
   <div className="grid gap-3 sm:grid-cols-3">
    <div className="rounded-xl border p-4" style={{background:'#fbf7ef',borderColor:'#ddd4c5'}}><h4 className="font-semibold">Istoricul complet</h4><p>{record.value.totalJobs} lucrări înregistrate · {record.value.completedJobs} finalizate</p></div>
    <div className="rounded-xl border p-4" style={{background:'#fbf7ef',borderColor:'#ddd4c5'}}><h4 className="font-semibold">Valoarea serviciilor finalizate</h4><p>{formatBani(record.value.completedServiceValueBani)}</p><p className="text-sm">Suma prețurilor brute înregistrate ale lucrărilor finalizate, din tot istoricul. Nu reprezintă încasări nete după credit sau rambursări.</p></div>
    <div className="rounded-xl border p-4" style={{background:'#fbf7ef',borderColor:'#ddd4c5'}}><h4 className="font-semibold">Marja operațională cumulată</h4><p>{record.value.margin.totalBani===null?'Incompletă: nu există costuri confirmate pentru toate lucrările finalizate.':formatBani(record.value.margin.totalBani)}</p><p className="text-sm">Subtotal confirmat: {formatBani(record.value.margin.knownConfirmedBani)} din {record.value.margin.confirmedJobs} lucrări. Cu estimări: {record.value.margin.estimatedJobs}. Cu date lipsă sau incomplete: {record.value.margin.missingOrIncompleteJobs}. Marja nu este profit contabil net.</p></div>
   </div>
   <form key={'tags'+record.user.id+record.classification.revision} className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void save(e.currentTarget,'classify');}}><label>Etichete separate prin virgulă<input className={inputClass} name="tags" maxLength={730} defaultValue={record.classification.tags.join(', ')} placeholder="nou, recurent, corporate" disabled={busy}/></label><label>Motivul clasificării<input className={inputClass} name="reason" maxLength={2000} required disabled={busy}/></label><button className="v2-btn v2-btn-primary" disabled={busy}>Salvează clasificarea</button></form>
   <form key={'restriction'+record.user.id+record.restriction.revision} className="rounded-xl border p-4 space-y-3" style={{background:'#fbf7ef',borderColor:'#ddd4c5'}} onSubmit={e=>{e.preventDefault();void save(e.currentTarget,'restrict');}}>
    <h4 className="font-bold">Restricții pentru cereri noi</h4>
    <p>Aplică numai după verificarea situației. Bifarea oprește tipul de cerere ales, inclusiv crearea vizitelor recurente noi. Debifarea îl permite din nou. Accesul la lucrările existente, sesizări, mesaje și operațiunile de plată rămâne disponibil; organizațiile Pro se administrează separat.</p>
    <label className="block"><input type="checkbox" name="blockBookings" defaultChecked={!!record.restriction.block_bookings} disabled={busy}/> Blochează rezervările noi Standard și Express, inclusiv ofertele asistate și vizitele recurente</label>
    <label className="block"><input type="checkbox" name="blockAssessments" defaultChecked={!!record.restriction.block_assessments} disabled={busy}/> Blochează cererile noi de evaluare</label>
    <label className="block">Motivul aplicării sau ridicării restricțiilor<textarea className={inputClass} name="reason" required maxLength={2000} disabled={busy}/></label>
    <button className="v2-btn v2-btn-primary" disabled={busy}>Salvează restricțiile</button>
   </form>
   <form className="space-y-2" onSubmit={e=>{e.preventDefault();void save(e.currentTarget,'note');}}><label className="block">Notă internă cu autor și dată<textarea className={inputClass} required name="note" maxLength={4000} disabled={busy}/></label><button className="v2-btn v2-btn-primary" disabled={busy}>Adaugă nota internă</button></form>
   <p className="text-sm">Pagina {record.offset/50+1} din istorice. Fiecare categorie afișează maximum 50 de înregistrări, cu paginare. Stările plății și referințele Stripe sunt doar citite; nu sunt recalculări contabile.</p>
   <div className="grid gap-3 lg:grid-cols-2">{([['Lucrări',record.jobs],['Cereri de evaluare',record.assessments],['Plăți și referințe Stripe',record.payments],['Sesizări',record.cases],['Evaluări',record.ratings],['Note interne',record.notes],['Istoricul restricțiilor',record.restrictions]] as const).map(([title,group])=><details key={title} className="rounded-xl border p-4" style={{background:'#fbf7ef',borderColor:'#ddd4c5'}}><summary>{title} · {group.rows.length}{group.hasMore?' +':''}</summary>{group.rows.map((r,i)=><dl key={i} className="my-3 border-t pt-2">{Object.entries(r as Record<string,unknown>).map(([k,v])=><div key={k} className="break-words"><dt className="inline font-semibold">{fieldNames[k]??k}: </dt><dd className="inline whitespace-pre-wrap">{v===null?'Neînregistrat':String(v)}</dd></div>)}</dl>)}{!group.rows.length&&<p>Nicio înregistrare pe această pagină.</p>}</details>)}</div>
   <div className="flex gap-2"><button className="v2-btn v2-btn-secondary" disabled={busy||record.offset===0} onClick={()=>void open(record.user.id,record.offset-50)}>Istoric anterior</button><button className="v2-btn v2-btn-secondary" disabled={busy||![record.jobs,record.assessments,record.payments,record.cases,record.ratings,record.notes,record.restrictions].some(g=>g.hasMore)} onClick={()=>void open(record.user.id,record.offset+50)}>Istoric următor</button></div>
  </article>}
 </section>;
}
const fieldNames:Record<string,string>={revision:'Revizie',block_bookings:'Rezervări blocate (1=da, 0=nu)',block_assessments:'Evaluări blocate (1=da, 0=nu)',reason:'Motiv',id:'Referință',job_id:'Lucrare',city:'Localitate',status:'Stare',mode:'Mod',price_gross:'Valoare lucrare (lei)',created_at:'Data înregistrării (UTC)',amount_gross:'Sumă plată (lei)',stripe_payment_intent_id:'Referință Stripe',refund_status:'Stare rambursare',category:'Categorie',stars:'Stele',moderation_status:'Moderare',body:'Notă',actor_id:'Autor (sesiune verificată)'};

const formatBani=(bani:number)=>new Intl.NumberFormat('ro-RO',{style:'currency',currency:'RON'}).format(bani/100);
