'use client';
import {useEffect,useState} from 'react';
import {COST_CODES,emptyManualEstimate,validateManualEstimate,calculateOperationalMargin,type Evidence,type DirectCost,type ManualEstimate} from '@/lib/operationalMargin';
const labels={materials:'Materiale',travel:'Deplasare',processor:'Procesare plată',other:'Alte costuri directe',fiscal:'Ajustare fiscală documentată'};
const money=(n:number)=>new Intl.NumberFormat('ro-RO',{style:'currency',currency:'RON'}).format(n/100);
type Revision={revision:number;assessment_version:number;definition:ManualEstimate;actor_id:string;created_at:string};
export function AdminManualEstimate({id,assessmentVersion}:{id:string;assessmentVersion:number}){
 const [open,setOpen]=useState(false);
 return <section className="design-panel"><button type="button" onClick={()=>setOpen(v=>!v)}>{open?'Închide calculul intern':'Pregătește oferta și marja'}</button>{open&&<Editor key={`${id}:${assessmentVersion}`} id={id} assessmentVersion={assessmentVersion}/>}</section>;
}
function Editor({id,assessmentVersion}:{id:string;assessmentVersion:number}){
 const [form,setForm]=useState(emptyManualEstimate),[history,setHistory]=useState<Revision[]>([]),[revision,setRevision]=useState(0),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch(`/api/admin/assessment-estimates?id=${encodeURIComponent(id)}`,{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{setHistory(d.estimates);if(d.estimates[0]){setForm(d.estimates[0].definition);setRevision(d.estimates[0].revision);}setLoaded(true);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[id]);
 let result:ReturnType<typeof calculateOperationalMargin>|null=null;
 try{result=calculateOperationalMargin(validateManualEstimate(form));}catch{/* A partial draft is not a valid financial result. */}
 function change(patch:Partial<ManualEstimate>){setForm(f=>({...f,...patch}));setMessage('');}
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/admin/assessment-estimates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,revision,assessmentVersion,definition:form})});const d=await r.json();if(!r.ok)throw Error(d.error);setRevision(d.estimate.revision);setHistory(h=>[d.estimate,...h]);setForm(d.estimate.definition);setMessage('Revizia internă a fost salvată. Clientului nu i-a fost transmisă o ofertă.');}catch(e){setError(e instanceof Error?e.message:'Salvare nereușită');}finally{setBusy(false);}}
 function evidenceEditor(label:string,value:Evidence,set:(e:Evidence)=>void){return <fieldset><legend>{label}</legend><div className="booking-fields"><label>Starea informației<select value={value.state} onChange={e=>{const state=e.target.value as Evidence['state'];set({...value,state,amountBani:state==='unknown'?null:value.amountBani,recordedAt:state==='unknown'?null:value.recordedAt??new Date().toISOString()});}}><option value="unknown">Necunoscut</option><option value="estimated">Estimat</option><option value="confirmed">Confirmat</option></select></label><label>Sumă în bani<input type="number" min="0" max="100000000" step="1" disabled={value.state==='unknown'} value={value.amountBani??''} onChange={e=>set({...value,amountBani:e.target.value===''?null:Number(e.target.value)})}/></label><label>Sursa / documentul justificativ<input maxLength={1000} value={value.source} onChange={e=>set({...value,source:e.target.value})}/></label>{value.state!=='unknown'&&<label>Data informației, cu fus orar<input required value={value.recordedAt??''} onChange={e=>set({...value,recordedAt:e.target.value})}/></label>}</div></fieldset>;}
 return <><h3>Ofertă manuală — calcul intern</h3><p>Componentele și costurile sunt vizibile numai în Admin. Salvarea nu confirmă o rezervare, nu trimite oferta clientului și nu pornește o plată.</p><p>100 bani = 1 leu. Completează sursa inclusiv pentru un cost confirmat de zero. Lasă costurile necunoscute ca necunoscute.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!loaded&&<p>Se încarcă reviziile…</p>}
 <form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy||!loaded}>
 {form.lines.map((line,i)=><div className="booking-fields" key={i}><label>Componenta {i+1}<input required maxLength={160} value={line.label} onChange={e=>change({lines:form.lines.map((l,j)=>i===j?{...l,label:e.target.value}:l)})}/></label><label>Valoare în bani<input required type="number" min="0" max="100000000" step="1" value={Number.isFinite(line.amountBani)?line.amountBani:''} onChange={e=>change({lines:form.lines.map((l,j)=>i===j?{...l,amountBani:e.target.value===''?NaN:Number(e.target.value)}:l)})}/></label><button type="button" disabled={form.lines.length===1} onClick={()=>change({lines:form.lines.filter((_,j)=>j!==i)})}>Elimină componenta {i+1}</button></div>)}
 <button type="button" disabled={form.lines.length>=20} onClick={()=>change({lines:[...form.lines,{label:'',amountBani:0}]})}>Adaugă componentă</button>
 <label>Reducere suportată de platformă, în bani<input required type="number" min="0" step="1" value={Number.isFinite(form.platformDiscountBani)?form.platformDiscountBani:''} onChange={e=>change({platformDiscountBani:e.target.value===''?NaN:Number(e.target.value)})}/></label>
 {evidenceEditor('Remunerația prestatorului',form.provider,provider=>change({provider}))}
 {COST_CODES.map(code=>{const cost=form.costs[code],update=(value:DirectCost)=>change({costs:{...form.costs,[code]:value}});return <div key={code}>{evidenceEditor(labels[code],cost,value=>update({...cost,...value}))}{code!=='fiscal'&&<><label>Suportator<select value={cost.bearer} onChange={e=>update({...cost,bearer:e.target.value as DirectCost['bearer'],includedInProvider:false})}><option value="platform">NITIDO, cost separat</option><option value="provider">Prestator</option></select></label><label><input type="checkbox" disabled={cost.bearer!=='provider'} checked={cost.includedInProvider} onChange={e=>update({...cost,includedInProvider:e.target.checked})}/>Inclus deja în remunerația prestatorului</label></>}</div>;})}
 <label>Motivul ofertei / al reviziei<textarea required maxLength={2000} value={form.reason} onChange={e=>change({reason:e.target.value})}/></label>
 {result?<section aria-live="polite"><h3>Marjă brută operațională</h3><p>Serviciu: {money(result.grossBani)} · Reducere: {money(result.platformDiscountBani)} · Datorat de client: {money(result.clientDueBani)}</p>{result.marginBani===null?<p>Calcul incomplet. Informații lipsă: {result.missing.map(k=>k==='provider'?'remunerația prestatorului':labels[k as keyof typeof labels]).join(', ')}.</p>:<p><strong>{money(result.marginBani)}</strong> · {result.status==='estimated'?'Calcul estimat':'Costuri declarate confirmate'}{result.marginBasisPoints===null?'':` · ${(result.marginBasisPoints/100).toFixed(2)}% din suma datorată de client`}</p>}<p>Pragul minim nu este configurat. Acest rezultat nu reprezintă profit net sau aprobare comercială.</p></section>:<p>Completează valorile și motivul pentru a calcula. Nu se presupune nicio cotă fiscală.</p>}
 <button type="submit" className="design-button" disabled={!result}>Salvează revizia internă</button>
 </fieldset></form><h3>Istoricul reviziilor</h3>{history.length?<ol>{history.map(r=><li key={r.revision}>Revizia {r.revision} · {new Date(r.created_at).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'})} · {r.definition.reason}<details><summary>Vezi calculul salvat</summary><p>Referință operator: {r.actor_id}</p><p>Total serviciu: {money(r.definition.lines.reduce((n,l)=>n+l.amountBani,0))}</p><p>Marjă: {calculateOperationalMargin(r.definition).marginBani===null?'incompletă':money(calculateOperationalMargin(r.definition).marginBani!)}</p></details></li>)}</ol>:<p>Nu există încă revizii salvate.</p>}</>;
}
