'use client';
import {useState} from 'react';
import type {JobRow} from '@/lib/types';
import {JOB_STATUS,money} from '@/lib/workspaceShared';
import {DesignIcon} from './DesignIcon';
type Payment={job_id:string;status:string;transfer_status:string;payout_status:string};
export function AdminOperations({jobs,payments}:{jobs:JobRow[];payments:Payment[]}){
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all'),[selected,setSelected]=useState('');
 const visible=jobs.filter(j=>(status==='all'||j.status===status)&&`${j.id} ${j.city} ${j.street}`.toLocaleLowerCase('ro').includes(query.toLocaleLowerCase('ro')));
 const job=visible.find(j=>j.id===selected)??visible[0];
 const payment=payments.find(p=>p.job_id===job?.id);
 return <section className="admin-operations-grid"><div className="design-panel"><div className="board-card-heading"><h2><DesignIcon name="briefcase"/>Monitorizare lucrări</h2><span>{visible.length} rezultate</span></div><div className="workspace-toolbar"><input aria-label="Caută lucrare, localitate sau adresă" placeholder="Caută lucrare, localitate, adresă…" value={query} onChange={e=>setQuery(e.target.value)} className="w-full rounded-lg border p-3"/><select aria-label="Filtrează starea lucrării" value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border p-3"><option value="all">Toate stările</option>{Object.entries(JOB_STATUS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div><div className="overflow-x-auto"><table className="workspace-table"><thead><tr><th>Lucrare</th><th>Programare</th><th>Stare</th><th>Total</th><th>Detalii</th></tr></thead><tbody>{visible.map(j=><tr key={j.id} className={job?.id===j.id?'admin-selected-row':''}><td><b>{j.city}</b><small>{j.street}</small></td><td>{j.scheduled_at?new Date(j.scheduled_at).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'Cât mai curând'}</td><td>{JOB_STATUS[j.status]}</td><td>{money(j.price_gross)}</td><td><button aria-label={`Vezi lucrarea ${j.id}`} onClick={()=>setSelected(j.id)} className="board-soft-button">Vezi <DesignIcon name="arrow" size={16}/></button></td></tr>)}</tbody></table>{!visible.length&&<p className="py-8 text-center text-slate-500">Nicio lucrare pentru filtrele selectate.</p>}</div></div><aside className="design-panel admin-job-inspector"><h2><DesignIcon name="search"/>Detaliile lucrării</h2>{job?<><p className="booking-muted">#{job.id}</p><h3>{job.street}</h3><p>{job.city} · {job.sqm} m²</p><dl><dt>Execuție</dt><dd>{JOB_STATUS[job.status]}</dd><dt>Durată estimată</dt><dd>{job.duration_minutes} minute</dd><dt>Valoarea lucrării</dt><dd>{money(job.price_gross)}</dd><dt>Plată</dt><dd>{payment?.status??'Nicio plată înregistrată'}</dd><dt>Transfer către firmă</dt><dd>{payment?.transfer_status??'—'}</dd><dt>Virament bancar</dt><dd>{payment?.payout_status??'—'}</dd></dl><a className="board-soft-button" href="#plati">Verifică plățile <DesignIcon name="arrow" size={18}/></a><a className="board-soft-button" href="#calitate">Verifică dovezile și calitatea <DesignIcon name="arrow" size={18}/></a></>:<p className="booking-muted">Selectează o lucrare pentru detalii.</p>}</aside></section>;
}
