'use client';
import {useEffect,useState} from 'react';
import type {MarginPolicy} from '@/lib/marginPolicy';
type Exception={offer_id:string;assessment_id:string;policy_revision:number;margin_bani:number;client_due_bani:number;exception_reason:string;created_at:string;offer_status:string};
const money=(n:number)=>new Intl.NumberFormat('ro-RO',{style:'currency',currency:'RON'}).format(n/100);
export function AdminMarginPolicy(){
 const [policy,setPolicy]=useState<MarginPolicy|null>(null),[amount,setAmount]=useState(''),[percent,setPercent]=useState(''),[reason,setReason]=useState(''),[exceptions,setExceptions]=useState<Exception[]>([]),[enabled,setEnabled]=useState(false),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 function apply(d:{policy:MarginPolicy|null;exceptions:Exception[];enabled:boolean}){setPolicy(d.policy);setAmount(d.policy?.min_bani==null?'':String(d.policy.min_bani));setPercent(d.policy?.min_basis_points==null?'':String(d.policy.min_basis_points));setExceptions(d.exceptions);setEnabled(d.enabled);setLoaded(true);}
 useEffect(()=>{const c=new AbortController();fetch('/api/admin/margin-policy',{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{if(!c.signal.aborted)apply(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[]);
 async function reload(){const r=await fetch('/api/admin/margin-policy',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);apply(d);}
 async function save(){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/margin-policy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:policy?.revision??0,minBani:amount===''?null:Number(amount),minBasisPoints:percent===''?null:Number(percent),reason})}),d=await r.json();if(!r.ok)throw Error(d.error);await reload();setReason('');setMessage('Regula a fost salvată. Ofertele deja publicate își păstrează decizia și pragul istoric.');}catch(e){setError(e instanceof Error?e.message:'Salvare nereușită');}finally{setBusy(false);}}
 return <section className="design-panel"><h2>Controlul marjei ofertelor manuale</h2><p>Configurează minimul valoric, minimul procentual sau ambele. Când sunt completate ambele, oferta trebuie să le respecte pe amândouă. O excepție necesită justificare înainte de publicare.</p><p>100 bani = 1 leu. 100 puncte de bază = 1%. Câmpul gol dezactivează doar acel prag; zero reprezintă un prag explicit de zero. Nu este presupusă nicio valoare comercială.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{!enabled&&<p>Configurarea este disponibilă numai în sandbox activat.</p>}<form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={!loaded||!enabled||busy}><legend>{policy?`Regula curentă: revizia ${policy.revision}`:'Praguri neconfigurate'}</legend><label>Marjă minimă în bani<input type="number" min={0} max={100000000} step={1} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Marjă minimă în puncte de bază<input type="number" min={0} max={10000} step={1} value={percent} onChange={e=>setPercent(e.target.value)}/></label><label>Motivul configurării<textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="submit" className="design-button">Salvează regula de marjă</button></fieldset></form><button type="button" disabled={busy} onClick={()=>void reload().then(()=>setError('')).catch(e=>setError(e.message))}>Reîncarcă regula și raportul</button><h3>Oferte publicate sub prag</h3><p>Ultimele 200 de excepții. Acesta este un raport al ofertelor, nu al comenzilor plătite și nici un calcul de profit net.</p>{exceptions.length?<ul>{exceptions.map(x=><li key={x.offer_id}>Cerere {x.assessment_id} · Ofertă {x.offer_id} · Marjă {money(x.margin_bani)} din {money(x.client_due_bani)} · Regulă {x.policy_revision}<p>{x.exception_reason}</p><p>{new Date(x.created_at).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'})} · Stare ofertă: {x.offer_status}</p></li>)}</ul>:<p>Nu există excepții înregistrate.</p>}</section>;
}
