'use client';
import {useEffect,useState} from 'react';
import {COST_CODES,type ManualEstimate,type Evidence,type DirectCost} from '@/lib/operationalMargin';
import type {jobCostReport} from '@/lib/jobActualCosts';
type Report=NonNullable<ReturnType<typeof jobCostReport>>;
const money=(n:number|null)=>n===null?'Necunoscut':new Intl.NumberFormat('ro-RO',{style:'currency',currency:'RON'}).format(n/100);
const labels={provider:'Remunerația prestatorului',materials:'Materiale',travel:'Deplasare',processor:'Procesare plată',other:'Alte costuri',fiscal:'Ajustare fiscală documentată'};
export function AdminJobCosts({offerId}:{offerId:string}){
 const [report,setReport]=useState<Report|null>(null),[form,setForm]=useState<ManualEstimate|null>(null),[enabled,setEnabled]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 const url=`/api/admin/job-costs?offerId=${encodeURIComponent(offerId)}`;
 function apply(r:Report|null){setReport(r);setForm(r?{...(r.history[0]?.definition??r.initial),reason:''}:null);setLoaded(true);}
 useEffect(()=>{const c=new AbortController();fetch(url,{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{if(!c.signal.aborted){apply(d.report);setEnabled(d.enabled);}}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort();},[url]);
 async function refresh(){setBusy(true);setError('');try{const r=await fetch(url,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);apply(d.report);setEnabled(d.enabled);}catch(e){setError(e instanceof Error?e.message:'Eroare la încărcare')}finally{setBusy(false)}}
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/admin/job-costs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({offerId,revision:report?.history[0]?.revision??0,definition:form})}),d=await r.json();if(!r.ok)throw Error(d.error);apply(d.report);}catch(e){setError(e instanceof Error?e.message:'Salvare nereușită')}finally{setBusy(false)}}
 function editor(key:'provider'|typeof COST_CODES[number]){
  if(!form)return null;const e=key==='provider'?form.provider:form.costs[key];
  const patch=(value:Partial<DirectCost>)=>setForm(f=>f?(key==='provider'?{...f,provider:{...f.provider,...value}}:{...f,costs:{...f.costs,[key]:{...f.costs[key],...value}}}):f);
  return <fieldset key={key} className="v2-card p-4"><legend>{labels[key]}</legend><label>Stare<select value={e.state} onChange={v=>patch(v.target.value==='unknown'?{state:'unknown',amountBani:null,recordedAt:null}:{state:'confirmed'})}><option value="unknown">Necunoscut — documente lipsă</option><option value="confirmed">Confirmat prin document / sursă</option></select></label>{e.state==='confirmed'&&<><label>Sumă, bani (100 bani = 1 leu)<input required type="number" min="0" max="100000000" step="1" value={e.amountBani??''} onChange={v=>patch({amountBani:v.target.value===''?null:Number(v.target.value)})}/></label><label>Sursa costului<textarea required maxLength={1000} value={e.source} onChange={v=>patch({source:v.target.value})}/></label><label>Data sursei<input required type="date" value={e.recordedAt?.slice(0,10)??''} onChange={v=>patch({recordedAt:v.target.value?`${v.target.value}T00:00:00.000Z`:null})}/></label></>}{key!=='provider'&&key!=='fiscal'&&<><label>Suportator<select value={(e as DirectCost).bearer} onChange={v=>patch({bearer:v.target.value as DirectCost['bearer'],includedInProvider:false})}><option value="platform">NITIDO — cost separat</option><option value="provider">Prestator</option></select></label><label><input type="checkbox" disabled={(e as DirectCost).bearer!=='provider'} checked={(e as DirectCost).includedInProvider} onChange={v=>patch({includedInProvider:v.target.checked})}/>Inclus deja în remunerația prestatorului</label></>}</fieldset>;
 }
 return <section className="design-panel"><h4>Cost estimat versus cost efectiv</h4><p>Raport intern pe lucrarea asociată. Suma clientului rămâne cea din oferta acceptată. Acest raport nu modifică încasarea, remunerația plătită sau rambursările și nu reprezintă profit contabil ori reconciliere Stripe.</p>{error&&<p role="alert">{error}</p>}<button type="button" disabled={busy} onClick={()=>void refresh()}>Reîncarcă raportul și formularul</button>{!loaded&&!error&&<p>Se încarcă raportul…</p>}{loaded&&!report&&<p>Clientul nu a creat încă o rezervare din această ofertă.</p>}{report&&form&&<><p>Lucrare: {report.jobId}. Costurile pot fi înregistrate după finalizarea execuției.</p><div className="overflow-x-auto" tabIndex={0} role="region" aria-label="Comparația costurilor"><table className="workspace-table"><thead><tr><th>Componentă</th><th>În oferta acceptată</th><th>Efectiv declarat</th></tr></thead><tbody>{(['provider',...COST_CODES] as const).map(key=>{const a:Evidence=key==='provider'?report.baseline.provider:report.baseline.costs[key],b=report.history[0]?.definition;return <tr key={key}><td>{labels[key]}</td><td>{money(a.amountBani)}{a.state==='estimated'?' · estimat':''}</td><td>{money(b?(key==='provider'?b.provider:b.costs[key]).amountBani:null)}</td></tr>})}</tbody></table></div><p>Marjă în oferta acceptată: {money(report.estimated.marginBani)}. Marjă cu costurile efective declarate: {money(report.actual?.marginBani??null)}. Diferență: {money(report.deltaBani)}.</p><p>Diferența pozitivă indică o marjă mai mare decât în calculul inițial. Costurile prestatorului nu se scad încă o dată din partea NITIDO. Orice cost necunoscut păstrează raportul incomplet.</p>{!enabled&&<p>Salvarea este dezactivată; istoricul rămâne disponibil.</p>}<form onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={busy||!enabled||report.jobStatus!=='completed'}><legend>Înregistrează o revizie de costuri efective</legend>{editor('provider')}{COST_CODES.map(editor)}<label>Motivul înregistrării sau corecției<textarea required maxLength={2000} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><button type="submit" className="design-button">Salvează costurile cu istoric</button></fieldset></form><h4>Istoricul costurilor declarate</h4>{report.history.map(r=><details key={r.revision}><summary>Revizia {r.revision} · {new Date(r.created_at).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'})}</summary><p>{r.definition.reason} · Operator: {r.actor_id}</p>{(['provider',...COST_CODES] as const).map(k=>{const e=k==='provider'?r.definition.provider:r.definition.costs[k];return <p key={k}>{labels[k]}: {money(e.amountBani)} · {e.source||'Sursă lipsă'} · {e.recordedAt?.slice(0,10)??'Dată lipsă'}{k==='provider'?'':` · Suportator: ${r.definition.costs[k].bearer==='platform'?'NITIDO':'prestator'}${r.definition.costs[k].includedInProvider?' · inclus în remunerație':''}`}</p>})}</details>)}</>}</section>;
}
