'use client';
import {useEffect,useState} from 'react';
import type {DeletionRequest} from '@/lib/accountDeletion';
type Queue={requests:(DeletionRequest & {userId:string;name:string;email:string|null;role:string})[];total:number;offset:number;hasMore:boolean};
export function AdminAccountDeletion(){
 const [queue,setQueue]=useState<Queue|null>(null),[offset,setOffset]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const controller=new AbortController();fetch('/api/admin/account-deletion?offset='+offset,{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setQueue(d);setError('');}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[offset,refresh]);
 async function review(form:HTMLFormElement,request:DeletionRequest){setBusy(true);setError('');try{const r=await fetch('/api/admin/account-deletion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:request.id,revision:request.revision,reason:String(new FormData(form).get('reason')??'')})}),d=await r.json();if(!r.ok)throw Error(d.error);setRefresh(x=>x+1);}catch(e){setError(e instanceof Error?e.message:'Preluare neconfirmată.');}finally{setBusy(false);}}
 return <section className="design-panel space-y-3 min-w-0" aria-label="Cereri de ștergere cont"><h2>Cereri de ștergere cont</h2><p>Registru de inițiere și preluare nominală. Preluarea pentru verificare nu șterge contul sau datele; executarea și confirmarea finală necesită procedura separată de procesare.</p>{error&&<p role="alert">{error}</p>}<button type="button" className="v2-btn v2-btn-secondary" disabled={busy} onClick={()=>setRefresh(x=>x+1)}>Actualizează cererile</button>{queue&&<><p>{queue.total} cereri înregistrate · maximum 50 pe pagină</p>{queue.requests.map(request=><article key={request.id} className="border rounded-xl p-3 space-y-2 break-words min-w-0"><h3 className="font-bold">{request.name} · {request.role==='firma'?'Prestator':'Client'}</h3><p className="break-all">{request.email??'Fără email'} · cont {request.userId}</p><p className="break-all">Cerere {request.id} · {new Date(request.createdAt).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'})}</p><p>{request.status==='under_review'?'Preluată pentru verificare; ștergerea nu este confirmată.':'În așteptarea preluării pentru verificare.'}</p>{request.status==='requested'&&<form onSubmit={e=>{e.preventDefault();void review(e.currentTarget,request);}} className="space-y-2"><label className="block">Motiv și referință internă de procesare<textarea name="reason" required maxLength={2000} disabled={busy} className="w-full min-w-0 rounded-xl border p-3"/></label><button className="v2-btn v2-btn-primary" disabled={busy}>Preia pentru verificare</button></form>}</article>)}<div className="flex flex-wrap gap-3"><button type="button" className="v2-btn v2-btn-secondary" disabled={offset===0||busy} onClick={()=>setOffset(x=>x-50)}>Pagina anterioară</button><button type="button" className="v2-btn v2-btn-secondary" disabled={!queue.hasMore||busy} onClick={()=>setOffset(x=>x+50)}>Pagina următoare</button></div></>}</section>;
}
