'use client';
import {useState} from 'react';
import {ASSESSMENT_STATUS,type Assessment} from '@/lib/assessmentShared';
import {CATALOG_CATEGORIES} from '@/lib/serviceCatalog';
const date=(v:string)=>new Date(v).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest',dateStyle:'medium',timeStyle:'short'});
export function AssessmentThread({request,admin=false,busy,onAction}:{request:Assessment;admin?:boolean;busy:boolean;onAction:(id:string,version:number,action:string,body:string)=>Promise<boolean>}){
 const [body,setBody]=useState(''),[decision,setDecision]=useState('needs_details');
 const open=['submitted','needs_details'].includes(request.status);
 return <article className="assessment-thread design-panel"><h3>{CATALOG_CATEGORIES.find(c=>c[0]===request.category)?.[1]} · {request.city}</h3><p><b>{ASSESSMENT_STATUS[request.status]}</b> · {date(request.createdAt)}{request.clientName?` · ${request.clientName}`:''}</p><p>{request.sqm} m² · {request.rooms} camere · {request.bathrooms} băi · Dificultate: {{light:'redusă',normal:'obișnuită',heavy:'ridicată'}[request.difficulty]}</p><p>Extraopțiuni solicitate: {request.appliances} aparate · {request.windowsSqm} m² geamuri · {request.linenSets} seturi lenjerie · {request.extraHours} ore suplimentare</p><p className="assessment-body">{request.notes}</p><ol className="assessment-messages">{request.messages.map(m=><li key={m.id}><b>{m.author==='admin'?'Echipa NITIDO':'Client'} · {date(m.createdAt)}</b><p className="assessment-body">{m.body}</p></li>)}</ol>{open&&<form onSubmit={async e=>{e.preventDefault();if(await onAction(request.id,request.version,admin?decision:'reply',body))setBody('')}}><fieldset disabled={busy}>{admin&&<label>Decizie<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="needs_details">Solicită completări</option><option value="reviewed">Trimite evaluarea și închide cererea</option><option value="declined">Nu putem prelua cererea</option></select></label>}<label>{admin?'Răspuns pentru client':'Completează cererea'}<textarea required minLength={1} maxLength={4000} rows={3} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="design-button" disabled={!body.trim()} type="submit">{busy?'Se salvează…':admin?'Salvează răspunsul în contul clientului':'Trimite completarea'}</button>{!admin&&<button type="button" onClick={()=>void onAction(request.id,request.version,'cancel','')}>Anulează cererea</button>}</fieldset></form>}<small>Cerere de evaluare, fără rezervare sau plată automată.</small></article>
}
