'use client';
import {useEffect,useState} from 'react';
type Evidence={version:number;enabled:boolean;photos:{id:string;url:string}[];review:{decision:string;current:boolean;reason?:string}|null};
export function AssessmentEvidence({id,admin=false}:{id:string;admin?:boolean}){
 const [data,setData]=useState<Evidence|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reason,setReason]=useState('');
 const url=`/api/assessments/evidence?id=${encodeURIComponent(id)}${admin?'&admin=true':''}`;
 useEffect(()=>{const c=new AbortController();fetch(url,{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[url]);
 async function load(){const r=await fetch(url,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}
 async function upload(file:File){setBusy(true);setError('');try{const form=new FormData();form.set('file',file);form.set('assessmentId',id);const r=await fetch('/api/uploads',{method:'POST',body:form}),d=await r.json();if(!r.ok)throw Error(d.error);await load();}catch(e){setError(e instanceof Error?e.message:'Încărcare nereușită');}finally{setBusy(false);}}
 async function review(decision:string){setBusy(true);setError('');try{const r=await fetch('/api/assessments/evidence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,version:data?.version,decision,reason})}),d=await r.json();if(!r.ok)throw Error(d.error);await load();setReason('');}catch(e){setError(e instanceof Error?e.message:'Verificare nereușită');}finally{setBusy(false);}}
 return <section className="design-panel"><h3>Fotografii pentru evaluare</h3><p>Adaugă imagini clare cu spațiul și zonele care necesită intervenție. Fotografiile sunt accesibile clientului proprietar și administratorilor autorizați. Pentru renovare, verificarea operatorului este obligatorie înainte de ofertare.</p>{error&&<p role="alert">{error}</p>}<button type="button" disabled={busy} onClick={()=>void load().then(()=>setError('')).catch(e=>setError(e.message))}>Actualizează fotografiile</button>{!admin&&<label>Încarcă o fotografie, maximum 8 MB; cel mult 10 per cerere<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={busy||!data?.enabled||(data?.photos.length??0)>=10} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label>}<ul>{data?.photos.map((p,i)=><li key={p.id}><a href={p.url} target="_blank" rel="noreferrer">Deschide fotografia {i+1}</a></li>)}</ul><p>{data?.review?.current?(data.review.decision==='approved'?'Fotografiile au fost verificate de operator.':'Operatorul solicită clarificări sau fotografii suplimentare.'):'Fotografiile pentru versiunea curentă nu au o verificare valabilă.'}</p>{admin&&<fieldset disabled={busy||!data?.enabled||!data.photos.length}><legend>Verificare operator</legend><p>Deschide fiecare fotografie. Confirmă că dovezile sunt suficiente și corespund cererii. După încărcări noi, actualizează cererea și calculul înainte de ofertare.</p><label>Motiv intern<textarea maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="button" disabled={!reason.trim()} onClick={()=>void review('approved')}>Confirmă verificarea fotografiilor</button><button type="button" disabled={!reason.trim()} onClick={()=>void review('rejected')}>Solicită completarea dovezilor</button>{data?.review?.reason&&<p>Ultima justificare: {data.review.reason}</p>}</fieldset>}</section>;
}
