'use client';
import {useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {DesignIcon} from './DesignIcon';
import {calcGrossPrice,calcDurationMinutes,SLOT_HOURS,type SpaceType} from '@/lib/pricing';
import type {EstimatorOption} from '@/lib/estimatorConfig';
export function BookingConfigurator({initial,options}:{initial:Record<string,string>;options:EstimatorOption[]}){
 const router=useRouter();
 const [type,setType]=useState<SpaceType>(options.find(o=>o.key===initial.spaceType)?.key??options[0]?.key??'apartament');
 const [area,setArea]=useState(initial.sqm&&Number(initial.sqm)>=10&&Number(initial.sqm)<=1000?initial.sqm:'80');
 const [city,setCity]=useState((initial.city??'București').slice(0,100));
 const [date,setDate]=useState(/^\d{4}-\d{2}-\d{2}$/.test(initial.date??'')?initial.date:'');
 const [hour,setHour]=useState('');
 const [mode,setMode]=useState(initial.mode==='express'?'express':'standard');
 const valid=Number.isInteger(Number(area))&&Number(area)>=10&&Number(area)<=1000;
 const price=valid?calcGrossPrice(type,Number(area)):null;
 const duration=valid?calcDurationMinutes(Number(area)):null;
 function next(){const params=new URLSearchParams({spaceType:type,sqm:area,city,mode});if(date){params.set('date',date);params.set('hour',hour)}router.push(`/client?${params}#sec-form`)}
 return <><section className="design-panel assessment-entry"><h2>Lucrarea ta necesită o evaluare?</h2><p>Pentru renovare, cerințe speciale sau suprafețe în afara calculatorului, descrie lucrarea înainte de a primi un preț.</p><Link className="design-button" href={`/client/evaluari?${new URLSearchParams({city,sqm:area})}`}>Solicită evaluare personalizată</Link></section><div className="booking-heading"><div><h1>Configurează curățenia</h1><p>Alege detaliile și programează serviciul în câțiva pași simpli.</p></div><ol className="booking-steps">{['Spațiu','Programare','Confirmare'].map((s,i)=><li key={s} className={i===0?'active':''}><span>{i+1}</span>{s}</li>)}</ol></div>
 <form className="booking-grid" onSubmit={e=>{e.preventDefault();next()}}><div className="booking-main"><section className="booking-property design-panel"><div className="booking-property-photo"><Image src="/design-v2/approved-living-room.webp" alt="" fill sizes="200px"/></div><div><h2>{options.find(o=>o.key===type)?.label}</h2><strong>{area||'—'} m²</strong><p><DesignIcon name="pin" size={18}/>{city||'Alege localitatea'}</p></div><a href="#booking-space">Modifică <DesignIcon name="arrow" size={18}/></a></section>
 <section className="design-panel" id="booking-space"><h2>1. Alege spațiul</h2><div className="booking-choice-grid">{options.map(o=><label className={`booking-choice ${type===o.key?'selected':''}`} key={o.key}><input type="radio" name="space" value={o.key} checked={type===o.key} onChange={()=>setType(o.key)}/><DesignIcon name={o.key==='birou'?'building':'home'} size={30}/><b>{o.label}</b><span>{o.key==='birou'?'Pentru un mediu de lucru îngrijit.':'Pentru un spațiu curat și primitor.'}</span></label>)}</div><div className="booking-fields"><label>Localitate<input required maxLength={100} value={city} onChange={e=>setCity(e.target.value)}/></label><label>Suprafață, m²<input type="number" required min={10} max={1000} step={1} value={area} onChange={e=>setArea(e.target.value)}/></label></div></section>
 <section className="design-panel"><h2>2. Alege data și intervalul</h2><p className="booking-muted">Adresa completă și instrucțiunile de acces se completează în cont.</p><div className="booking-fields"><label>Data preferată<input type="date" value={date} onChange={e=>{setDate(e.target.value);setHour('')}}/></label><label>Ora de începere<select value={hour} required={!!date} disabled={!date} onChange={e=>setHour(e.target.value)}><option value="">{date?'Selectează ora':'Cât mai curând'}</option>{SLOT_HOURS.map(h=><option key={h} value={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label></div><p className="booking-muted">Disponibilitatea firmei se confirmă la alocare.</p></section>
 <section className="design-panel"><h2>3. Alege modul de rezervare</h2><div className="booking-choice-grid booking-mode-grid">{[['standard','Standard','Alegi firma la prețul afișat.'],['express','Express','Prima firmă eligibilă care acceptă.']].map(([value,title,desc])=><label key={value} className={`booking-choice ${mode===value?'selected':''}`}><input type="radio" name="mode" value={value} checked={mode===value} onChange={()=>setMode(value)}/><DesignIcon name={value==='express'?'bolt':'calendar'} size={28}/><b>{title}</b><span>{desc}</span></label>)}</div></section></div>
 <aside className="booking-summary design-panel"><h2>Rezumatul rezervării</h2><p className="booking-muted">Verifică detaliile înainte de a continua.</p><div className="booking-summary-line"><DesignIcon name="home"/><div><b>{options.find(o=>o.key===type)?.label}</b><p>{area||'—'} m² · {city||'Localitate nespecificată'}</p></div></div><div className="booking-summary-line"><DesignIcon name="sparkles"/><div><b>Serviciu de curățenie</b><p>Conform tarifului activ</p></div><strong>{price??'—'} lei</strong></div><div className="booking-summary-line"><DesignIcon name="calendar"/><div><b>{date||'Cât mai curând'}</b><p>{date?(hour?`${hour.padStart(2,'0')}:00`:'Alege ora'):'În funcție de disponibilitate'}</p></div></div><div className="booking-total"><b>Total estimat</b><output aria-live="polite">{price??'—'} lei</output></div><div className="booking-included"><b>Fiecare etapă, la vedere</b><p><DesignIcon name="check" size={17}/>Preț verificat înainte de publicare</p><p><DesignIcon name="check" size={17}/>Alegerea firmei în modul Standard</p><p><DesignIcon name="check" size={17}/>Dovezi foto la finalizarea lucrării</p>{duration&&<p><DesignIcon name="clock" size={17}/>Durată estimată: {Math.floor(duration/60)} h {duration%60||''}</p>}</div><p className="booking-muted">Eventualul credit eligibil se aplică în cont. Nu se încasează bani la acest pas.</p><button type="submit" disabled={!valid||!options.length} className="design-button">Continuă <DesignIcon name="arrow"/></button><small><DesignIcon name="shield" size={16}/>Confirmare și plată din contul tău</small></aside></form></>;
}
