'use client';
import {useState} from 'react';
import Link from 'next/link';
import type {JobRow} from '@/lib/types';
import {businessCalendarJobs,businessJobOnDay,businessJobEnd,type BusinessLocation} from '@/lib/businessCalendar';
import {calendarDays,serviceDate,shiftCalendarDate,type CalendarView} from '@/lib/calendarView';
import {JOB_STATUS} from '@/lib/workspaceShared';
export function BusinessCalendar({jobs,locations,links,firms}:{jobs:JobRow[];locations:BusinessLocation[];links:{property_id:string;job_id:string}[];firms:{id:string;name:string}[]}){
 const [anchor,setAnchor]=useState(()=>serviceDate(new Date())),[view,setView]=useState<CalendarView>('week'),[location,setLocation]=useState(''),[firm,setFirm]=useState(''),[status,setStatus]=useState('');
 const rows=businessCalendarJobs(jobs,locations,links,{location,firm,status});const days=calendarDays(anchor,view);
 const label=(day:string)=>new Date(day+'T12:00:00Z').toLocaleDateString('ro-RO',{timeZone:'UTC',day:'numeric',month:'short'});
 const time=(v:string)=>new Date(v).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
 const pending=rows.filter(r=>!businessJobEnd(r.job));const visible=rows.filter(r=>days.some(d=>businessJobOnDay(r.job,d)));
 const card=(r:typeof rows[number])=><article className="business-calendar-job" key={r.job.id}><b>{r.locations.map(p=>p.name).join(' · ')}</b><span>{JOB_STATUS[r.job.status]??r.job.status}</span><small>{r.job.accepted_firm_id?firms.find(f=>f.id===r.job.accepted_firm_id)?.name??'Firmă alocată':'Fără firmă alocată'}</small>{businessJobEnd(r.job)&&<small>{time(r.job.scheduled_at!)} – {time(businessJobEnd(r.job)!)}</small>}<small>{r.job.city} · {r.job.sqm} m²</small><Link href={`/client?jobId=${encodeURIComponent(r.job.id)}#sec-lucrari`}>Deschide lucrarea</Link></article>;
 return <section id="calendar-business" className="design-panel mt-6"><h2 className="font-bold text-xl">Calendarul tuturor locațiilor</h2><p className="text-sm text-muted mt-2">Programările asociate locațiilor Business. Orele sunt afișate pentru România; intervalul include durata estimată a lucrării. Starea lucrării nu confirmă încasarea plății.</p><div className="schedule-view-controls"><div role="group" aria-label="Vizualizare calendar Business">{([['day','Zi'],['week','Săptămână'],['month','Lună']] as const).map(([key,label])=><button key={key} aria-pressed={view===key} onClick={()=>setView(key)}>{label}</button>)}</div><label>Data<input type="date" value={anchor} onChange={e=>{if(/^\d{4}-\d{2}-\d{2}$/.test(e.target.value)&&Number.isFinite(Date.parse(e.target.value)))setAnchor(e.target.value)}}/></label><label>Locația<select value={location} onChange={e=>setLocation(e.target.value)}><option value="">Toate locațiile Business</option>{locations.filter(p=>p.kind==='business').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Firma<select value={firm} onChange={e=>setFirm(e.target.value)}><option value="">Toate firmele</option><option value="unassigned">Fără firmă alocată</option>{firms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Toate stările</option>{Object.entries(JOB_STATUS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><div className="workspace-toolbar"><button className="v2-btn v2-btn-secondary" aria-label="Intervalul anterior Business" onClick={()=>setAnchor(d=>shiftCalendarDate(d,-1,view))}>Anterior</button><button className="v2-btn v2-btn-secondary" onClick={()=>setAnchor(serviceDate(new Date()))}>Astăzi</button><button className="v2-btn v2-btn-secondary" aria-label="Intervalul următor Business" onClick={()=>setAnchor(d=>shiftCalendarDate(d,1,view))}>Următor</button><span>{label(days[0])} – {label(days[days.length-1])} · {visible.length} lucrări</span></div><div className={`business-calendar-days ${view==='day'?'single-day':''}`}>{days.map(day=><section key={day}><h3>{label(day)}</h3>{rows.filter(r=>businessJobOnDay(r.job,day)).map(card)}{!rows.some(r=>businessJobOnDay(r.job,day))&&<p className="text-sm text-muted">Fără programări</p>}</section>)}</div>{pending.length>0&&<div className="mt-6"><h3 className="font-bold">Fără interval confirmat · {pending.length}</h3><p className="text-sm text-muted">Aceste lucrări respectă filtrele de locație, firmă și status, dar nu pot fi plasate într-o zi a calendarului.</p><div className="business-calendar-days mt-3">{pending.map(card)}</div></div>}</section>
}
