'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {DesignIcon} from './DesignIcon';
import {money} from '@/lib/workspaceShared';
type Approval={id:string;property_id:string;date:string;note:string;price_bani:number;status:string;requester_name:string};
export function BusinessApprovals({properties}:{properties:{id:string;name:string}[]}){
 const [approvals,setApprovals]=useState<Approval[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState('');
 const lock=useRef(false);
 const refresh=useCallback(async()=>{const r=await fetch('/api/collaboration');if(!r.ok)throw Error('Aprobările nu au putut fi încărcate.');const d=await r.json();setApprovals(d.approvals??[])},[]);
 useEffect(()=>{let live=true;fetch('/api/collaboration').then(async r=>{if(!r.ok)throw Error('Aprobările nu au putut fi încărcate.');return r.json()}).then(d=>{if(live)setApprovals(d.approvals??[])}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[]);
 async function decide(id:string,approve:boolean){if(lock.current)return;lock.current=true;setBusy(id);setError('');setNotice('');try{const r=await fetch('/api/collaboration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'approval.decide',id,approve,note:''})});const d=await r.json();if(!r.ok)throw Error(d.error??'Decizia nu a putut fi salvată.');setNotice(approve?'Solicitare aprobată. Rezervarea se creează separat, din Aprobări și membri.':'Solicitare respinsă.');await refresh()}catch(e){setError(e instanceof Error?e.message:'Eroare de conexiune.')}finally{lock.current=false;setBusy('')}}
 const pending=approvals.filter(a=>a.status==='pending'&&properties.some(p=>p.id===a.property_id));
 return <section className="design-panel business-approvals" id="aprobari"><div className="board-card-heading"><h2><DesignIcon name="check"/>Aprobări în așteptare</h2><span className="eyebrow-pill">{pending.length}</span></div><p className="booking-muted">Solicitări pentru locațiile afișate.</p>{error&&<p role="alert" className="workspace-error">{error} <button className="underline" onClick={()=>void refresh().then(()=>setError('')).catch(e=>setError(e.message))}>Reîncearcă</button></p>}{notice&&<p role="status" className="workspace-notice">{notice}</p>}{loading?<p role="status">Se încarcă aprobările…</p>:!pending.length&&!error?<p className="booking-muted">Nu ai solicitări în așteptare pentru aceste locații.</p>:pending.map(a=><article className="business-approval-card" key={a.id}><div className="board-card-heading"><b>Curățenie solicitată</b><strong>{money(a.price_bani/100)}</strong></div><p>{properties.find(p=>p.id===a.property_id)?.name}</p><p className="booking-muted">{a.date.split('-').reverse().join('.')} · {a.requester_name}</p>{a.note&&<p>{a.note}</p>}<div className="business-approval-actions"><button disabled={!!busy} className="v2-btn v2-btn-primary" onClick={()=>void decide(a.id,true)}>{busy===a.id?'Se salvează…':'Aprobă'}</button><button disabled={!!busy} className="v2-btn v2-btn-secondary" onClick={()=>void decide(a.id,false)}>Respinge</button></div></article>)}<Link href="/colaborari" className="board-soft-button">Aprobări și membri <DesignIcon name="arrow" size={18}/></Link></section>;
}
