'use client';
import {useState} from 'react';
import type {ExecutionReport} from '@/lib/business';
import {money} from '@/lib/workspaceShared';
export function BusinessExecutionReport(){
 const [month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)),[report,setReport]=useState<ExecutionReport|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setBusy(true);setError('');setReport(null);try{const r=await fetch(`/api/reports/execution?month=${encodeURIComponent(month)}`);const d=await r.json();if(!r.ok)throw new Error(d.error||'Raport indisponibil');setReport(d.report)}catch(e){setError(e instanceof Error?e.message:'Eroare de conexiune')}finally{setBusy(false)}}
 return <section className="design-panel mt-6"><h2 className="font-bold text-xl">Raport lunar de execuție</h2><p className="text-sm text-muted mt-2">Lucrările finalizate din întregul cont client, inclusiv cele fără locație asociată. Luna se calculează după data finalizării în UTC. Valorile lucrărilor nu reprezintă confirmări de încasare, solduri bancare sau facturi.</p><div className="workspace-toolbar"><label>Luna<input className="booking-input" type="month" value={month} disabled={busy} onChange={e=>{setMonth(e.target.value);setReport(null);setError('')}}/></label><button className="v2-btn v2-btn-primary" disabled={busy||!month} onClick={()=>void load()}>{busy?'Se încarcă…':'Generează raportul'}</button></div>{error&&<p role="alert" className="workspace-error">{error}</p>}{report&&<><p role="status">{report.totalJobs} lucrări finalizate · Valoare totală: {money(report.totalAmount)}</p><div className="overflow-x-auto"><table className="workspace-table"><thead><tr><th>Lucrare</th><th>Finalizată (UTC)</th><th>Adresă</th><th>Firmă</th><th>Valoare RON</th></tr></thead><tbody>{report.rows.map(r=><tr key={r.jobId}><td>{r.jobId}</td><td>{r.completedAt??'—'}</td><td>{r.city} · {r.street}</td><td>{r.firmName??'—'}</td><td>{money(r.priceGross)}</td></tr>)}</tbody></table></div>{!report.rows.length&&<p className="mt-3">Nicio lucrare finalizată în luna selectată.</p>}<a className="v2-btn v2-btn-secondary mt-4" href={`/api/reports/execution?month=${encodeURIComponent(month)}&format=csv`} download>Descarcă raportul CSV</a><p className="text-sm text-muted mt-2">Exportul aplică aceeași lună. Dacă datele se schimbă între generare și descărcare, exportul reflectă situația actualizată.</p></>}</section>
}
