'use client';
import {useState} from 'react';
interface Firm{id:string;name:string;configured:boolean;eligible:boolean;reasons:string[];coverageCity:string;activeTeams:number;availableTeams:number|null}
export function CatalogFirmCapacity({category}:{category:string}){
 const [city,setCity]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[firms,setFirms]=useState<Firm[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[checked,setChecked]=useState(false),[checkedQuery,setCheckedQuery]=useState('');
 function query(){const p=new URLSearchParams({key:category,city});if(start||end){if(!start||!end)throw new Error('Completează începutul și sfârșitul intervalului.');p.set('start',new Date(start).toISOString());p.set('end',new Date(end).toISOString())}return p.toString()}
 async function load(){const q=query(),r=await fetch(`/api/admin/catalog/capacity?${q}`),d=await r.json();if(!r.ok)throw new Error(d.error||'Verificare nereușită');setFirms(d.firms);setChecked(true);setCheckedQuery(q)}
 async function check(){setBusy(true);setError('');try{await load()}catch(e){setError(e instanceof Error?e.message:'Verificare nereușită');setChecked(false)}finally{setBusy(false)}}
 async function toggle(f:Firm){setBusy(true);setError('');try{const r=await fetch('/api/admin/catalog/capacity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:category,firmId:f.id,enabled:!f.configured})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Salvare nereușită');await load()}catch(e){setError(e instanceof Error?e.message:'Salvare nereușită');setChecked(false)}finally{setBusy(false)}}
 let stale=true;try{stale=query()!==checkedQuery}catch{}
 return <section className="catalog-capacity"><h3>Firme asociate și capacitate</h3><p className="booking-muted">Asocierea stabilește ce categorie poate presta firma. Verificarea este informativă la momentul cererii și nu rezervă o echipă. Include timpul de deplasare în intervalul verificat.</p><form onSubmit={e=>{e.preventDefault();void check()}}><fieldset disabled={busy}><div className="booking-fields"><label>Localitate<input required maxLength={100} value={city} onChange={e=>setCity(e.target.value)}/></label><label>Început (ora locală din browser)<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Sfârșit, inclusiv deplasarea<input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><button className="design-button" type="submit">{busy?'Se verifică…':'Verifică firmele'}</button></fieldset></form>{error&&<p role="alert">{error}</p>}{checked&&stale&&<p role="status">Criteriile s-au modificat. Verifică din nou pentru rezultate actualizate.</p>}{checked&&!stale&&<><p role="status">{firms.filter(f=>f.eligible).length} firme eligibile {start?'în intervalul verificat':'pentru categorie și localitate; intervalul nu a fost verificat'}.</p>{firms.map(f=><article key={f.id} className="catalog-firm"><div><b>{f.name}</b><p>{f.coverageCity} · {f.activeTeams} echipe active{f.availableTeams!==null?` · ${f.availableTeams} echipe fără suprapuneri`:''}</p><p>{f.eligible?'Criteriile verificate sunt îndeplinite':f.reasons.join(' · ')}</p></div><button disabled={busy} type="button" onClick={()=>void toggle(f)}>{f.configured?'Retrage asocierea':'Asociază categoria'}</button></article>)}{!firms.length&&<p>Nu există firme înregistrate.</p>}</>}</section>
}
