'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {CATALOG_CATEGORIES} from '@/lib/serviceCatalog';
import type {Assessment,AssessmentInput} from '@/lib/assessmentShared';
import {AssessmentThread} from './AssessmentThread';
export function ClientAssessments({initialCity='',initialSqm=100}:{initialCity?:string;initialSqm?:number}){
 const [input,setInput]=useState<AssessmentInput>({category:'general',city:initialCity,sqm:initialSqm,rooms:0,bathrooms:0,difficulty:'normal',notes:'',appliances:0,windowsSqm:0,linenSets:0,extraHours:0}),[requests,setRequests]=useState<Assessment[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const retry=useRef<{payload:string;key:string}|null>(null);
 const load=useCallback(async()=>{const r=await fetch('/api/assessments'),d=await r.json();if(!r.ok)throw new Error(d.error||'Cererile nu pot fi încărcate');setRequests(d.requests)},[]);
 useEffect(()=>{const controller=new AbortController();fetch('/api/assessments',{signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Cererile nu pot fi încărcate');return d}).then(d=>{if(!controller.signal.aborted)setRequests(d.requests)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[]);
 async function post(value:unknown){const r=await fetch('/api/assessments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Cererea nu a putut fi salvată');return d}
 async function create(){setBusy(true);setError('');setNotice('');try{const payload=JSON.stringify(input);if(retry.current?.payload!==payload)retry.current={payload,key:crypto.randomUUID()};await post({action:'create',input,requestKey:retry.current.key});setNotice('Cererea a fost înregistrată. Răspunsul va apărea aici, în cont.');setInput(i=>({...i,notes:''}));await load()}catch(e){setError(e instanceof Error?e.message:'Eroare la salvare')}finally{setBusy(false)}}
 async function action(id:string,version:number,action:string,body:string){setBusy(true);setError('');try{await post({id,version,action,body});await load();return true}catch(e){setError(e instanceof Error?e.message:'Eroare la salvare');return false}finally{setBusy(false)}}
 function patch(p:Partial<AssessmentInput>){setInput(i=>({...i,...p}));setNotice('')}
 return <div className="assessment-workspace"><h1>Solicită o evaluare</h1><p>Descrie lucrarea care are nevoie de o analiză înainte de rezervare. Echipa NITIDO verifică detaliile, serviciile și posibilitatea de preluare.</p><p className="booking-muted">Nu se calculează un preț final și nu se autorizează cardul la trimiterea acestei cereri.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<form className="design-panel" onSubmit={e=>{e.preventDefault();void create()}}><fieldset disabled={busy}><div className="booking-fields"><label>Serviciu solicitat<select value={input.category} onChange={e=>patch({category:e.target.value})}>{CATALOG_CATEGORIES.map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label>Localitate<input required maxLength={100} value={input.city} onChange={e=>patch({city:e.target.value})}/></label>{([['sqm','Suprafață, m²',1,1000000],['rooms','Număr camere',0,10000],['bathrooms','Număr băi',0,10000]] as const).map(([key,label,min,max])=><label key={key}>{label}<input required type="number" min={min} max={max} step={1} value={input[key]} onChange={e=>patch({[key]:Number(e.target.value)})}/></label>)}<label>Dificultate declarată<select value={input.difficulty} onChange={e=>patch({difficulty:e.target.value as AssessmentInput['difficulty']})}><option value="light">Redusă</option><option value="normal">Obișnuită</option><option value="heavy">Ridicată / murdărie persistentă</option></select></label></div><h2>Extraopțiuni de evaluat</h2><div className="booking-fields">{([['appliances','Număr aparate',1000000],['windowsSqm','Geamuri, m²',1000000],['linenSets','Seturi lenjerie',1000000],['extraHours','Ore suplimentare',10000]] as const).map(([key,label,max])=><label key={key}>{label}<input required type="number" min={0} max={max} step={1} value={input[key]} onChange={e=>patch({[key]:Number(e.target.value)})}/></label>)}</div><label>Ce trebuie făcut? Materiale sensibile, acces, preferințe și perioada dorită<textarea required maxLength={4000} rows={5} value={input.notes} onChange={e=>patch({notes:e.target.value})}/></label><p className="booking-muted">Detaliile sunt vizibile doar ție și echipei de administrare NITIDO. Nu introduce parole sau coduri de acces.</p><button className="design-button" type="submit" disabled={!input.notes.trim()||!input.city.trim()}>{busy?'Se trimite…':'Trimite spre evaluare'}</button></fieldset></form><div className="section-heading"><h2>Cererile tale</h2><button disabled={busy} onClick={()=>void load().then(()=>setError('')).catch(e=>setError(e.message))}>Actualizează</button></div><p className="booking-muted">Ultimele 200 de cereri. Răspunsurile sunt afișate în cont.</p>{loading?<p>Se încarcă…</p>:requests.length?requests.map(r=><AssessmentThread key={r.id} request={r} busy={busy} onAction={action}/>):<p>Nu ai cereri de evaluare înregistrate.</p>}</div>
}
