"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {TeamExecutionCard} from './TeamExecutionCard';
import {useCurrentUser} from '@/lib/useCurrentUser';
import {WorkspaceNav} from './WorkspaceNav';
import {money} from '@/lib/workspaceShared';
import {Logo,inputClass} from './ui';
interface Resource {id:string;kind:string;name:string;role:string}
interface Property extends Resource {budget_bani:number;budget_enforced:number;sqm:number;city:string;street:string}
interface Approval {id:string;property_id:string;date:string;note:string;requester_name:string;price_bani:number;status:string;decision_note:string}
interface Member {id:string;resource_id:string;name?:string;email:string;role:string}
interface Job {id:string;street:string;city:string;sqm:number;status:string;scheduled_at:string;details:string;checklist:{item_key:string;done:number}[];photos:{id:string;proof_type:string}[];report:{note:string;submitted_at:string}|null}
interface Snapshot {resources:Resource[];members:Member[];invites:Member[];properties:Property[];approvals:Approval[];jobs:Job[]}
const empty:Snapshot={resources:[],members:[],invites:[],properties:[],approvals:[],jobs:[]};
export function CollaborationWorkspace({mode}:{mode:'team'|'business'|'invite'}){
 const {user,loading}=useCurrentUser();const [data,setData]=useState(empty),[busy,setBusy]=useState(false),[pending,setPending]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[resource,setResource]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState('manager'),[link,setLink]=useState(''),[date,setDate]=useState(''),[note,setNote]=useState(''),[token,setToken]=useState(''),[decisionNotes,setDecisionNotes]=useState<Record<string,string>>({});
 const refresh=useCallback(async()=>{try{const r=await fetch('/api/collaboration');const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}catch(e){setError(e instanceof Error?e.message:'Conexiune indisponibilă')}finally{setPending(false)}},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- authenticated initial request and invitation URL
 useEffect(()=>{if(user)void refresh();setToken(new URLSearchParams(window.location.search).get('token')??'')},[user,refresh]);
 const requestRef=useRef<{signature:string;key:unknown}|null>(null);
 async function act(body:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{if(body.action==='approval.request'){const signature=JSON.stringify({...body,requestKey:undefined});if(requestRef.current?.signature!==signature)requestRef.current={signature,key:body.requestKey};body={...body,requestKey:requestRef.current.key}}const r=await fetch('/api/collaboration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);if(body.action==='approval.request')requestRef.current=null;await refresh();setNotice('Modificarea a fost salvată.');return d}catch(e){setError(e instanceof Error?e.message:'Operație nereușită');return null}finally{setBusy(false)}}
 async function upload(jobId:string,proofType:string,file:File){setBusy(true);setError('');try{const form=new FormData();form.append('file',file);form.append('jobId',jobId);form.append('proofType',proofType);const r=await fetch('/api/uploads',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw Error(d.error);await refresh();setNotice('Fotografia a fost salvată.')}catch(e){setError(e instanceof Error?e.message:'Încărcare nereușită')}finally{setBusy(false)}}
 if(loading)return <main className="p-10" role="status">Se încarcă…</main>;
 if(!user)return <main className="max-w-xl mx-auto p-10"><Logo/><h1 className="workspace-title mt-8">Intră în spațiul tău</h1><p className="my-5">Folosește contul cu adresa de email din invitație.</p><Link className="v2-btn v2-btn-primary" href={`/login?next=${encodeURIComponent(mode==='invite'?`/invitatie?token=${token}`:'/colaborari')}`}>Autentificare</Link></main>;
 const owned=data.resources.filter(r=>r.role==='owner'&&r.kind===(mode==='team'?'team':'property'));
 const statuses:Record<string,string>={pending:'Așteaptă aprobare',approved:'Aprobată · de rezervat',rejected:'Respinsă',fulfilled:'Rezervare creată'};
 return <div className={`operations-layout approved-operations ${mode==='team'?'team-execution-workspace':''}`}><aside className="operations-sidebar"><Logo/><WorkspaceNav role={user.role}/><p className="sidebar-user">{user.name}</p></aside><main className="operations-main"><header className="section-heading"><div><p className="v2-eyebrow">NITIDO · COLABORARE</p><h1 className="workspace-title">{mode==='team'?'Lucrările echipei':mode==='invite'?'Acceptă invitația':'Aprobări și acces pe locații'}</h1><p className="text-muted mt-3">{mode==='team'?'Acces individual, verificări și raport de execuție.':'Gestionează accesul și solicitările, cu decizie înainte de rezervare.'}</p></div></header>
 {error&&<p role="alert" className="workspace-error">{error}</p>}{notice&&<p role="status" className="workspace-notice">{notice}</p>}
 {mode==='invite'?<form className="v2-card p-6" onSubmit={async e=>{e.preventDefault();const d=await act({action:'invite.accept',token});if(d)window.location.assign(d.kind==='team'?'/echipa':'/colaborari')}}><label>Codul invitației<input className={inputClass} required value={token} onChange={e=>setToken(e.target.value)}/></label><p className="text-muted my-4">Conectat ca {user.email}. Invitația este valabilă 7 zile.</p><button disabled={busy} className="v2-btn v2-btn-primary">Acceptă și deschide spațiul</button></form>:pending?<p role="status">Se încarcă datele…</p>:<>
 {!!owned.length&&<section className="v2-card p-6 mb-6"><h2 className="text-xl font-bold mb-4">Invită un coleg</h2><form className="form-grid" onSubmit={async e=>{e.preventDefault();const r=owned.find(r=>r.id===resource);if(!r)return;const d=await act({action:'invite.create',kind:r.kind,resourceId:r.id,email,role:r.kind==='team'?'worker':role});if(d)setLink(`${window.location.origin}/invitatie?token=${d.token}`)}}><label>{mode==='team'?'Echipă':'Locație'}<select className={inputClass} required value={resource} onChange={e=>setResource(e.target.value)}><option value="">Alege…</option>{owned.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Email coleg<input type="email" required className={inputClass} value={email} onChange={e=>setEmail(e.target.value)}/></label>{mode==='business'&&<label>Permisiune<select className={inputClass} value={role} onChange={e=>setRole(e.target.value)}><option value="manager">Manager · solicită lucrări</option><option value="viewer">Vizualizare</option></select></label>}<button disabled={busy} className="v2-btn v2-btn-primary">Creează invitația</button></form>{link&&<div className="workspace-notice mt-4"><label>Link de transmis colegului<input readOnly className={inputClass} value={link} onFocus={e=>e.target.select()}/></label><button className="v2-btn v2-btn-secondary mt-2" onClick={()=>void navigator.clipboard.writeText(link).then(()=>setNotice('Link copiat.')).catch(()=>setError('Selectează și copiază linkul din câmp.'))}>Copiază linkul</button><p className="text-sm mt-2">Invitația funcționează numai pentru adresa indicată. Emailul nu se trimite automat.</p></div>}</section>}
 {owned.map(r=><section key={r.id} className="v2-card p-5 mb-4"><h2 className="font-bold">{r.name} · acces</h2>{data.members.filter(m=>m.resource_id===r.id).map(m=><div className="flex flex-wrap justify-between items-center gap-3 py-3 border-b border-line" key={m.id}><p>{m.name} · {m.email}<small className="block text-muted">{m.role==='worker'?'Angajat':m.role==='manager'?'Manager':'Vizualizare'}</small></p><button disabled={busy} className="v2-btn v2-btn-secondary" onClick={()=>void act({action:'member.revoke',id:m.id})}>Revocă accesul</button></div>)}{data.invites.filter(i=>i.resource_id===r.id).map(i=><div key={i.id} className="flex flex-wrap justify-between gap-3 py-3"><p>{i.email} · invitație în așteptare</p><button disabled={busy} className="underline" onClick={()=>void act({action:'invite.revoke',id:i.id})}>Revocă invitația</button></div>)}</section>)}
 {mode==='team'&&<>{!data.jobs.length&&<div className="empty-workspace"><h2>Nicio lucrare alocată</h2><p>Lucrările apar după acceptarea invitației și alocarea echipei.</p>{user.role==='firma'&&<Link href="/firma/echipe" className="v2-btn v2-btn-primary mt-4">Creează și alocă echipe</Link>}</div>}{data.jobs.map(j=><TeamExecutionCard key={j.id} job={j} busy={busy} isOwner={user.role==='firma'} act={act} upload={upload}/>)}</>}
 {mode==='business'&&<>{!data.properties.length&&<div className="empty-workspace"><h2>Nicio locație disponibilă</h2><p>Adaugă o locație sau acceptă invitația titularului.</p><Link href="/client/proprietati" className="v2-btn v2-btn-primary mt-4">Gestionează proprietățile</Link></div>}{data.properties.map(p=><article key={p.id} className="v2-card p-5 my-4"><h2 className="text-xl font-bold">{p.name}</h2><p className="text-muted my-3">{p.street}, {p.city} · Buget lunar {money(p.budget_bani/100)}</p>{p.role==='owner'&&<label className="flex gap-3"><input type="checkbox" disabled={busy} checked={!!p.budget_enforced} onChange={e=>void act({action:'budget.configure',propertyId:p.id,enabled:e.target.checked})}/>Blochează aprobările și rezervările peste buget</label>}{p.role!=='viewer'&&<form className="form-grid mt-5" onSubmit={async e=>{e.preventDefault();await act({action:'approval.request',propertyId:p.id,date,note,requestKey:crypto.randomUUID()})}}><label>Data lucrării<input type="date" required className={inputClass} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Detalii<input className={inputClass} value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/></label><button disabled={busy} className="v2-btn v2-btn-secondary">Solicită aprobare</button></form>}{data.approvals.filter(a=>a.property_id===p.id).map(a=><div className="mt-5 border-t border-line pt-4" key={a.id}><div className="flex flex-wrap justify-between gap-3"><b>{a.date} · {money(a.price_bani/100)}</b><span className="eyebrow-pill">{statuses[a.status]}</span></div><p className="text-sm text-muted mt-2">Solicitat de {a.requester_name}</p><p className="my-3">{a.note}</p>{a.decision_note&&<p>Decizie: {a.decision_note}</p>}{p.role==='owner'&&a.status==='pending'&&<><input aria-label="Motivul deciziei" placeholder="Motivul deciziei (opțional)" maxLength={1000} className={inputClass} value={decisionNotes[a.id]??''} onChange={e=>setDecisionNotes({...decisionNotes,[a.id]:e.target.value})}/><div className="flex gap-3 mt-3"><button disabled={busy} className="v2-btn v2-btn-primary" onClick={()=>void act({action:'approval.decide',id:a.id,approve:true,note:decisionNotes[a.id]??''})}>Aprobă</button><button disabled={busy} className="v2-btn v2-btn-secondary" onClick={()=>void act({action:'approval.decide',id:a.id,approve:false,note:decisionNotes[a.id]??''})}>Respinge</button></div></>}{p.role==='owner'&&a.status==='approved'&&<><button disabled={busy} className="v2-btn v2-btn-secondary mr-3" onClick={()=>void act({action:'approval.decide',id:a.id,approve:false,note:'Aprobare retrasă de titular'})}>Retrage aprobarea</button><Link className="v2-btn v2-btn-primary" href={`/client?propertyId=${encodeURIComponent(p.id)}&approvalId=${encodeURIComponent(a.id)}#sec-form`}>Rezervă lucrarea aprobată</Link></>}</div>)}</article>)}</>}
 </> }</main></div>
}
