'use client';
import {useEffect,useState} from 'react';
import {bucharestDay,utcDate,type EarningRow} from '@/lib/monthlyFirmEarnings';
const money=(n:number|null)=>n===null?'—':new Intl.NumberFormat('ro-RO',{style:'currency',currency:'RON'}).format(n);
const time=(s:string|null)=>s?utcDate(s).toLocaleTimeString('ro-RO',{timeZone:'Europe/Bucharest',hour:'2-digit',minute:'2-digit'}):'—';
export function FirmEarnings({revision=""}:{revision?:string}){
 const [month,setMonth]=useState(()=>bucharestDay(new Date().toISOString()).slice(0,7)),[day,setDay]=useState(''),[rows,setRows]=useState<EarningRow[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();fetch(`/api/firm/earnings?month=${encodeURIComponent(month)}`,{signal:controller.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('Câștigurile nu au putut fi încărcate.');return r.json();}).then(d=>{if(!controller.signal.aborted){setRows(d.rows);setError('');setLoading(false);}}).catch(e=>{if(!controller.signal.aborted){setRows([]);setError(e instanceof Error?e.message:'Conexiune întreruptă');setLoading(false);}});return()=>controller.abort();},[month,retry,revision]);
 const days=[...new Set(rows.map(r=>r.day))].sort().reverse(),selected=day?rows.filter(r=>r.day===day):rows;
 return <section className="rounded-2xl border border-line bg-white p-5" aria-label="Câștiguri pe zile"><h2 className="font-display font-bold">Câștiguri pe zile</h2><p className="text-sm text-muted mt-2">Grupare după ziua finalizării, ora României. Câștigurile confirmate includ plăți capturate, fără rambursări sau dispute. Viramentul bancar se verifică separat.</p><div className="flex flex-wrap gap-4 my-4"><label>Luna<input aria-label="Luna câștigurilor" type="month" min="2000-01" max="2099-12" value={month} onChange={e=>{if(e.target.value){setLoading(true);setRows([]);setDay('');setMonth(e.target.value);}}} className="block border border-line rounded-lg p-2"/></label><label>Ziua<select aria-label="Ziua câștigurilor" value={day} onChange={e=>setDay(e.target.value)} className="block border border-line rounded-lg p-2"><option value="">Toate zilele</option>{days.map(d=><option key={d} value={d}>{d.split('-').reverse().join('.')} · {money(rows.filter(r=>r.day===d).reduce((s,r)=>s+r.confirmedNet,0))}</option>)}</select></label></div>
 {loading?<p role="status">Se încarcă…</p>:error?<p role="alert">{error} <button className="underline" onClick={()=>{setLoading(true);setRetry(n=>n+1);}}>Reîncearcă</button></p>:<><p className="font-bold mb-4">{selected.length} lucrări · {money(selected.reduce((s,r)=>s+r.confirmedNet,0))} câștig confirmat</p>{!selected.length?<p className="text-muted">Nicio lucrare finalizată în perioada selectată.</p>:<div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr>{['Data / client','Lucrarea','Sosire → final','Durată','Câștigul tău','Stare'].map(h=><th className="p-3 border-b border-line" key={h}>{h}</th>)}</tr></thead><tbody>{selected.map(r=><tr key={r.id}><td className="p-3 border-b border-line"><b>{r.day.split('-').reverse().join('.')}</b><div>{r.clientName}</div></td><td className="p-3 border-b border-line">{r.street}, {r.city}<small className="block text-muted">{r.id}</small></td><td className="p-3 border-b border-line whitespace-nowrap">{time(r.arrivedAt)} → {time(r.completedAt)}</td><td className="p-3 border-b border-line"><b>{r.recordedMinutes===null?'—':`${r.recordedMinutes} min`}</b><small className="block text-muted">înregistrate · estimat {r.estimatedMinutes} min</small></td><td className="p-3 border-b border-line"><b>{money(r.net)}</b></td><td className="p-3 border-b border-line">{r.paymentStatus==='captured'?'Plată capturată':r.paymentStatus==='authorized'?'Doar autorizată':r.paymentStatus==='refunded'?'Rambursată':r.paymentStatus==='cancelled'?'Anulată':'Neconfirmată'}{r.refundStatus&&r.refundStatus!=='none'&&<small className="block">Rambursare: {r.refundStatus}</small>}{r.disputeStatus&&r.disputeStatus!=='none'&&<small className="block">Dispută: {r.disputeStatus}</small>}<small className="block text-muted">{r.payoutStatus==='paid'?'Virament bancar confirmat':'Virament bancar neconfirmat'}</small></td></tr>)}</tbody></table></div>}</>}
 </section>;
}
