'use client';
import Link from 'next/link';
import {HostCalendarSync} from './HostCalendarSync';
import {useCallback,useEffect,useRef,useState} from 'react';
import {DesignIcon} from './DesignIcon';
import type {HostWindow} from '@/lib/hostTurnover';
import {HOST_DEFAULTS,type HostSettings} from '@/lib/hostScheduleShared';
import {bucharestDateKey} from '@/lib/scheduling';
import {JOB_STATUS} from '@/lib/workspaceShared';
type Property={id:string;name:string};
type Event={id:string;source:string;starts_at:string;ends_at:string;status:string;imported_at:string};
type Plan={settings:HostSettings;windows:HostWindow[];events:Event[]};
const display=(value:string)=>new Date(value).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
const hour=(value:string)=>Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Bucharest',hour:'2-digit',hourCycle:'h23'}).format(new Date(value)));
const hours=Array.from({length:24},(_,i)=>i);
export function HostCleaningPlanner({properties,events,selected,onSelect,onChanged}:{properties:Property[];events:unknown[];selected:string;onSelect:(id:string)=>void;onChanged:()=>Promise<void>}){
 const property=properties.find(p=>p.id===selected)??properties[0];
 const [plan,setPlan]=useState<Plan|null>(null),[settings,setSettings]=useState<HostSettings>({...HOST_DEFAULTS}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const [editing,setEditing]=useState<{version?:string;id:string;arrivalDate:string;departureDate:string;arrivalHour:number;departureHour:number}|null>(null);
 const propertyId=property?.id;
 const loadVersion=useRef(0);
 const load=useCallback(async()=>{
  if(!propertyId){setPlan(null);setLoading(false);return;}
  const version=++loadVersion.current;setLoading(true);setError('');
  try{const r=await fetch(`/api/host-turnover?propertyId=${encodeURIComponent(propertyId)}`);const d=await r.json();if(!r.ok)throw new Error(d.error);if(version===loadVersion.current){setPlan(d);setSettings(d.settings);}}catch(e){if(version===loadVersion.current){setPlan(null);setError(e instanceof Error?e.message:'Calendar indisponibil.');}}finally{if(version===loadVersion.current)setLoading(false);}
 },[propertyId]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- synchronize the selected property's server calendar
 useEffect(()=>{setEditing(null);setNotice('');void load();},[load,events]);
 async function mutate(payload:Record<string,unknown>){
  setBusy(true);setError('');setNotice('');
  try{const r=await fetch('/api/host-turnover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({propertyId,...payload})});const d=await r.json();if(!r.ok)throw new Error(d.error);setEditing(null);await onChanged();await load();setNotice('Salvat. Lucrările existente își păstrează programarea; verifică eventualele avertizări.');}catch(e){setError(e instanceof Error?e.message:'Modificarea nu poate fi salvată.');}finally{setBusy(false);}
 }
 if(!property)return <section className="design-panel"><h2 className="font-bold text-xl">Curățenie între rezervări</h2><p>Adaugă prima proprietate pentru a organiza curățenia între plecarea și sosirea oaspeților.</p></section>;
 return <section className="design-panel host-cleaning-planner" id="plan-curatenie">
  <div className="board-card-heading"><h2><DesignIcon name="broom" variant="booking"/>Curățenie între rezervări</h2><select aria-label="Proprietate pentru curățenie între rezervări" value={property.id} disabled={busy} onChange={e=>onSelect(e.target.value)}>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>
  <p className="booking-muted">Introdu perioadele ocupate sau importă calendarul. NITIDO propune curățenia; tu verifici și confirmi rezervarea. Propunerea verifică intervalul proprietății; disponibilitatea firmei se confirmă în fluxul rezervării. Toate orele sunt ale României.</p>
  {error&&<p role="alert" className="workspace-error">{error}</p>}{notice&&<p role="status" className="workspace-notice">{notice}</p>}
  <div className="workspace-toolbar"><button type="button" className="v2-btn v2-btn-primary" disabled={busy||loading} onClick={()=>{const today=bucharestDateKey(new Date());setEditing({id:crypto.randomUUID(),arrivalDate:today,departureDate:'',arrivalHour:settings.arrival_hour,departureHour:settings.departure_hour});}}>Adaugă perioadă ocupată</button><a href="#calendar-import" className="v2-btn v2-btn-secondary">Importă calendar .ics</a><button type="button" className="v2-btn v2-btn-secondary" disabled={busy||loading} onClick={()=>void load()}>Actualizează propunerile</button></div>
  <HostCalendarSync key={property.id} propertyId={property.id} onChanged={async()=>{await onChanged();await load();}}/>
  <details className="host-hours"><summary>Ore uzuale și marje de pregătire</summary><p className="booking-muted">Orele se aplică importurilor care conțin numai date. Perioadele introduse cu ore exacte își păstrează orele. Schimbarea setărilor nu reprogramează lucrările existente.</p><form onSubmit={e=>{e.preventDefault();void mutate({action:'settings',...settings});}}><div className="form-grid">{(['departure_hour','arrival_hour'] as const).map(key=><label key={key}>{key==='departure_hour'?'Plecare oaspeți':'Sosire oaspeți'}<select value={settings[key]} disabled={busy||loading} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})}>{hours.map(h=><option value={h} key={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label>)}{(['after_minutes','before_minutes'] as const).map(key=><label key={key}>{key==='after_minutes'?'Marjă după plecare, minute':'Marjă înainte de sosire, minute'}<input type="number" min={0} max={240} required disabled={busy||loading} value={settings[key]} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)})}/></label>)}</div><button className="v2-btn v2-btn-primary mt-4" disabled={busy||loading}>Salvează orele și marjele</button></form></details>
  {editing&&<form className="host-stay-editor" onSubmit={e=>{e.preventDefault();void mutate({action:'stay',...editing});}}><h3 className="font-bold">Perioadă ocupată</h3><p className="booking-muted">Înregistrezi doar intervalul necesar organizării curățeniei, fără datele personale ale oaspeților.</p><div className="form-grid">{(['arrival','departure'] as const).map(kind=><label key={kind}>{kind==='arrival'?'Sosire':'Plecare'}<input type="date" required value={editing[`${kind}Date`]} onChange={e=>setEditing({...editing,[`${kind}Date`]:e.target.value})}/><select aria-label={kind==='arrival'?'Ora sosirii':'Ora plecării'} value={editing[`${kind}Hour`]} onChange={e=>setEditing({...editing,[`${kind}Hour`]:Number(e.target.value)})}>{hours.map(h=><option value={h} key={h}>{String(h).padStart(2,'0')}:00</option>)}</select></label>)}</div><div className="workspace-toolbar"><button className="v2-btn v2-btn-primary" disabled={busy}>Salvează perioada</button><button type="button" className="v2-btn v2-btn-secondary" disabled={busy} onClick={()=>setEditing(null)}>Renunță</button></div></form>}
  <h3 className="font-bold text-lg mt-6">Curățenii de organizat · următoarele 30 de zile</h3><p className="booking-muted">Sunt incluse și plecările din ultimele 7 zile și perioadele cu lucrări active (maximum 200 de propuneri). Fără o sosire următoare, căutăm un interval în primele 24 de ore după plecare. Durata și marja de lucru trebuie să încapă integral.</p>
  {loading?<p role="status">Se calculează intervalele…</p>:<div className="host-proposal-grid">{plan?.windows.map(w=>{
   const params=w.slot?new URLSearchParams({propertyId:property.id,hostEventId:w.eventId,hostRevision:w.revision,date:w.slot.date,hour:String(w.slot.hour)}):null;
   return <article className="host-proposal" key={w.eventId}><div className="flex justify-between gap-3"><b>Plecare: {display(w.departure)}</b><span>{w.cancelled?'Perioadă anulată':w.jobStatus?JOB_STATUS[w.jobStatus]??w.jobStatus:'De programat'}</span></div><p>Sosire următoare: {w.nextArrival?display(w.nextArrival):'Încă neconfirmată'}</p><p>Interval disponibil: {display(w.earliest)} – {display(w.deadline)}</p><p className="booking-muted">Curățenie estimată: {w.duration} min + marjă de lucru {w.buffer} min.</p>{w.problem&&<p role="status" className="workspace-error">{w.problem}</p>}{w.jobId?<Link className="v2-btn v2-btn-secondary" href="/client#sec-lucrari">Vezi lucrarea existentă</Link>:!w.problem&&params?<Link className="v2-btn v2-btn-primary" href={`/client?${params.toString()}#sec-form`}>Rezervă curățenia · {w.slot!.date.split('-').reverse().join('.')} la {String(w.slot!.hour).padStart(2,'0')}:00</Link>:null}</article>;
  })}{!plan?.windows.length&&<p className="booking-muted">Nicio plecare în această perioadă. Adaugă perioadele ocupate pentru a primi propuneri.</p>}</div>}
  {!!plan?.events.some(e=>e.source==='Manual NITIDO')&&<details className="host-hours"><summary>Gestionează perioadele introduse manual</summary><div className="host-proposal-grid">{plan.events.filter(e=>e.source==='Manual NITIDO').map(e=><article className="host-proposal" key={e.id}><b>{display(e.starts_at)} – {display(e.ends_at)}</b><p>{e.status==='cancelled'?'Anulată':'Ocupată'}</p><div className="workspace-toolbar"><button className="v2-btn v2-btn-secondary" disabled={busy} onClick={()=>setEditing({id:e.id,version:e.imported_at,arrivalDate:bucharestDateKey(new Date(e.starts_at)),departureDate:bucharestDateKey(new Date(e.ends_at)),arrivalHour:hour(e.starts_at),departureHour:hour(e.ends_at)})}>Editează perioada</button>{e.status!=='cancelled'&&<button className="v2-btn v2-btn-secondary" disabled={busy} onClick={()=>{if(window.confirm('Anulezi perioada ocupată? Curățenia deja rezervată rămâne activă și se gestionează separat din Rezervări.'))void mutate({action:'stay',id:e.id,version:e.imported_at,cancel:true});}}>Anulează perioada</button>}</div></article>)}</div></details>}
 </section>;
}
