'use client';
import {useRef,useState} from 'react';
export type InventoryItem={id:string;property_id:string;name:string;unit:string;quantity:number;threshold:number};
export type InventoryMovement={id:string;property_id:string;name:string;unit:string;delta:number;note:string;created_at:string};
export function HostInventory({properties,items,history,busy,onSave}:{history:InventoryMovement[];properties:{id:string;name:string}[];items:InventoryItem[];busy:boolean;onSave:(p:Record<string,unknown>,s:string)=>Promise<boolean>}){
 const [property,setProperty]=useState(''),[selected,setSelected]=useState('');
 const retry=useRef<{signature:string;key:string}|null>(null),lock=useRef(false);
 const propertyId=properties.some(p=>p.id===property)?property:properties[0]?.id??'';
 const visible=items.filter(i=>i.property_id===propertyId),item=visible.find(i=>i.id===selected);
 return <section id="inventar" className="design-panel host-inventory"><div className="board-card-heading"><h2>Lenjerie și consumabile</h2><select aria-label="Proprietate pentru inventar" value={propertyId} onChange={e=>{setProperty(e.target.value);setSelected('')}}>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div><p className="booking-muted">Urmărește stocul și necesarul de completare. Nicio achiziție nu se face automat.</p>{!properties.length?<p>Adaugă mai întâi o proprietate de tip Gazdă.</p>:<>
 <div className="inventory-grid">{visible.map(i=><article key={i.id} className={`inventory-item ${i.quantity<=i.threshold?'inventory-low':''}`}><h3>{i.name}</h3><strong>{i.quantity} <small>{i.unit}</small></strong><p>Prag de alertă: {i.threshold} {i.unit}</p><p>{i.quantity<=i.threshold?'Necesită completare':'Stoc peste prag'}</p><button className="board-soft-button" onClick={()=>setSelected(i.id)}>Înregistrează intrare / consum</button><details><summary>Modifică pragul</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await onSave({action:'inventory.threshold',itemId:i.id,threshold:Number(f.get('threshold'))},'Prag actualizat.')}}><label>Prag ({i.unit})<input key={i.threshold} name="threshold" type="number" min="0" max="1000000" step="1" defaultValue={i.threshold} required/></label><button disabled={busy} className="board-soft-button">Salvează pragul</button></form></details></article>)}</div>{!visible.length&&<p className="booking-muted">Inventarul este gol. Adaugă primul articol mai jos.</p>}
 {item&&<form className="inventory-movement" onSubmit={async e=>{e.preventDefault();if(lock.current)return;const form=e.currentTarget,f=new FormData(form);const delta=Number(f.get('quantity'))*(f.get('kind')==='consume'?-1:1),note=String(f.get('note'));const signature=JSON.stringify([item.id,delta,note]);if(retry.current?.signature!==signature)retry.current={signature,key:crypto.randomUUID()};lock.current=true;try{if(await onSave({action:'inventory.move',itemId:item.id,delta,note,requestKey:retry.current.key},'Stoc actualizat.')){retry.current=null;form.reset();setSelected('')}}finally{lock.current=false}}}><h3>{item.name} · stoc {item.quantity} {item.unit}</h3><div className="availability-fields"><label>Operație<select name="kind"><option value="add">Intrare în stoc</option><option value="consume">Consum / ieșire</option></select></label><label>Cantitate ({item.unit})<input name="quantity" type="number" min="1" max="1000000" step="1" required/></label><label>Motiv<input name="note" required maxLength={250} placeholder="Aprovizionare, pregătire sejur…"/></label></div><button disabled={busy} className="v2-btn v2-btn-primary">Salvează mișcarea</button><button type="button" className="v2-btn v2-btn-secondary" onClick={()=>setSelected('')}>Închide</button></form>}
 <details className="inventory-create"><summary>Adaugă articol în inventar</summary><form onSubmit={async e=>{e.preventDefault();if(lock.current)return;lock.current=true;const form=e.currentTarget,f=new FormData(form);try{if(await onSave({action:'inventory.create',propertyId,name:f.get('name'),unit:f.get('unit'),threshold:Number(f.get('threshold'))},'Articol adăugat cu stoc zero. Înregistrează intrarea în stoc.'))form.reset()}finally{lock.current=false}}}><div className="availability-fields"><label>Denumire<input name="name" required maxLength={100} placeholder="Set lenjerie, săpun…"/></label><label>Unitate<input name="unit" required maxLength={30} placeholder="bucăți, seturi, ml"/></label><label>Prag de alertă<input name="threshold" type="number" min="0" max="1000000" step="1" defaultValue="2" required/></label></div><button className="v2-btn v2-btn-primary" disabled={busy}>Adaugă articol</button></form></details></>}
 <details className="inventory-create"><summary>Istoricul mișcărilor</summary><p className="booking-muted">Cele mai recente 100 de mișcări din cont, filtrate pentru această proprietate.</p><ul className="availability-list">{history.filter(m=>m.property_id===propertyId).map(m=><li key={m.id}><div><b>{m.name} · {m.delta>0?'+':''}{m.delta} {m.unit}</b><p>{m.note}</p><p>{new Date(m.created_at).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'})}</p></div></li>)}</ul>{!history.some(m=>m.property_id===propertyId)&&<p>Nicio mișcare în lista curentă.</p>}</details></section>;
}
