'use client';
import Image from 'next/image';
import type {JobRow} from '@/lib/types';
import {JOB_STATUS,money} from '@/lib/workspaceShared';
import {ExecutionChecklist} from './ExecutionChecklist';
import {JobMessages} from './JobMessages';
import {DesignIcon} from './DesignIcon';
const date=(value:string|null)=>value?new Date(value).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'În așteptare';
const paymentLabels:Record<string,string>={authorized:'Sumă autorizată',captured:'Plată încasată',refunded:'Plată rambursată',cancelled:'Autorizare anulată',failed:'Plată nereușită',pending:'Plată în așteptare'};
export function JobExecutionDetail({job,firmName,onBack}:{job:JobRow;firmName:string|null;onBack:()=>void}){
 const proofs=job.proofs??[];
 const stages=[{label:'Confirmată',at:job.accepted_at,done:Boolean(job.accepted_at)},{label:'Echipa a sosit',at:job.arrived_confirmed_at,done:Boolean(job.arrived_confirmed_at)},{label:'În lucru',at:job.arrived_confirmed_at,done:Boolean(job.arrived_confirmed_at)},{label:'Raport foto',at:proofs.find(p=>p.type==='COMPLETION')?.createdAt??null,done:proofs.some(p=>p.type==='COMPLETION')},{label:'Finalizată',at:job.completed_at,done:job.status==='completed'}];
 return <section className="execution-detail"><button className="execution-back" onClick={onBack}><DesignIcon name="arrow" size={18}/>Înapoi la rezervările mele</button><header className="execution-heading"><div><h1>Curățenie · {job.space_type}</h1><p><DesignIcon name="pin" size={18}/>{job.street}, {job.city}<span><DesignIcon name="calendar" size={18}/>{job.scheduled_at?date(job.scheduled_at):'Cât mai curând'}</span></p></div><span className="eyebrow-pill">{JOB_STATUS[job.status]}</span></header><ol className="execution-timeline" aria-label="Evoluția lucrării">{stages.map(s=><li key={s.label} className={s.done?'is-done':''}><span>{s.done?<DesignIcon name="check" size={18}/>:<DesignIcon name="clock" size={18}/>}</span><b>{s.label}</b><small>{s.done?date(s.at):'În așteptare'}</small></li>)}</ol>{['cancelled','no_show'].includes(job.status)&&<p role="status" className="workspace-error">{JOB_STATUS[job.status]}. Etapele neatinse nu sunt confirmate.</p>}
 <div className="execution-detail-grid"><ExecutionChecklist key={job.id} jobId={job.id}/><section className="design-panel execution-proof-panel"><h2>Fotografii și raport</h2>{(['ARRIVAL','COMPLETION'] as const).map(type=><section key={type}><h3>{type==='ARRIVAL'?'Fotografii la sosire':'Fotografii la finalizare'}<small>{proofs.filter(p=>p.type===type).length} fotografii</small></h3><div className="execution-proof-grid">{proofs.filter(p=>p.type===type).map(p=><a href={p.url} key={p.id} target="_blank" rel="noreferrer"><Image unoptimized src={p.url} alt={`${type==='ARRIVAL'?'Sosire':'Finalizare'} — dovadă foto`} width={400} height={320}/><small>{date(p.createdAt)}</small></a>)}</div>{!proofs.some(p=>p.type===type)&&<p className="execution-photo-empty"><DesignIcon name="photo" size={28}/>Fotografiile vor apărea după încărcarea și validarea lor.</p>}</section>)}</section><aside className="execution-detail-aside"><section className="design-panel"><h2>Firma parteneră</h2><div className="execution-firm"><span>{firmName?.slice(0,1)||'N'}</span><div><h3>{firmName|| (job.accepted_firm_id?'Se încarcă firma…':'Firma nu este încă alocată')}</h3><p>{job.duration_minutes} minute estimate · {job.sqm} m²</p></div></div></section>{job.accepted_firm_id&&<JobMessages key={job.id} jobId={job.id}/>}<section className="design-panel"><h2><DesignIcon name="card"/>Detalii plată</h2><strong className="execution-payment-total">{money(job.price_gross)}</strong><p>{paymentLabels[job.financial?.paymentStatus??'']??'Starea plății nu este confirmată'}</p>{job.financial?.refundStatus&&job.financial.refundStatus!=='none'&&<p>Rambursare: {job.financial.refundStatus}</p>}<p className="booking-muted">Starea plății este distinctă de starea lucrării. O bifă de progres nu confirmă încasarea.</p></section></aside></div></section>;
}
