"use client";
import {useEffect,useState,useCallback,useRef} from "react";
export function JobMessages({jobId}:{jobId:string}){
 const [messages,setMessages]=useState<{id:string;body:string;sender_name:string;created_at:string}[]>([]),[body,setBody]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const request=useRef<{body:string;id:string}|null>(null);
 const refresh=useCallback(async()=>{try{const res=await fetch(`/api/workspace/messages?jobId=${encodeURIComponent(jobId)}`);const d=await res.json();if(!res.ok)throw new Error(d.error);setMessages(d.messages);setError(null)}catch{setError("Nu putem încărca mesajele. Reîncearcă.")}},[jobId]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- initial authenticated remote fetch
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),10000);return ()=>clearInterval(timer)},[refresh]);
 async function send(e:React.FormEvent){e.preventDefault();if(!body.trim()||busy)return;setBusy(true);setError(null);if(request.current?.body!==body)request.current={body,id:crypto.randomUUID()};try{const res=await fetch("/api/workspace/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId,body,requestId:request.current.id})});const d=await res.json();if(!res.ok)throw new Error(d.error);setBody("");request.current=null;await refresh()}catch(e){setError(e instanceof Error?e.message:"Mesaj netrimis")}finally{setBusy(false)}}
 return <section className="v2-card p-5"><h2 className="font-bold text-lg">Conversația lucrării</h2><p className="text-sm text-muted mt-1">Mesajele sunt vizibile clientului și firmei alocate.</p><div className="job-messages" aria-live="polite">{!messages.length?<p className="text-muted text-sm py-8">Nu există mesaje încă.</p>:messages.map(m=><article key={m.id}><div className="flex justify-between gap-3 text-xs text-muted"><b>{m.sender_name}</b><time>{new Date(m.created_at).toLocaleString("ro-RO")}</time></div><p className="whitespace-pre-wrap break-words text-sm mt-2">{m.body}</p></article>)}</div>{error&&<p role="alert" className="text-red-700 text-sm my-3">{error} <button onClick={()=>void refresh()} className="underline">Reîncearcă</button></p>}<form onSubmit={send}><label className="block text-sm font-medium">Mesaj<textarea maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} className="w-full border border-line rounded-xl p-3 mt-2" rows={3}/></label><button disabled={busy||!body.trim()} className="v2-btn v2-btn-primary mt-2 disabled:opacity-40">{busy?"Se trimite…":"Trimite mesajul"}</button></form></section>
}
