'use client';
import {useState} from 'react';
import type {PublicManualOffer} from '@/lib/manualOffers';
export type BookableManualOffer=PublicManualOffer&{booking?:{enabled:boolean;reason?:string;jobId?:string|null;windowsSqm?:number}};
export function ManualOfferReservation({offer}:{offer:BookableManualOffer}){
 const [street,setStreet]=useState(''),[postalCode,setPostalCode]=useState(''),[floor,setFloor]=useState(''),[spaceType,setSpaceType]=useState('apartament'),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[jobId,setJobId]=useState(offer.booking?.jobId??null);
 const [retry,setRetry]=useState<Record<string,unknown>|null>(null);
 const total=new Intl.NumberFormat('ro-RO',{style:'currency',currency:'RON'}).format(offer.terms.totalBani/100);
 async function reserve(){setBusy(true);setError('');try{const payload=retry??{manualOfferId:offer.id,manualBookingConfirmed:true,confirmedManualTotalBani:offer.terms.totalBani,city:offer.terms.context.city,sqm:offer.terms.context.sqm,windowsSqm:offer.booking?.windowsSqm??0,street,postalCode,floor,spaceType,mode:'express',whenType:'asap',photoIds:[]};setRetry(payload);const r=await fetch('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok){if(r.status<500)setRetry(null);throw Error(d.error||'Rezervarea nu a fost confirmată.');}setJobId(d.job.id);}catch(e){setError(e instanceof Error?e.message:'Rezervare nereușită');}finally{setBusy(false);}}
 if(jobId)return <p role="status">Rezervarea {jobId} este creată. Verifică starea și eventuala autorizare a cardului în <a href="/client">contul clientului</a>.</p>;
 if(!offer.booking)return <p>Crearea rezervării din această ofertă nu este activată.</p>;
 if(!offer.booking.enabled)return <p>{offer.booking.reason}</p>;
 return <form onSubmit={e=>{e.preventDefault();void reserve();}}><h4>Rezervare la suma acceptată: {total}</h4><p>Lucrarea intră în fluxul de preluare de către o firmă, la următorul interval disponibil. Nu include garanția Express 60. Cardul se autorizează conform fluxului existent când firma preia lucrarea. Creditul din cont nu se aplică suplimentar acestei oferte.</p>{error&&<p role="alert">{error}</p>}<fieldset disabled={busy}><label>Adresa exactă<input required maxLength={200} value={street} disabled={retry!==null} onChange={e=>setStreet(e.target.value)}/></label><label>Cod poștal<input required maxLength={12} value={postalCode} disabled={retry!==null} onChange={e=>setPostalCode(e.target.value)}/></label><label>Etaj<input maxLength={20} value={floor} disabled={retry!==null} onChange={e=>setFloor(e.target.value)}/></label><label>Tip proprietate<select value={spaceType} disabled={retry!==null} onChange={e=>setSpaceType(e.target.value)}><option value="apartament">Apartament</option><option value="casa">Casă</option><option value="birou">Birou</option><option value="altul">Altul</option></select></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Confirm crearea unei rezervări la {total}, pentru serviciile ofertei acceptate.</label><button type="submit" className="design-button" disabled={!confirmed}>{busy?'Se creează…':'Creează rezervarea la prețul acceptat'}</button></fieldset></form>;
}
