'use client';
import {useCallback,useEffect,useState} from 'react';
import type {PublicManualOffer} from '@/lib/manualOffers';
const money=(n:number)=>new Intl.NumberFormat('ro-RO',{style:'currency',currency:'RON'}).format(n/100);
const statuses:Record<string,string>={offered:'Disponibilă pentru decizie',expired:'Expirată — este necesară o ofertă nouă',accepted:'Acceptată',rejected:'Refuzată',withdrawn:'Retrasă de NITIDO',superseded:'Înlocuită cu o revizie nouă'};
export function ManualOfferPanel({id,admin=false,revision,dirty=false}:{id:string;admin?:boolean;revision?:number;dirty?:boolean}){
 const [offers,setOffers]=useState<PublicManualOffer[]>([]),[enabled,setEnabled]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[scope,setScope]=useState(''),[expires,setExpires]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState<string|null>(null);
 const endpoint=admin?'/api/admin/manual-offers':'/api/assessments/offers';
 const load=useCallback(async(signal?:AbortSignal)=>{const r=await fetch(`${endpoint}?id=${encodeURIComponent(id)}`,{signal,cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setOffers(d.offers);setEnabled(d.enabled);},[endpoint,id]);
 useEffect(()=>{const c=new AbortController();fetch(`${endpoint}?id=${encodeURIComponent(id)}`,{signal:c.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d;}).then(d=>{if(!c.signal.aborted){setOffers(d.offers);setEnabled(d.enabled);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[endpoint,id]);
 async function act(body:unknown){setBusy(true);setError('');try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error);setConfirmed(null);await load();}catch(e){setError(e instanceof Error?e.message:'Operațiune nereușită');}finally{setBusy(false);}}
 return <section className="design-panel"><h3>{admin?'Publicarea ofertei salvate':'Ofertele pentru această cerere'}</h3><p>Oferta fixează serviciile, reducerea, totalul și valabilitatea. Acceptarea în această etapă de test nu creează o rezervare și nu autorizează sau încasează bani.</p>{error&&<p role="alert">{error}</p>}{!enabled&&<p>Fluxul de decizie nu este activat. Istoricul rămâne disponibil.</p>}<button type="button" disabled={busy} onClick={()=>void load().then(()=>setError('')).catch(e=>setError(e.message))}>Actualizează ofertele</button>
 {admin&&revision!==undefined&&<form onSubmit={e=>{e.preventDefault();void act({action:'publish',id,revision,scope,expiresAt:new Date(expires).toISOString(),reason});}}><fieldset disabled={!enabled||busy||dirty}><legend>Publică revizia internă salvată {revision}</legend><p>Verifică sumele din calculul salvat. Descrierea de mai jos este vizibilă clientului; costurile, marja și motivul intern nu sunt publicate. Oferta anterioară neacceptată va fi înlocuită.</p><label>Servicii incluse, limite și condiții<textarea required maxLength={4000} value={scope} onChange={e=>setScope(e.target.value)}/></label><label>Valabilă până la (ora locală a acestui dispozitiv)<input required type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)}/></label><label>Motiv intern pentru publicare sau retragere<textarea required maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button type="submit" className="design-button">Publică oferta în contul clientului</button></fieldset>{dirty&&<p>Salvează modificările calculului înainte de publicare.</p>}</form>}
 {!offers.length&&<p>Nu există oferte publicate pentru această cerere.</p>}{offers.map(o=><article key={o.id}><h4>Oferta · revizia {o.revision} · {statuses[o.status]??o.status}</h4><p>{o.terms.context.city} · {o.terms.context.sqm} m² · Datele cererii la publicare</p><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{o.terms.scope}</p><ul>{o.terms.lines.map((l,i)=><li key={i}>{l.label}: {money(l.amountBani)}</li>)}</ul><p>Subtotal: {money(o.terms.grossBani)} · Reducere: {money(o.terms.discountBani)} · <strong>Total: {money(o.terms.totalBani)}</strong></p><p>Valabilitate: {new Date(o.expiresAt).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'})} (ora României).</p>{o.status==='accepted'&&<p role="status">Acceptarea este înregistrată. Rezervarea și plata nu au fost create prin această ofertă.</p>}{o.status==='offered'&&(admin?<button type="button" disabled={!enabled||busy||!reason.trim()} onClick={()=>void act({action:'withdraw',id:o.id,reason})}>Retrage oferta cu motivul intern completat</button>:<fieldset disabled={!enabled||busy}><label><input type="checkbox" checked={confirmed===o.id} onChange={e=>setConfirmed(e.target.checked?o.id:null)}/>Am citit serviciile și condițiile și accept totalul de {money(o.terms.totalBani)}.</label><button type="button" disabled={confirmed!==o.id} onClick={()=>void act({action:'accept',id:o.id,confirmed:true,totalBani:o.terms.totalBani})}>Acceptă oferta afișată</button><button type="button" onClick={()=>void act({action:'reject',id:o.id})}>Refuză oferta</button></fieldset>)}</article>)}</section>;
}
