'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {OrganizationModuleSettings} from './OrganizationModuleSettings';
import {ORGANIZATION_MODULES,type OrganizationModules} from '@/lib/organizationModulesShared';
import {Logo,inputClass} from './ui';
import {WorkspaceNav} from './WorkspaceNav';
import {useCurrentUser} from '@/lib/useCurrentUser';
import {money} from '@/lib/workspaceShared';
type Member={id:string;name?:string;email:string;role:string};
type Organization={modules:OrganizationModules;id:string;name:string;role:string;revision:number;approval_threshold_bani:number;separate_approver:number;properties:{id:string;name:string;city:string;cost_center:string;kind:string}[];members:Member[];invites:Member[];history:{action:string;actor:string;created_at:string;details:string;resource_id:string}[]};
type Data={organizations:Organization[];availableProperties:{id:string;name:string;kind:string}[]};
const roles:Record<string,string>={owner:'Titular',manager:'Solicitant',approver:'Aprobator',viewer:'Vizualizare'};
const actions:Record<string,string>={'modules.save':'Module actualizate','policy.save':'Politică salvată','property.attach':'Locație adăugată','property.detach':'Locație eliminată','member.invite':'Invitație creată','member.accept':'Invitație acceptată','member.revoke':'Acces revocat','invite.revoke':'Invitație revocată','approval.request':'Solicitare creată','approval.approve':'Solicitare aprobată','approval.reject':'Solicitare respinsă'};
export function OrganizationManagement(){
 const {user,loading}=useCurrentUser();
 const [data,setData]=useState<Data>({organizations:[],availableProperties:[]}),[pending,setPending]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState(''),[link,setLink]=useState('');
 const lock=useRef(false);
 const refresh=useCallback(async()=>{const r=await fetch('/api/organizations');const d=await r.json();if(!r.ok)throw Error(d.error);setData(d as Data)},[]);
 useEffect(()=>{if(!user||user.role!=='client')return;let live=true;
  void fetch('/api/organizations').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d as Data}).then(d=>{if(live)setData(d)}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setPending(false)});
  return()=>{live=false};
 },[user]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),13000);return()=>clearTimeout(timer)},[notice]);
 async function act(body:Record<string,unknown>){
  if(lock.current)return null;lock.current=true;setBusy(true);setError('');setNotice('');
  try{const r=await fetch('/api/organizations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);await refresh();setNotice('Modificarea a fost salvată.');return d}catch(e){setError(e instanceof Error?e.message:'Conexiune indisponibilă.');return null}finally{setBusy(false);lock.current=false}
 }
 if(loading)return <main className="p-8" role="status">Se încarcă…</main>;
 if(!user||user.role!=='client')return <main className="max-w-xl p-8 mx-auto"><Logo/><h1 className="workspace-title mt-6">Organizații Business</h1><p className="my-4">Intră în contul client care deține locațiile sau în contul client invitat.</p><Link className="v2-btn v2-btn-primary" href="/login?next=%2Fclient%2Forganizatii">Autentificare client</Link></main>;
 const org=data.organizations.find(o=>o.id===selected)??data.organizations[0];
 return <div className="operations-layout approved-operations role-client"><aside className="operations-sidebar"><Logo href="/client"/><WorkspaceNav role="client"/></aside><main className="operations-main">
  <header className="section-heading"><div><p className="v2-eyebrow">NITIDO BUSINESS</p><h1 className="workspace-title">Organizații și aprobări</h1><p className="text-muted mt-3">Portofolii separate, acces pe roluri și reguli înainte de rezervare.</p></div><Link href="/client/business" className="v2-btn v2-btn-secondary">Portofoliul Business</Link></header>
  {error&&<p className="workspace-error" role="alert">{error} <button className="underline" onClick={()=>void refresh().then(()=>setError('')).catch(e=>setError(e.message))}>Reîncarcă datele</button></p>}{notice&&<p className="workspace-notice" role="status">{notice}</p>}
  {pending?<p role="status">Se încarcă organizațiile…</p>:<>
   <details className="v2-card p-5 mb-6" open={!data.organizations.length}><summary className="font-bold cursor-pointer">Creează o organizație</summary><p className="text-sm text-muted my-3">Vei fi titularul organizației. Inițial, orice sumă necesită aprobarea altei persoane.</p><form className="workspace-toolbar organization-create-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const d=await act({action:'save',name:f.get('name'),thresholdBani:0,separateApprover:true});if(d){setSelected(d.id);form.reset()}}}><label>Denumire<input className={inputClass} name="name" required maxLength={100} placeholder="Ex. Portofoliu Constanța"/></label><button disabled={busy} className="v2-btn v2-btn-primary">Creează organizația</button></form></details>
   {!!data.organizations.length&&<label className="block mb-5">Organizația activă<select className={inputClass} value={org?.id??''} onChange={e=>{setSelected(e.target.value);setLink('')}}>{data.organizations.map(o=><option value={o.id} key={o.id}>{o.name} · {roles[o.role]}</option>)}</select></label>}
   {org&&<div key={`${org.id}:${org.revision}`}>
    <OrganizationModuleSettings key={`${org.id}:${org.modules.revision}`} id={org.id} modules={org.modules} owner={org.role==='owner'} busy={busy} onSave={act}/>
    <section className="v2-card p-5 mb-5"><h2 className="text-xl font-bold">{org.name}</h2><p className="my-3">Rolul tău: <b>{roles[org.role]}</b></p><p>Solicitările de <b>{money(org.approval_threshold_bani/100)}</b> sau mai mult necesită aprobare manuală. Sub prag, aprobarea este automată, în limita bugetului locației.</p><p className="text-sm text-muted mt-3">Aprobarea nu efectuează plata. Titularul finalizează rezervarea și selectează cardul. Fără o altă persoană cu drept de aprobare, propriile solicitări care cer aprobator separat rămân în așteptare.</p>
    {org.role==='owner'&&<form className="mt-5" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!window.confirm('Salvezi politica? Solicitările și aprobările încă nefolosite vor fi retrase și trebuie create din nou.'))return;await act({action:'save',id:org.id,revision:org.revision,name:f.get('name'),thresholdBani:Math.round(Number(f.get('threshold'))*100),separateApprover:f.get('separate')==='on'})}}><div className="form-grid"><label>Denumire<input name="name" className={inputClass} defaultValue={org.name} required maxLength={100}/></label><label>Aprobare manuală de la, RON<input name="threshold" type="number" className={inputClass} defaultValue={org.approval_threshold_bani/100} min={0} max={1000000} step="0.01" required/></label></div><label className="flex gap-3 items-start my-4"><input name="separate" type="checkbox" defaultChecked={!!org.separate_approver}/>Solicitantul nu își poate aproba manual propria cerere</label><p className="text-sm text-muted mb-3">Pragul 0 cere aprobare manuală pentru orice valoare. Schimbarea politicii retrage solicitările nefolosite. Vizitele recurente care ating pragul se opresc cu motiv afișat și necesită rezervare aprobată individual.</p><button className="v2-btn v2-btn-primary" disabled={busy}>Salvează politica</button></form>}
    </section>
    <section className="v2-card p-5 mb-5"><div className="section-heading"><h2 className="font-bold text-xl">Locațiile organizației</h2><Link href="/colaborari" className="v2-btn v2-btn-secondary">Solicitări și aprobări</Link></div><p className="text-sm text-muted mb-4">Membrii organizației au acces numai la locațiile acestui portofoliu. Pentru locațiile asociate se aplică rolurile organizației, în locul invitațiilor vechi pe locație.</p>
     {!org.properties.length&&<p className="text-muted my-4">Nu există încă locații în această organizație.</p>}
     {org.properties.map(p=><div key={p.id} className="flex flex-wrap justify-between gap-3 py-3 border-b border-line"><div><b>{p.name}</b><p className="text-sm text-muted">{p.city}{p.cost_center?` · ${p.cost_center}`:''}</p></div>{org.role==='owner'&&<button disabled={busy} className="v2-btn v2-btn-secondary" onClick={()=>{if(window.confirm('Elimini locația din organizație? Membrii organizației pierd accesul, iar invitațiile existente pe locație se aplică din nou.'))void act({action:'property.detach',organizationId:org.id,propertyId:p.id})}}>Elimină din organizație</button>}</div>)}
     {org.role==='owner'&&<form className="workspace-toolbar mt-4" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(window.confirm('Asociezi locația? Se vor aplica rolurile și pragul acestei organizații, inclusiv vizitelor recurente viitoare.'))await act({action:'property.attach',organizationId:org.id,propertyId:f.get('propertyId')})}}><label>Proprietate disponibilă<select name="propertyId" required className={inputClass}><option value="">Alege locația…</option>{data.availableProperties.filter(p=>p.kind==='business'?org.modules.business:org.modules.host).map(p=><option value={p.id} key={p.id}>{p.name} · {p.kind==='host'?'Între rezervări':'Business'}</option>)}</select></label><button className="v2-btn v2-btn-primary" disabled={busy||!data.availableProperties.length}>Adaugă în organizație</button><Link href="/client/proprietati" className="underline">Gestionează proprietățile</Link></form>}
    </section>
    {org.role==='owner'&&<section className="v2-card p-5 mb-5"><h2 className="font-bold text-xl">Membri și invitații</h2><p className="text-sm text-muted my-3">Solicitantul cere lucrări; aprobatorul decide; rolul de vizualizare citește locațiile și solicitările. Plata și administrarea politicii rămân la titular.</p>
     <form className="form-grid" onSubmit={async e=>{e.preventDefault();setLink('');const f=new FormData(e.currentTarget);const d=await act({action:'invite',organizationId:org.id,email:f.get('email'),role:f.get('role')});if(d)setLink(`${window.location.origin}/invitatie?token=${d.token}`)}}><label>Email coleg<input type="email" name="email" className={inputClass} required maxLength={254}/></label><label>Rol<select name="role" className={inputClass}><option value="manager">Solicitant</option><option value="approver">Aprobator</option><option value="viewer">Vizualizare</option></select></label><button className="v2-btn v2-btn-primary" disabled={busy}>Creează invitația</button></form>
     {link&&<div className="workspace-notice mt-4"><label>Linkul invitației<input className={inputClass} readOnly value={link} onFocus={e=>e.target.select()}/></label><button className="underline mt-2" onClick={()=>void navigator.clipboard.writeText(link).then(()=>setNotice('Link copiat.')).catch(()=>setError('Selectează și copiază linkul din câmp.'))}>Copiază linkul</button><p className="text-sm mt-2">Valabil 7 zile, numai pentru contul client cu adresa indicată. Trimite tu linkul colegului; emailul nu este trimis automat.</p></div>}
     {org.members.map(m=><div className="flex flex-wrap justify-between gap-3 py-4 border-b border-line" key={m.id}><div><b>{m.name??m.email}</b><p className="text-sm">{m.email} · {roles[m.role]}</p></div><button className="v2-btn v2-btn-secondary" disabled={busy} onClick={()=>{if(window.confirm('Revoci accesul? Solicitările nefolosite ale colegului și aprobările date de el vor fi retrase.'))void act({action:'member.revoke',organizationId:org.id,id:m.id})}}>Revocă accesul</button></div>)}
     {org.invites.map(i=><div className="flex flex-wrap justify-between gap-3 py-3" key={i.id}><p>{i.email} · {roles[i.role]} · în așteptare</p><button className="underline" disabled={busy} onClick={()=>void act({action:'invite.revoke',organizationId:org.id,id:i.id})}>Revocă invitația</button></div>)}
    </section>}
    {org.role==='owner'&&<details className="v2-card p-5"><summary className="font-bold cursor-pointer">Istoric organizație · ultimele 30 de acțiuni</summary>{org.history.map((h,i)=><div className="py-3 border-b border-line" key={`${h.created_at}:${i}`}><b>{actions[h.action]??h.action}</b><p className="text-sm text-muted">{h.actor} · {new Date(h.created_at).toLocaleString('ro-RO')}</p><HistoryDetail action={h.action} details={h.details}/></div>)}</details>}
   </div>}
  </>}
 </main></div>;
}
function HistoryDetail({action,details}:{action:string;details:string}){
 let d:Record<string,unknown>;try{d=JSON.parse(details)}catch{return null}
 if(action==='modules.save'&&d.after&&typeof d.after==='object'){const state=d.after as Record<string,unknown>;return <p className="text-sm">{ORGANIZATION_MODULES.map(m=>`${m.label}: ${state[m.key]?'activ':'dezactivat'}`).join(' · ')}</p>;}
 if(action==='policy.save')return <p className="text-sm">Prag: {money(Number(d.thresholdBani)/100)} · Aprobator separat: {d.separateApprover?'Da':'Nu'}</p>;
 if(action==='approval.request')return <p className="text-sm">{money(Number(d.priceBani)/100)} · {d.automatic?'Sub prag, aprobare automată':'Aprobare manuală necesară'}</p>;
 if(typeof d.email==='string')return <p className="text-sm">{d.email} · {roles[String(d.role)]}</p>;
 if(typeof d.note==='string'&&d.note)return <p className="text-sm">{d.note}</p>;
 return null;
}
