'use client';
import {useState} from 'react';
import type {PropertyImportRow} from '@/lib/propertyImport';
export function PropertyCsvImport({onImported}:{onImported:()=>Promise<void>}){
 const [csv,setCsv]=useState(''),[rows,setRows]=useState<PropertyImportRow[]|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function submit(commit:boolean){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:commit?'property.import':'property.preview',csv})});const body=await r.json();if(!r.ok)throw new Error(body.error||'Import indisponibil.');if(commit){setRows(null);setCsv('');setNotice(`${body.created} locații create. ${body.skipped} duplicate omise.`);await onImported()}else setRows(body.rows)}catch(e){setError(e instanceof Error?e.message:'Eroare de conexiune.')}finally{setBusy(false)}}
 function template(){const blob=new Blob(['\uFEFFname,city,street,sqm,space_type,kind,cost_center,budget_ron,notes\r\nBirou exemplu,București,Strada Exemplu 1,100,birou,business,Administrativ,1500.00,\r\n'],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='nitido-model-import-locatii.csv';a.click();URL.revokeObjectURL(url)}
 return <details className="v2-card p-6 mt-6"><summary className="font-bold cursor-pointer">Importă locații din CSV</summary><p className="text-sm text-muted mt-3">Maximum 200 de locații și 500 KB. Descarcă modelul, înlocuiește exemplul și verifică previzualizarea. Importul adaugă locații; nu creează rezervări.</p><p className="text-sm text-muted mt-2">Tip spațiu: apartament, casa, birou, altul. Utilizare: home, business, host. Bugetul folosește punct pentru zecimale. Duplicate: aceeași denumire, același oraș și aceeași adresă în cont, inclusiv locații arhivate; acestea sunt omise.</p><div className="workspace-toolbar"><button type="button" className="v2-btn v2-btn-secondary" onClick={template}>Descarcă model CSV</button><label className="v2-btn v2-btn-secondary">Alege fișierul CSV<input className="sr-only" type="file" accept=".csv,text/csv" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;setRows(null);setCsv('');setError('');setNotice('');if(f.size>500000){setError('Maximum 500 KB.');return}setBusy(true);try{setCsv(await f.text())}catch{setError('Fișierul nu poate fi citit.')}finally{setBusy(false)}}}/></label><button className="v2-btn v2-btn-primary" disabled={busy||!csv} onClick={()=>void submit(false)}>Previzualizează importul</button></div>{error&&<p role="alert" className="workspace-error">{error}</p>}{notice&&<p role="status" className="workspace-notice">{notice}</p>}{rows&&<><div className="overflow-x-auto"><table className="workspace-table"><thead><tr><th>Rând CSV</th><th>Locație</th><th>Oraș / adresă</th><th>Suprafață / tip</th><th>Utilizare / centru de cost</th><th>Buget RON</th><th>Note</th><th>Validare</th></tr></thead><tbody>{rows.map(r=><tr key={r.row}><td>{r.row}</td><td>{r.name}</td><td>{r.city} · {r.street}</td><td>{r.values.sqm} m² · {r.values.space_type}</td><td>{r.values.kind} · {r.values.cost_center}</td><td>{r.values.budget_ron||'0'}</td><td className="whitespace-pre-wrap">{r.values.notes}</td><td>{r.status==='new'?'Locație nouă':r.status==='duplicate'?'Duplicat — se omite':r.errors.join(' ')}</td></tr>)}</tbody></table></div><button className="v2-btn v2-btn-primary mt-4" disabled={busy||rows.some(r=>r.status==='invalid')||!rows.some(r=>r.status==='new')} onClick={()=>void submit(true)}>{busy?'Se procesează…':`Importă ${rows.filter(r=>r.status==='new').length} locații noi`}</button></>}</details>
}
