'use client';
import {useState} from 'react';
import {inputClass} from './ui';
type Visit={jobId:string;originalAt:string;proposedAt:string;firmConfirmation:boolean};
export function SeriesChanges({plans,visits,onSaved}:{plans:{id:string;city:string;status:string}[];visits:{job_id:string;plan_id:string;scheduled_at:string;status:string}[];onSaved:()=>Promise<void>}){
 const [job,setJob]=useState(''),[date,setDate]=useState(''),[hour,setHour]=useState(10),[frequency,setFrequency]=useState('weekly'),[preview,setPreview]=useState<{revision:string;visits:Visit[]}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const selected=visits.find(v=>v.job_id===job);
 const time=(s:string)=>new Date(s).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest',dateStyle:'medium',timeStyle:'short'});
 async function send(apply:boolean){if(!selected||busy)return;setBusy(true);setError('');try{const r=await fetch(`/api/recurring/${encodeURIComponent(selected.plan_id)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:apply?'apply_following':'preview_following',fromJobId:job,date,hour,frequency,revision:preview?.revision})});const d=await r.json();if(!r.ok)throw Error(d.error);if(apply){setPreview(null);setError('Program salvat. Vizitele alocate așteaptă acordul firmei și, dacă este necesar, reconfirmarea cardului.');await onSaved()}else setPreview(d)}catch(e){setPreview(null);setError(e instanceof Error?e.message:'Conexiune indisponibilă')}finally{setBusy(false)}}
 return <details className="mt-4 border-t border-line pt-3"><summary className="cursor-pointer font-bold text-sm">Modifică această vizită și următoarele</summary><p className="text-sm text-muted my-3">Alegi prima vizită și noul ritm. Vezi toate schimbările înainte de salvare. Pentru vizitele deja alocate, intervalul actual rămâne valabil până la confirmarea firmei și a plății.</p><fieldset disabled={busy} className="form-grid" onChange={()=>setPreview(null)}><label>Prima vizită<select className={inputClass} required value={job} onChange={e=>setJob(e.target.value)}><option value="">Alege vizita</option>{visits.filter(v=>['waiting','accepted'].includes(v.status)&&Date.parse(v.scheduled_at)>Date.now()&&plans.some(p=>p.id===v.plan_id&&p.status==='active')).map(v=><option key={v.job_id} value={v.job_id}>{time(v.scheduled_at)} · {plans.find(p=>p.id===v.plan_id)?.city}</option>)}</select></label><label>Noua dată<input type="date" className={inputClass} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Ora<select className={inputClass} value={hour} onChange={e=>setHour(Number(e.target.value))}>{[8,10,12,14,16,18].map(h=><option key={h} value={h}>{h}:00</option>)}</select></label><label>Frecvență<select className={inputClass} value={frequency} onChange={e=>setFrequency(e.target.value)}><option value="weekly">Săptămânal</option><option value="biweekly">La două săptămâni</option><option value="monthly">Lunar</option></select></label></fieldset><button className="v2-btn v2-btn-secondary mt-3" disabled={busy||!date||!selected} onClick={()=>void send(false)}>Vezi schimbările</button>{preview&&<div className="mt-3"><ul className="space-y-2">{preview.visits.map(v=><li key={v.jobId} className="text-sm">{time(v.originalAt)} → {time(v.proposedAt)} · {v.firmConfirmation?'necesită confirmarea firmei':'actualizare directă'}</li>)}</ul><p className="text-xs text-muted my-3">Vizitele păstrează prețul publicat. Candidaturile vizitelor nealocate care își schimbă data se retrag. Ziua lunară inexistentă devine ultima zi a lunii.</p><button className="v2-btn v2-btn-primary" disabled={busy} onClick={()=>void send(true)}>Confirmă schimbările</button></div>}{error&&<p role="status" className="my-3 text-sm">{error}</p>}</details>;
}
