'use client';
import {useRef,useState} from 'react';
export type TeamBlock={id:string;team_id:string;team_name:string;starts_at:string;ends_at:string;reason:string};
const format=(s:string)=>new Date(s).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest',dateStyle:'medium',timeStyle:'short'});
export function TeamAvailability({teams,blocks,onSave,busy}:{teams:{id:string;name:string}[];blocks:TeamBlock[];onSave:(p:Record<string,unknown>,message:string)=>Promise<boolean>;busy:boolean}){
 const [team,setTeam]=useState(''),[error,setError]=useState(''),[history,setHistory]=useState(false);
 const lock=useRef(false);
 const [now]=useState(()=>Date.now());
 const visible=blocks.filter(b=>(!team||b.team_id===team)&&(history||Date.parse(b.ends_at)>=now));
 return <section className="design-panel team-availability" id="indisponibilitati"><h2>Concedii și indisponibilități</h2><p className="booking-muted">Intervalele blochează alocarea echipei, inclusiv timpul de deplasare al lucrării. Lucrările existente trebuie realocate înainte de blocare.</p>{error&&<p role="alert" className="workspace-error">{error}</p>}
 <form onSubmit={async e=>{e.preventDefault();if(lock.current)return;const form=e.currentTarget;const f=new FormData(form);const start=new Date(String(f.get('start'))),end=new Date(String(f.get('end')));if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start){setError('Alege un interval valid.');return}lock.current=true;setError('');try{if(await onSave({action:'team.block',teamId:f.get('team'),startsAt:start.toISOString(),endsAt:end.toISOString(),reason:f.get('reason')},'Indisponibilitate salvată. Echipa nu poate fi alocată în acest interval.'))form.reset()}finally{lock.current=false}}}>
 <div className="availability-fields"><label>Echipă<select name="team" required disabled={busy||!teams.length}><option value="">Alege echipa</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>De la<input type="datetime-local" name="start" required disabled={busy}/></label><label>Până la<input type="datetime-local" name="end" required disabled={busy}/></label><label>Motiv<input name="reason" required maxLength={160} placeholder="Concediu, mentenanță…" disabled={busy}/></label></div><p className="booking-muted">Introdu orele în fusul dispozitivului: {Intl.DateTimeFormat().resolvedOptions().timeZone}. Calendarul și lista afișează ora României.</p><button className="v2-btn v2-btn-primary" disabled={busy||!teams.length}>{busy?'Se salvează…':'Blochează intervalul'}</button>{!teams.length&&<p className="booking-muted">Adaugă mai întâi o echipă.</p>}</form>
 <div className="workspace-toolbar"><label>Filtrează echipa<select value={team} onChange={e=>setTeam(e.target.value)}><option value="">Toate echipele</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/> Arată și intervalele trecute</label></div>
 {!visible.length?<p className="booking-muted">Nicio indisponibilitate pentru filtrul selectat.</p>:<ul className="availability-list">{visible.map(b=><li key={b.id}><div><b>{b.team_name} · {b.reason}</b><p>{format(b.starts_at)} – {format(b.ends_at)}</p></div><button className="v2-btn v2-btn-secondary" disabled={busy} onClick={()=>void onSave({action:'team.unblock',id:b.id},'Intervalul a fost deblocat.')}>Deblochează</button></li>)}</ul>}
 </section>;
}
