'use client';
import {useState} from 'react';
import type {JobRow} from '@/lib/types';
import type {TeamBlock} from './TeamAvailability';
import {DesignIcon} from './DesignIcon';
import {JOB_STATUS} from '@/lib/workspaceShared';
const dateKey=(d:Date|string)=>new Date(d).toLocaleDateString('en-CA',{timeZone:'Europe/Bucharest'});
export function TeamSchedule({blocks=[],jobs,teams,assignments,selected,onSelect,onAssign,busy}:{blocks?:TeamBlock[];jobs:JobRow[];teams:{id:string;name:string}[];assignments:{job_id:string;team_id:string}[];selected:string;onSelect:(id:string)=>void;onAssign:(jobId:string,teamId:string)=>void;busy:boolean}){
 const [week,setWeek]=useState(0),[team,setTeam]=useState('');
 const start=new Date();start.setHours(12,0,0,0);start.setDate(start.getDate()-((start.getDay()+6)%7)+week*7);
 const days=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d});
 const filtered=jobs.filter(j=>['accepted','arrived'].includes(j.status)&&(!team||assignments.some(a=>a.job_id===j.id&&a.team_id===team)));
 const current=jobs.find(j=>j.id===selected);
 return <><div className="schedule-toolbar"><div className="schedule-team-tabs"><button className={!team?'active':''} onClick={()=>setTeam('')}>Toate echipele</button>{teams.map(t=><button key={t.id} className={team===t.id?'active':''} onClick={()=>setTeam(t.id)}>{t.name}</button>)}</div><div className="schedule-week"><button aria-label="Săptămâna anterioară" onClick={()=>setWeek(w=>w-1)}>‹</button><button onClick={()=>setWeek(0)}><DesignIcon name="calendar" size={18}/>{start.toLocaleDateString('ro-RO',{day:'numeric',month:'short'})} – {days[6].toLocaleDateString('ro-RO',{day:'numeric',month:'short'})}</button><button aria-label="Săptămâna următoare" onClick={()=>setWeek(w=>w+1)}>›</button></div></div>
 <div className="schedule-layout"><div className="schedule-scroll"><div className="schedule-grid"><div className="schedule-hours"><div className="schedule-day-heading"/>{Array.from({length:13},(_,i)=><span key={i}>{String(i+7).padStart(2,'0')}:00</span>)}</div>{days.map(d=><section key={dateKey(d)} className="schedule-day"><h3 className="schedule-day-heading">{d.toLocaleDateString('ro-RO',{weekday:'long'})}<small>{d.toLocaleDateString('ro-RO',{day:'numeric',month:'short'})}</small></h3><div className="schedule-day-body">{blocks.filter(b=>(!team||b.team_id===team)&&dateKey(b.starts_at)<=dateKey(d)&&dateKey(b.ends_at)>=dateKey(d)).map(b=>{const minute=(v:string)=>{const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Bucharest',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(v)).split(':').map(Number);return parts[0]*60+parts[1]};const from=dateKey(b.starts_at)===dateKey(d)?minute(b.starts_at):0;const to=dateKey(b.ends_at)===dateKey(d)?minute(b.ends_at):1440;const top=Math.max(0,(from-420)*.9),bottom=Math.min(702,(to-420)*.9);return bottom>top?<a href="#indisponibilitati" key={b.id} className="schedule-block" style={{top,height:bottom-top}} title={`${b.team_name}: ${b.reason}`}><b>{b.team_name}</b><span>Indisponibilă · {b.reason}</span></a>:null})}{filtered.filter(j=>j.scheduled_at&&dateKey(j.scheduled_at)===dateKey(d)).map(j=>{const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Bucharest',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(j.scheduled_at!));const [h,m]=parts.split(':').map(Number);const top=Math.max(0,Math.min(12*54,(h-7+m/60)*54));const height=Math.max(50,Math.min(13*54-top,j.duration_minutes/60*54));return <button key={j.id} onClick={()=>onSelect(j.id)} className={`schedule-event ${j.space_type==='birou'?'office':''} ${j.id===selected?'selected':''}`} style={{top,height}}><small>{parts}</small><b>{j.space_type==='birou'?'Birou':'Locuință'}</b><span>{j.city} · {j.sqm} m²</span></button>})}</div></section>)}</div></div>
 <aside className="design-panel schedule-detail"><h2>Detalii programare</h2>{current?<><div className="booking-summary-line"><DesignIcon name="calendar"/><b>{current.scheduled_at?new Date(current.scheduled_at).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest',dateStyle:'medium',timeStyle:'short'}):'Fără dată'}</b></div><h3>{current.space_type} · {current.city}</h3><p className="booking-muted">{current.street}</p><dl><div><dt>Suprafață</dt><dd>{current.sqm} m²</dd></div><div><dt>Durată</dt><dd>{current.duration_minutes} minute</dd></div><div><dt>Rezervă deplasare</dt><dd>{current.buffer_minutes} minute</dd></div><div><dt>Status</dt><dd>{JOB_STATUS[current.status]}</dd></div></dl><label className="schedule-assignment">Echipa alocată<select disabled={busy} value={assignments.find(a=>a.job_id===current.id)?.team_id??''} onChange={e=>{if(e.target.value)onAssign(current.id,e.target.value)}}><option value="">Selectează echipa</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></>:<div className="schedule-empty"><DesignIcon name="calendar" size={40}/><p>Selectează o programare din calendar pentru detalii și alocarea echipei.</p></div>}</aside></div></>;
}
