'use client';
import Image from 'next/image';
import Link from 'next/link';
import {CHECKLIST,JOB_STATUS} from '@/lib/workspaceShared';
import {DesignIcon} from './DesignIcon';
export interface TeamExecutionJob{id:string;street:string;city:string;sqm:number;status:string;scheduled_at:string|null;details:string;checklist:{item_key:string;done:number}[];photos:{id:string;proof_type:string}[];report:{note:string;submitted_at:string}|null}
export function TeamExecutionCard({job:j,busy,isOwner,act,upload}:{job:TeamExecutionJob;busy:boolean;isOwner:boolean;act:(body:Record<string,unknown>)=>Promise<unknown>;upload:(jobId:string,type:string,file:File)=>Promise<void>}){
 const done=CHECKLIST.filter(c=>j.checklist.some(x=>x.item_key===c.key&&x.done===1)).length;
 const arrival=j.photos.some(p=>p.proof_type==='ARRIVAL'),completion=j.photos.some(p=>p.proof_type==='COMPLETION');
 const ready=j.status==='arrived'&&arrival&&completion&&done===CHECKLIST.length;
 return <article className="team-execution-card"><section className="design-panel"><div className="board-card-heading"><p>Lucrarea de astăzi</p><span className="eyebrow-pill">{JOB_STATUS[j.status]}</span></div><h2>Curățenie · {j.sqm} m²</h2><p className="team-job-address"><DesignIcon name="pin" size={20}/>{j.street}, {j.city}</p><p className="booking-muted">{j.scheduled_at?new Date(j.scheduled_at).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'}):'Cât mai curând'}</p><ol className="team-execution-steps">{['Sosire','Sarcini','Raport'].map((label,index)=><li key={label} className={(index===0&&j.status==='arrived'||index===1&&done===CHECKLIST.length||index===2&&j.report)?'is-done':''}><span>{index+1}</span><b>{label}</b><small>{index===0?(j.status==='arrived'?'Confirmată':'În așteptare'):index===1?`${done} / ${CHECKLIST.length}`:j.report?'Trimis':'În așteptare'}</small></li>)}</ol>{j.details&&<p className="booking-muted">{j.details}</p>}</section>
 <section className="design-panel execution-checklist"><div className="board-card-heading"><h3>Lista de verificări</h3><span>{done} / {CHECKLIST.length}</span></div><progress max={CHECKLIST.length} value={done} aria-label="Progres verificări"/>{CHECKLIST.map(c=><div className="execution-check-row" key={c.key}><label><input type="checkbox" disabled={busy||!!j.report} checked={!!j.checklist.find(x=>x.item_key===c.key)?.done} onChange={e=>void act({action:'checklist.set',jobId:j.id,key:c.key,done:e.target.checked})}/><span>{c.label}</span></label></div>)}</section>
 <section className="design-panel"><h3>Raport foto</h3>{(['ARRIVAL','COMPLETION'] as const).map(type=><section className="team-proof-section" key={type}><div className="board-card-heading"><h4>{type==='ARRIVAL'?'Foto la sosire':'Foto la final'}</h4><span>{j.photos.filter(p=>p.proof_type===type).length} fotografii</span></div><div className="team-proof-grid">{j.photos.filter(p=>p.proof_type===type).map(p=><a href={`/api/uploads/${p.id}`} key={p.id} target="_blank" rel="noreferrer"><Image unoptimized src={`/api/uploads/${p.id}`} alt={type==='ARRIVAL'?'Dovadă foto la sosire':'Dovadă foto la final'} width={240} height={180}/></a>)}{!j.report&&<label className={`team-photo-upload ${busy||type==='COMPLETION'&&j.status!=='arrived'?'is-disabled':''}`}><DesignIcon name="photo" size={30}/><span>Adaugă fotografie</span><input className="sr-only" aria-label={type==='ARRIVAL'?'Adaugă fotografie la sosire':'Adaugă fotografie la final'} type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||type==='COMPLETION'&&j.status!=='arrived'} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(j.id,type,f);e.target.value=''}}/></label>}</div></section>)}<Link href="/contact" className="board-soft-button"><DesignIcon name="help"/>Raportează o problemă<DesignIcon name="arrow" size={18}/></Link></section>
 {j.report?<section className="workspace-notice"><b>Raport trimis</b><p>{new Date(j.report.submitted_at).toLocaleString('ro-RO',{timeZone:'Europe/Bucharest'})}</p>{j.report.note&&<p>{j.report.note}</p>}{isOwner&&<Link href="/firma#lucrari-active" className="board-soft-button">Verifică și finalizează</Link>}</section>:j.status==='accepted'?<button disabled={busy||!arrival} className="design-button" onClick={()=>void act({action:'execution.arrived',jobId:j.id})}>Confirmă sosirea și începe lucrarea</button>:<form onSubmit={e=>{e.preventDefault();if(!ready)return;const f=new FormData(e.currentTarget);void act({action:'execution.submit',jobId:j.id,note:f.get('note')})}}><label className="team-report-note">Observații la final<textarea name="note" maxLength={2000}/></label><button disabled={busy||!ready} className="design-button"><DesignIcon name="arrow"/>Trimite raportul</button><p className="booking-muted">Completează verificările și fotografiile de sosire/final. Trimiterea raportului nu încasează plata.</p></form>}
 </article>;
}
