import { useCallback, useEffect, useState } from "react";
import { router, useFocusEffect, useLocalSearchParams } from "expo-router";
import { Linking, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { api, normalizeApiError } from "@/api";
import { jobTypeLabel } from "@/jobTypes";
import { AppScreen, EmptyState, InlineState, Pill, PremiumCard, PrimaryButton } from "@/mobileUi";
import { colors } from "@/theme";
import { getTracking, trackingMessage, type TrackingState } from "@/tracking";
import type { Job } from "@/types";

export default function ClientJobDetail(){
  const {id}=useLocalSearchParams<{id:string}>();const [job,setJob]=useState<Job|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [tracking,setTracking]=useState<TrackingState|null>(null);const [rating,setRating]=useState(5);const [reviewText,setReviewText]=useState("");const [reviewing,setReviewing]=useState(false);
  const load=useCallback(async()=>{if(!id)return;setLoading(true);setError(null);try{const result=await api<{job:Job}>(`/api/jobs/${id}`);setJob(result.job)}catch(cause){setError(normalizeApiError(cause).message)}finally{setLoading(false)}},[id]);
  useFocusEffect(useCallback(()=>{void load()},[load]));
  useEffect(()=>{if(job?.status!=="arrived")return;let alive=true;const poll=async()=>{try{const state=await getTracking(job.id,api);if(alive)setTracking(state)}catch{if(alive)setTracking(null)}};void poll();const timer=setInterval(()=>void poll(),15_000);return()=>{alive=false;clearInterval(timer)}},[job?.id,job?.status]);
  async function submitReview(){if(!job||reviewing)return;setReviewing(true);setError(null);try{await api(`/api/jobs/${job.id}/rating`,{method:"POST",body:JSON.stringify({stars:rating,reviewText})});await load()}catch(cause){setError(normalizeApiError(cause).message)}finally{setReviewing(false)}}
  if(loading||error&&!job)return <AppScreen title="Detaliu lucrare"><InlineState loading={loading} error={error} onRetry={()=>void load()}/></AppScreen>;
  if(!job)return <AppScreen title="Detaliu lucrare"><EmptyState icon="alert-circle-outline" title="Lucrarea nu este disponibilă" body="Verifică lista lucrărilor tale."/></AppScreen>;
  const waiting=job.status==="waiting";const timeline=[{key:"waiting",label:"Lucrare publicată"},{key:"accepted",label:"Firmă alocată"},{key:"arrived",label:"În desfășurare"},{key:"completed",label:"Finalizată"}];const statusIndex=timeline.findIndex(item=>item.key===job.status);const date=job.scheduled_at?new Date(job.scheduled_at).toLocaleString("ro-RO",{day:"numeric",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—";
  return <AppScreen eyebrow={`REFERINȚĂ ${job.id}`} title={jobTypeLabel(job.space_type)} subtitle={`${job.city} · ${job.sqm} m²`}>
    <PremiumCard><View style={s.head}><Text style={s.title}>Status curent</Text><Pill tone={waiting?"amber":"green"} label={waiting?"ÎN AȘTEPTARE":job.status.toUpperCase()}/></View><Text style={s.status}>{waiting?"Așteptăm o firmă":"Status confirmat de NITIDO"}</Text></PremiumCard>
    <PremiumCard><Row label="Programare" value={date}/><Row label="Adresă" value={`${job.street??"—"}, ${job.city}`}/><Row label="Suprafață" value={`${job.sqm} m²`}/><Row label="Preț total" value={`${job.price_gross} lei`}/><Row label="Fotografii" value={String(job.photos_count??0)}/></PremiumCard>
    <PremiumCard><Text style={s.title}>Plată</Text><Row label="Stare" value={clientPaymentLabel(job)}/>{job.financial?.refundStatus&&job.financial.refundStatus!=="none"?<Row label="Rambursare" value={job.financial.refundStatus}/>:null}<Text style={s.privacy}>Starea este furnizată de backend și procesator. Aplicația nu poate autoriza sau captura plata.</Text></PremiumCard>
    <PremiumCard><Text style={s.title}>Evoluția lucrării</Text>{timeline.map((item,index)=><View key={item.key} style={s.timeline}><View style={[s.dot,index<=statusIndex&&s.dotActive]}/><Text style={[s.timelineText,index<=statusIndex&&s.timelineTextActive]}>{item.label}</Text></View>)}{job.status==="cancelled"?<Text style={s.cancelled}>Lucrarea este anulată.</Text>:null}{job.status==="no_show"?<Text style={s.cancelled}>Incident de neprezentare înregistrat.</Text>:null}</PremiumCard>
    {job.status==="arrived"?<PremiumCard><Text style={s.title}>Urmărire activă</Text><Text style={s.privacy}>{trackingMessage(tracking)}</Text>{tracking?.location?<><Text style={s.status}>Poziție autorizată actualizată de firmă.</Text><PrimaryButton secondary title="Deschide poziția în hartă" icon="map-outline" onPress={()=>void Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${tracking.location?.latitude},${tracking.location?.longitude}`)}/></>:<Text style={s.privacy}>Harta este indisponibilă până când firma transmite o poziție autorizată.</Text>}<Text style={s.privacy}>Locația este transmisă numai pentru lucrarea activă și nu este expusă după finalizare.</Text></PremiumCard>:null}
    {job.status==="completed"&&!job.ownReview?<PremiumCard><Text style={s.title}>Evaluează firma</Text><View style={s.stars}>{[1,2,3,4,5].map(star=><Pressable accessibilityRole="button" accessibilityLabel={`${star} stele`} key={star} onPress={()=>setRating(star)}><Text style={[s.star,star<=rating&&s.starActive]}>★</Text></Pressable>)}</View><TextInput accessibilityLabel="Comentariu opțional" multiline maxLength={1000} value={reviewText} onChangeText={setReviewText} placeholder="Comentariu opțional" placeholderTextColor={colors.muted} style={s.reviewInput}/><PrimaryButton loading={reviewing} disabled={reviewing} title="Trimite recenzia" icon="star-outline" onPress={()=>void submitReview()}/><Text style={s.privacy}>Eligibilitatea și insigna verificată sunt stabilite exclusiv de server.</Text></PremiumCard>:null}
    {job.ownReview?<PremiumCard><View style={s.head}><Text style={s.title}>Evaluarea ta</Text><Pill label={job.ownReview.badge} tone="green"/></View><Text style={s.starActive}>{"★".repeat(job.ownReview.rating)}</Text>{job.ownReview.reviewText?<Text style={s.privacy}>{job.ownReview.reviewText}</Text>:null}</PremiumCard>:null}
    {error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}<Text style={s.privacy}>Adresa completă este vizibilă numai în contul tău și firmei alocate după autorizarea serverului.</Text><PrimaryButton secondary title="Lucrările mele" icon="briefcase-outline" onPress={()=>router.replace("/(client)/jobs")}/>
  </AppScreen>;
}
function clientPaymentLabel(job:Job){const status=job.financial?.paymentStatus;if(job.financial?.refundStatus&&job.financial.refundStatus!=="none")return job.financial.refundStatus==="succeeded"?"Plată rambursată":"Rambursare în procesare";if(status==="authorized")return "Plată autorizată";if(status==="captured")return "Plată capturată după finalizare";if(status==="refunded")return "Plată rambursată";if(status==="cancelled")return "Autorizare anulată";return job.financial?"Plata necesită verificare":"Stare indisponibilă"}
function Row({label,value}:{label:string;value:string}){return <View style={s.row}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({head:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",gap:12},title:{fontSize:17,fontWeight:"800",color:colors.ink},status:{fontSize:14,color:colors.greenDark},row:{flexDirection:"row",justifyContent:"space-between",gap:16,paddingVertical:9,borderBottomWidth:1,borderBottomColor:colors.border},label:{fontSize:12,color:colors.muted},value:{flex:1,textAlign:"right",fontSize:13,fontWeight:"700",color:colors.ink},timeline:{minHeight:38,flexDirection:"row",alignItems:"center",gap:12},dot:{width:12,height:12,borderRadius:6,backgroundColor:colors.border},dotActive:{backgroundColor:colors.green},timelineText:{fontSize:13,color:colors.muted},timelineTextActive:{fontWeight:"700",color:colors.ink},cancelled:{fontSize:13,fontWeight:"700",color:colors.danger,marginTop:7},privacy:{fontSize:12,lineHeight:18,color:colors.muted},stars:{flexDirection:"row",gap:9},star:{fontSize:32,color:colors.border},starActive:{fontSize:24,color:"#B98017"},reviewInput:{minHeight:90,textAlignVertical:"top",borderWidth:1,borderColor:colors.border,borderRadius:15,padding:13,fontSize:14,color:colors.ink},error:{fontSize:13,color:colors.danger}});
