import {publicPageMetadata} from '@/lib/publicSeo';
import {InformationPage} from '@/components/InformationPage';
import {APARTMENT_TIERS,PER_SQM_RATES,MINIMUM_PRICES,WINDOWS_RATE_LEI} from '@/lib/pricing';
export const metadata=publicPageMetadata('/preturi');
export default function Page(){return <InformationPage eyebrow="PREȚURI NITIDO" title="Știi cât plătești înainte să rezervi." intro="Calculăm curățenia după tipul spațiului și suprafață. Numărul camerelor nu adaugă o taxă separată. Spălarea geamurilor este opțională și se plătește separat." cta={{label:'Configurează curățenia',href:'/rezervare'}} sections={[
 {title:'Apartamente · pachete după suprafață',items:[...APARTMENT_TIERS.map((t,i)=>`${i?APARTMENT_TIERS[i-1].max+1:1}–${t.max} m²: ${t.price} lei`),'Peste 100 m²: 650 lei + 6,50 lei pentru fiecare m² suplimentar.']},
 {title:'Case, birouri și alte spații',items:[`Casă / vilă: ${PER_SQM_RATES.casa} lei/m², minimum ${MINIMUM_PRICES.casa} lei/intervenție.`,`Birou: ${PER_SQM_RATES.birou} lei/m², minimum ${MINIMUM_PRICES.birou} lei/intervenție.`,`Alte spații obișnuite: ${PER_SQM_RATES.altul} lei/m², minimum ${MINIMUM_PRICES.altul} lei/intervenție.`]},
 {title:'Spălare geamuri · separat',paragraphs:[`${WINDOWS_RATE_LEI} lei/m² de geam, adăugați la serviciul de curățenie. Măsori fiecare geam o singură dată (lățime × înălțime), însumezi suprafețele și rotunjești totalul în sus. Tariful include ambele fețe accesibile și ramele. Nu dubla suprafața pentru cele două fețe.`,'La 0 m² nu se adaugă costul spălării geamurilor. Accesul la înălțime, suprafețele inaccesibile și resturile de constructor necesită evaluare înainte de rezervare.']},
 {title:'Ce include curățenia',paragraphs:['Curățenie obișnuită: aspirare și spălare pardoseli, ștergere praf pe suprafețe accesibile, curățarea bucătăriei și băilor. Geamurile nu sunt incluse în pachetul de bază.','După constructor, murdărie dificilă, tapițerii, interiorul electrocasnicelor și alte cerințe speciale: solicită o evaluare. Calculatorul automat nu tarifează aceste intervenții ca o curățenie obișnuită.']},
 {title:'Rezumat și plată',paragraphs:['Tariful serviciului, geamurile, suplimentul Express 60 dacă îl alegi și creditul disponibil apar separat înainte de publicare. Totalul afișat este suma rezervării; nu se adaugă TVA peste acest total la plată.','Noua grilă se aplică rezervărilor noi. Prețul înregistrat al unei rezervări deja publicate se păstrează.']},
 {title:'Ai o cerință specială?',paragraphs:['Pentru o suprafață peste 1.000 m² sau o intervenție specială, folosește secțiunea Evaluări din cont. Pentru clarificări: 0341.402.403 sau contact@nitido.ro.']}
 ]}/>}
