import {test} from 'node:test';
import assert from 'node:assert/strict';
import {evaluateRelease,GATES} from './release-gate.mjs';
import {inspectStaging,verifyStripeAccount} from './staging-preflight.mjs';
const sha='a'.repeat(40);
function record(){return {schemaVersion:1,candidateSha:sha,ci:{sha,status:'pass',evidence:['https://github.com/example/run/1']},gates:GATES.map(id=>({id,sha,status:'pass',owner:'reviewer',checkedAt:'2026-01-01T00:00:00Z',evidence:['evidence/report.md']}))};}
test('all gates need evidence for the exact candidate',()=>{assert.equal(evaluateRelease(record(),sha).decision,'GO');assert.equal(evaluateRelease(record(),'b'.repeat(40)).decision,'NO_GO');});
test('green CI cannot substitute any missing release gate',()=>{for(const id of GATES){const r=record();r.gates=r.gates.filter(g=>g.id!==id);assert.deepEqual(evaluateRelease(r,sha).blockers,[id]);}});
test('pending, waived, duplicate, stale and unsupported gate assertions remain blocked',()=>{for(const change of [{status:'pending'},{status:'waived'},{evidence:[]},{evidence:['TBD']},{sha:'b'.repeat(40)},{owner:''},{checkedAt:'not-a-date'}]){const r=record();Object.assign(r.gates[0],change);assert.equal(evaluateRelease(r,sha).decision,'NO_GO');}const r=record();r.gates.push(r.gates[0]);assert.equal(evaluateRelease(r,sha).decision,'NO_GO');});
test('malformed records fail closed',()=>{for(const r of [null,{},[],{gates:[null]}])assert.equal(evaluateRelease(r,sha).decision,'NO_GO');});
const env={STRIPE_SECRET_KEY:'rk_test_123ABC',NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:'pk_test_123ABC',STRIPE_WEBHOOK_SECRET:'whsec_123ABC',NEXT_PUBLIC_SITE_URL:'https://sandbox.nitido.ro',NITIDO_STRIPE_CONNECT_TRANSFERS_ENABLED:'false',NITIDO_SEED_DEMO:'false',NITIDO_STRIPE_PLATFORM_ACCOUNT_ID:'acct_one'};
test('staging report never exposes credentials and distinguishes configuration from runtime QA',()=>{const r=inspectStaging(env);assert.equal(r.configurationReady,true);assert.ok(r.unverified.includes('publishable_key_same_account'));assert.ok(!JSON.stringify(r).includes('123ABC'));});
test('production, placeholder and missing configuration fail closed',()=>{for(const change of [{STRIPE_SECRET_KEY:'sk_live_123ABC'},{STRIPE_SECRET_KEY:'sk_test_ci_dummy'},{NEXT_PUBLIC_SITE_URL:'https://nitido.ro'},{NEXT_PUBLIC_SITE_URL:'https://sandbox.nitido.ro@evil.test'},{NITIDO_STRIPE_CONNECT_TRANSFERS_ENABLED:'true'},{NITIDO_STRIPE_PLATFORM_ACCOUNT_ID:''}])assert.equal(inspectStaging({...env,...change}).configurationReady,false);assert.equal(inspectStaging({}).configurationReady,false);});
test('account verification is read only and checks expected identity',async()=>{class Good{accounts={retrieve:async()=>({id:'acct_one'})}}class Wrong{accounts={retrieve:async()=>({id:'acct_other'})}}class Failed{accounts={retrieve:async()=>{throw Error('secret123')}}}assert.equal((await verifyStripeAccount(env,Good)).status,'pass');assert.equal((await verifyStripeAccount(env,Wrong)).status,'fail');assert.equal((await verifyStripeAccount(env,Failed)).status,'fail');assert.equal((await verifyStripeAccount({},Good)).status,'blocked');});
