import { InformationPage } from "@/components/InformationPage";

export default function Page(){return <InformationPage eyebrow="MODEL OPERAȚIONAL" title="Cum funcționează NITIDO.RO" intro="NITIDO.RO coordonează publicarea, eligibilitatea, alocarea, statusurile și plata unei lucrări prin reguli controlate de server." cta={{label:"Postează o lucrare",href:"/signup?role=client"}} sections={[
  {title:"Parcursul clientului",items:["Creează un cont de client și se autentifică.","Postează lucrarea cu tipul serviciului, suprafața, localitatea, adresa, programarea și informațiile necesare.","Verifică prețul calculat înainte de publicare.","Primește confirmarea după alocare și urmărește statusul.","După finalizare poate evalua firma pentru lucrarea reală."]},
  {title:"Eligibilitate și alertare",paragraphs:["Sistemul identifică firmele verificate, nesuspendate și cu acoperire în localitatea lucrării. Firmele eligibile pot primi alertă prin platformă și SMS atunci când serviciul este activ."],items:["Notificarea nu alocă lucrarea.","SMS-ul este doar un canal de informare.","Starea oficială rămâne cea confirmată de server."]},
  {title:"Alocarea pe server",paragraphs:["Firma verifică informațiile permise și apasă Accept. Serverul validează autentificarea, eligibilitatea, starea lucrării și plata aplicabilă."],items:["Prima acceptare validă confirmată de server câștigă.","Acceptarea este atomică: două firme nu pot primi aceeași lucrare.","Celelalte firme află că lucrarea nu mai este disponibilă."]},
  {title:"Confidențialitatea adresei",paragraphs:["Înainte de alocare, firma vede localitatea, tipul serviciului, suprafața, programarea și alte date neconfidențiale. Adresa exactă și fotografiile protejate devin disponibile numai firmei câștigătoare, după alocare."]},
  {title:"Execuție și status",items:["Firma primește detaliile necesare executării.","Lucrarea poate trece prin stările în așteptare, acceptată, sosită, finalizată, anulată sau no-show.","Clientul și firma văd numai informațiile autorizate rolului lor."]},
  {title:"Plată și finalizare",paragraphs:["Providerul de plată și serverul NITIDO controlează autorizarea și capturarea. Interfața și Asistentul AI nu pot declara plata reușită, captura, rambursa sau transfera bani."],items:["Autorizarea poate preceda executarea.","Capturarea urmează starea reală a lucrării.","Un eșec de plată nu trebuie să lase o alocare fals confirmată."]},
  {title:"Rating și reputație",paragraphs:["După finalizare, clientul poate acorda un rating asociat lucrării reale. Ratingurile și incidentele no-show contribuie la istoricul operațional al firmei."]},
]}/>}
